import type { IbTopicSpec } from "./ib-question-types";

const b = (
  id: string,
  code: string,
  name: string,
  level: "SL & HL" | "HL only",
  concepts: IbTopicSpec["concepts"],
): IbTopicSpec => ({ id, code, name, subject: "Biology", level, concepts });

export const biologyIbTopicSpecs: IbTopicSpec[] = [
  b("ib-bio-a11", "A1.1", "Water", "SL & HL", [
    ["polarity", "an unequal distribution of charge within a molecule", "water's polar bonds and bent shape allow attraction to ions and other polar molecules"],
    ["hydrogen bond", "a weak attraction between a partially positive hydrogen and an electronegative atom", "many hydrogen bonds give water strong cohesion and unusual thermal properties"],
    ["cohesion", "attraction between molecules of the same substance", "cohesion helps maintain continuous water columns in plant xylem"],
    ["solvent", "a liquid that dissolves solutes to form a solution", "water transports dissolved substances and provides a medium for metabolic reactions"],
    ["specific heat capacity", "the energy required to raise the temperature of unit mass by one degree", "water's high value stabilizes aquatic habitats and organism temperatures"],
    ["latent heat of vaporization", "the energy needed to change liquid to vapour without temperature change", "evaporation of water removes substantial energy and enables cooling"],
  ]),
  b("ib-bio-a12", "A1.2", "Nucleic acids", "SL & HL", [
    ["nucleotide", "a phosphate, pentose sugar and nitrogenous base joined together", "nucleotides are the monomers of DNA and RNA and can also transfer energy"],
    ["DNA", "a double-stranded nucleic acid that stores hereditary information", "its base sequence provides stable instructions for cell structure and function"],
    ["RNA", "usually a single-stranded nucleic acid containing ribose and uracil", "different RNA molecules transfer and use genetic information in protein synthesis"],
    ["complementary base pairing", "specific pairing of bases through hydrogen bonds", "it enables accurate replication and transcription from a template strand"],
    ["antiparallel strands", "two nucleic-acid strands running in opposite 5-prime to 3-prime directions", "their orientation is essential for DNA structure and enzyme action"],
    ["genetic code", "the relationship between mRNA base triplets and amino acids or stop signals", "it translates nucleotide sequence into polypeptide sequence"],
  ]),
  b("ib-bio-a21", "A2.1", "Origins of cells", "HL only", [
    ["abiogenesis", "the origin of living systems from non-living chemical components", "hypotheses must explain formation of organic molecules, membranes, heredity and metabolism"],
    ["protocell", "a non-living compartment with some cell-like properties", "membrane-bound droplets could concentrate molecules and support early chemical systems"],
    ["RNA world", "the hypothesis that RNA once stored information and catalysed reactions", "RNA can combine hereditary and enzymatic functions needed before DNA-protein systems"],
    ["hydrothermal vent", "a seafloor system supplying chemical gradients and mineral surfaces", "it is one proposed environment for early metabolic pathways"],
    ["last universal common ancestor", "the ancestral population from which all current cellular life descends", "shared genetic code and cellular machinery support common ancestry"],
    ["endosymbiosis", "the incorporation of one cell into another in a mutually beneficial association", "it explains the bacterial ancestry of mitochondria and chloroplasts"],
  ]),
  b("ib-bio-a22", "A2.2", "Cell structure", "SL & HL", [
    ["prokaryotic cell", "a cell without a membrane-bound nucleus or membrane-bound organelles", "its DNA lies in the cytoplasm and its structure suits small size and rapid growth"],
    ["eukaryotic cell", "a cell with DNA enclosed in a nucleus and specialized membrane-bound organelles", "compartmentalization supports complex and regulated cellular processes"],
    ["plasma membrane", "a phospholipid bilayer with embedded proteins surrounding the cell", "it controls exchange and enables communication with the environment"],
    ["ribosome", "a ribonucleoprotein complex that translates mRNA into polypeptide", "all cells need ribosomes to synthesize proteins"],
    ["surface-area-to-volume ratio", "surface area divided by volume for a cell or organism", "it constrains cell size because exchange capacity grows more slowly than metabolic demand"],
    ["microscopy", "the use of instruments to resolve structures too small for unaided vision", "magnification and resolution determine which cell features can be observed"],
  ]),
  b("ib-bio-a23", "A2.3", "Viruses", "HL only", [
    ["virus", "an acellular infectious particle containing nucleic acid inside a protein coat", "it depends on host-cell machinery for replication"],
    ["capsid", "the protein shell surrounding a viral genome", "it protects nucleic acid and can help the virus attach to host cells"],
    ["host specificity", "restriction of a virus to cells with suitable receptors and internal conditions", "receptor compatibility helps determine which species and tissues can be infected"],
    ["lytic cycle", "viral replication followed by host-cell rupture and particle release", "it rapidly produces virions while destroying infected cells"],
    ["lysogenic cycle", "integration or persistence of viral genetic material without immediate cell lysis", "the viral genome can be copied with the host before later activation"],
    ["retrovirus", "an RNA virus that uses reverse transcriptase to make DNA", "the DNA can integrate into a host genome and establish persistent infection"],
  ]),
  b("ib-bio-a31", "A3.1", "Diversity of organisms", "SL & HL", [
    ["biodiversity", "the variety of genes, species and ecosystems in a region or on Earth", "greater diversity can support ecosystem resilience and provides biological resources"],
    ["species", "a group whose members can interbreed to produce fertile offspring under natural conditions", "species identification is central to measuring diversity and studying evolution"],
    ["domain", "the highest taxonomic rank separating Bacteria, Archaea and Eukarya", "molecular evidence reveals deep evolutionary divisions among cellular organisms"],
    ["taxon", "a named group at any level of biological classification", "nested taxa organize organisms using shared features and ancestry"],
    ["binomial nomenclature", "a two-part scientific naming system using genus and species", "it provides a universal and unambiguous organism name"],
    ["species richness", "the number of different species present in a community", "it is one component of diversity but does not include relative abundance"],
  ]),
  b("ib-bio-a32", "A3.2", "Classification and cladistics", "HL only", [
    ["clade", "an ancestor and all of its descendants", "valid cladistic groups represent complete branches of evolutionary history"],
    ["cladogram", "a branching diagram showing hypotheses about evolutionary relationships", "branching order is inferred from shared derived characteristics or sequence data"],
    ["node", "a branching point representing a common ancestor", "more recent shared nodes indicate closer evolutionary relationships"],
    ["outgroup", "a comparison taxon outside the group being analysed", "it helps determine which character states are ancestral or derived"],
    ["molecular clock", "the use of sequence differences and an estimated mutation rate to infer divergence time", "it links genetic distance to evolutionary timing when calibrated"],
    ["homologous character", "a feature shared because of common ancestry", "homologies provide evidence for constructing natural classifications"],
  ]),
  b("ib-bio-a41", "A4.1", "Evolution and speciation", "SL & HL", [
    ["evolution", "change in heritable characteristics or allele frequencies across generations", "it explains both shared features and the diversity of living organisms"],
    ["natural selection", "differential survival and reproduction associated with heritable variation", "advantageous alleles tend to increase in a particular environment"],
    ["reproductive isolation", "barriers that prevent gene flow between populations", "isolation allows populations to diverge independently and become separate species"],
    ["allopatric speciation", "species formation after geographic separation of populations", "different selection and drift can cause divergence until reproductive isolation evolves"],
    ["sympatric speciation", "species formation without geographic separation", "ecological, behavioural or chromosomal differences can reduce gene flow within one area"],
    ["adaptive radiation", "rapid diversification from a common ancestor into multiple ecological roles", "new habitats or reduced competition can expose many available niches"],
  ]),
  b("ib-bio-a42", "A4.2", "Conservation of biodiversity", "SL & HL", [
    ["conservation", "planned protection and management of biodiversity and natural processes", "it aims to reduce extinction risk while maintaining ecosystem function"],
    ["in situ conservation", "protection of species within their natural habitats", "it preserves ecological interactions and ongoing evolution"],
    ["ex situ conservation", "protection outside natural habitats such as seed banks or captive breeding", "it can safeguard small populations and support later reintroduction"],
    ["threatened species", "a species facing elevated risk of extinction", "risk assessment guides conservation priorities and action"],
    ["habitat fragmentation", "division of continuous habitat into smaller isolated patches", "it reduces population size, gene flow and access to resources"],
    ["restoration ecology", "assisted recovery of degraded ecosystems", "restoration can rebuild habitat, interactions and ecosystem services"],
  ]),
  b("ib-bio-b11", "B1.1", "Carbohydrates and lipids", "SL & HL", [
    ["monosaccharide", "a single sugar unit that can be used in respiration or as a building block", "monosaccharides combine to form transport and storage carbohydrates"],
    ["polysaccharide", "a polymer made from many monosaccharides joined by glycosidic bonds", "different branching and bonding create storage or structural functions"],
    ["triglyceride", "a lipid formed from glycerol and three fatty acids", "it stores concentrated energy and provides insulation and protection"],
    ["phospholipid", "a lipid with a hydrophilic phosphate head and hydrophobic fatty-acid tails", "its amphipathic nature drives bilayer formation in water"],
    ["saturated fatty acid", "a fatty acid with no carbon-carbon double bonds", "straight chains pack closely and often form fats with higher melting points"],
    ["unsaturated fatty acid", "a fatty acid containing one or more carbon-carbon double bonds", "cis double bonds create bends that reduce packing and increase fluidity"],
  ]),
  b("ib-bio-b12", "B1.2", "Proteins", "SL & HL", [
    ["amino acid", "a monomer with amino, carboxyl and variable R groups", "R-group chemistry creates diversity among proteins"],
    ["peptide bond", "the covalent bond formed between amino acids by condensation", "many peptide bonds create a polypeptide backbone"],
    ["primary structure", "the amino-acid sequence of a polypeptide", "sequence determines interactions that produce higher levels of protein structure"],
    ["tertiary structure", "the overall three-dimensional folding of one polypeptide", "its shape creates active, binding and structural regions needed for function"],
    ["denaturation", "loss of a protein's functional shape after disruption of stabilizing interactions", "temperature or pH extremes can remove biological activity without breaking every peptide bond"],
    ["proteome", "the complete set of proteins expressed by a cell or organism at a time", "it varies with cell type and conditions despite cells sharing a genome"],
  ]),
  b("ib-bio-b21", "B2.1", "Membranes and membrane transport", "SL & HL", [
    ["fluid mosaic model", "the model of a mobile phospholipid bilayer containing diverse proteins", "it explains flexibility, selective permeability and dynamic membrane function"],
    ["simple diffusion", "net movement down a concentration gradient without transport proteins or ATP", "small non-polar molecules can cross the bilayer directly"],
    ["facilitated diffusion", "passive movement down a gradient through a channel or carrier protein", "it enables selective transfer of ions and polar molecules"],
    ["osmosis", "net water movement across a selectively permeable membrane down a water-potential gradient", "it changes cell volume and creates turgor in plants"],
    ["active transport", "movement against an electrochemical gradient using energy and transport proteins", "it establishes concentration differences needed for absorption and signalling"],
    ["vesicle transport", "movement of material by membrane-bound vesicles through endocytosis or exocytosis", "it transfers substances too large for channels and carriers"],
  ]),
  b("ib-bio-b22", "B2.2", "Organelles and compartmentalization", "SL & HL", [
    ["compartmentalization", "separation of cellular processes into distinct membrane-bound regions", "it creates specialized conditions and prevents incompatible reactions from interfering"],
    ["nucleus", "the double-membrane organelle containing most eukaryotic DNA", "it separates transcription and genome regulation from cytoplasmic translation"],
    ["mitochondrion", "a double-membrane organelle where aerobic respiration generates most ATP", "inner-membrane folds provide a large area for electron transport and chemiosmosis"],
    ["chloroplast", "a photosynthetic organelle containing thylakoids and stroma", "it separates light-dependent reactions from carbon fixation"],
    ["endoplasmic reticulum", "an internal membrane network involved in protein or lipid synthesis", "rough and smooth regions support different biosynthetic pathways"],
    ["Golgi apparatus", "stacks of membranes that modify, sort and package cellular products", "it directs proteins and lipids to their correct destinations"],
  ]),
  b("ib-bio-b23", "B2.3", "Cell specialization", "SL & HL", [
    ["differentiation", "the process by which cells develop specialized structure and function", "selective gene expression allows genetically similar cells to become different cell types"],
    ["stem cell", "an unspecialized cell able to self-renew and produce differentiated cells", "stem cells support development, tissue maintenance and some medical treatments"],
    ["gene expression", "use of genetic information to produce functional RNA or protein", "different expression patterns create distinct cell structures and activities"],
    ["specialized structure", "a cellular feature adapted to a particular function", "shape, organelle abundance and membrane proteins match the demands placed on a cell"],
    ["tissue", "an organized group of cells working together in a shared function", "cell specialization and coordination produce properties beyond those of individual cells"],
    ["cell replacement", "production of new cells to maintain or repair a tissue", "controlled stem-cell division and differentiation preserve organ function"],
  ]),
  b("ib-bio-b31", "B3.1", "Gas exchange", "SL & HL", [
    ["gas-exchange surface", "a specialized boundary across which oxygen and carbon dioxide diffuse", "large area, short distance and maintained gradients increase exchange rate"],
    ["ventilation", "bulk movement of air or water across a gas-exchange surface", "it refreshes the medium and maintains concentration gradients"],
    ["alveolus", "a tiny air sac in mammalian lungs surrounded by capillaries", "many alveoli provide a moist, thin and extensive exchange surface"],
    ["stoma", "a controlled pore in the leaf epidermis", "guard cells balance carbon-dioxide uptake against water loss"],
    ["countercurrent exchange", "flow of two fluids in opposite directions across an exchange surface", "it maintains a diffusion gradient along the full exchange length"],
    ["respiratory pigment", "a molecule that reversibly binds oxygen", "binding increases oxygen transport capacity and supports delivery to respiring tissues"],
  ]),
  b("ib-bio-b32", "B3.2", "Transport", "SL & HL", [
    ["mass transport", "bulk movement of materials through a vessel or transport system", "it overcomes diffusion limits in large multicellular organisms"],
    ["xylem", "plant vascular tissue transporting water and mineral ions mainly from roots to shoots", "lignified vessels withstand tension generated by transpiration"],
    ["phloem", "living vascular tissue translocating organic solutes between sources and sinks", "pressure-flow moves assimilates to growing or storage tissues"],
    ["transpiration", "loss of water vapour from plant leaves, mainly through stomata", "evaporation and cohesion generate tension that pulls water through xylem"],
    ["cardiac cycle", "the repeating sequence of filling and contraction in the heart", "pressure changes and valves maintain one-way blood flow"],
    ["capillary", "a microscopic vessel with a thin wall connecting arterioles and venules", "slow flow and short diffusion distance support exchange with tissues"],
  ]),
  b("ib-bio-b33", "B3.3", "Muscle and motility", "HL only", [
    ["sarcomere", "the repeating contractile unit between Z lines in striated muscle", "its shortening results from actin sliding past myosin"],
    ["actin", "a thin filament with binding sites for myosin heads", "its relative movement towards the sarcomere centre shortens muscle fibres"],
    ["myosin", "a motor protein whose heads bind actin and hydrolyse ATP", "repeated cross-bridge cycles generate force and movement"],
    ["calcium ion", "an intracellular signal that exposes actin binding sites", "calcium release couples electrical excitation to muscle contraction"],
    ["ATP", "the immediate energy-transfer molecule used in cross-bridge cycling", "ATP binding detaches myosin and hydrolysis resets the head"],
    ["antagonistic muscle pair", "two muscles producing opposite movements at a joint", "one contracts while the other relaxes because muscles pull but do not push"],
  ]),
  b("ib-bio-b41", "B4.1", "Adaptation to environment", "SL & HL", [
    ["adaptation", "a heritable feature increasing survival or reproductive success in an environment", "natural selection raises the frequency of advantageous adaptations"],
    ["structural adaptation", "a physical feature of an organism that improves fitness", "body form can reduce water loss, capture food or aid temperature control"],
    ["physiological adaptation", "an internal biochemical or functional trait that improves fitness", "metabolic adjustments help organisms tolerate environmental conditions"],
    ["behavioural adaptation", "an inherited or learned action that improves survival or reproduction", "movement, timing or social behaviour can reduce exposure to challenges"],
    ["convergent evolution", "independent evolution of similar traits in unrelated lineages", "similar environmental pressures can favour analogous solutions"],
    ["trade-off", "a fitness compromise in which improving one function has a cost to another", "adaptations are constrained by energy, materials and evolutionary history"],
  ]),
  b("ib-bio-b42", "B4.2", "Ecological niches", "SL & HL", [
    ["ecological niche", "the full set of resources, conditions and interactions used by a species", "it describes how a species survives and contributes to its ecosystem"],
    ["fundamental niche", "the potential range of conditions and resources a species could use without biotic limits", "it is broader than the niche usually occupied in nature"],
    ["realized niche", "the part of the fundamental niche occupied after competition and other interactions", "biotic relationships restrict actual distribution and resource use"],
    ["competitive exclusion", "the principle that species with identical niches cannot coexist indefinitely", "competition favours displacement or niche differentiation"],
    ["resource partitioning", "division of resources by space, time or method among competing species", "it reduces niche overlap and allows coexistence"],
    ["keystone species", "a species with an ecological effect disproportionately large relative to abundance", "its removal can reorganize communities and alter many niches"],
  ]),
  b("ib-bio-c11", "C1.1", "Enzymes and metabolism", "SL & HL", [
    ["enzyme", "a biological catalyst that lowers activation energy without being consumed", "enzymes control reaction rates under cellular conditions"],
    ["active site", "the enzyme region where a specific substrate binds and reacts", "shape and chemical properties determine substrate specificity"],
    ["induced fit", "a conformational change that improves enzyme-substrate interaction after binding", "it positions reacting groups and can strain substrate bonds"],
    ["metabolic pathway", "a sequence of enzyme-catalysed reactions linking substrates and products", "regulation coordinates material and energy flow through cells"],
    ["competitive inhibitor", "a molecule that competes with substrate for the active site", "its effect can be reduced by increasing substrate concentration"],
    ["allosteric regulation", "control through binding at a site other than the active site", "it changes enzyme shape and supports feedback control of pathways"],
  ]),
  b("ib-bio-c12", "C1.2", "Cell respiration", "SL & HL", [
    ["ATP", "a nucleotide that transfers small amounts of usable energy between reactions", "respiration regenerates ATP to power cellular work"],
    ["glycolysis", "the cytoplasmic pathway splitting glucose into pyruvate", "it produces a small ATP yield and reduced electron carriers without requiring oxygen"],
    ["link reaction", "the conversion of pyruvate to acetyl coenzyme A", "it connects glycolysis to the Krebs cycle and releases carbon dioxide"],
    ["Krebs cycle", "a cyclic mitochondrial pathway oxidizing acetyl groups", "it releases carbon dioxide and transfers energy to reduced carriers"],
    ["electron transport chain", "a series of carriers transferring electrons and pumping protons across a membrane", "the resulting gradient drives ATP synthesis by chemiosmosis"],
    ["anaerobic respiration", "ATP production without oxygen through glycolysis and regeneration of oxidized carriers", "it sustains short-term ATP production but yields much less ATP per glucose"],
  ]),
  b("ib-bio-c13", "C1.3", "Photosynthesis", "SL & HL", [
    ["photosynthetic pigment", "a molecule that absorbs selected wavelengths of light", "pigments transfer excitation energy to reaction centres"],
    ["photosystem", "a pigment-protein complex that captures light and transfers excited electrons", "photosystems drive electron flow in the thylakoid membrane"],
    ["photolysis", "light-driven splitting of water", "it replaces electrons, releases oxygen and contributes protons for chemiosmosis"],
    ["photophosphorylation", "light-driven ATP production using an electron-transport proton gradient", "it supplies ATP for carbon fixation"],
    ["Calvin cycle", "a stromal pathway that fixes carbon dioxide and produces triose phosphate", "it uses ATP and reduced carriers from light-dependent reactions"],
    ["limiting factor", "the variable in shortest supply relative to photosynthetic demand", "changing it alters rate until another factor becomes limiting"],
  ]),
  b("ib-bio-c21", "C2.1", "Chemical signalling", "HL only", [
    ["ligand", "a signalling molecule that binds specifically to a receptor", "ligand binding initiates a cellular response without necessarily entering the cell"],
    ["receptor", "a protein that detects a specific signal and changes activity", "receptor distribution determines which cells respond"],
    ["signal transduction", "conversion of receptor activation into intracellular molecular events", "cascades relay and amplify information across the cell"],
    ["second messenger", "a small intracellular molecule produced or released after receptor activation", "it rapidly distributes and amplifies a signal"],
    ["hormone", "a chemical messenger transported to target cells in an organism", "hormones coordinate slower and often widespread physiological responses"],
    ["feedback regulation", "control in which a pathway's output influences earlier steps", "negative feedback stabilizes responses while positive feedback can amplify them"],
  ]),
  b("ib-bio-c22", "C2.2", "Neural signalling", "SL & HL", [
    ["resting potential", "the membrane voltage of an unstimulated neuron", "ion gradients and selective permeability prepare the membrane for rapid signalling"],
    ["action potential", "a rapid all-or-none reversal and restoration of membrane potential", "it propagates information along an axon without decreasing in size"],
    ["depolarization", "a change making membrane potential less negative", "opening sodium channels can trigger the rising phase of an action potential"],
    ["refractory period", "the period after an action potential when another is impossible or harder to trigger", "it enforces one-way propagation and limits maximum firing frequency"],
    ["synapse", "a junction where a neuron communicates with another cell", "chemical transmitter release converts an electrical signal into a controlled postsynaptic response"],
    ["myelin", "an insulating sheath around many axons", "it enables faster saltatory conduction between nodes"],
  ]),
  b("ib-bio-c31", "C3.1", "Integration of body systems", "SL & HL", [
    ["integration", "coordination of components so they function as a unified system", "nervous and endocrine signals match organ responses to changing needs"],
    ["sensor", "a cell or receptor that detects a change in a variable", "sensory information provides the input for regulation"],
    ["control centre", "a structure that compares information with a target and coordinates a response", "it integrates inputs and sends signals to effectors"],
    ["effector", "a muscle, gland or cell that carries out a response", "effectors change the regulated variable or produce behaviour"],
    ["organ system", "interacting organs performing major physiological functions", "exchange, transport and control systems depend on one another"],
    ["emergent property", "a system-level feature arising from interactions among components", "whole-body regulation cannot be explained by one organ acting alone"],
  ]),
  b("ib-bio-c32", "C3.2", "Defence against disease", "SL & HL", [
    ["pathogen", "an organism or agent capable of causing disease", "pathogen type and transmission route shape the host defence required"],
    ["physical barrier", "a surface defence that blocks pathogen entry", "skin and mucous membranes provide broad non-specific protection"],
    ["innate immunity", "rapid non-specific defence present before exposure", "inflammation and phagocytosis contain many infections early"],
    ["adaptive immunity", "specific defence involving lymphocyte recognition and memory", "clonal selection creates targeted responses and faster protection on re-exposure"],
    ["antibody", "a protein that binds a specific antigen", "binding can neutralize pathogens or mark them for destruction"],
    ["vaccination", "exposure to antigenic material that safely induces immune memory", "memory cells provide a faster and stronger response to later infection"],
  ]),
  b("ib-bio-c41", "C4.1", "Populations and communities", "SL & HL", [
    ["population", "members of one species living in the same area at the same time", "births, deaths and movement change population size"],
    ["community", "all interacting populations in an area", "competition, predation and mutualism shape community structure"],
    ["carrying capacity", "the largest population an environment can sustain over time", "limiting resources and density-dependent factors cause growth to level off"],
    ["density-dependent factor", "a factor whose effect strengthens as population density rises", "competition and disease help regulate crowded populations"],
    ["predation", "an interaction in which one organism kills and consumes another", "predator and prey numbers can influence one another through feedback"],
    ["mutualism", "an interaction in which both participating species gain a benefit", "mutual dependencies can affect survival, distribution and coevolution"],
  ]),
  b("ib-bio-c42", "C4.2", "Transfers of energy and matter", "SL & HL", [
    ["trophic level", "a feeding position in a food chain or web", "energy and biomass generally decrease at higher trophic levels"],
    ["primary productivity", "the rate at which producers convert external energy into chemical energy", "it sets the energy available to the rest of an ecosystem"],
    ["ecological efficiency", "the fraction of energy transferred from one trophic level to the next", "respiration, waste and uneaten material limit transfer"],
    ["decomposer", "an organism that externally digests dead material and waste", "decomposers release mineral nutrients for reuse by producers"],
    ["carbon cycle", "movement of carbon among organisms, atmosphere, water and rocks", "photosynthesis, respiration, decomposition and combustion link major carbon stores"],
    ["nitrogen cycle", "movement and transformation of nitrogen among atmosphere, soil and organisms", "microbial processes make nitrogen available and return it to the atmosphere"],
  ]),
  b("ib-bio-d11", "D1.1", "DNA replication", "SL & HL", [
    ["semi-conservative replication", "DNA copying in which each product contains one old and one new strand", "template strands preserve sequence information across cell generations"],
    ["helicase", "an enzyme that unwinds DNA and separates the strands", "it exposes bases so each strand can be copied"],
    ["DNA polymerase", "an enzyme that adds nucleotides to a growing DNA strand", "complementary pairing and proofreading support accurate replication"],
    ["leading strand", "the new strand synthesized continuously towards the replication fork", "its orientation allows polymerase to follow fork movement"],
    ["lagging strand", "the new strand synthesized discontinuously away from the fork", "short fragments are needed because polymerase works only in one direction"],
    ["DNA ligase", "an enzyme that joins adjacent DNA fragments by sealing the sugar-phosphate backbone", "it makes the lagging strand continuous after fragment synthesis"],
  ]),
  b("ib-bio-d12", "D1.2", "Protein synthesis", "SL & HL", [
    ["transcription", "synthesis of RNA using a DNA template", "it creates a portable copy of gene information for expression"],
    ["messenger RNA", "an RNA molecule carrying codons copied from a gene", "ribosomes read its sequence during translation"],
    ["translation", "assembly of a polypeptide according to an mRNA codon sequence", "it converts nucleic-acid information into amino-acid sequence"],
    ["transfer RNA", "an adaptor RNA carrying an amino acid and an anticodon", "anticodon-codon pairing places amino acids in the specified order"],
    ["ribosome", "the RNA-protein complex that coordinates mRNA and tRNA", "it catalyses peptide-bond formation during translation"],
    ["codon", "a three-base mRNA sequence specifying an amino acid or stop signal", "the sequence of codons determines primary protein structure"],
  ]),
  b("ib-bio-d13", "D1.3", "Mutation and gene editing", "SL & HL", [
    ["mutation", "a permanent change in a DNA sequence", "mutation creates new alleles and can alter gene function or regulation"],
    ["substitution", "replacement of one nucleotide by another", "it may be silent, change one amino acid or create a stop codon"],
    ["frameshift", "a reading-frame change caused by insertion or deletion not in multiples of three", "it can alter every downstream codon and severely affect protein function"],
    ["mutagen", "a physical or chemical agent that increases mutation rate", "radiation and reactive chemicals can damage DNA"],
    ["CRISPR-Cas", "a programmable gene-editing system using guide RNA and a DNA-cutting enzyme", "targeted breaks allow genes to be disrupted or changed"],
    ["off-target effect", "an unintended edit at a DNA sequence similar to the target", "it is a key safety and reliability concern in gene editing"],
  ]),
  b("ib-bio-d21", "D2.1", "Cell and nuclear division", "SL & HL", [
    ["cell cycle", "the ordered stages of growth, DNA replication and division", "checkpoints coordinate accurate genome duplication and distribution"],
    ["mitosis", "nuclear division producing genetically equivalent chromosome sets", "it supports growth, repair and asexual reproduction"],
    ["cytokinesis", "division of cytoplasm to form separate daughter cells", "it completes cell division after nuclear material separates"],
    ["meiosis", "two divisions producing haploid cells from one diploid cell", "it reduces chromosome number and creates variation for sexual reproduction"],
    ["crossing over", "exchange between non-sister chromatids of homologous chromosomes", "it creates recombinant chromosomes with new allele combinations"],
    ["independent assortment", "random orientation and separation of homologous chromosome pairs", "it generates many combinations of maternal and paternal chromosomes in gametes"],
  ]),
  b("ib-bio-d22", "D2.2", "Gene expression", "HL only", [
    ["gene regulation", "control of when and how strongly a gene is expressed", "it allows cells to respond to conditions and maintain specialized identities"],
    ["transcription factor", "a protein that influences transcription by binding regulatory DNA or other proteins", "combinations of factors activate or repress particular genes"],
    ["promoter", "a DNA region where transcription machinery assembles", "promoter accessibility and bound regulators affect transcription initiation"],
    ["epigenetic modification", "a heritable or stable change in gene activity without changing DNA sequence", "DNA methylation and histone changes alter chromatin accessibility"],
    ["alternative splicing", "production of different mature mRNAs from one pre-mRNA", "different exon combinations allow one gene to produce several polypeptides"],
    ["operon", "a group of prokaryotic genes controlled together by shared regulatory DNA", "operons coordinate expression of proteins in one pathway"],
  ]),
  b("ib-bio-d23", "D2.3", "Water potential", "SL & HL", [
    ["water potential", "the tendency of water to move relative to pure water under stated conditions", "water moves from higher to lower water potential across a permeable pathway"],
    ["solute potential", "the negative contribution dissolved solutes make to water potential", "adding solute lowers water potential and can draw water into a solution"],
    ["pressure potential", "the contribution of physical pressure to water potential", "positive pressure in turgid plant cells raises total water potential"],
    ["turgor pressure", "outward pressure of cell contents against a plant cell wall", "it supports non-woody tissues and limits further water entry"],
    ["plasmolysis", "separation of the plasma membrane from the cell wall after water loss", "it occurs when plant cells are placed in sufficiently low water potential"],
    ["isotonic condition", "a condition with no net water movement because water potentials are equal", "cells then show no continuing volume change from osmosis"],
  ]),
  b("ib-bio-d31", "D3.1", "Reproduction", "SL & HL", [
    ["sexual reproduction", "production of offspring through fusion of genetically different gametes", "meiosis and fertilization generate genetic variation"],
    ["asexual reproduction", "production of offspring from one parent without gamete fusion", "it can rapidly produce genetically similar offspring in stable conditions"],
    ["gamete", "a haploid reproductive cell specialized for fusion", "gamete union restores the diploid chromosome number"],
    ["fertilization", "fusion of gamete nuclei to form a zygote", "it combines parental alleles and initiates development"],
    ["pollination", "transfer of pollen to a compatible stigma in flowering plants", "it brings the male gametophyte to the female reproductive structure"],
    ["reproductive hormone", "a chemical messenger coordinating reproductive development and cycles", "hormone interactions regulate gamete production, ovulation and pregnancy"],
  ]),
  b("ib-bio-d32", "D3.2", "Inheritance", "SL & HL", [
    ["allele", "an alternative DNA sequence at a gene locus", "allele combinations contribute to genotype and inherited variation"],
    ["genotype", "the allele combination of an organism at specified loci", "genotype interacts with environment to influence phenotype"],
    ["phenotype", "an observable or measurable characteristic", "it results from gene expression and environmental effects"],
    ["dominance", "an interaction in which one allele determines the heterozygous phenotype", "dominance affects phenotype ratios but not allele segregation"],
    ["genetic cross", "a model predicting offspring genotypes from parental gametes", "probability and segregation rules generate expected ratios"],
    ["linkage", "the tendency of genes on the same chromosome to be inherited together", "crossing over can produce recombinants, with frequency related to gene distance"],
  ]),
  b("ib-bio-d33", "D3.3", "Homeostasis", "SL & HL", [
    ["homeostasis", "maintenance of internal conditions within limits despite change", "stable conditions allow enzymes and cells to function effectively"],
    ["negative feedback", "a response that opposes deviation from a target range", "it stabilizes variables such as temperature and blood glucose"],
    ["set point", "the target value or range used by a regulatory system", "sensors and control centres compare current conditions with this target"],
    ["thermoregulation", "control of body temperature", "heat production and heat loss are adjusted to protect physiological function"],
    ["blood-glucose regulation", "control of glucose concentration through hormones and tissue responses", "insulin and glucagon coordinate storage, release and uptake"],
    ["osmoregulation", "control of water and solute balance", "kidney function and hormones adjust water retention and urine concentration"],
  ]),
  b("ib-bio-d41", "D4.1", "Natural selection", "SL & HL", [
    ["heritable variation", "genetically based differences that can pass to offspring", "selection can change allele frequencies only when relevant variation is inherited"],
    ["selection pressure", "an environmental factor causing differences in survival or reproduction", "it determines which phenotypes have greater fitness in that context"],
    ["fitness", "relative reproductive contribution to future generations", "higher-fitness phenotypes pass associated alleles on more often"],
    ["directional selection", "selection favouring one extreme of a phenotypic range", "the population mean shifts towards the favoured extreme"],
    ["stabilizing selection", "selection favouring intermediate phenotypes", "variation narrows while the mean remains near the optimum"],
    ["antibiotic resistance", "ability of microbes to survive an antimicrobial treatment", "drug exposure selects resistant variants rather than causing purposeful adaptation"],
  ]),
  b("ib-bio-d42", "D4.2", "Stability and change", "SL & HL", [
    ["ecosystem stability", "the tendency of an ecosystem to maintain structure and function through time", "diversity and feedbacks can influence resistance to disturbance"],
    ["resistance", "the ability of a system to remain little changed during disturbance", "high resistance reduces immediate displacement from the previous state"],
    ["resilience", "the ability of a system to recover after disturbance", "recolonization, diversity and retained resources affect recovery rate"],
    ["ecological succession", "directional change in community composition over time", "colonization and environmental modification produce a sequence of communities"],
    ["tipping point", "a threshold beyond which feedback drives a large shift in system state", "small additional pressures can then cause difficult-to-reverse change"],
    ["regime shift", "a persistent reorganization into a different ecosystem state", "feedbacks can maintain the new state even if the original disturbance is reduced"],
  ]),
  b("ib-bio-d43", "D4.3", "Climate change", "SL & HL", [
    ["greenhouse effect", "warming caused when atmospheric gases absorb and re-emit outgoing infrared radiation", "it is natural but strengthened by increasing greenhouse-gas concentrations"],
    ["carbon sink", "a reservoir that absorbs more carbon than it releases over a period", "oceans, soils and vegetation can slow atmospheric carbon-dioxide increase"],
    ["climate feedback", "a process that amplifies or dampens an initial climate change", "ice-albedo and water-vapour feedbacks can alter warming"],
    ["ocean acidification", "decrease in seawater pH as dissolved carbon dioxide forms carbonic acid", "it reduces carbonate availability for many shell-forming organisms"],
    ["range shift", "movement of a species' geographic distribution as conditions change", "climate change can move suitable temperature and rainfall zones"],
    ["mitigation", "action that reduces greenhouse-gas sources or increases removals", "mitigation limits future climate change while adaptation addresses unavoidable effects"],
  ]),
];
