import type { IbTopicSpec } from "./ib-question-types";

const c = (
  id: string,
  code: string,
  name: string,
  level: "SL & HL" | "HL only",
  concepts: IbTopicSpec["concepts"],
): IbTopicSpec => ({ id, code, name, subject: "Chemistry", level, concepts });

export const chemistryIbTopicSpecs: IbTopicSpec[] = [
  c("ib-chem-s11", "Structure 1.1", "Introduction to the particulate nature of matter", "SL & HL", [
    ["particle model", "a model that describes matter as moving particles with spaces and attractions between them", "it explains physical states, diffusion and changes of state at a microscopic level"],
    ["element", "a pure substance made of atoms with the same proton number", "elements are the basic chemical identities used to classify matter"],
    ["compound", "a pure substance containing different elements chemically bonded in fixed proportions", "its properties differ from those of its constituent elements"],
    ["mixture", "two or more substances physically combined in variable proportions", "components retain their chemical identities and can be separated by physical methods"],
    ["physical change", "a change of state or form that does not create a new chemical substance", "particle arrangement or spacing changes while chemical identity remains the same"],
    ["separation technique", "a physical method that exploits differences such as boiling point, solubility or particle size", "it allows mixture components to be isolated without changing their chemical identities"],
  ]),
  c("ib-chem-s12", "Structure 1.2", "The nuclear atom", "SL & HL", [
    ["atomic number", "the number of protons in an atomic nucleus", "it defines the element and equals electron number in a neutral atom"],
    ["mass number", "the total number of protons and neutrons in a nucleus", "it distinguishes isotopes when combined with atomic number"],
    ["isotope", "atoms of one element with equal proton number but different neutron number", "isotopes share similar chemistry but differ in mass and nuclear stability"],
    ["relative atomic mass", "the weighted mean mass of an element's atoms relative to one twelfth of carbon-12", "it incorporates both isotope masses and their natural abundances"],
    ["mass spectrometry", "a technique that separates ions by mass-to-charge ratio", "its spectrum can be used to identify isotopes and calculate relative atomic mass"],
    ["nuclear symbol", "notation showing an element symbol with mass number and atomic number", "it enables proton, neutron and electron numbers to be determined for atoms and ions"],
  ]),
  c("ib-chem-s13", "Structure 1.3", "Electron configurations", "SL & HL", [
    ["energy level", "an allowed electron energy associated with a shell or orbital", "electron arrangements and transitions depend on quantized energy differences"],
    ["atomic orbital", "a region described by a wavefunction that can hold at most two opposite-spin electrons", "orbital type and energy determine electron configurations"],
    ["electron configuration", "the distribution of an atom's electrons among shells, subshells and orbitals", "it predicts valence behaviour and an element's position in the periodic table"],
    ["Aufbau principle", "the rule that electrons occupy available lower-energy orbitals before higher-energy ones", "it provides the normal filling order for ground-state configurations"],
    ["successive ionization energy", "the energy required to remove each electron in turn from gaseous particles", "large jumps reveal when removal begins from a lower principal energy level"],
    ["valence electron", "an electron in the outer occupied shell involved in chemical bonding", "valence configurations explain group trends and common ion charges"],
  ]),
  c("ib-chem-s14", "Structure 1.4", "Counting particles by mass: The mole", "SL & HL", [
    ["mole", "the amount containing exactly the Avogadro constant of specified entities", "it connects microscopic particle numbers to measurable laboratory quantities"],
    ["Avogadro constant", "the number of specified entities in one mole", "it converts between amount in moles and the number of particles"],
    ["molar mass", "the mass per mole of a substance", "it converts measured mass into chemical amount for stoichiometry"],
    ["empirical formula", "the simplest whole-number ratio of atoms or ions in a substance", "it is obtained from composition data or reacting amounts"],
    ["molecular formula", "the actual number of each type of atom in a molecule", "it is a whole-number multiple of the empirical formula and requires molar mass"],
    ["amount concentration", "the amount of solute in moles divided by solution volume", "it connects solution composition to reacting amounts and titration calculations"],
  ]),
  c("ib-chem-s15", "Structure 1.5", "Ideal gases", "SL & HL", [
    ["ideal gas", "a model gas of negligible-volume particles with no intermolecular forces and elastic collisions", "it provides a simple relationship among pressure, volume, temperature and amount"],
    ["gas pressure", "force per unit area caused by particle collisions with container walls", "its value changes with collision frequency and momentum transfer"],
    ["absolute temperature", "temperature measured in kelvin from absolute zero", "it is proportional to average translational kinetic energy in the ideal-gas model"],
    ["ideal gas equation", "the relationship pV = nRT", "it enables one gas variable to be calculated from the other equilibrium variables"],
    ["molar gas constant", "the constant R linking pressure, volume, amount and temperature", "consistent units for R and all measured quantities are essential in calculations"],
    ["real-gas deviation", "departure from ideal behaviour caused by particle volume and intermolecular attractions", "it becomes more important at high pressure and low temperature"],
  ]),
  c("ib-chem-s21", "Structure 2.1", "The ionic model", "SL & HL", [
    ["ion", "a charged particle formed when an atom or group gains or loses electrons", "oppositely charged ions are the building units of ionic substances"],
    ["ionic bond", "electrostatic attraction between oppositely charged ions", "strong non-directional attractions extend throughout an ionic lattice"],
    ["ionic lattice", "a repeating three-dimensional arrangement of cations and anions", "its structure accounts for high melting points and brittleness"],
    ["formula unit", "the simplest whole-number ratio of ions in an ionic compound", "charge balance determines the empirical formula of the compound"],
    ["lattice enthalpy", "the enthalpy change associated with forming or separating an ionic lattice under stated conventions", "its magnitude reflects ion charge, ion size and lattice attraction"],
    ["ionic conductivity", "movement of mobile ions that carries electric charge", "ionic substances conduct when molten or aqueous but not when ions are fixed in a solid"],
  ]),
  c("ib-chem-s22", "Structure 2.2", "The covalent model", "SL & HL", [
    ["covalent bond", "electrostatic attraction between nuclei and a shared pair of electrons", "directional electron sharing produces molecules and network structures"],
    ["Lewis structure", "a representation of bonding pairs, lone pairs and valence electrons", "it helps determine formal charge, connectivity and molecular shape"],
    ["electron-domain geometry", "the arrangement that minimizes repulsion among electron regions around a central atom", "it provides the basis of VSEPR predictions"],
    ["bond polarity", "unequal sharing of bonding electrons caused by an electronegativity difference", "bond dipoles combine with molecular shape to determine molecular polarity"],
    ["intermolecular force", "an attraction between separate particles rather than within a covalent bond", "its strength influences boiling point, volatility and solubility"],
    ["delocalization", "spreading of electrons over more than two atoms", "it stabilizes structures and makes a single localized-bond drawing incomplete"],
  ]),
  c("ib-chem-s23", "Structure 2.3", "The metallic model", "SL & HL", [
    ["metallic bond", "electrostatic attraction between positive metal ions and delocalized electrons", "non-directional bonding holds the lattice together while allowing layers to move"],
    ["delocalized electron", "a valence electron free to move through a metallic structure", "mobile electrons account for electrical and thermal conductivity"],
    ["metallic lattice", "a regular arrangement of positive ions surrounded by mobile electrons", "its packing and bonding influence density, strength and melting point"],
    ["malleability", "the ability to be shaped under compression without fracturing", "metal-ion layers can slide while metallic attraction persists"],
    ["ductility", "the ability to be drawn into a wire", "non-directional metallic bonding allows substantial shape change without breaking the structure"],
    ["alloy", "a metallic mixture containing atoms of more than one element", "different atom sizes disrupt layer movement and can increase hardness"],
  ]),
  c("ib-chem-s24", "Structure 2.4", "From models to materials", "SL & HL", [
    ["structure-property relationship", "the connection between microscopic arrangement and macroscopic material behaviour", "it allows bonding models to explain and predict material uses"],
    ["polymer", "a large molecule made from many repeating monomer units", "chain structure and intermolecular forces control flexibility, strength and thermal behaviour"],
    ["composite", "a material combining distinct components to obtain complementary properties", "the matrix and reinforcement work together to outperform either component alone"],
    ["allotrope", "one of several structural forms of the same element in the same physical state", "different bonding or arrangement gives allotropes different properties"],
    ["nanomaterial", "a material with important structural dimensions on the nanometre scale", "high surface-area-to-volume ratio and quantum effects can create unusual properties"],
    ["material selection", "choosing a substance by matching properties, cost and impacts to a purpose", "scientific models support evidence-based decisions about suitability and sustainability"],
  ]),
  c("ib-chem-s31", "Structure 3.1", "The periodic table: Classification of elements", "SL & HL", [
    ["periodicity", "the repeating pattern of properties when elements are arranged by atomic number", "it arises from recurring valence-electron configurations"],
    ["effective nuclear charge", "the net attractive nuclear charge experienced by an electron after shielding", "its increase across a period helps explain radius and ionization trends"],
    ["shielding", "reduction of nuclear attraction by electrons between the nucleus and an outer electron", "additional occupied shells weaken attraction down a group"],
    ["atomic radius", "a measure of atomic size based on distances between bonded nuclei", "it generally decreases across a period and increases down a group"],
    ["first ionization energy", "the energy required to remove one electron from each atom in one mole of gaseous atoms", "its trend reflects nuclear charge, shielding, distance and subshell stability"],
    ["electronegativity", "an atom's attraction for a shared pair of electrons in a bond", "differences in electronegativity help predict bond polarity and bonding type"],
  ]),
  c("ib-chem-s32", "Structure 3.2", "Functional groups: Classification of organic compounds", "SL & HL", [
    ["functional group", "a characteristic atom or group responsible for typical organic reactions", "it provides a basis for classifying and predicting the reactivity of organic compounds"],
    ["homologous series", "a family with the same functional group and general formula whose members differ by CH2", "members show similar chemistry and gradual physical-property trends"],
    ["IUPAC name", "a systematic name that communicates parent chain, substituents and functional groups", "consistent naming allows an organic structure to be reconstructed unambiguously"],
    ["structural isomer", "a compound with the same molecular formula but different atom connectivity", "different structures can produce different physical and chemical properties"],
    ["stereoisomer", "a compound with the same connectivity but a different three-dimensional arrangement", "geometry or chirality can affect reactivity and biological action"],
    ["spectroscopic identification", "use of characteristic interactions with electromagnetic radiation to infer structure", "IR, mass and NMR evidence can be combined to identify an unknown organic compound"],
  ]),
  c("ib-chem-r11", "Reactivity 1.1", "Measuring enthalpy changes", "SL & HL", [
    ["enthalpy change", "the heat transferred at constant pressure for a stated process", "its sign distinguishes energy released by the system from energy absorbed"],
    ["exothermic reaction", "a reaction with negative enthalpy change that transfers heat to the surroundings", "products lie at lower enthalpy than reactants"],
    ["endothermic reaction", "a reaction with positive enthalpy change that absorbs heat from the surroundings", "products lie at higher enthalpy than reactants"],
    ["calorimetry", "measurement of heat transfer from temperature change in a known system", "q = mc delta T links the observed change to reaction energy"],
    ["molar enthalpy change", "enthalpy change per mole of a specified reaction or substance", "it allows results from different reacting amounts to be compared"],
    ["energy profile", "a diagram showing enthalpy along a reaction pathway", "it displays activation energy and the difference between reactant and product enthalpies"],
  ]),
  c("ib-chem-r12", "Reactivity 1.2", "Energy cycles in reactions", "SL & HL", [
    ["Hess's law", "the rule that reaction enthalpy depends only on initial and final states", "alternative reaction pathways can be combined algebraically to find an unknown enthalpy"],
    ["standard enthalpy of formation", "the enthalpy change when one mole of a compound forms from its elements in standard states", "formation data provide a common route for calculating reaction enthalpy"],
    ["standard enthalpy of combustion", "the enthalpy change when one mole of substance burns completely in oxygen under standard conditions", "combustion cycles can determine otherwise difficult reaction enthalpies"],
    ["average bond enthalpy", "the mean enthalpy needed to break one mole of a specified gaseous bond", "bonds broken minus bonds formed gives an estimate of reaction enthalpy"],
    ["Born-Haber cycle", "a Hess cycle that separates ionic-solid formation into gaseous and ionic steps", "it links lattice enthalpy to atomization, ionization and electron-affinity data"],
    ["state function", "a property determined only by a system's current state, not the path taken", "enthalpy being a state function is the reason Hess cycles are valid"],
  ]),
  c("ib-chem-r13", "Reactivity 1.3", "Energy from fuels", "SL & HL", [
    ["fuel", "a substance that releases usable energy through a chemical or nuclear process", "fuel choice depends on energy yield, availability, handling and environmental impact"],
    ["specific energy", "energy released per unit mass of fuel", "it allows fuels with different molar masses to be compared for transport and storage"],
    ["complete combustion", "reaction with sufficient oxygen to form fully oxidized products", "for hydrocarbons it maximizes energy release and produces carbon dioxide and water"],
    ["incomplete combustion", "combustion with insufficient oxygen producing carbon monoxide or carbon", "it releases less energy and creates harmful pollutants"],
    ["fossil fuel", "a carbon-rich fuel formed over geological time from ancient biomass", "its use transfers stored carbon to the atmosphere and is not renewable on human timescales"],
    ["fuel cell", "an electrochemical cell supplied continuously with reactants to generate electrical energy", "it converts chemical energy directly and can reduce local pollution depending on the fuel source"],
  ]),
  c("ib-chem-r14", "Reactivity 1.4", "Entropy and spontaneity", "HL only", [
    ["entropy", "a state function related to energy dispersal and the number of accessible arrangements", "greater dispersal or more possible microstates generally means higher entropy"],
    ["spontaneous change", "a change thermodynamically able to proceed under stated conditions without continuous external work", "spontaneity depends on the total entropy change or Gibbs energy, not simply reaction speed"],
    ["Gibbs energy", "the state function G = H - TS used to predict spontaneity at constant temperature and pressure", "a negative reaction Gibbs energy favours the forward change"],
    ["standard entropy change", "the sum of product molar entropies minus the sum for reactants", "it quantifies the system's contribution to the entropy balance"],
    ["temperature dependence", "the way the T delta S term changes the balance between enthalpy and entropy", "some reactions become spontaneous only above or below a particular temperature"],
    ["thermodynamic equilibrium", "the state in which forward and reverse changes have no net driving force", "reaction Gibbs energy is zero and composition remains constant macroscopically"],
  ]),
  c("ib-chem-r21", "Reactivity 2.1", "How much? The amount of chemical change", "SL & HL", [
    ["stoichiometric ratio", "the mole ratio given by coefficients in a balanced chemical equation", "it converts the amount of one reactant or product into another"],
    ["limiting reactant", "the reactant consumed first and therefore fixing the maximum product amount", "excess reactant remains after the limiting reactant is used"],
    ["theoretical yield", "the maximum product amount predicted from stoichiometry and the limiting reactant", "it is the reference used to calculate percentage yield"],
    ["percentage yield", "actual yield divided by theoretical yield multiplied by 100 percent", "it measures how closely an experiment or process approaches the stoichiometric maximum"],
    ["atom economy", "the percentage of reactant atom mass incorporated into the desired product", "it evaluates waste inherent in the balanced reaction rather than experimental losses"],
    ["titration", "controlled reaction of measured solution volumes to determine an unknown amount or concentration", "the equivalence relationship and balanced equation supply the required mole ratio"],
  ]),
  c("ib-chem-r22", "Reactivity 2.2", "How fast? The rate of chemical change", "SL & HL", [
    ["reaction rate", "the change in reactant or product concentration per unit time", "it describes how quickly macroscopic composition changes"],
    ["collision theory", "the model that reactions require collisions with sufficient energy and suitable orientation", "it explains how temperature, concentration and surface area affect rate"],
    ["activation energy", "the minimum collision energy needed to reach the transition state", "a lower barrier increases the fraction of successful collisions"],
    ["catalyst", "a substance that increases reaction rate by providing a lower-activation-energy pathway", "it is regenerated and does not change the equilibrium constant"],
    ["rate expression", "an equation relating rate to reactant concentrations raised to experimentally determined powers", "it identifies how strongly each concentration affects rate"],
    ["reaction order", "the exponent of a concentration term in a rate expression", "it must be determined experimentally and can help test a proposed mechanism"],
  ]),
  c("ib-chem-r23", "Reactivity 2.3", "How far? The extent of chemical change", "SL & HL", [
    ["dynamic equilibrium", "the state in a closed system where forward and reverse reaction rates are equal", "concentrations remain constant even though reactions continue microscopically"],
    ["equilibrium constant", "the ratio of product and reactant activities or concentrations at equilibrium for a stated temperature", "its magnitude indicates the equilibrium position and changes only with temperature"],
    ["reaction quotient", "an expression with the equilibrium-constant form evaluated at any composition", "comparison with K predicts the direction of net change towards equilibrium"],
    ["Le Chatelier's principle", "the idea that an equilibrium shifts to oppose an imposed change", "it predicts qualitative effects of concentration, pressure and temperature changes"],
    ["equilibrium yield", "the product amount present when dynamic equilibrium is reached", "conditions can be chosen to balance yield, rate, cost and safety"],
    ["equilibrium free energy", "the relationship between Gibbs energy, reaction quotient and equilibrium constant", "it links thermodynamic driving force to equilibrium composition"],
  ]),
  c("ib-chem-r31", "Reactivity 3.1", "Proton transfer reactions", "SL & HL", [
    ["Bronsted-Lowry acid", "a species that donates a proton", "acid reactions are analysed by identifying the proton transferred to a base"],
    ["Bronsted-Lowry base", "a species that accepts a proton", "it forms a conjugate acid after proton gain"],
    ["conjugate acid-base pair", "two species differing by one proton", "stronger acids have weaker conjugate bases and vice versa"],
    ["pH", "the negative base-ten logarithm of hydrogen-ion activity or concentration in dilute solution", "it expresses acidity on a convenient logarithmic scale"],
    ["acid dissociation constant", "the equilibrium constant Ka for proton donation by an acid in water", "its magnitude or pKa indicates acid strength"],
    ["buffer solution", "a solution that resists pH change when small amounts of acid or base are added", "a weak acid-base conjugate pair removes added hydrogen or hydroxide ions"],
  ]),
  c("ib-chem-r32", "Reactivity 3.2", "Electron transfer reactions", "SL & HL", [
    ["oxidation", "loss of electrons or an increase in oxidation state", "it occurs together with reduction in every redox reaction"],
    ["reduction", "gain of electrons or a decrease in oxidation state", "the reducing species accepts electrons and changes oxidation state"],
    ["oxidation state", "a formal charge assigned by electron-allocation rules", "changes in oxidation state identify which atoms are oxidized and reduced"],
    ["voltaic cell", "an electrochemical cell that uses a spontaneous redox reaction to produce electrical energy", "separated half-reactions drive electrons through an external circuit"],
    ["standard electrode potential", "the reduction potential of a half-cell measured relative to the standard hydrogen electrode", "differences between potentials predict standard cell voltage and reaction feasibility"],
    ["electrolysis", "use of electrical energy to drive a non-spontaneous redox reaction", "charge, current and time determine the amount transformed at electrodes"],
  ]),
  c("ib-chem-r33", "Reactivity 3.3", "Electron sharing reactions", "SL & HL", [
    ["homolytic fission", "bond breaking in which each atom takes one electron from the shared pair", "it forms radicals and is promoted by energy such as ultraviolet light"],
    ["radical", "a species containing an unpaired electron", "its high reactivity drives chain mechanisms"],
    ["radical substitution", "a chain reaction in which a radical replaces an atom or group in a molecule", "initiation, propagation and termination steps explain product formation"],
    ["initiation step", "a step that creates radicals, often by homolytic bond breaking", "it starts a radical chain reaction"],
    ["propagation step", "a step that consumes one radical and produces another", "it continues the chain while forming reaction products"],
    ["termination step", "a step in which radicals combine to form non-radical products", "it removes chain carriers and brings chains to an end"],
  ]),
  c("ib-chem-r34", "Reactivity 3.4", "Electron-pair sharing reactions", "SL & HL", [
    ["heterolytic fission", "bond breaking in which one atom takes both electrons from the shared pair", "it forms ions and creates electrophilic or nucleophilic reaction centres"],
    ["nucleophile", "an electron-pair donor attracted to an electron-deficient centre", "it forms a new covalent bond by supplying both bonding electrons"],
    ["electrophile", "an electron-pair acceptor attracted to an electron-rich centre", "it reacts with nucleophiles or pi bonds"],
    ["curly arrow", "a mechanism symbol showing movement of an electron pair from its source to its destination", "correct arrows account for bond breaking, bond making and charge changes"],
    ["nucleophilic substitution", "a reaction in which a nucleophile replaces a leaving group", "its pathway depends on substrate structure, nucleophile and reaction conditions"],
    ["electrophilic addition", "a reaction in which an electrophile attacks a pi bond and atoms add across it", "the electron-rich double bond is converted into stronger sigma bonds"],
  ]),
];
