import type { IbTopicSpec } from "./ib-question-types";

const p = (
  id: string,
  code: string,
  name: string,
  level: "SL & HL" | "HL only",
  concepts: IbTopicSpec["concepts"],
): IbTopicSpec => ({ id, code, name, subject: "Physics", level, concepts });

export const physicsIbTopicSpecs: IbTopicSpec[] = [
  p("ib-physics-a1", "A.1", "Kinematics", "SL & HL", [
    ["distance", "the total path length travelled by an object", "it is a scalar quantity and does not include direction"],
    ["displacement", "the vector change in position from start to finish", "it includes both magnitude and direction"],
    ["velocity", "the rate of change of displacement", "its sign and direction describe motion in one or more dimensions"],
    ["acceleration", "the rate of change of velocity", "it describes how velocity changes with time"],
    ["motion graph", "a graph showing how displacement, velocity or acceleration changes with time", "gradients and areas can be used to determine motion quantities"],
    ["kinematic equation", "an equation connecting displacement, initial velocity, final velocity, acceleration and time for constant acceleration", "it is used when acceleration is uniform"],
    ["projectile motion", "two-dimensional motion under gravity when air resistance is neglected", "horizontal velocity is constant while vertical motion has gravitational acceleration"],
    ["fluid resistance", "a resistive force that opposes the motion of an object through a fluid", "it increases as the relative speed through the fluid increases"],
    ["terminal speed", "the constant speed reached when resistive forces balance the driving force", "the resultant force and acceleration are then zero"],
  ]),
  p("ib-physics-a2", "A.2", "Forces and momentum", "SL & HL", [
    ["free-body diagram", "a diagram showing the external forces acting on one chosen object", "it allows the resultant force and force components to be analysed"],
    ["Newton's first law", "the principle that an object remains at rest or at constant velocity unless acted on by a resultant force", "it describes motion when the resultant force is zero"],
    ["Newton's second law", "the rate of change of momentum is proportional to the resultant force", "for constant mass it gives F = ma"],
    ["Newton's third law", "the principle that interacting bodies exert equal-magnitude opposite-direction forces on each other", "the two forces act on different bodies"],
    ["friction", "a contact force that opposes relative motion or attempted motion between surfaces", "it acts parallel to the surfaces in contact"],
    ["Hooke's law", "the relationship in which extension is proportional to force within the elastic limit", "the spring constant gives the force required per unit extension"],
    ["Stokes' law", "the relationship for the viscous drag force on a small sphere moving slowly through a fluid", "the drag force depends on viscosity, sphere radius and speed"],
    ["upthrust", "the upward force exerted by a fluid on an immersed object", "it results from the pressure difference between the lower and upper surfaces"],
    ["momentum", "the vector product of mass and velocity", "total momentum is conserved in an isolated system"],
    ["impulse", "the change in momentum, equal to force multiplied by the time for which it acts", "the area under a force-time graph gives impulse"],
    ["collision", "an interaction in which objects exert forces on each other for a short time", "momentum is conserved for an isolated collision system"],
    ["angular velocity", "the rate of change of angular displacement", "it is used to describe circular motion"],
    ["centripetal acceleration", "the acceleration directed towards the centre of a circular path", "it changes the direction of velocity in circular motion"],
    ["centripetal force", "the resultant inward force that produces centripetal acceleration", "it is directed towards the centre of the circular path"],
  ]),
  p("ib-physics-a3", "A.3", "Work, energy and power", "SL & HL", [
    ["energy conservation", "the principle that total energy in a closed system remains constant", "energy can be transferred between stores but is not created or destroyed"],
    ["Sankey diagram", "a flow diagram in which arrow widths represent amounts of energy transferred", "it shows useful and dissipated energy pathways"],
    ["work", "energy transferred when a force acts through a displacement", "only the component of force parallel to the displacement does mechanical work"],
    ["kinetic energy", "the energy associated with motion, equal to one half mv squared", "the change in kinetic energy equals the net work done"],
    ["gravitational potential energy", "energy associated with position in a gravitational field", "near Earth's surface its change is mg times the vertical height change"],
    ["elastic potential energy", "energy stored when an elastic object is stretched or compressed", "for a Hooke's-law spring it equals one half kx squared"],
    ["mechanical energy", "the sum of kinetic and potential energies in a system", "it is conserved when no energy is dissipated by non-conservative forces"],
    ["power", "the rate at which work is done or energy is transferred", "it compares how quickly energy is transferred"],
    ["efficiency", "the ratio of useful energy or power output to total input", "it measures the fraction of input transferred usefully"],
    ["energy density", "energy stored or released per unit mass or per unit volume as specified", "it allows the energy available from different systems or fuels to be compared"],
  ]),
  p("ib-physics-a4", "A.4", "Rigid body mechanics", "HL only", [
    ["torque", "the turning effect of a force about an axis", "it equals force multiplied by perpendicular distance from the axis"],
    ["couple", "a pair of equal and opposite forces separated by a distance", "it produces a turning effect with no resultant force"],
    ["rotational equilibrium", "the condition in which the resultant torque on a body is zero", "clockwise and anticlockwise torques balance"],
    ["angular displacement", "the angle through which an object rotates about an axis", "it is measured in radians for rotational calculations"],
    ["angular velocity", "the rate of change of angular displacement", "it describes how quickly rotational position changes"],
    ["angular acceleration", "the rate of change of angular velocity", "it is produced by a non-zero resultant torque"],
    ["moment of inertia", "the rotational analogue of mass that depends on how mass is distributed about an axis", "a larger moment of inertia gives less angular acceleration for the same torque"],
    ["Newton's second law for rotation", "the relationship between resultant torque, moment of inertia and angular acceleration", "it is the rotational analogue of F = ma"],
    ["angular momentum", "the rotational quantity equal to moment of inertia multiplied by angular velocity", "it is conserved when resultant external torque is zero"],
    ["angular impulse", "the change in angular momentum produced by torque acting for a time interval", "it is the rotational analogue of linear impulse"],
    ["rotational kinetic energy", "the kinetic energy of a rotating body, equal to one half I omega squared", "it must be included when energy is shared between translation and rotation"],
  ]),
  p("ib-physics-a5", "A.5", "Galilean and special relativity", "HL only", [
    ["reference frame", "a coordinate system and clock used by an observer to describe events", "measurements of position, time and velocity are made relative to a chosen frame"],
    ["inertial reference frame", "a frame in which an object with no resultant force moves at constant velocity", "the laws of physics take the same form in all inertial frames"],
    ["Galilean transformation", "the classical relationship between positions and velocities in frames moving at constant relative velocity", "it is appropriate at speeds much smaller than the speed of light"],
    ["special relativity", "the theory based on identical physical laws in inertial frames and invariant vacuum light speed", "it changes classical relationships between space and time at high relative speeds"],
    ["Lorentz transformation", "the transformation relating space and time coordinates between inertial frames in special relativity", "it replaces the Galilean transformation at relativistic speeds"],
    ["relativistic velocity addition", "the transformation used to combine velocities between inertial frames", "it ensures the calculated speed of light remains invariant"],
    ["spacetime interval", "a quantity combining space and time separations that is invariant between inertial frames", "it provides an observer-independent relationship between events"],
    ["time dilation", "the increase in measured time interval for a moving clock compared with its proper time", "it becomes significant when relative speed is a substantial fraction of light speed"],
    ["length contraction", "the reduction in measured length parallel to motion relative to proper length", "the contraction is described by the Lorentz factor"],
    ["relativity of simultaneity", "the principle that events simultaneous in one inertial frame need not be simultaneous in another", "simultaneity depends on the observer's state of motion"],
    ["spacetime diagram", "a graph showing the positions and times of events and worldlines", "it is used to compare measurements made in different inertial frames"],
  ]),
  p("ib-physics-b1", "B.1", "Thermal energy transfers", "SL & HL", [
    ["density", "mass per unit volume", "it links the mass and volume of solids, liquids and gases"],
    ["absolute temperature", "temperature measured from absolute zero on the kelvin scale", "kelvin temperature is used in microscopic and thermal relationships"],
    ["temperature", "a measure related to the average random kinetic energy of particles", "temperature difference determines the direction of net thermal energy transfer"],
    ["internal energy", "the total random kinetic and intermolecular potential energy of particles in a system", "heating and work can change internal energy"],
    ["thermal equilibrium", "the condition in which objects in thermal contact have the same temperature", "there is then no net thermal energy transfer between them"],
    ["specific heat capacity", "the energy required to raise the temperature of one kilogram by one kelvin", "it connects energy transfer to mass and temperature change"],
    ["specific latent heat", "the energy per kilogram needed for a change of state at constant temperature", "energy changes particle potential energy while temperature stays constant"],
    ["thermal conduction", "thermal energy transfer through particle interactions within a material", "the rate depends on temperature gradient, conductivity and geometry"],
    ["thermal convection", "thermal energy transfer by bulk motion of a fluid", "density differences can produce convection currents"],
    ["thermal radiation", "energy transfer by electromagnetic radiation", "it can occur through a vacuum and depends on temperature and surface properties"],
    ["luminosity", "the total power radiated by an object such as a star", "apparent brightness also depends on the observer's distance from the source"],
    ["Stefan-Boltzmann law", "the relationship in which radiated power per unit area is proportional to the fourth power of absolute temperature", "it connects temperature, surface area and luminosity"],
    ["Wien's displacement law", "the relationship between absolute temperature and the wavelength of peak emission", "hotter objects have a shorter peak-emission wavelength"],
  ]),
  p("ib-physics-b2", "B.2", "Greenhouse effect", "SL & HL", [
    ["albedo", "the fraction of incident radiation reflected by a surface", "a higher albedo reduces the fraction of incoming solar energy absorbed"],
    ["emissivity", "the ratio of radiation emitted by a surface to that emitted by a black body at the same temperature", "surface properties affect thermal radiation emission"],
    ["solar constant", "the solar power received per unit area at Earth's orbit on a surface perpendicular to the rays", "it is used when calculating incoming solar power"],
    ["greenhouse gas", "an atmospheric gas that absorbs and re-emits particular infrared wavelengths", "it reduces the rate at which infrared energy escapes directly to space"],
    ["greenhouse effect", "the warming effect produced when atmospheric gases absorb and re-emit outgoing infrared radiation", "it raises Earth's surface temperature above the value expected without an absorbing atmosphere"],
    ["energy balance", "the comparison of incoming absorbed solar power with outgoing thermal radiation", "a stable average temperature requires incoming and outgoing power to balance"],
  ]),
  p("ib-physics-b3", "B.3", "Gas laws", "SL & HL", [
    ["gas pressure", "force per unit area caused by particle collisions with container walls", "more frequent or more forceful collisions raise gas pressure"],
    ["amount of substance", "the quantity of particles measured in moles", "one mole contains Avogadro's number of particles"],
    ["Boyle's law", "the inverse relationship between pressure and volume for a fixed amount of gas at constant temperature", "the product pV remains constant under these conditions"],
    ["Charles' law", "the direct relationship between volume and absolute temperature for a fixed amount of gas at constant pressure", "volume is proportional to kelvin temperature"],
    ["pressure law", "the direct relationship between pressure and absolute temperature for a fixed amount of gas at constant volume", "pressure is proportional to kelvin temperature"],
    ["ideal gas", "a model gas of negligible-volume particles with elastic collisions and no intermolecular forces", "it connects macroscopic gas variables to a simple particle model"],
    ["ideal gas equation", "the relationship pV = nRT for an ideal gas", "it connects pressure, volume, amount of substance and absolute temperature"],
    ["kinetic theory of gases", "a particle model that explains gas behaviour using random molecular motion and elastic collisions", "gas pressure results from momentum changes during collisions with container walls"],
    ["average molecular kinetic energy", "the mean translational kinetic energy of a gas molecule", "it is proportional to absolute temperature"],
  ]),
  p("ib-physics-b4", "B.4", "Thermodynamics", "HL only", [
    ["thermodynamic system", "the chosen matter or region being studied in a thermodynamic process", "energy can cross the system boundary as heating or work depending on the system type"],
    ["first law of thermodynamics", "the conservation statement relating internal-energy change, heating and work", "it accounts for energy transferred into or out of a thermodynamic system"],
    ["entropy", "a state quantity related to the dispersal of energy and number of accessible microstates", "entropy change is used to determine the direction of thermodynamic processes"],
    ["second law of thermodynamics", "the principle that natural processes have a preferred direction associated with total entropy increase", "it limits the efficiency of heat engines"],
    ["isothermal process", "a thermodynamic process at constant temperature", "for an ideal gas the internal energy does not change during an isothermal process"],
    ["isovolumetric process", "a thermodynamic process at constant volume", "no pressure-volume work is done when volume does not change"],
    ["isobaric process", "a thermodynamic process at constant pressure", "work done by the gas is pressure multiplied by volume change"],
    ["adiabatic process", "a thermodynamic process with no thermal energy transferred to or from the system", "changes in internal energy are linked to work done"],
    ["heat engine", "a cyclic device that takes in energy at high temperature, does work and rejects energy at lower temperature", "its efficiency is constrained by the first and second laws"],
    ["Carnot cycle", "an ideal reversible cycle operating between hot and cold reservoirs", "it sets the maximum possible heat-engine efficiency for the two reservoir temperatures"],
    ["pressure-volume diagram", "a graph representing thermodynamic states and processes using pressure and volume", "the area under a process curve represents work done by the gas"],
  ]),
  p("ib-physics-b5", "B.5", "Current and circuits", "SL & HL", [
    ["circuit diagram", "a diagram that uses standard symbols to represent electrical components and connections", "it shows how components are connected in a circuit"],
    ["electric current", "the rate of flow of electric charge", "conventional current is defined in the direction of positive charge flow"],
    ["potential difference", "the energy transferred per unit charge between two points", "it measures electrical energy transfer per coulomb"],
    ["electrical conductor", "a material in which charge carriers can move and produce an electric current", "conductors allow charge to flow when a potential difference is applied"],
    ["resistance", "the ratio of potential difference to current for a component", "it quantifies opposition to charge flow"],
    ["resistivity", "a material property relating resistance to conductor length and cross-sectional area", "it allows the resistance of different conductor geometries to be compared"],
    ["Ohm's law", "the proportional relationship between current and potential difference at constant physical conditions", "an ohmic component has a linear current-potential-difference characteristic"],
    ["series circuit", "a circuit in which components lie on one current path", "the same current flows through series components and potential differences add"],
    ["parallel circuit", "a circuit in which components are connected across the same two points", "parallel branches have the same potential difference and current divides between branches"],
    ["electrical power", "the rate at which electrical energy is transferred", "it can be calculated from current and potential difference"],
    ["electromotive force", "the energy supplied by a source per unit charge", "it is the source voltage when no current is drawn"],
    ["internal resistance", "the resistance inside a source of electrical energy", "it causes terminal potential difference to fall below emf when current flows"],
    ["variable resistor", "a component whose resistance can be changed", "it is used to control current or potential difference in a circuit"],
  ]),
  p("ib-physics-c1", "C.1", "Simple harmonic motion", "SL & HL", [
    ["oscillation", "repeated motion about an equilibrium position", "period, frequency and amplitude are used to describe oscillatory motion"],
    ["equilibrium position", "the position where the resultant force on an oscillator is zero", "displacement is measured from this position"],
    ["simple harmonic motion", "oscillation in which acceleration is proportional to displacement and directed towards equilibrium", "the restoring acceleration is opposite to displacement"],
    ["amplitude", "the maximum magnitude of displacement from equilibrium", "it gives the greatest displacement reached during the oscillation"],
    ["angular frequency", "the rate of phase change in radians per second", "it is related to frequency and period"],
    ["mass-spring period", "the time for one oscillation of an ideal mass-spring system", "the period depends on mass and spring constant but not amplitude"],
    ["simple pendulum period", "the time for one small-angle oscillation of a simple pendulum", "the period depends on pendulum length and gravitational field strength"],
    ["SHM energy", "the sum of kinetic and potential energy during simple harmonic motion", "in an ideal oscillator energy transfers between kinetic and potential forms while the total remains constant"],
  ]),
  p("ib-physics-c2", "C.2", "Wave model", "SL & HL", [
    ["wave", "a travelling disturbance that transfers energy without net transfer of matter", "wave behaviour is described using amplitude, wavelength, frequency and speed"],
    ["amplitude", "the maximum displacement of an oscillating point from equilibrium", "greater amplitude corresponds to greater wave energy or intensity for the same system"],
    ["wavelength", "the shortest distance between points in the same phase", "together with frequency it determines wave speed"],
    ["frequency", "the number of complete oscillations passing a point per second", "it is fixed by the source and remains unchanged at a boundary"],
    ["wave speed", "the distance travelled by a wave disturbance per unit time", "it equals frequency multiplied by wavelength"],
    ["transverse wave", "a wave in which oscillations are perpendicular to the direction of energy transfer", "electromagnetic waves are transverse"],
    ["longitudinal wave", "a wave in which oscillations are parallel to the direction of energy transfer", "sound in air travels as compressions and rarefactions"],
    ["sound wave", "a longitudinal mechanical wave produced by oscillations in a medium", "it requires a medium and cannot travel through a vacuum"],
    ["electromagnetic wave", "a transverse wave of oscillating electric and magnetic fields", "electromagnetic waves can travel through a vacuum"],
  ]),
  p("ib-physics-c3", "C.3", "Wave phenomena", "SL & HL", [
    ["wavefront", "a line or surface joining points on a wave that are in the same phase", "rays are drawn perpendicular to wavefronts to show the direction of travel"],
    ["reflection", "the change in direction when a wave returns from a boundary", "the angle of reflection equals the angle of incidence"],
    ["refraction", "a change in wave direction caused by a change in speed across a boundary", "frequency stays constant while speed and wavelength change"],
    ["transmission", "the passage of wave energy through a boundary into another medium", "energy can be split between reflected and transmitted waves"],
    ["diffraction", "the spreading of a wave after an aperture or around an obstacle", "it is strongest when the aperture or obstacle size is comparable to wavelength"],
    ["superposition", "the principle that overlapping wave displacements add algebraically", "it explains interference patterns"],
    ["interference", "the redistribution of intensity when coherent waves superpose", "path difference determines whether reinforcement or cancellation occurs"],
    ["Young's double-slit experiment", "an interference experiment using coherent waves from two narrow openings", "fringe spacing depends on wavelength, slit separation and screen distance"],
  ]),
  p("ib-physics-c4", "C.4", "Standing waves and resonance", "SL & HL", [
    ["standing wave", "a fixed pattern formed by equal-frequency waves travelling in opposite directions", "it contains stationary nodes and antinodes"],
    ["node", "a point in a standing wave with zero amplitude", "destructive interference occurs there at all times"],
    ["antinode", "a point in a standing wave with maximum amplitude", "constructive interference is greatest there"],
    ["boundary condition", "a restriction on the displacement at the ends or boundaries of a standing-wave system", "it determines which standing-wave wavelengths are allowed"],
    ["fundamental frequency", "the lowest natural frequency of a standing-wave system", "higher harmonics occur at allowed multiples or related modes set by the boundaries"],
    ["harmonic", "an allowed standing-wave mode above the fundamental", "strings and pipes support characteristic harmonic patterns"],
    ["natural frequency", "a frequency at which a system oscillates freely after disturbance", "driving near a natural frequency can produce resonance"],
    ["resonance", "a large-amplitude response when driving frequency matches a natural frequency", "energy transfer to the oscillator is greatest near resonance"],
    ["damping", "the removal of mechanical energy from an oscillator by resistive forces", "greater damping lowers and broadens the resonance peak"],
  ]),
  p("ib-physics-c5", "C.5", "Doppler effect", "SL & HL", [
    ["Doppler effect", "the change in observed frequency caused by relative motion between source and observer", "approach raises observed frequency while separation lowers it"],
    ["observed frequency", "the rate at which wavefronts arrive at an observer", "it differs from emitted frequency when source-observer separation changes"],
    ["moving source", "a source whose motion changes wavefront spacing in the medium", "wavefronts bunch ahead of the source and spread behind it"],
    ["moving observer", "an observer whose motion changes the rate at which wavefronts are encountered", "motion towards the source increases the arrival rate"],
    ["redshift", "a shift of received electromagnetic radiation towards longer wavelength", "it is observed when an astronomical source is receding"],
    ["blueshift", "a shift of received electromagnetic radiation towards shorter wavelength", "it is observed when a source is approaching"],
    ["galactic redshift", "the redshift observed in light from distant galaxies", "larger redshift indicates greater recession speed in the non-relativistic treatment used here"],
  ]),
  p("ib-physics-d1", "D.1", "Gravitational fields", "SL & HL", [
    ["Newton's law of gravitation", "the inverse-square attractive force law between two point masses", "the force depends on both masses and the square of their separation"],
    ["gravitational field strength", "force per unit mass at a point in a gravitational field", "it is also the acceleration of a freely falling test mass"],
    ["gravitational field line", "a line whose tangent gives the direction of the gravitational field", "closer line spacing represents a stronger field"],
    ["inverse-square law", "a relationship in which field strength decreases with the square of distance", "it describes the radial gravitational field outside a spherical mass"],
    ["Kepler's first law", "the law that planets move in elliptical orbits with the Sun at one focus", "it describes the shape of planetary orbits"],
    ["Kepler's second law", "the law that a line from the Sun to a planet sweeps out equal areas in equal times", "a planet moves faster when it is nearer the Sun"],
    ["Kepler's third law", "the relationship in which orbital period squared is proportional to orbital radius cubed for bodies orbiting the same central mass", "it links orbital period and size"],
    ["circular orbit", "motion in which gravity supplies the centripetal force", "orbital speed follows from equating gravitational and centripetal forces"],
  ]),
  p("ib-physics-d2", "D.2", "Electric and magnetic fields", "SL & HL", [
    ["electric charge", "a property of matter that causes electric forces", "charge is quantized in integer multiples of the elementary charge"],
    ["Millikan oil-drop experiment", "an experiment that measured the elementary electric charge using charged oil droplets", "it provided evidence that electric charge is quantized"],
    ["static electricity", "the build-up of electric charge on an object", "charge can be transferred by processes such as friction or contact"],
    ["Coulomb's law", "the inverse-square force law between point charges", "the force depends on both charges and the square of their separation"],
    ["electric field strength", "force per unit positive test charge", "it gives the direction and magnitude of electrical force at a point"],
    ["electric field line", "a line whose tangent gives the direction of an electric field", "line spacing indicates relative field strength"],
    ["magnetic field", "a region in which magnetic materials, currents or moving charges experience magnetic forces", "magnetic field direction is represented by field lines"],
    ["magnetic flux density", "a measure of magnetic field strength defined through force on a current or moving charge", "it determines the magnitude of magnetic force in field calculations"],
  ]),
  p("ib-physics-d3", "D.3", "Motion in electromagnetic fields", "SL & HL", [
    ["electric force on a charge", "the force qE on a charge in an electric field", "the force can change both the speed and direction of a charged particle"],
    ["charged particle in an electric field", "motion produced when an electric field exerts force on a charged particle", "a uniform electric field produces constant acceleration when other forces are negligible"],
    ["magnetic force on a charge", "the force on a moving charge in a magnetic field", "the force is perpendicular to velocity and field and does no work"],
    ["charged particle in a magnetic field", "motion produced when magnetic force acts on a moving charged particle", "a perpendicular magnetic force can produce circular motion"],
    ["charged particle in electric and magnetic fields", "motion determined by the combined effects of electric and magnetic forces", "the two forces may reinforce or oppose each other depending on directions"],
    ["magnetic force on a current-carrying conductor", "the force on a conductor carrying current in a magnetic field", "the force depends on magnetic flux density, current, conductor length and angle"],
    ["force between parallel conductors", "the magnetic interaction between current-carrying parallel wires", "currents in the same direction attract and currents in opposite directions repel"],
    ["circular particle path", "the circular motion produced when magnetic force supplies the centripetal force", "the path radius depends on momentum, charge and magnetic flux density"],
  ]),
  p("ib-physics-d4", "D.4", "Induction", "HL only", [
    ["electromagnetic induction", "the production of an emf by changing magnetic flux linkage", "relative motion or a changing magnetic field can produce an induced emf"],
    ["magnetic flux", "the product of magnetic flux density and perpendicular area for a uniform field", "it measures magnetic field passing through a surface"],
    ["flux linkage", "magnetic flux through one loop multiplied by the number of turns", "its rate of change determines induced emf"],
    ["Faraday's law", "the law that induced emf equals the negative rate of change of flux linkage", "faster flux change or more turns produces a larger induced emf"],
    ["Lenz's law", "the rule that induced effects oppose the change that produces them", "it sets the direction of induced current and expresses energy conservation"],
    ["self-induction", "induction in which a changing current in a circuit produces an emf in the same circuit", "the induced emf opposes the change in current"],
    ["mutual induction", "induction in which a changing current in one circuit produces an emf in a neighbouring circuit", "it is the operating principle of a transformer"],
    ["transformer", "a device that uses mutual induction to change alternating voltage and current", "the turns ratio links input and output voltages in an ideal transformer"],
    ["AC generator", "a device that converts mechanical energy to electrical energy by rotating a coil in a magnetic field", "rotation produces a changing flux linkage and an alternating emf"],
  ]),
  p("ib-physics-e1", "E.1", "Structure of the atom", "SL & HL", [
    ["Rutherford gold-foil experiment", "an alpha-scattering experiment that tested the structure of the atom", "rare large deflections provided evidence for a small dense positive nucleus"],
    ["nuclear notation", "notation showing an element symbol together with nucleon number and proton number", "it identifies the numbers of protons and neutrons in a nucleus"],
    ["atomic energy level", "an allowed discrete energy state for an electron in an atom", "transitions between levels explain line spectra"],
    ["emission spectrum", "discrete wavelengths emitted when excited electrons move to lower energy levels", "each element has a characteristic line spectrum"],
    ["absorption spectrum", "dark wavelengths produced when atoms absorb photons matching energy gaps", "the missing wavelengths correspond to allowed upward electron transitions"],
    ["photon energy", "the energy carried by one photon, equal to hf", "photon energy must match an atomic energy difference for absorption or emission"],
  ]),
  p("ib-physics-e2", "E.2", "Quantum physics", "HL only", [
    ["photoelectric effect", "electron emission from a metal surface when incident electromagnetic radiation has sufficient frequency", "it provides evidence that light energy is quantized in photons"],
    ["threshold frequency", "the minimum incident frequency required to eject photoelectrons from a material", "below this frequency no photoelectrons are emitted regardless of intensity"],
    ["work function", "the minimum energy needed to remove an electron from a material surface", "it is related to the threshold frequency"],
    ["photoelectric equation", "the energy-conservation relationship between photon energy, work function and maximum photoelectron kinetic energy", "it explains how photoelectron kinetic energy depends on incident frequency"],
    ["photon", "a discrete quantum of electromagnetic radiation", "photon energy is proportional to frequency"],
    ["de Broglie wavelength", "the wavelength associated with a particle of momentum p, equal to h divided by p", "it describes the wave behaviour of matter"],
    ["wave-particle duality", "the principle that quantum objects can display both wave-like and particle-like behaviour", "light and matter show different aspects depending on the experiment"],
    ["Compton scattering", "the scattering of a photon by a particle such as an electron with an increase in photon wavelength", "it provides evidence for photon momentum and the particle nature of light"],
  ]),
  p("ib-physics-e3", "E.3", "Radioactive decay", "SL & HL", [
    ["isotope", "atoms of one element with the same proton number but different neutron numbers", "unstable isotopes can undergo radioactive decay"],
    ["radioactive decay", "the spontaneous random transformation of an unstable nucleus", "decay is unaffected by ordinary physical and chemical conditions"],
    ["background radiation", "ionizing radiation detected from natural and artificial environmental sources", "it must be allowed for when analysing low count rates"],
    ["alpha particle", "a helium nucleus emitted in alpha decay", "alpha emission reduces nucleon number by four and proton number by two"],
    ["beta-minus particle", "an electron emitted when a neutron changes into a proton in beta-minus decay", "beta-minus emission increases proton number by one while nucleon number stays constant"],
    ["gamma radiation", "high-energy electromagnetic radiation emitted by an excited nucleus", "gamma emission changes neither proton number nor nucleon number"],
    ["nuclear decay equation", "an equation that conserves nucleon number and charge during a nuclear transformation", "it identifies daughter nuclei and emitted radiation"],
    ["activity", "the number of nuclear decays per unit time", "activity is measured in becquerels"],
    ["half-life", "the time for the number of undecayed nuclei or activity to fall to half", "it is constant for exponential radioactive decay"],
    ["mass defect", "the difference between the total mass of separated nucleons and the mass of the bound nucleus", "the corresponding energy is the nuclear binding energy"],
    ["binding energy per nucleon", "the binding energy of a nucleus divided by its number of nucleons", "the binding-energy-per-nucleon curve is used to compare nuclear stability and energy release"],
  ]),
  p("ib-physics-e4", "E.4", "Fission", "SL & HL", [
    ["nuclear fission", "the splitting of a heavy nucleus into smaller nuclei with neutrons and energy released", "fission can occur spontaneously or be induced by neutron absorption"],
    ["induced fission", "fission triggered when a suitable nucleus absorbs a neutron", "the products include daughter nuclei, additional neutrons and released energy"],
    ["chain reaction", "a sequence in which neutrons from one fission trigger further fissions", "its rate depends on how many released neutrons cause another fission"],
    ["critical mass", "the amount and arrangement of fissile material needed for a self-sustaining chain reaction", "below the critical condition too many neutrons escape"],
    ["moderator", "material that slows neutrons mainly through collisions", "slower neutrons are more likely to cause further fission in common reactor fuel"],
    ["control rod", "a neutron-absorbing component used to regulate reactor power", "inserting control rods reduces the number of neutrons available for further fission"],
    ["nuclear reactor", "a system designed to maintain and control a fission chain reaction", "fuel, moderator, control rods and shielding allow energy to be released safely"],
    ["radioactive waste", "radioactive material produced during nuclear processes that requires controlled handling and disposal", "waste management depends on activity and half-life"],
  ]),
  p("ib-physics-e5", "E.5", "Fusion and stars", "SL & HL", [
    ["nuclear fusion", "the joining of light nuclei to form heavier nuclei with energy released", "fusion in stellar cores provides the energy that supports stars"],
    ["fusion in stars", "nuclear fusion reactions occurring in stellar cores at very high temperature and pressure", "fusion releases energy and helps balance inward gravitational collapse"],
    ["star formation", "the formation of a star from gravitational collapse of gas and dust in a nebula", "collapse increases temperature until sustained fusion can begin"],
    ["main-sequence star", "a stable star generating energy mainly by hydrogen fusion in its core", "inward gravitational force is balanced by outward pressure"],
    ["stellar life cycle", "the sequence of stages a star passes through as its fuel and structure change", "the later stages depend strongly on the star's mass"],
    ["Hertzsprung-Russell diagram", "a plot of stellar luminosity against surface temperature or spectral class", "it groups stars into regions such as main sequence, giants and white dwarfs"],
    ["stellar spectrum", "the emission or absorption spectrum observed from a star", "spectral lines can identify elements present in stellar atmospheres"],
    ["stellar parallax", "the apparent shift in position of a nearby star caused by viewing it from different positions in Earth's orbit", "the parallax angle is used to determine distances to nearby stars"],
    ["stellar radius", "the radius of a star inferred from its luminosity and surface temperature", "the Stefan-Boltzmann relationship can be rearranged to determine stellar size"],
  ]),
  p("ib-physics-tools-measurements", "Tools", "Measurements in physics", "SL & HL", [
    ["SI base unit", "one of the fundamental units from which derived SI units are constructed", "base units provide a consistent system for physical measurements"],
    ["derived unit", "a unit formed by combining SI base units according to a physical relationship", "derived units can be expressed in base-unit form"],
    ["scientific notation", "a way of writing a number as a coefficient multiplied by a power of ten", "it is used to represent very large and very small physical quantities clearly"],
    ["order of magnitude", "the power of ten that indicates the approximate scale of a quantity", "it is useful for comparing the sizes of physical quantities"],
    ["dimensional analysis", "the checking of physical relationships by comparing the dimensions of quantities on each side", "a physically valid equation must be dimensionally consistent"],
    ["measurement technique", "a method used to obtain a physical quantity with suitable apparatus and procedure", "repeated readings and appropriate instruments improve the reliability of measurements"],
  ]),
  p("ib-physics-tools-uncertainties", "Tools", "Processing uncertainties", "SL & HL", [
    ["random error", "unpredictable variation that causes repeated measurements to scatter", "repeated measurements can reduce the effect of random error on a mean value"],
    ["systematic error", "a consistent bias that shifts measurements in the same direction", "repeating measurements does not remove a systematic error"],
    ["absolute uncertainty", "an uncertainty stated in the same units as the measured quantity", "it gives the interval around a measurement within which the value is expected to lie"],
    ["fractional uncertainty", "absolute uncertainty divided by the measured value", "fractional uncertainties allow relative measurement quality to be compared"],
    ["percentage uncertainty", "fractional uncertainty expressed as a percentage", "it is used when combining and comparing experimental uncertainties"],
    ["error bar", "a graphical line showing the uncertainty range of a plotted data point", "error bars show whether differences between data points are significant relative to uncertainty"],
    ["gradient uncertainty", "the uncertainty in a graph gradient estimated from the steepest and shallowest acceptable lines", "it is used to report uncertainty in quantities obtained from graph slopes"],
  ]),
  p("ib-physics-tools-vectors", "Tools", "Scalars and vectors", "SL & HL", [
    ["scalar", "a physical quantity with magnitude only", "scalars can be added without considering direction"],
    ["vector", "a physical quantity with both magnitude and direction", "vector addition must account for direction"],
    ["resultant vector", "the single vector that has the same effect as two or more vectors combined", "it is found by vector addition"],
    ["vector component", "the part of a vector resolved along a chosen axis", "components allow vector problems to be analysed independently in perpendicular directions"],
    ["resolving a vector", "the process of splitting a vector into components along chosen axes", "trigonometry is used to calculate perpendicular components"],
    ["scale diagram", "a graphical method of representing vectors with lengths and directions drawn to scale", "the resultant can be found by measuring the completed vector diagram"],
  ]),
];
