import type { IbTopicSpec } from "./ib-question-types";

const p = (
  id: string,
  code: string,
  name: string,
  level: "SL & HL" | "HL only",
  concepts: IbTopicSpec["concepts"],
): IbTopicSpec => ({ id, code, name, subject: "Physics", level, concepts });

export const physicsIbTopicSpecs: IbTopicSpec[] = [
  p("ib-physics-a1", "A.1", "Kinematics", "SL & HL", [
    ["displacement", "the vector change in position from start to finish", "it records both how far and in which direction an object has moved"],
    ["velocity", "the rate of change of displacement", "its sign and direction are needed when describing motion in one or more dimensions"],
    ["acceleration", "the rate of change of velocity", "it links changes in speed or direction to the time over which they occur"],
    ["motion graph", "a graph showing how position, velocity or acceleration changes with time", "gradients and areas allow motion quantities to be determined from experimental data"],
    ["kinematic equation", "an equation connecting displacement, initial velocity, final velocity, acceleration and time for constant acceleration", "it allows an unknown motion quantity to be calculated when acceleration is uniform"],
    ["projectile motion", "two-dimensional motion under gravity when air resistance is neglected", "horizontal velocity is constant while vertical motion has gravitational acceleration"],
  ]),
  p("ib-physics-a2", "A.2", "Forces and momentum", "SL & HL", [
    ["resultant force", "the vector sum of all forces acting on a system", "a non-zero resultant force causes acceleration according to Newton's second law"],
    ["free-body diagram", "a diagram showing the external forces acting on one chosen object", "it separates the object from its surroundings so force components can be analysed"],
    ["Newton's second law", "the rate of change of momentum is proportional to the resultant force", "for constant mass it gives F = ma and predicts the acceleration produced by forces"],
    ["momentum", "the vector product of mass and velocity", "total momentum is conserved in an isolated system and is central to collision analysis"],
    ["impulse", "the change in momentum, equal to force multiplied by the time for which it acts", "increasing collision time reduces the average force for the same momentum change"],
    ["terminal speed", "the constant speed reached when resistive forces balance the driving force", "zero resultant force then means acceleration becomes zero even though the object continues moving"],
  ]),
  p("ib-physics-a3", "A.3", "Work, energy and power", "SL & HL", [
    ["work", "energy transferred when a force acts through a displacement", "only the component of force parallel to the displacement transfers energy mechanically"],
    ["kinetic energy", "the energy associated with motion, equal to one half mv squared", "changes in kinetic energy equal the net work done on an object"],
    ["gravitational potential energy", "energy stored because of position in a gravitational field", "near Earth's surface its change is mg times the vertical height change"],
    ["energy conservation", "the principle that total energy in a closed system remains constant", "it allows transfers between kinetic, potential, thermal and other stores to be tracked"],
    ["power", "the rate at which work is done or energy is transferred", "it distinguishes devices that transfer the same energy in different times"],
    ["efficiency", "the ratio of useful energy or power output to total input", "it measures the fraction of input that reaches the intended store or pathway"],
  ]),
  p("ib-physics-a4", "A.4", "Rigid body mechanics", "HL only", [
    ["torque", "the turning effect of a force about an axis", "it depends on force and perpendicular distance and produces angular acceleration"],
    ["moment of inertia", "the rotational analogue of mass that depends on how mass is distributed about an axis", "a larger value gives less angular acceleration for the same torque"],
    ["angular velocity", "the rate of change of angular displacement", "it describes rotational motion and connects tangential speed to distance from the axis"],
    ["angular acceleration", "the rate of change of angular velocity", "it results from a non-zero resultant torque"],
    ["rotational kinetic energy", "the kinetic energy of a rotating body, equal to one half I omega squared", "it must be included when energy is shared between translation and rotation"],
    ["angular momentum", "the rotational quantity equal to moment of inertia multiplied by angular velocity", "it is conserved when the resultant external torque is zero"],
  ]),
  p("ib-physics-a5", "A.5", "Galilean and special relativity", "HL only", [
    ["inertial reference frame", "a frame in which an object with no resultant force moves at constant velocity", "the laws of physics take the same form in all inertial frames"],
    ["Galilean transformation", "the classical relationship between positions and velocities in frames moving at constant relative velocity", "it works at low speeds but does not preserve the measured speed of light"],
    ["invariance of light speed", "the postulate that all inertial observers measure the same vacuum speed of light", "it requires space and time measurements to depend on the observer's motion"],
    ["time dilation", "the increase in measured time interval for a moving clock compared with its proper time", "it becomes significant when relative speed is a substantial fraction of the speed of light"],
    ["length contraction", "the reduction in measured length parallel to motion relative to proper length", "it is paired with time dilation by the Lorentz factor"],
    ["spacetime interval", "a quantity combining space and time separations that is invariant between inertial frames", "it provides an observer-independent way to classify separated events"],
  ]),
  p("ib-physics-b1", "B.1", "Thermal energy transfers", "SL & HL", [
    ["temperature", "a measure related to the average random kinetic energy of particles", "temperature difference determines the direction of net thermal energy transfer"],
    ["internal energy", "the total random kinetic and intermolecular potential energy of particles in a system", "heating and work can change internal energy without necessarily changing temperature"],
    ["specific heat capacity", "the energy required to raise the temperature of one kilogram by one kelvin", "it connects thermal energy change to mass and temperature change"],
    ["specific latent heat", "the energy per kilogram needed for a change of state at constant temperature", "energy changes particle potential energy while temperature remains unchanged"],
    ["thermal conduction", "thermal energy transfer through a solid by interactions between neighbouring particles", "its rate depends on temperature gradient, material conductivity and geometry"],
    ["thermal radiation", "energy transfer by electromagnetic waves, mainly infrared at everyday temperatures", "it can occur through a vacuum and depends on temperature and surface properties"],
  ]),
  p("ib-physics-b2", "B.2", "Greenhouse effect", "SL & HL", [
    ["solar irradiance", "the power of incoming solar radiation per unit area", "it is the main external energy input to Earth's climate system"],
    ["albedo", "the fraction of incident radiation reflected by a surface", "higher albedo reduces absorbed solar power and can cool the climate system"],
    ["infrared emission", "electromagnetic radiation emitted by Earth because of its temperature", "outgoing infrared must balance absorbed solar energy for stable average temperature"],
    ["greenhouse gas", "an atmospheric gas that absorbs and re-emits particular infrared wavelengths", "it reduces the rate at which energy escapes directly to space"],
    ["radiative equilibrium", "the condition in which average absorbed power equals average emitted power", "it determines a planet's long-term effective temperature"],
    ["climate feedback", "a process that amplifies or reduces an initial climate change", "ice-albedo, water vapour and cloud responses can alter the size of warming or cooling"],
  ]),
  p("ib-physics-b3", "B.3", "Gas laws", "SL & HL", [
    ["absolute temperature", "temperature measured from absolute zero on the kelvin scale", "gas-law relationships require kelvin because particle kinetic energy is proportional to absolute temperature"],
    ["gas pressure", "force per unit area caused by particle collisions with container walls", "more frequent or more forceful collisions raise the measured pressure"],
    ["ideal gas", "a model gas of negligible-volume particles with elastic collisions and no intermolecular forces", "the model connects macroscopic variables to simple particle behaviour"],
    ["ideal gas equation", "the relationship pV = nRT for an ideal gas", "it connects pressure, volume, amount and absolute temperature in equilibrium states"],
    ["molar gas constant", "the proportionality constant R in the ideal gas equation", "it links the mole-scale gas law to thermodynamic temperature"],
    ["kinetic model", "a microscopic model explaining gas behaviour using random particle motion", "it explains pressure and temperature through momentum transfer and kinetic energy"],
  ]),
  p("ib-physics-b4", "B.4", "Thermodynamics", "HL only", [
    ["first law of thermodynamics", "the conservation statement relating internal-energy change, heating and work", "it accounts for every energy transfer into or out of a thermodynamic system"],
    ["entropy", "a state quantity related to the dispersal of energy and number of accessible microstates", "the total entropy of an isolated system does not decrease in a spontaneous process"],
    ["second law of thermodynamics", "the principle that natural processes have a preferred direction associated with entropy increase", "it limits the efficiency of heat engines and rules out complete conversion of heat to work"],
    ["heat engine", "a cyclic device that takes in energy at high temperature, does work and rejects energy at lower temperature", "its operation is constrained by energy conservation and entropy change"],
    ["Carnot efficiency", "the maximum theoretical heat-engine efficiency set only by hot and cold reservoir temperatures", "no real engine operating between the same reservoirs can exceed this value"],
    ["pressure-volume diagram", "a graph representing thermodynamic states and processes using pressure and volume", "the signed area under a process curve gives work done by the gas"],
  ]),
  p("ib-physics-b5", "B.5", "Current and circuits", "SL & HL", [
    ["electric current", "the rate of flow of electric charge", "it is common through components in series and divides at junctions"],
    ["potential difference", "the energy transferred per unit charge between two points", "it measures how much electrical energy each coulomb gains or loses"],
    ["resistance", "the ratio of potential difference to current for a component", "it quantifies opposition to charge flow and depends on material and geometry"],
    ["Ohm's law", "the proportional relationship between current and potential difference at constant physical conditions", "it identifies ohmic behaviour and supports linear circuit calculations"],
    ["Kirchhoff's junction rule", "the rule that total current entering a junction equals total current leaving", "it follows from conservation of electric charge"],
    ["Kirchhoff's loop rule", "the rule that potential rises and drops sum to zero around a closed loop", "it follows from conservation of energy in a circuit"],
  ]),
  p("ib-physics-c1", "C.1", "Simple harmonic motion", "SL & HL", [
    ["equilibrium position", "the position where the resultant force on an oscillator is zero", "displacement is measured from this point and the restoring force points back towards it"],
    ["restoring force", "a force directed towards equilibrium and proportional to displacement in simple harmonic motion", "it produces an acceleration opposite to displacement"],
    ["amplitude", "the maximum magnitude of displacement from equilibrium", "it sets the total mechanical energy of an ideal oscillator"],
    ["angular frequency", "the rate of phase change in radians per second", "it connects period and frequency to the sinusoidal equations of motion"],
    ["oscillator energy", "the sum of kinetic and potential energy during oscillation", "in undamped SHM it is constant while continuously transferring between the two forms"],
    ["damping", "the removal of mechanical energy from an oscillator by resistive forces", "it causes amplitude to decrease with time and affects resonance"],
  ]),
  p("ib-physics-c2", "C.2", "Wave model", "SL & HL", [
    ["transverse wave", "a wave in which oscillations are perpendicular to energy transfer", "polarization is possible only for transverse waves"],
    ["longitudinal wave", "a wave in which oscillations are parallel to energy transfer", "compressions and rarefactions carry energy through the medium"],
    ["wavelength", "the shortest distance between points in the same phase", "together with frequency it determines wave speed"],
    ["frequency", "the number of complete oscillations passing a point per second", "it is fixed by the source and remains unchanged at a boundary"],
    ["wave speed", "the distance travelled by a wave disturbance per unit time", "it equals frequency multiplied by wavelength and depends on the medium"],
    ["wave intensity", "the power transferred by a wave per unit area", "for a point source it decreases with the square of distance when energy is conserved"],
  ]),
  p("ib-physics-c3", "C.3", "Wave phenomena", "SL & HL", [
    ["superposition", "the principle that overlapping wave displacements add algebraically", "it explains interference patterns and standing waves"],
    ["interference", "the redistribution of intensity when coherent waves superpose", "path difference determines whether reinforcement or cancellation occurs"],
    ["diffraction", "the spreading of a wave after an aperture or around an obstacle", "it is strongest when the aperture or obstacle size is comparable to wavelength"],
    ["refraction", "a change in wave direction caused by a change in speed across a boundary", "frequency stays constant while speed and wavelength change"],
    ["polarization", "restriction of transverse oscillations to a particular direction", "it provides evidence that a wave is transverse"],
    ["double-slit interference", "an interference pattern formed by coherent waves from two narrow openings", "fringe spacing links wavelength, slit separation and screen distance"],
  ]),
  p("ib-physics-c4", "C.4", "Standing waves and resonance", "SL & HL", [
    ["standing wave", "a fixed pattern formed by equal-frequency waves travelling in opposite directions", "it transfers no net energy along the pattern and contains nodes and antinodes"],
    ["node", "a point in a standing wave with zero amplitude", "destructive interference occurs there at all times"],
    ["antinode", "a point in a standing wave with maximum amplitude", "constructive interference is greatest there"],
    ["natural frequency", "a frequency at which a system oscillates freely after disturbance", "driving near this frequency can produce resonance"],
    ["resonance", "a large-amplitude response when driving frequency matches a natural frequency", "energy is transferred to the oscillator most efficiently at resonance"],
    ["harmonic", "an allowed standing-wave mode with frequency an integer multiple of the fundamental in many systems", "boundary conditions determine which wavelengths and frequencies can exist"],
  ]),
  p("ib-physics-c5", "C.5", "Doppler effect", "SL & HL", [
    ["Doppler effect", "the change in observed frequency caused by relative motion between source and observer", "approach raises observed frequency while separation lowers it"],
    ["observed frequency", "the rate at which wavefronts arrive at an observer", "it differs from emitted frequency when source-observer separation changes"],
    ["moving source", "a source whose motion changes wavefront spacing in the medium", "wavefronts bunch ahead of the source and spread behind it"],
    ["moving observer", "an observer whose motion changes the rate of encountering wavefronts", "motion towards the source increases arrival rate without changing wavelength in the medium"],
    ["redshift", "a shift of received electromagnetic radiation towards longer wavelength", "it provides evidence that an astronomical source is receding"],
    ["Doppler ultrasound", "use of reflected ultrasound frequency shifts to measure motion", "it allows blood-flow speed or other target velocities to be estimated"],
  ]),
  p("ib-physics-d1", "D.1", "Gravitational fields", "SL & HL", [
    ["gravitational field strength", "force per unit mass at a point in a gravitational field", "it is also the acceleration of a freely falling test mass"],
    ["gravitational potential", "work done per unit mass in bringing a test mass from infinity to a point", "its negative value expresses binding in an attractive field"],
    ["inverse-square law", "a relationship in which field strength decreases with the square of distance", "it follows from the spreading of a central field over spherical area"],
    ["equipotential", "a line or surface of constant gravitational potential", "no work is done moving a mass along it and the field is perpendicular to it"],
    ["circular orbit", "motion in which gravity supplies the centripetal force", "orbital speed and period follow from equating gravitational and centripetal forces"],
    ["escape speed", "the minimum launch speed needed to reach infinity with zero final kinetic energy", "it follows from conservation of mechanical energy in a gravitational field"],
  ]),
  p("ib-physics-d2", "D.2", "Electric and magnetic fields", "SL & HL", [
    ["electric field strength", "force per unit positive test charge", "it gives both the direction and magnitude of electrical force at a point"],
    ["electric potential", "electric potential energy per unit charge", "potential difference determines work done when charge moves between points"],
    ["Coulomb's law", "the inverse-square force law between point charges", "it predicts how force depends on both charges and their separation"],
    ["electric equipotential", "a line or surface of constant electric potential", "moving charge along it requires no work and field lines cross it at right angles"],
    ["magnetic flux density", "a measure of magnetic field strength defined through force on current or moving charge", "it determines magnetic force magnitude and direction"],
    ["field line", "a representation whose tangent gives field direction and whose spacing indicates strength", "it helps visualize superposed electric, magnetic and gravitational fields"],
  ]),
  p("ib-physics-d3", "D.3", "Motion in electromagnetic fields", "SL & HL", [
    ["electric force", "the force qE on a charge in an electric field", "it can do work and change both the speed and direction of a charged particle"],
    ["magnetic force", "the force on moving charge perpendicular to its velocity and magnetic field", "it changes direction but does no work on the particle"],
    ["circular particle path", "the path produced when magnetic force supplies centripetal force", "its radius depends on momentum, charge and magnetic flux density"],
    ["velocity selector", "crossed electric and magnetic fields that transmit only particles of one speed", "electric and magnetic forces balance for the selected velocity"],
    ["mass spectrometer", "a device that separates ions using their motion in electric and magnetic fields", "measured paths allow mass-to-charge ratio and isotopic abundance to be determined"],
    ["Lorentz force", "the combined electric and magnetic force on a charged particle", "it provides one expression for analysing motion in simultaneous fields"],
  ]),
  p("ib-physics-d4", "D.4", "Induction", "HL only", [
    ["magnetic flux", "the product of magnetic flux density and perpendicular area for a uniform field", "it measures how much magnetic field passes through a surface"],
    ["flux linkage", "magnetic flux through one loop multiplied by the number of turns", "its rate of change determines induced electromotive force"],
    ["Faraday's law", "the law that induced emf equals the negative rate of change of flux linkage", "faster flux change or more turns produces a larger induced emf"],
    ["Lenz's law", "the rule that induced effects oppose the change that produces them", "it sets current direction and expresses conservation of energy"],
    ["generator", "a device that converts mechanical energy to electrical energy by electromagnetic induction", "rotation changes flux linkage and produces an alternating emf"],
    ["transformer", "a device using mutual induction between coils to change alternating voltage", "the turns ratio links input and output voltage in an ideal transformer"],
  ]),
  p("ib-physics-e1", "E.1", "Structure of the atom", "SL & HL", [
    ["Rutherford scattering", "alpha-particle scattering evidence for a small dense positive nucleus", "rare large deflections showed that most mass and positive charge occupy very little volume"],
    ["atomic energy level", "an allowed discrete energy state for an electron in an atom", "transitions between levels explain line emission and absorption spectra"],
    ["emission spectrum", "discrete wavelengths emitted when excited electrons move to lower energy levels", "it provides a characteristic fingerprint for each element"],
    ["absorption spectrum", "dark wavelengths produced when atoms absorb photons matching energy gaps", "the missing wavelengths correspond to allowed upward electron transitions"],
    ["photon", "a quantum of electromagnetic radiation with energy hf", "its energy must match an atomic energy difference for absorption or emission"],
    ["ionization energy", "the minimum energy needed to remove an electron from an atom in a stated state", "it marks the energy required to reach the continuum above bound levels"],
  ]),
  p("ib-physics-e2", "E.2", "Quantum physics", "HL only", [
    ["photoelectric effect", "electron emission from a material when incident photons exceed a threshold frequency", "it supports photon quantization because intensity alone cannot overcome an insufficient photon energy"],
    ["work function", "the minimum energy needed to remove an electron from a surface", "it sets the threshold frequency for photoelectric emission"],
    ["matter wave", "the wave behaviour associated with a particle of momentum p and wavelength h divided by p", "electron diffraction demonstrates that particles can show interference"],
    ["wavefunction", "a mathematical description whose squared magnitude gives probability density", "it replaces a definite classical trajectory with probabilistic predictions"],
    ["uncertainty principle", "the limit on simultaneous precision of conjugate quantities such as position and momentum", "it is an intrinsic quantum restriction rather than a flaw in measuring equipment"],
    ["quantum tunnelling", "the finite probability of a particle crossing a barrier higher than its classical energy", "it follows from wavefunction penetration and explains phenomena such as alpha decay"],
  ]),
  p("ib-physics-e3", "E.3", "Radioactive decay", "SL & HL", [
    ["isotope", "atoms of one element with the same proton number but different neutron numbers", "unstable isotope nuclei can transform through radioactive decay"],
    ["activity", "the number of nuclear decays per unit time", "it equals decay constant multiplied by the number of undecayed nuclei"],
    ["decay constant", "the probability per unit time that an individual nucleus decays", "it is fixed for an isotope and determines the exponential decay rate"],
    ["half-life", "the time for the number of undecayed nuclei or activity to fall to half", "it is constant for exponential radioactive decay"],
    ["nuclear decay equation", "an equation conserving nucleon number and charge during a nuclear transformation", "it identifies daughter nuclei and emitted particles"],
    ["background radiation", "ionizing radiation detected from natural and artificial environmental sources", "it must be measured or allowed for when analysing low count rates"],
  ]),
  p("ib-physics-e4", "E.4", "Fission", "SL & HL", [
    ["nuclear fission", "the splitting of a heavy nucleus into smaller nuclei with neutrons and energy released", "the products have greater binding energy per nucleon so mass-energy is released"],
    ["chain reaction", "a sequence in which neutrons from one fission trigger further fissions", "its rate depends on how many neutrons cause another split"],
    ["critical mass", "the minimum fissile mass and geometry needed for a self-sustaining chain reaction", "below it too many neutrons escape before causing further fission"],
    ["moderator", "material that slows neutrons mainly through collisions", "slower neutrons are more likely to trigger fission in common reactor fuel"],
    ["control rod", "a neutron-absorbing component used to regulate reactor power", "inserting it reduces the number of neutrons available for further fission"],
    ["mass defect", "the difference between the total mass before and after a nuclear process", "it corresponds to released or absorbed energy through E = mc squared"],
  ]),
  p("ib-physics-e5", "E.5", "Fusion and stars", "SL & HL", [
    ["nuclear fusion", "the joining of light nuclei to form heavier nuclei with energy released", "energy is released when products have greater binding energy per nucleon"],
    ["stellar equilibrium", "the balance between inward gravity and outward pressure in a stable star", "it maintains the star's size during long main-sequence stages"],
    ["main-sequence star", "a star generating energy mainly by hydrogen fusion in its core", "its mass strongly influences luminosity, temperature and lifetime"],
    ["stellar nucleosynthesis", "the production of new nuclei through reactions inside stars", "it explains the cosmic origin of many elements"],
    ["Hertzsprung-Russell diagram", "a plot relating stellar luminosity to surface temperature or spectral class", "it organizes stars into evolutionary groups such as main sequence, giants and white dwarfs"],
    ["stellar luminosity", "the total power radiated by a star", "it depends on surface area and the fourth power of absolute surface temperature"],
  ]),
];
