import type { BankQuestion } from "./question-bank-legacy";

type Row = readonly [
  string,
  string,
  BankQuestion["difficulty"],
  BankQuestion["kind"],
];

const rows: Record<string, Row[]> = {
  "y7-material-properties": [
    ["Why should a material property not depend on an object's size or shape?", "A material property describes the material itself, so it should remain meaningful for different objects made from that material.", "stretch", "explain"],
    ["How is hardness defined in this topic?", "Resistance to scratching or denting", "core", "explain"],
    ["What does strength describe?", "How well a material withstands a force without breaking or permanently deforming", "core", "explain"],
    ["What does stiffness describe?", "Resistance to bending or changing shape", "core", "explain"],
    ["What does elasticity allow a material to do?", "Return to its original shape after the force is removed", "core", "explain"],
    ["What is a thermal conductor?", "A material through which thermal energy transfers readily", "core", "explain"],
    ["What is an electrical conductor?", "A material that allows electric current to pass through it", "core", "explain"],
    ["What is an insulator?", "A material that reduces the transfer of thermal energy or electric current", "core", "explain"],
    ["How is elastic deformation different from plastic deformation?", "Elastic deformation is reversed when the force is removed; plastic deformation is permanent.", "stretch", "explain"],
    ["Give one example of elastic deformation.", "For example, a stretched rubber band returning to its original shape.", "foundation", "explain"],
    ["Give one example of plastic deformation.", "For example, Blu-Tack or foil staying bent after the force is removed.", "foundation", "explain"],
    ["What should happen to an elastically deformed object when the force is removed?", "It should return to its original shape.", "foundation", "short"],
    ["What does toughness describe?", "Resistance to breaking when struck or impacted", "core", "explain"],
    ["What does brittle mean?", "Likely to break rather than deform when a force is applied", "core", "explain"],
    ["Can a hard material also be brittle?", "Yes. Hardness and toughness describe different properties.", "core", "explain"],
    ["Why should the same test method be used for every material sample?", "So the comparison is fair and differences can be linked to the materials.", "core", "explain"],
    ["Why should samples have similar size and shape in an impact test?", "Size and shape can affect the result, so controlling them makes the comparison fair.", "core", "explain"],
    ["How could samples be compared for hardness?", "Use the same scratching or denting test and compare the results.", "core", "explain"],
    ["Which property makes metals useful for transferring heat in cookware?", "High thermal conductivity", "foundation", "short"],
    ["Why are insulating materials used for saucepan handles?", "They reduce thermal energy transfer to the hand.", "core", "explain"],
    ["What role does plastic insulation have around a metal wire?", "It reduces the chance of electric current passing into a person or another conductor.", "core", "explain"],
    ["Why must a conductivity test use a closed circuit?", "Electric current can flow only when the circuit is complete.", "core", "explain"],
    ["Name one non-metal that can conduct electricity.", "Graphite", "stretch", "short"],
    ["Does insulation stop thermal energy transfer completely?", "No. It reduces the rate of transfer.", "core", "explain"],
    ["What can a cooling curve show when insulation is tested?", "How temperature changes with time for each insulating material", "core", "explain"],
    ["On a cooling graph, which container has the better insulation?", "The one whose temperature falls more slowly under the same conditions", "core", "explain"],
    ["How can increasing insulation thickness affect cooling?", "It can reduce the rate of cooling.", "core", "explain"],
    ["Why can a poor fit reduce the effectiveness of insulation?", "Gaps allow more thermal energy to transfer to the surroundings.", "core", "explain"],
    ["Why should surface area be controlled in an insulation comparison?", "Different surface areas can change the rate of thermal energy transfer.", "stretch", "explain"],
    ["What does diminishing returns mean for added insulation?", "Each extra layer may produce a smaller additional reduction in heat transfer.", "stretch", "explain"],
    ["Does foil create thermal energy when used as insulation?", "No. Its shiny surface can reflect thermal radiation.", "core", "explain"],
    ["How should a material be chosen for a particular use?", "Match the material's tested properties to the requirements of the use.", "core", "explain"],
  ],
  "y7-particle-model": [
    ["How are particles arranged in a solid?", "They are closely packed in fixed positions.", "core", "explain"],
    ["How do particles move in a solid?", "They vibrate about fixed positions.", "foundation", "explain"],
    ["How are particles arranged in a liquid?", "They are close together but not in fixed positions.", "core", "explain"],
    ["Why can a liquid flow?", "Its particles can move past one another.", "core", "explain"],
    ["How are particles arranged in a gas?", "They are far apart with no fixed arrangement.", "core", "explain"],
    ["Why does a gas fill its container?", "Its particles move freely in all directions.", "core", "explain"],
    ["Which state has neither a fixed shape nor a fixed volume?", "Gas", "foundation", "short"],
    ["Do particles themselves get bigger when a substance is heated?", "No. Their motion and average spacing can change.", "core", "explain"],
    ["What is melting?", "The change of state from solid to liquid", "foundation", "explain"],
    ["What is freezing?", "The change of state from liquid to solid", "foundation", "explain"],
    ["What is boiling?", "A change from liquid to gas throughout the liquid at its boiling point", "core", "explain"],
    ["What is condensation?", "The change of state from gas to liquid", "foundation", "explain"],
    ["What is sublimation?", "The direct change of state from solid to gas", "stretch", "explain"],
    ["What is deposition?", "The direct change of state from gas to solid", "stretch", "explain"],
    ["What happens to particle movement as a substance cools?", "The particles move or vibrate more slowly.", "core", "explain"],
    ["What happens to particle movement as a substance is heated?", "The particles move or vibrate faster.", "core", "explain"],
    ["Do particles disappear during evaporation?", "No. They remain present in the gas state.", "foundation", "explain"],
    ["Why does mass stay constant during a state change in a closed system?", "No particles enter or leave the closed system.", "core", "explain"],
    ["Why can measured mass decrease during evaporation in an open container?", "Gas particles can leave the container and enter the surroundings.", "stretch", "explain"],
    ["What happens to temperature during the melting plateau of a pure substance?", "It stays approximately constant while melting occurs.", "core", "explain"],
    ["Where does evaporation occur in a liquid?", "At the surface", "foundation", "short"],
    ["Where does boiling occur in a liquid?", "Throughout the liquid", "foundation", "short"],
    ["Can evaporation happen below a liquid's boiling point?", "Yes", "foundation", "short"],
    ["How does a higher temperature usually affect evaporation?", "It increases the rate of evaporation.", "core", "explain"],
    ["How does a larger exposed surface area affect evaporation?", "It increases the rate of evaporation.", "core", "explain"],
    ["How can airflow above a liquid affect evaporation?", "Greater airflow usually increases the rate of evaporation.", "core", "explain"],
    ["Why should only one factor be changed in an evaporation investigation?", "So any change in evaporation rate can be linked to that factor.", "core", "explain"],
    ["What evidence would show faster evaporation in a fair test?", "A greater decrease in liquid mass or volume over the same time", "core", "explain"],
    ["What stays the same about the substance during melting and freezing?", "Its particles remain the same substance.", "core", "explain"],
    ["Why are state changes described as physical changes?", "The substance does not become a new substance.", "core", "explain"],
    ["What does a particle model represent?", "The spacing, arrangement and motion of particles too small to see directly", "core", "explain"],
    ["Give one limitation of a simple particle diagram.", "It may not show the true scale, number, speed or three-dimensional movement of particles.", "stretch", "explain"],
  ],
  "y7-cells": [
    ["What does cell theory identify as the basic unit of life?", "The cell", "foundation", "short"],
    ["What is the function of the nucleus?", "It contains genetic material and helps control cell activities.", "core", "explain"],
    ["What is the function of the cell membrane?", "It controls what enters and leaves the cell.", "core", "explain"],
    ["What is the function of the cytoplasm?", "It is where many cell reactions occur.", "core", "explain"],
    ["What is the function of mitochondria?", "They are a site of cellular respiration and energy release.", "core", "explain"],
    ["What is the function of chloroplasts?", "They absorb light for photosynthesis.", "core", "explain"],
    ["What is the function of a plant cell wall?", "It supports and strengthens the cell.", "core", "explain"],
    ["What is stored in a plant cell's large vacuole?", "Cell sap", "foundation", "short"],
    ["Name one structure shared by plant and animal cells.", "For example, a nucleus, cytoplasm, cell membrane or mitochondrion", "foundation", "short"],
    ["Name one structure found in a typical plant cell but not a typical animal cell.", "A cell wall, chloroplast or large permanent vacuole", "foundation", "short"],
    ["What does a light microscope allow a scientist to observe?", "Structures too small to see clearly with the unaided eye", "foundation", "explain"],
    ["How is total microscope magnification calculated?", "Eyepiece magnification multiplied by objective magnification", "core", "explain"],
    ["A 10× eyepiece and 4× objective are used. What is the total magnification?", "40×", "core", "short"],
    ["Why should the lowest-power objective usually be used first?", "It gives a wider field of view and makes the specimen easier to locate.", "core", "explain"],
    ["What happens to the field of view as magnification increases?", "It becomes smaller.", "core", "short"],
    ["Why should the microscope be focused carefully?", "To obtain a clear image without damaging the slide or lens.", "core", "explain"],
    ["What does a scale bar show on a cell image?", "The actual size represented by a stated length on the image", "core", "explain"],
    ["Which unit is often used to measure cells?", "Micrometre (µm)", "core", "short"],
    ["What is a tissue?", "A group of similar cells working together to perform a function", "core", "explain"],
    ["What is an organ?", "A group of different tissues working together to perform a function", "core", "explain"],
    ["What is an organ system?", "A group of organs working together to perform a major function", "core", "explain"],
    ["What is an organism?", "An individual living thing", "foundation", "short"],
    ["Which level of organisation comes between cell and organ?", "Tissue", "foundation", "short"],
    ["Which level of organisation comes between organ and organism?", "Organ system", "foundation", "short"],
    ["What is a unicellular organism?", "An organism made of one cell", "core", "explain"],
    ["Do unicellular organisms carry out all life processes?", "Yes. Their single cell carries out the processes needed for life.", "core", "explain"],
    ["What is a specialised cell?", "A cell with structures suited to a particular function", "core", "explain"],
    ["How does a root hair cell's extension support its function?", "It increases surface area for absorbing water and mineral ions.", "core", "explain"],
    ["Why do palisade cells contain many chloroplasts?", "To absorb light for photosynthesis", "core", "explain"],
    ["How do ciliated cells help move material?", "Their cilia beat to move substances along a surface.", "core", "explain"],
    ["Why can cells in one organism have different structures?", "They are specialised for different functions.", "core", "explain"],
    ["Why is a labelled cell model useful?", "It shows the relative positions and functions of important structures.", "stretch", "explain"],
  ],
  "y7-thermal-energy": [
    ["Name one source of thermal energy studied in this topic.", "For example, the Sun, fire, friction or electricity", "foundation", "explain"],
    ["What happens when a warm object touches a cooler object?", "Thermal energy transfers from the warmer object to the cooler one.", "core", "explain"],
    ["When is there no net thermal energy transfer between two objects?", "When they are at the same temperature", "core", "short"],
    ["What instrument is used to measure temperature?", "A thermometer", "foundation", "short"],
    ["Why should temperature readings be recorded at regular time intervals?", "So changes over time can be compared clearly.", "core", "explain"],
    ["How does conduction transfer thermal energy?", "Through direct contact between neighbouring particles, without the material flowing as a whole.", "core", "explain"],
    ["In which state is conduction usually most effective?", "Solid", "foundation", "short"],
    ["Does matter flow from the hot end to the cold end during conduction in a solid?", "No", "foundation", "short"],
    ["Can conduction occur in a still liquid or gas?", "Yes, but it is usually slower than in solids.", "core", "explain"],
    ["Which materials are usually good thermal conductors?", "Metals", "foundation", "short"],
    ["Which materials are often used as thermal insulators?", "Plastics, rubbers and trapped air", "foundation", "short"],
    ["What evidence can compare conduction through different materials?", "The rate at which temperature changes along or through each material", "core", "explain"],
    ["How does convection transfer thermal energy?", "By the movement of warmer and cooler parts of a liquid or gas.", "core", "explain"],
    ["Why does a heated fluid expand?", "Its particles move more and become more spread out.", "core", "explain"],
    ["Why is warm fluid usually less dense?", "The same mass occupies a larger volume after expansion.", "stretch", "explain"],
    ["What happens to cooler, denser fluid in a convection current?", "It sinks.", "foundation", "short"],
    ["What is a convection current?", "Circulating movement in a fluid caused by temperature and density differences", "core", "explain"],
    ["Why can convection not occur in a solid?", "The solid cannot flow and carry thermal energy from place to place.", "core", "explain"],
    ["Can convection occur in a vacuum?", "No. Convection requires moving matter.", "core", "explain"],
    ["How does thermal radiation transfer energy?", "By electromagnetic waves, mainly infrared radiation", "core", "explain"],
    ["Does thermal radiation require particles?", "No", "foundation", "short"],
    ["Why can energy from the Sun reach Earth?", "Radiation can travel through the vacuum of space.", "core", "explain"],
    ["Do all objects emit thermal radiation?", "Yes", "foundation", "short"],
    ["How does an object's temperature affect the radiation it emits?", "Hotter objects emit more thermal radiation.", "core", "explain"],
    ["What happens when an object absorbs infrared radiation?", "Its thermal energy and usually its temperature increase.", "core", "explain"],
    ["What happens to most materials when they are heated?", "They expand.", "foundation", "short"],
    ["What happens to most materials when they are cooled?", "They contract.", "foundation", "short"],
    ["Why are most solids denser than their liquids?", "Their particles are usually packed more closely together.", "core", "explain"],
    ["What unusual change happens to water as it freezes?", "It expands.", "core", "short"],
    ["Why is ice less dense than liquid water?", "The frozen structure occupies more volume for the same mass.", "core", "explain"],
    ["Why is water's expansion on freezing important in nature?", "It makes ice float, so ice can form on the surface of water.", "stretch", "explain"],
    ["Which three processes transfer thermal energy?", "Conduction, convection and radiation", "foundation", "short"],
  ],
  "y8-mixtures": [
    ["What is a component of a mixture?", "One of the substances present in the mixture", "foundation", "explain"],
    ["How are components arranged in a homogeneous mixture?", "They are evenly distributed so the mixture looks the same throughout.", "core", "explain"],
    ["How are components arranged in a heterogeneous mixture?", "They are unevenly distributed, often in visible layers, clumps or phases.", "core", "explain"],
    ["Does a clear liquid have to be pure?", "No. A clear solution can contain more than one substance.", "core", "explain"],
    ["What is a phase in a mixture?", "A region with visibly uniform properties that is distinct from another region", "core", "explain"],
    ["Which method separates solid pieces of different sizes?", "Sieving", "foundation", "short"],
    ["What property allows sieving to separate a mixture?", "Difference in particle size", "core", "short"],
    ["Which method separates an insoluble solid from a liquid using a barrier?", "Filtration", "foundation", "short"],
    ["What is the residue in filtration?", "The insoluble solid left on the filter", "core", "explain"],
    ["What is the filtrate in filtration?", "The liquid that passes through the filter", "core", "explain"],
    ["Why does an insoluble solid remain on filter paper?", "Its particles are too large to pass through the filter pores.", "core", "explain"],
    ["What is settling?", "Allowing suspended particles to fall to the bottom of a liquid", "core", "explain"],
    ["What is decanting?", "Carefully pouring off a liquid after a solid has settled", "core", "explain"],
    ["When can settling followed by decanting be useful?", "When an insoluble solid settles beneath a liquid", "core", "explain"],
    ["How can evaporation separate a dissolved solid from its solution?", "The solvent leaves as a gas while the dissolved solid remains.", "core", "explain"],
    ["What is a solution?", "A homogeneous mixture in which a solute is dissolved in a solvent", "core", "explain"],
    ["What is a suspension?", "A heterogeneous mixture containing particles that can settle or be filtered", "core", "explain"],
    ["How can appearance help distinguish a solution from a suspension?", "A solution is uniform; a suspension may look cloudy or contain visible particles.", "core", "explain"],
    ["What can a visible laser beam through a mixture indicate?", "Suspended particles are scattering the light.", "stretch", "explain"],
    ["What happens when a suspension is left to stand?", "Its particles may settle.", "foundation", "short"],
    ["What happens when a true solution is passed through ordinary filter paper?", "The dissolved solute and solvent pass through together.", "core", "explain"],
    ["Why should several tests be used to classify an unknown mixture?", "One observation may be misleading, while combined evidence gives a stronger classification.", "stretch", "explain"],
    ["Can changing the solvent change whether a substance dissolves?", "Yes", "foundation", "short"],
    ["Why might a substance dissolve in one solvent but not another?", "Solubility depends on the interaction between the solute and the chosen solvent.", "stretch", "explain"],
    ["What does a concentrated solution contain relative to the same volume of a dilute solution?", "More dissolved solute", "core", "explain"],
    ["What does dilution do to concentration?", "It lowers concentration by adding solvent.", "core", "explain"],
    ["What is a serial dilution?", "A sequence of stepwise dilutions made using the same measured dilution process", "core", "explain"],
    ["Why must volumes be measured consistently in a serial dilution?", "So each step has the intended concentration and can be compared fairly.", "core", "explain"],
    ["How does adding more solute to the same volume affect concentration if it dissolves?", "Concentration increases.", "core", "explain"],
    ["How does adding solvent to a solution affect concentration?", "Concentration decreases.", "core", "explain"],
    ["What is crystallisation used for in this topic?", "Recovering a dissolved solid as crystals from a solution", "core", "explain"],
    ["What does yield mean when crystals are recovered?", "The amount of solid product collected", "core", "explain"],
  ],
  "y8-solubility": [
    ["How can solubility be measured in a school investigation?", "As the maximum mass of solute that dissolves in a fixed volume of solvent at a stated temperature", "core", "explain"],
    ["What observation shows that a solution has become saturated?", "Added solute remains undissolved after enough time and mixing.", "core", "explain"],
    ["Why must the temperature be stated with a solubility result?", "Solubility can change with temperature.", "core", "explain"],
    ["Why should a solubility test use a fixed volume of solvent?", "Changing solvent volume would change how much solute can dissolve.", "core", "explain"],
    ["Why should each trial use the same mixing time?", "Time can affect whether the system has reached the same endpoint in every trial.", "core", "explain"],
    ["Why should stirring be controlled in a solubility comparison?", "Stirring affects how quickly dissolving occurs and could make endpoints inconsistent.", "core", "explain"],
    ["Does stirring make the final solubility larger at the same temperature?", "No. It can change the rate of dissolving, not the final solubility.", "core", "explain"],
    ["Which variable is changed when investigating the effect of temperature on solubility?", "The solvent temperature", "foundation", "short"],
    ["What could be the dependent variable in a solid-solubility investigation?", "The maximum mass of solute that dissolves", "core", "explain"],
    ["Name one control variable for comparing solubility at different temperatures.", "For example, solvent volume, solute type, solvent type, stirring method or mixing time", "core", "explain"],
    ["Why must the same solute be used when testing temperature?", "Different solutes can have different solubilities.", "core", "explain"],
    ["Why must the same solvent be used when testing temperature?", "Changing the solvent would introduce another factor that affects solubility.", "core", "explain"],
    ["How can the effect of solvent type on solubility be tested fairly?", "Keep the solute amount, solvent volume, temperature, time and mixing method the same while changing only the solvent.", "stretch", "explain"],
    ["Why should a balance be used in a quantitative solubility investigation?", "To measure solute mass consistently.", "core", "explain"],
    ["Why are repeat measurements useful in a solubility investigation?", "They show variation, help identify anomalies and improve confidence in the result.", "core", "explain"],
    ["How is a mean solubility result calculated?", "Add the repeat results and divide by the number of results used.", "core", "explain"],
    ["What should be done with an anomalous solubility result?", "Check the method and repeat the measurement rather than ignoring it without reason.", "stretch", "explain"],
    ["What trend is often seen for a solid solute as water temperature rises?", "More solid can dissolve.", "core", "explain"],
    ["How can increased particle motion help explain greater solid solubility at higher temperature?", "Faster particle motion can increase interactions between solvent and solute particles, allowing more solute to separate and mix.", "stretch", "explain"],
    ["Does every solid have exactly the same solubility-temperature pattern?", "No", "foundation", "short"],
    ["What does a solubility curve show?", "How the solubility of a substance changes with temperature", "core", "explain"],
    ["How can a solubility curve be used at a temperature between measured points?", "Estimate the solubility from the pattern between nearby data points.", "stretch", "explain"],
    ["What should be on the horizontal axis of a temperature-solubility graph?", "Temperature", "foundation", "short"],
    ["What should be on the vertical axis of a temperature-solubility graph?", "Measured solubility, such as mass dissolved in the fixed solvent volume", "core", "explain"],
    ["How does gas solubility in a liquid usually change as temperature rises?", "It decreases.", "core", "short"],
    ["Why does warming a fizzy drink encourage gas to escape?", "The gas is less soluble at the higher temperature.", "core", "explain"],
    ["What visible evidence shows gas leaving a fizzy drink?", "Bubbles or fizzing", "foundation", "short"],
    ["Why should a warm fizzy drink and a cold one be compared in identical containers?", "Container differences could affect gas loss and make the test unfair.", "core", "explain"],
    ["What conclusion is supported if every repeated warm sample loses gas faster?", "Higher temperature reduced gas solubility under those conditions.", "stretch", "explain"],
    ["Why is a clearly defined endpoint important in a solubility test?", "It ensures each trial uses the same rule for deciding when no more solute has dissolved.", "core", "explain"],
    ["What makes solubility data reliable?", "A controlled method, appropriate measurements and consistent repeat results", "core", "explain"],
    ["Why should a conclusion refer to the collected data?", "The data provide the evidence for the claimed solubility pattern.", "core", "explain"],
  ],
  "y8-reproduction": [
    ["How does sexual reproduction combine information from parents?", "Gametes from two parents join at fertilisation.", "core", "explain"],
    ["How many parents are needed for asexual reproduction?", "One", "foundation", "short"],
    ["Why are offspring from asexual reproduction usually genetically similar to the parent?", "They are produced from one parent without fusion of gametes.", "core", "explain"],
    ["Give one advantage of asexual reproduction.", "It can produce offspring quickly without needing a mate.", "core", "explain"],
    ["Give one advantage of sexual reproduction.", "It produces variation among offspring.", "core", "explain"],
    ["What is the function of an anther?", "To produce pollen", "foundation", "short"],
    ["What is the function of a filament in a flower?", "To support the anther", "core", "short"],
    ["What is the function of a stigma?", "To receive pollen", "foundation", "short"],
    ["What is the function of the style?", "To connect the stigma to the ovary and provide a route for pollen-tube growth", "core", "explain"],
    ["What is the function of a flower's ovary?", "It contains ovules.", "foundation", "short"],
    ["What happens to an ovule after fertilisation?", "It develops into a seed.", "core", "short"],
    ["How is pollination different from fertilisation?", "Pollination transfers pollen to a stigma; fertilisation is the joining of male and female gametes.", "core", "explain"],
    ["Name one agent that can transfer pollen.", "For example, wind or an animal such as an insect", "foundation", "explain"],
    ["What conditions are commonly needed for seed germination?", "Water, oxygen and a suitable temperature", "core", "short"],
    ["What could be the independent variable in a germination investigation?", "One condition such as water amount, temperature or light", "core", "explain"],
    ["What could be the dependent variable in a germination investigation?", "The number or percentage of seeds that germinate", "core", "explain"],
    ["Why should many seeds be used in a germination test?", "A larger sample reduces the effect of natural variation and improves reliability.", "core", "explain"],
    ["Why should germination trials be repeated?", "Repeats improve confidence and show whether the pattern is consistent.", "core", "explain"],
    ["What is the function of the testes?", "To produce sperm cells and male sex hormones", "core", "explain"],
    ["What is the function of the ovaries?", "To produce egg cells and female sex hormones", "core", "explain"],
    ["Where does human fertilisation usually occur?", "In an oviduct or fallopian tube", "core", "short"],
    ["What is implantation?", "Attachment of the early embryo to the lining of the uterus", "core", "explain"],
    ["Where does an embryo develop during pregnancy?", "In the uterus", "foundation", "short"],
    ["What is the role of the placenta?", "It allows exchange of substances between the pregnant person and fetus.", "core", "explain"],
    ["What is the role of the umbilical cord?", "It connects the fetus to the placenta and carries blood between them.", "core", "explain"],
    ["What is the role of amniotic fluid?", "It cushions and protects the developing fetus.", "core", "explain"],
    ["Do maternal and fetal blood normally mix directly in the placenta?", "No", "core", "short"],
    ["What is puberty?", "The period of physical and reproductive development controlled by hormones", "core", "explain"],
    ["What is menstruation?", "Shedding of the uterus lining when pregnancy has not occurred", "core", "explain"],
    ["Why is the menstrual cycle described as a cycle?", "Changes in the ovaries and uterus repeat in a sequence over time.", "core", "explain"],
    ["Why is seed dispersal useful to a plant?", "It reduces competition with the parent plant and helps spread offspring to new places.", "core", "explain"],
    ["How can a seed's structure provide evidence for its dispersal method?", "Features such as wings, hooks or buoyant coverings are suited to wind, animals or water.", "stretch", "explain"],
  ],
  "y8-chemical-changes": [
    ["How can a chemical change be distinguished from a physical change?", "A chemical change forms one or more new substances; a physical change does not.", "core", "explain"],
    ["Does a change of state create a new substance?", "No", "foundation", "short"],
    ["Why is dissolving not automatically evidence of chemical change?", "A substance can dissolve without forming a new substance.", "core", "explain"],
    ["What might bubbling indicate during a change?", "A gas may be forming, which can be evidence of a chemical change.", "core", "explain"],
    ["What might an unexpected colour change indicate?", "A new substance may have formed.", "core", "explain"],
    ["What might an unexpected temperature change indicate?", "Energy transfer associated with a chemical change may have occurred.", "core", "explain"],
    ["What might light being produced indicate?", "It can be evidence that a chemical change is occurring.", "foundation", "explain"],
    ["What might a new smell indicate?", "A new substance may have formed.", "foundation", "explain"],
    ["What does a newly formed solid in a liquid suggest?", "A precipitate may have formed in a chemical change.", "core", "explain"],
    ["Is one clue always enough to prove a chemical change?", "No. The conclusion should be supported by evidence that a new substance formed.", "core", "explain"],
    ["Why should observations be recorded before and after a change?", "Comparing them helps identify evidence of new properties or substances.", "core", "explain"],
    ["What is a qualitative observation?", "A descriptive observation, such as colour, smell or appearance", "core", "explain"],
    ["What is a quantitative observation?", "A numerical measurement, such as temperature, time or mass", "core", "explain"],
    ["Why can both qualitative and quantitative evidence be useful?", "They provide different kinds of evidence that can strengthen a conclusion.", "stretch", "explain"],
    ["What does reversible mean?", "Able to be changed back to the original substance or state", "core", "explain"],
    ["Can reversibility alone decide whether a change is chemical?", "No. It is one piece of evidence and the formation of new substances remains the key test.", "stretch", "explain"],
    ["Give one example of a physical change.", "For example, melting, freezing, cutting or dissolving when no new substance forms", "foundation", "explain"],
    ["Give one example of a chemical change.", "For example, burning or a reaction that forms a gas or precipitate", "foundation", "explain"],
    ["What is an independent variable?", "The factor deliberately changed in an investigation", "core", "explain"],
    ["What is a dependent variable?", "The outcome measured or observed", "core", "explain"],
    ["What are control variables?", "Factors kept the same to make a comparison fair", "core", "explain"],
    ["Why should only one independent variable be changed?", "So any difference in the outcome can be linked to that variable.", "core", "explain"],
    ["Name one measurement that could provide evidence during a chemical-change investigation.", "For example, temperature, mass, time, gas volume or colour reading", "core", "explain"],
    ["Why should equipment and quantities be kept consistent between trials?", "So the trials can be fairly compared.", "core", "explain"],
    ["What is reliability?", "The extent to which repeated measurements or observations are consistent", "core", "explain"],
    ["How can repeats reveal an anomalous result?", "An anomalous result differs markedly from the pattern in the other repeats.", "core", "explain"],
    ["Why should an anomalous result be investigated?", "It may indicate a measurement or method problem and can affect the conclusion.", "stretch", "explain"],
    ["What should a scientific conclusion state?", "What the evidence shows about the question or variable being investigated", "core", "explain"],
    ["Why must a conclusion refer to observations or measurements?", "Evidence is needed to justify the claim.", "core", "explain"],
    ["A liquid changes colour but no other evidence is collected. What should the conclusion say?", "The colour change is a clue, but more evidence is needed to show that a new substance formed.", "stretch", "explain"],
    ["A solid melts and freezes back into the same material. What type of change is supported?", "A physical change", "core", "short"],
    ["A new insoluble solid and a temperature change are observed. What type of change is supported?", "A chemical change", "core", "short"],
  ],
  "y9-elements-compounds": [
    ["What two properties define matter?", "It has mass and takes up space.", "foundation", "short"],
    ["What is all matter made from?", "Atoms", "foundation", "short"],
    ["What does sub-microscopic mean when describing atoms?", "They are too small to see directly with an ordinary microscope.", "core", "explain"],
    ["Is the space between particles completely filled with matter?", "No. The particle model includes empty space between particles.", "core", "explain"],
    ["What changes when a gas is compressed?", "The spacing between its particles decreases, not the particle size.", "core", "explain"],
    ["What should a solid particle diagram show?", "Particles close together in a fixed arrangement", "core", "explain"],
    ["What should a liquid particle diagram show?", "Particles close together with an irregular arrangement and able to move past one another", "core", "explain"],
    ["What should a gas particle diagram show?", "Particles far apart and moving in different directions", "core", "explain"],
    ["Where are all known elements listed?", "On the periodic table", "foundation", "short"],
    ["What does a chemical symbol identify?", "An element", "foundation", "short"],
    ["How is a two-letter element symbol capitalised?", "The first letter is uppercase and the second is lowercase.", "core", "explain"],
    ["How can a particle diagram show a pure element?", "Every particle contains only the same type of atom.", "core", "explain"],
    ["Can an elemental particle contain two or more bonded atoms?", "Yes. An elemental molecule such as O₂ still contains only one atom type.", "core", "explain"],
    ["How can a compound be recognised in a particle diagram?", "Each compound particle contains two or more different atom types bonded in a fixed ratio.", "core", "explain"],
    ["Can a molecule be an element?", "Yes, if all its atoms are the same element.", "core", "short"],
    ["Why is carbon dioxide both a molecule and a compound?", "It is a bonded group containing atoms of two different elements.", "core", "explain"],
    ["What does chemically bonded mean?", "Atoms are joined through a chemical interaction as part of the same particle or structure.", "core", "explain"],
    ["What does a fixed ratio mean in a compound?", "The elements occur in the same numerical proportion in that compound.", "core", "explain"],
    ["What does a formula tell you first?", "Which elements are present in the substance", "foundation", "short"],
    ["If a symbol in a formula has no subscript, how many atoms does it represent?", "One", "foundation", "short"],
    ["How many hydrogen atoms are represented in H₂O?", "Two", "foundation", "short"],
    ["How many oxygen atoms are represented in H₂O?", "One", "foundation", "short"],
    ["What do brackets mean in a chemical formula?", "The group inside the brackets is treated together and multiplied by the following subscript.", "stretch", "explain"],
    ["What does a coefficient in front of a formula multiply?", "The whole formula", "core", "explain"],
    ["Why does NaCl represent a ratio rather than one molecule?", "Sodium chloride forms a repeating ionic lattice.", "stretch", "explain"],
    ["What is a scientific model?", "A simplified representation used to explain, predict or communicate an idea", "core", "explain"],
    ["Why might a formula be a useful model?", "It communicates which elements are present and their numerical proportions.", "core", "explain"],
    ["Why might a particle diagram be a useful model?", "It can represent particle types, spacing, arrangement and bonding.", "core", "explain"],
    ["Why is a model not a perfect copy of a substance?", "It simplifies selected features and leaves other features out.", "stretch", "explain"],
    ["How does a pure substance appear in a particle diagram?", "Only one type of particle is present.", "core", "explain"],
    ["How does a mixture appear in a particle diagram?", "More than one type of particle is present and the substances are not bonded into a new substance.", "core", "explain"],
    ["Can a homogeneous sample still be a mixture?", "Yes. Air and salt water are mixtures even though they can look uniform.", "core", "explain"],
  ],
  "y9-periodic-table": [
    ["Why are elements arranged in a periodic table?", "The arrangement reveals repeating patterns in their physical and chemical properties.", "core", "explain"],
    ["What do elements in one vertical group tend to share?", "Similar chemical properties", "core", "short"],
    ["Who developed an early periodic table that successfully predicted missing elements?", "Dmitri Mendeleev", "foundation", "short"],
    ["Explain why Mendeleev's gaps were scientifically useful.", "They allowed him to predict the properties of elements that had not yet been discovered.", "stretch", "explain"],
    ["How can the periodic table be used as a scientific model?", "Position and patterns help classify elements and predict properties.", "core", "explain"],
    ["How are elements broadly classified in this topic?", "As metals or non-metals", "foundation", "short"],
    ["State one physical property commonly shown by metals.", "For example, lustre, malleability, ductility, high conductivity or a relatively high melting point", "foundation", "explain"],
    ["State one physical property commonly shown by non-metals.", "For example, low conductivity, a lower boiling point or being a gas at room temperature", "foundation", "explain"],
    ["Are all metals magnetic?", "No", "foundation", "short"],
    ["Are all non-metals gases at room temperature?", "No", "foundation", "short"],
    ["Why are metals often used for electrical wiring?", "Many metals conduct electricity and can be drawn into wires.", "core", "explain"],
    ["What name is given to the Group 1 elements?", "Alkali metals", "foundation", "short"],
    ["Name one Group 1 element studied in this topic.", "Lithium, sodium, potassium, rubidium or caesium", "foundation", "short"],
    ["Why are Group 1 metals stored under oil?", "They are very reactive, so the oil limits contact with air and water.", "core", "explain"],
    ["How does the reaction with water change from lithium to sodium to potassium?", "It becomes more vigorous down the group.", "core", "explain"],
    ["What gas forms when a Group 1 metal reacts with water?", "Hydrogen", "core", "short"],
    ["What type of compound forms when a Group 1 metal reacts with water?", "A metal hydroxide", "core", "short"],
    ["State one physical property common to Group 1 metals.", "They are soft, low-density metals with relatively low melting points.", "core", "explain"],
    ["What name is given to the Group 2 elements?", "Alkaline earth metals", "foundation", "short"],
    ["How does Group 2 reactivity compare with Group 1?", "Group 2 metals are reactive but less reactive than Group 1 metals.", "core", "explain"],
    ["How does reactivity change down Group 2?", "It increases.", "core", "short"],
    ["Which reacts more vigorously with hydrochloric acid: magnesium or calcium?", "Calcium, because it is lower in Group 2.", "core", "explain"],
    ["What are the products when a Group 2 metal reacts with an acid?", "A salt and hydrogen gas", "core", "short"],
    ["What is the positive test for hydrogen gas?", "A lit splint gives a squeaky pop.", "core", "explain"],
    ["What name is given to the Group 17 elements?", "Halogens", "foundation", "short"],
    ["Name one halogen studied in this topic.", "Fluorine, chlorine, bromine or iodine", "foundation", "short"],
    ["How does reactivity change down Group 17?", "It decreases.", "core", "short"],
    ["How can the Group 17 trend be described using position language?", "A halogen higher up Group 17 is more reactive than one lower down.", "core", "explain"],
    ["Give one use of a halogen from the guide.", "For example, chlorine sterilises water or iodine is used as an antiseptic.", "core", "explain"],
    ["What happens when iodine is warmed?", "It forms a purple vapour.", "core", "short"],
    ["What are Group 18 elements called?", "Noble gases", "foundation", "short"],
    ["Why are noble gases used in balloons, signs or welding?", "They are non-reactive under normal conditions, so they are useful when reactions are unwanted.", "core", "explain"],
  ],
  "y9-traits": [
    ["What is an observable trait?", "A characteristic that can be seen or measured", "foundation", "explain"],
    ["Why can two organisms with similar inherited information show different traits?", "Environmental conditions can affect how traits develop or are expressed.", "core", "explain"],
    ["Where is most DNA found in a plant or animal cell?", "In chromosomes in the nucleus", "foundation", "short"],
    ["What is a chromosome?", "A structure made of DNA that carries many genes", "core", "explain"],
    ["How are nucleus, chromosome, DNA and gene related?", "The nucleus contains chromosomes; chromosomes are made of DNA; genes are sections of DNA.", "stretch", "explain"],
    ["What instructions does a gene contain?", "Instructions for making a protein or part of a protein", "core", "explain"],
    ["How can a protein affect an observable trait?", "Proteins influence cell structures and processes that contribute to the trait.", "core", "explain"],
    ["Can one whole trait always be linked to one gene?", "No. Most traits are influenced by many genes and the environment.", "core", "explain"],
    ["What does it mean when a gene is active?", "Its information is being used to make its product.", "core", "explain"],
    ["Can an environmental signal affect gene activity?", "Yes", "foundation", "short"],
    ["How can soil pH affect hydrangea flower colour?", "Soil conditions can influence processes and gene activity involved in producing flower pigments.", "core", "explain"],
    ["How can temperature affect traits in some organisms?", "Temperature can act as an environmental signal during development.", "core", "explain"],
    ["How can nutrition influence phenotype?", "Nutrient availability can affect growth, development and the activity of cell processes.", "core", "explain"],
    ["Why should phenotype not be described as caused only by DNA?", "Many phenotypes result from interactions between genetic information and the environment.", "core", "explain"],
    ["What is inherited variation?", "Differences linked to genetic information received from parents", "core", "explain"],
    ["What is environmental variation?", "Differences produced by conditions or experiences in the environment", "core", "explain"],
    ["Can a trait be influenced by both inherited and environmental factors?", "Yes", "foundation", "short"],
    ["What is the independent variable in an investigation?", "The factor deliberately changed", "core", "explain"],
    ["What is the dependent variable in an investigation?", "The outcome measured or observed", "core", "explain"],
    ["What are control variables?", "Factors kept the same so the test is fair", "core", "explain"],
    ["Why are repeats needed in an investigation of environmental effects?", "They show variation and improve confidence that a pattern is reliable.", "core", "explain"],
    ["Why should an investigation use an appropriate range of environmental conditions?", "A suitable range makes it possible to detect and describe a trend.", "stretch", "explain"],
    ["What should a results table contain?", "Clearly labelled variables, units where needed, and recorded repeat measurements or observations", "core", "explain"],
    ["What is a trend in data?", "A consistent pattern or relationship between variables", "core", "explain"],
    ["Why must a conclusion refer to data?", "The data are the evidence for the claimed effect on the trait.", "core", "explain"],
    ["What is continuous variation?", "Variation that can take any value across a range", "core", "explain"],
    ["Give one example of a continuously varying trait.", "For example, height or mass", "foundation", "explain"],
    ["What is discontinuous variation?", "Variation that falls into separate categories", "core", "explain"],
    ["Which graph is suitable for separate trait categories?", "A bar chart", "core", "short"],
    ["Which graph is suitable for continuous measurements grouped into intervals?", "A histogram", "core", "short"],
    ["Why is a model linking genes, proteins and environment useful?", "It shows how several influences can combine to produce a phenotype.", "stretch", "explain"],
    ["What is one limitation of a simple trait model?", "It may make a multi-gene, environmentally influenced trait look simpler than it really is.", "stretch", "explain"],
  ],
  "y9-reactions": [
    ["Name one observation that can provide evidence of a chemical reaction.", "For example, gas formation, a precipitate, temperature change or colour change", "foundation", "explain"],
    ["Why can gas bubbles be evidence of a reaction?", "A new gas substance may be forming.", "core", "explain"],
    ["What is a precipitate?", "A new insoluble solid formed during a reaction", "core", "explain"],
    ["Why can a temperature change be evidence of a reaction?", "Energy may be transferred as new substances form.", "core", "explain"],
    ["What is a reactant?", "A starting substance in a chemical reaction", "foundation", "explain"],
    ["What is a product?", "A new substance formed in a chemical reaction", "foundation", "explain"],
    ["What does a word equation communicate?", "The names of the reactants and products in a reaction", "core", "explain"],
    ["How can the arrow in a word equation be read aloud?", "Reacts to form", "foundation", "short"],
    ["Where are reactants written in a chemical equation?", "On the left of the arrow", "foundation", "short"],
    ["Where are products written in a chemical equation?", "On the right of the arrow", "foundation", "short"],
    ["What must be equal on both sides of a balanced equation?", "The number of atoms of each element", "core", "explain"],
    ["What number can be changed to balance an equation?", "A coefficient in front of a formula", "core", "short"],
    ["Why would changing a subscript be incorrect when balancing?", "It changes the identity or formula of the substance.", "core", "explain"],
    ["How should an equation be checked after coefficients are added?", "Count the atoms of every element on both sides again.", "core", "explain"],
    ["How does a balanced equation represent conservation of atoms?", "It shows that the same number of each type of atom is present before and after the reaction.", "core", "explain"],
    ["What does the pH scale help classify?", "Whether a solution is acidic, neutral or alkaline", "core", "explain"],
    ["What can an indicator show?", "A colour that gives evidence about a solution's pH range", "core", "explain"],
    ["What pH is neutral?", "7", "foundation", "short"],
    ["What pH values are acidic?", "Below 7", "foundation", "short"],
    ["What pH values are alkaline?", "Above 7", "foundation", "short"],
    ["What are the products of neutralisation between an acid and a base?", "A salt and water", "core", "short"],
    ["What gas forms when a suitable metal reacts with an acid?", "Hydrogen", "core", "short"],
    ["What gas forms when an acid reacts with a carbonate?", "Carbon dioxide", "core", "short"],
    ["What happens to the surroundings during an exothermic reaction?", "They gain energy and usually warm up.", "core", "explain"],
    ["What happens to the surroundings during an endothermic reaction?", "They lose energy and usually cool down.", "core", "explain"],
    ["A reaction mixture warms its surroundings. How is the reaction classified?", "Exothermic", "foundation", "short"],
    ["A reaction mixture cools its surroundings. How is the reaction classified?", "Endothermic", "foundation", "short"],
    ["What two reactants are required for combustion?", "A fuel and oxygen", "core", "short"],
    ["What energy changes are commonly observed in combustion?", "Heat and light are released.", "core", "explain"],
    ["What forms during complete combustion of a hydrocarbon?", "Carbon dioxide and water", "core", "short"],
    ["When can one metal displace another from a compound solution?", "When the added metal is more reactive than the metal in the compound.", "core", "explain"],
    ["How can a displacement reaction compare metal reactivity?", "If one metal replaces another, the added metal is more reactive.", "stretch", "explain"],
  ],
  "y9-forces": [
    ["What is a force?", "A push or pull caused by an interaction between objects", "foundation", "explain"],
    ["Name one change a force can cause.", "A change in speed, direction or shape", "foundation", "short"],
    ["What does the arrowhead show in a force diagram?", "The direction of the force", "foundation", "short"],
    ["What does the length of an arrow show in a force diagram?", "The relative magnitude of the force", "core", "short"],
    ["Name one common force used in the guide's force diagrams.", "An applied push or pull, friction, or weight", "foundation", "explain"],
    ["What is a contact force?", "A force caused by an interaction between objects that are touching", "core", "explain"],
    ["What is a non-contact force?", "A force that acts between objects without direct contact", "core", "explain"],
    ["How is net force found for forces acting in opposite directions?", "Subtract the smaller magnitude from the larger and use the direction of the larger force.", "core", "explain"],
    ["How is net force found for forces acting in the same direction?", "Add their magnitudes.", "foundation", "explain"],
    ["What does balanced forces mean?", "The forces combine to give a net force of zero.", "core", "explain"],
    ["Can a moving object have balanced forces?", "Yes. It can move at constant velocity in a straight line.", "core", "explain"],
    ["What happens when the net force is non-zero?", "The object's speed and/or direction changes.", "core", "explain"],
    ["State Newton's First Law.", "With zero net force, an object stays at rest or moves at constant velocity in a straight line.", "core", "explain"],
    ["Is a force required to keep an object moving at constant velocity?", "No, not when the net force is zero.", "core", "explain"],
    ["Is inertia a force?", "No. It is resistance to a change in motion.", "core", "explain"],
    ["Why is a more massive object harder to start or stop?", "It has greater inertia.", "core", "explain"],
    ["Why does a passenger lurch forward when a bus stops suddenly?", "The passenger's inertia resists the sudden change in motion.", "core", "explain"],
    ["How does a seatbelt relate to Newton's First Law?", "It provides a force that changes the passenger's motion during a sudden stop.", "stretch", "explain"],
    ["What does acceleration mean in Newton's Second Law?", "A change in velocity", "core", "explain"],
    ["Which unit should mass use in F = ma?", "Kilograms (kg)", "foundation", "short"],
    ["Which unit should acceleration use in F = ma?", "Metres per second squared (m/s²)", "core", "short"],
    ["A 3 kg object accelerates at 2 m/s². What net force acts?", "6 N", "core", "short"],
    ["For the same net force, what happens to acceleration when mass increases?", "Acceleration decreases.", "core", "explain"],
    ["Why does an empty trolley accelerate more than a full trolley under the same force?", "The empty trolley has less mass.", "core", "explain"],
    ["State Newton's Third Law.", "Interaction forces occur in pairs on different objects, in opposite directions.", "core", "explain"],
    ["On how many objects does an action-reaction pair act?", "Two different objects", "foundation", "short"],
    ["How do the directions of a Newton's Third Law pair compare?", "They are opposite.", "foundation", "short"],
    ["How do the magnitudes of a Newton's Third Law pair compare?", "They are equal.", "core", "short"],
    ["Why do action and reaction forces not cancel each other?", "They act on different objects.", "core", "explain"],
    ["What force pair helps a person walk forward?", "The foot pushes the ground backward and the ground pushes the foot forward.", "core", "explain"],
    ["How does a rocket use a force pair?", "The rocket pushes exhaust gases backward and the gases push the rocket forward.", "core", "explain"],
    ["In a collision, does the larger object exert a larger interaction force?", "No. The interaction forces on the two objects are equal in magnitude and opposite in direction.", "stretch", "explain"],
  ],
  "y9-pressure-fluids": [
    ["Are liquids fluids?", "Yes", "foundation", "short"],
    ["Are gases fluids?", "Yes", "foundation", "short"],
    ["Why are liquids and gases called fluids?", "They can flow.", "foundation", "explain"],
    ["What is depth?", "Distance below a surface", "foundation", "explain"],
    ["What is altitude?", "Height above a reference level, such as sea level", "foundation", "explain"],
    ["At which position is water pressure greater: near the surface or deeper down?", "Deeper down", "foundation", "short"],
    ["What causes the depth-pressure pattern in a liquid?", "The weight of the liquid above the point being considered", "core", "explain"],
    ["Why does a diver experience greater pressure when descending?", "The diver has a greater depth and therefore more water weight above.", "core", "explain"],
    ["Does liquid pressure stay the same at every depth?", "No", "foundation", "short"],
    ["At which position is atmospheric pressure greater: sea level or a high mountain?", "Sea level", "foundation", "short"],
    ["What causes the altitude-pressure pattern in air?", "The changing weight of air above", "core", "explain"],
    ["Why is there less atmospheric pressure high on a mountain?", "There is less air above, so the weight of air above is smaller.", "core", "explain"],
    ["Does invisible air exert pressure?", "Yes", "foundation", "short"],
    ["What pattern should a graph of liquid pressure against depth show?", "Pressure increases as depth increases.", "core", "explain"],
    ["What pattern should a graph of atmospheric pressure against altitude show?", "Pressure decreases as altitude increases.", "core", "explain"],
    ["How can a demonstration provide evidence about fluid pressure?", "Its observations can show a consistent pressure pattern as depth or altitude changes.", "core", "explain"],
    ["What should a labelled pressure model identify?", "The fluid, the depth or altitude, and the weight of fluid above", "core", "explain"],
    ["Why are models used to explain fluid pressure?", "They represent mechanisms and patterns that are difficult to observe directly.", "core", "explain"],
    ["Is a model identical to the real system?", "No. It is a simplified representation.", "core", "explain"],
    ["Name one possible limitation of a classroom fluid-pressure model.", "It may not reproduce the real scale, materials or natural conditions.", "stretch", "explain"],
    ["Why should an explanation connect model evidence to a real system?", "The model is useful only when its observed pattern supports the real-world claim.", "stretch", "explain"],
    ["Which scientist is linked in the guide to early pressure investigations?", "Blaise Pascal", "foundation", "short"],
    ["What direction does upthrust act?", "Upward", "foundation", "short"],
    ["Which type of material exerts upthrust?", "A fluid, so either a liquid or a gas", "core", "explain"],
    ["Which downward force is compared with upthrust?", "Weight", "foundation", "short"],
    ["What happens when upthrust is greater than weight?", "The object moves or accelerates upward.", "core", "explain"],
    ["What happens when weight is greater than upthrust?", "The object moves or accelerates downward and sinks.", "core", "explain"],
    ["What happens when upthrust and weight are balanced?", "There is no vertical acceleration, so the object can float at rest.", "core", "explain"],
    ["Does floating mean that no forces act on an object?", "No. Upthrust and weight can be balanced.", "core", "explain"],
    ["Why is saying an object floats only because it is light incomplete?", "Floating is explained by comparing its upthrust with its weight.", "core", "explain"],
    ["Is upthrust the same thing as pressure?", "No. Upthrust is an upward force in a fluid.", "core", "explain"],
    ["How can a prediction about floating or sinking be justified?", "Compare the expected upthrust with the object's weight.", "stretch", "explain"],
  ],
};

export const juniorGuideSupplementQuestions: Record<string, BankQuestion[]> =
  Object.fromEntries(
    Object.entries(rows).map(([topicId, topicRows]) => [
      topicId,
      topicRows.map(([q, a, difficulty, kind]) => ({ q, a, difficulty, kind })),
    ]),
  );
