export type BankQuestion = {
  q: string;
  a: string;
  difficulty: "foundation" | "core" | "stretch";
  kind: "short" | "explain";
};

type Row = readonly [string, string, BankQuestion["difficulty"], BankQuestion["kind"]];

const rows: Record<string, Row[]> = {
  "y7-material-properties": [
    ["What word describes a material that light passes through clearly?", "Transparent", "foundation", "short"],
    ["What word describes a material that lets some light through but not a clear image?", "Translucent", "core", "short"],
    ["What word describes a material that does not let light pass through?", "Opaque", "foundation", "short"],
    ["What property describes a material that soaks up water?", "Absorbent", "foundation", "short"],
    ["What property describes a material that does not let water pass through?", "Waterproof", "foundation", "short"],
    ["What word describes a material that breaks rather than bends?", "Brittle", "core", "short"],
    ["What word describes a material that is difficult to bend?", "Rigid", "foundation", "short"],
    ["What property allows a material to return to its original shape after being stretched?", "Elasticity", "core", "short"],
    ["Name one material that is attracted to a magnet.", "Iron or steel", "foundation", "short"],
    ["Are all metals magnetic?", "No", "foundation", "short"],
    ["What type of conductor allows thermal energy to pass through easily?", "A thermal conductor", "core", "short"],
    ["Why is plastic used around electrical wires?", "It is an electrical insulator and helps prevent electric shock.", "core", "explain"],
    ["Why is metal often used for the base of a saucepan?", "It conducts thermal energy well.", "core", "explain"],
    ["Why are saucepan handles often made from plastic or wood?", "They are thermal insulators, so the handle heats more slowly.", "core", "explain"],
    ["Which property is most important for the material of a raincoat?", "Waterproof", "foundation", "short"],
    ["Which property is most important for a material used in a clear safety visor?", "Transparency", "foundation", "short"],
    ["Why must a bridge material be strong?", "It must withstand large forces without breaking or deforming.", "core", "explain"],
    ["Why is rubber suitable for an elastic band?", "It is flexible and elastic.", "core", "explain"],
    ["How are strength and hardness different?", "Strength is resistance to breaking under force; hardness is resistance to scratching or denting.", "stretch", "explain"],
    ["How are flexible and elastic different?", "Flexible materials bend; elastic materials return to their original shape after the force is removed.", "stretch", "explain"],
    ["What two measurements are needed to calculate density?", "Mass and volume", "core", "short"],
    ["Write the equation for density.", "Density = mass ÷ volume", "core", "short"],
    ["Two equal-sized blocks have different masses. Which has the greater density?", "The block with the greater mass", "core", "short"],
    ["Why is low density useful for a life jacket?", "It helps the life jacket float and support a person in water.", "stretch", "explain"],
    ["Why is ceramic useful as an electrical insulator?", "It does not allow electric charge to flow through it easily.", "core", "explain"],
    ["A towel takes in spilled water. Which property is being used?", "Absorbency", "foundation", "short"],
    ["A hammer head resists scratching and denting. Which property is being used?", "Hardness", "core", "short"],
    ["Why might glass be unsuitable for a dropped water bottle?", "It is brittle and may shatter when hit.", "core", "explain"],
    ["What should be considered when choosing a material for a product?", "The properties required for the product's purpose.", "core", "explain"],
    ["Give one reason aluminium is useful for drink cans.", "It is lightweight, malleable and resistant to corrosion.", "stretch", "explain"],
    ["Why is cotton suitable for a bath towel?", "It is soft, flexible and absorbent.", "core", "explain"],
    ["A material is strong but not transparent. Would it be suitable for a window? Explain.", "No, because a window must allow light to pass through.", "stretch", "explain"],
  ],
  "y7-particle-model": [
    ["In which state are particles close together but able to move past one another?", "Liquid", "foundation", "short"],
    ["In which state are particles far apart and moving rapidly in random directions?", "Gas", "foundation", "short"],
    ["How are particles arranged in a solid?", "Closely packed in a fixed, regular arrangement.", "core", "explain"],
    ["How are particles arranged in a liquid?", "Close together in an irregular arrangement.", "core", "explain"],
    ["How are particles arranged in a gas?", "Far apart with no fixed arrangement.", "core", "explain"],
    ["How do particles move in a solid?", "They vibrate about fixed positions.", "foundation", "explain"],
    ["Why does a liquid flow?", "Its particles can move and slide past one another.", "core", "explain"],
    ["Why does a solid keep its shape?", "Its particles are held in fixed positions by strong attractions.", "core", "explain"],
    ["Why does a gas fill its container?", "Its particles move freely in all directions.", "core", "explain"],
    ["What is the change of state from solid to liquid?", "Melting", "foundation", "short"],
    ["What is the change of state from liquid to solid?", "Freezing", "foundation", "short"],
    ["What is the change of state from liquid to gas below the boiling point?", "Evaporation", "core", "short"],
    ["What is the direct change from solid to gas called?", "Sublimation", "stretch", "short"],
    ["What happens to particle energy during melting?", "It increases as energy is transferred to the substance.", "core", "explain"],
    ["What happens to particle movement when a substance cools?", "The particles move or vibrate more slowly.", "core", "explain"],
    ["Do particles disappear when a liquid evaporates?", "No; they move into the gas state.", "foundation", "explain"],
    ["Does the number of particles change during a change of state in a closed container?", "No", "core", "short"],
    ["Why can gases be compressed more easily than liquids?", "Gas particles have much larger spaces between them.", "core", "explain"],
    ["Why are liquids difficult to compress?", "Their particles are already close together.", "core", "explain"],
    ["What causes gas pressure on the walls of a container?", "Gas particles colliding with the walls.", "stretch", "explain"],
    ["Why does food colouring spread through still water?", "Its particles diffuse through the spaces between water particles.", "core", "explain"],
    ["From which concentration to which concentration does diffusion occur overall?", "From high concentration to low concentration.", "core", "short"],
    ["Why is diffusion usually faster at a higher temperature?", "Particles move faster and spread out more quickly.", "stretch", "explain"],
    ["What is the boiling point?", "The temperature at which a liquid boils throughout the liquid.", "core", "explain"],
    ["How is boiling different from evaporation?", "Boiling occurs throughout a liquid at its boiling point; evaporation occurs at the surface and can happen below it.", "stretch", "explain"],
    ["What happens to the spacing between particles when most substances expand?", "The average spacing increases.", "core", "explain"],
    ["Why does the smell of perfume eventually reach the other side of a room?", "Perfume particles diffuse through the air.", "core", "explain"],
    ["A substance has a fixed volume but no fixed shape. What state is it?", "Liquid", "foundation", "short"],
    ["A substance has no fixed shape and no fixed volume. What state is it?", "Gas", "foundation", "short"],
    ["A substance has a fixed shape and a fixed volume. What state is it?", "Solid", "foundation", "short"],
    ["What happens to attractions between particles when a liquid becomes a gas?", "They are overcome as particles separate.", "stretch", "explain"],
    ["Use the particle model to explain why melting is a physical change.", "The particles remain the same substance; only their arrangement and movement change.", "stretch", "explain"],
  ],
  "y7-cells": [
    ["Which cell structure contains the cell sap in a plant cell?", "Vacuole", "foundation", "short"],
    ["Which structure supports and strengthens a plant cell?", "Cell wall", "foundation", "short"],
    ["Which cell structure is the site of most energy release?", "Mitochondria", "core", "short"],
    ["Which jelly-like material is where many cell reactions occur?", "Cytoplasm", "foundation", "short"],
    ["Name one structure found in plant cells but not animal cells.", "Cell wall, chloroplast or large permanent vacuole", "foundation", "short"],
    ["Name one structure found in both plant and animal cells.", "For example: nucleus, cytoplasm, cell membrane or mitochondria.", "foundation", "short"],
    ["What is the function of the nucleus?", "It contains genetic material and controls the cell's activities.", "core", "explain"],
    ["What is the function of the cytoplasm?", "It is where many chemical reactions occur.", "core", "explain"],
    ["What is the function of mitochondria?", "They are where energy is released by respiration.", "core", "explain"],
    ["What is the function of chloroplasts?", "They absorb light for photosynthesis.", "core", "explain"],
    ["What is the function of a plant cell wall?", "It supports and strengthens the cell.", "core", "explain"],
    ["What is an organ?", "A group of different tissues working together to perform a function.", "core", "explain"],
    ["What is an organ system?", "A group of organs working together to perform a major function.", "core", "explain"],
    ["What is an organism?", "An individual living thing.", "foundation", "short"],
    ["Which level of organisation comes directly after tissue?", "Organ", "foundation", "short"],
    ["Which level of organisation comes directly before organ system?", "Organ", "foundation", "short"],
    ["Give one example of a tissue.", "For example: muscle tissue, nervous tissue or xylem tissue.", "core", "short"],
    ["Give one example of an organ.", "For example: heart, lung, stomach, leaf or root.", "foundation", "short"],
    ["Why is the heart described as an organ?", "It contains different tissues working together to pump blood.", "stretch", "explain"],
    ["What is a specialised cell?", "A cell adapted to carry out a particular function.", "core", "explain"],
    ["How is a red blood cell adapted to carry oxygen?", "It has a biconcave shape, is packed with haemoglobin and has no nucleus.", "stretch", "explain"],
    ["How is a nerve cell adapted to carry signals?", "It is long and has branched connections to communicate with other cells.", "stretch", "explain"],
    ["How is a muscle cell adapted to contract?", "It contains fibres that shorten and many mitochondria to release energy.", "stretch", "explain"],
    ["How is a sperm cell specialised for its function?", "It has a tail for movement and many mitochondria to release energy.", "stretch", "explain"],
    ["Why do palisade cells contain many chloroplasts?", "To absorb lots of light for photosynthesis.", "core", "explain"],
    ["Why are root hair cells found near the tips of roots?", "They absorb water and mineral ions from the soil.", "core", "explain"],
    ["What does a microscope allow scientists to do?", "View objects too small to see clearly with the unaided eye.", "foundation", "explain"],
    ["What happens to the field of view when magnification increases?", "It becomes smaller.", "stretch", "short"],
    ["Why should a biological drawing use clear single lines?", "So structures are represented accurately and without shading ambiguity.", "core", "explain"],
    ["A group of muscle cells works together. What level of organisation is this?", "Tissue", "core", "short"],
    ["The stomach and intestines work together. What level of organisation do they form?", "An organ system", "core", "short"],
    ["Explain why cells in the same organism can have different shapes.", "They are specialised for different functions.", "core", "explain"],
  ],
  "y7-thermal-energy": [
    ["What does temperature measure about particles?", "Their average kinetic energy.", "core", "explain"],
    ["Is temperature the same as thermal energy?", "No", "foundation", "short"],
    ["What happens to thermal energy when a warmer object cools?", "It is transferred to the cooler surroundings.", "core", "explain"],
    ["When does net thermal energy transfer stop between two objects?", "When they reach the same temperature.", "core", "short"],
    ["What is thermal equilibrium?", "The state when objects in contact are at the same temperature and there is no net thermal energy transfer.", "core", "explain"],
    ["In which states of matter can convection occur?", "Liquids and gases", "foundation", "short"],
    ["Why can convection not occur in a solid?", "Solid particles cannot flow from place to place.", "core", "explain"],
    ["What happens to most fluids when they are heated?", "They expand and become less dense.", "core", "explain"],
    ["What is a convection current?", "A circulating movement caused by density differences in a fluid.", "core", "explain"],
    ["Why does cooler fluid sink in a convection current?", "It is denser than the warmer fluid around it.", "core", "explain"],
    ["What type of electromagnetic radiation transfers thermal energy?", "Infrared radiation", "core", "short"],
    ["What colour and surface finish is a good absorber of infrared radiation?", "Dark and matt", "core", "short"],
    ["What colour and surface finish is a poor absorber of infrared radiation?", "Light and shiny", "core", "short"],
    ["Why does a shiny emergency blanket reduce thermal energy loss?", "Its surface reflects infrared radiation.", "stretch", "explain"],
    ["Why are loft insulation materials full of trapped air?", "Trapped air is a poor conductor and cannot form large convection currents.", "stretch", "explain"],
    ["How does a vacuum reduce thermal energy transfer?", "It prevents conduction and convection because there are no particles.", "stretch", "explain"],
    ["Can infrared radiation travel through empty space?", "Yes", "foundation", "short"],
    ["Why does conduction happen faster in metals than in many non-metals?", "Metals contain mobile electrons that transfer energy quickly.", "stretch", "explain"],
    ["During conduction, do particles travel through the whole solid?", "No; they vibrate and transfer energy to neighbours.", "core", "explain"],
    ["What happens to particle vibrations when a solid is heated?", "They vibrate faster and with greater amplitude.", "core", "explain"],
    ["Why does a larger temperature difference usually increase the rate of thermal energy transfer?", "There is a greater energy difference driving the transfer.", "stretch", "explain"],
    ["Why does a hot drink cool faster at first than later?", "The temperature difference with the surroundings is greatest at first.", "stretch", "explain"],
    ["Name one way to reduce thermal energy transfer from a house.", "For example: loft insulation, double glazing, wall insulation or draught proofing.", "foundation", "short"],
    ["How does double glazing reduce conduction?", "The trapped air or gas layer is a poor conductor.", "core", "explain"],
    ["How do curtains reduce thermal energy transfer through a window?", "They trap a layer of insulating air and reduce convection.", "core", "explain"],
    ["Why does a wool jumper help keep a person warm?", "It traps air, reducing conduction and convection.", "core", "explain"],
    ["Why does metal feel colder than wood when both are at room temperature?", "Metal transfers thermal energy away from the hand more quickly.", "stretch", "explain"],
    ["Which method transfers thermal energy through direct contact in a solid?", "Conduction", "foundation", "short"],
    ["Which method transfers thermal energy through the movement of a fluid?", "Convection", "foundation", "short"],
    ["Which method transfers thermal energy without particles?", "Radiation", "foundation", "short"],
    ["A radiator warms nearby air, which rises. Which transfer process is this?", "Convection", "core", "short"],
    ["A person feels warmth from a fire across the room. Which transfer process is mainly responsible?", "Infrared radiation", "core", "short"],
  ],
  "y8-mixtures": [
    ["What is a mixture?", "Two or more substances together that are not chemically bonded.", "foundation", "explain"],
    ["What is a pure substance?", "A substance containing only one element or one compound.", "core", "explain"],
    ["In salt water, which substance is the solute?", "Salt", "foundation", "short"],
    ["In salt water, which substance is the solvent?", "Water", "foundation", "short"],
    ["What does dilute mean?", "A small amount of solute is present in a given volume of solution.", "core", "explain"],
    ["How can a solution be made more concentrated without adding solute?", "Remove some solvent by evaporation.", "stretch", "explain"],
    ["What happens to concentration when more solute dissolves in the same volume?", "The concentration increases.", "core", "short"],
    ["What happens to concentration when more solvent is added?", "The concentration decreases.", "core", "short"],
    ["Does a clear liquid always contain a pure substance?", "No; a solution can also be clear.", "core", "explain"],
    ["Why is a solution described as a mixture?", "The solute and solvent are together but are not chemically bonded.", "core", "explain"],
    ["Which separation method removes an insoluble solid from a liquid?", "Filtration", "foundation", "short"],
    ["What is the solid left on filter paper called?", "Residue", "core", "short"],
    ["What is the liquid that passes through filter paper called?", "Filtrate", "core", "short"],
    ["Why can sand be separated from water by filtration?", "Sand is insoluble and its particles are trapped by the filter paper.", "core", "explain"],
    ["Why can dissolved sugar not be separated from water by filtration?", "The dissolved sugar particles pass through the filter paper.", "core", "explain"],
    ["Which method can separate and recover a solvent from a solution?", "Simple distillation", "core", "short"],
    ["What happens to the solvent during distillation?", "It evaporates and then condenses.", "core", "explain"],
    ["Why can distillation separate salt from water?", "Water boils and condenses while the non-volatile salt remains behind.", "stretch", "explain"],
    ["Which method separates soluble coloured substances?", "Chromatography", "foundation", "short"],
    ["Why do dyes separate during chromatography?", "They have different solubilities in the solvent and attractions to the paper.", "stretch", "explain"],
    ["What does one spot on a chromatogram suggest about an ink?", "It may contain one soluble dye under those conditions.", "stretch", "explain"],
    ["What do several spots from one ink suggest?", "The ink is a mixture of several dyes.", "core", "explain"],
    ["Why must the start line in paper chromatography be drawn in pencil?", "Pencil does not dissolve in the solvent and move up the paper.", "core", "explain"],
    ["Why must the solvent level begin below the sample spots?", "Otherwise the samples may dissolve directly into the solvent instead of travelling up the paper.", "stretch", "explain"],
    ["Which property can be used to separate magnetic iron from sand?", "Magnetism", "foundation", "short"],
    ["How could differently sized solids be separated?", "By sieving.", "foundation", "short"],
    ["Why can mixtures be separated using physical methods?", "Their substances keep their own properties and are not chemically bonded.", "core", "explain"],
    ["A student adds water to orange juice. Is the amount of solute changed?", "No", "core", "short"],
    ["A student adds water to orange juice. What happens to its concentration?", "It decreases; the juice becomes more dilute.", "core", "explain"],
    ["What happens to solute particles when they dissolve?", "They separate and spread among the solvent particles.", "core", "explain"],
    ["Is dissolving the same as melting?", "No", "foundation", "short"],
    ["Explain one difference between dissolving and melting.", "Dissolving mixes a solute with a solvent; melting is a change of state caused by heating.", "stretch", "explain"],
  ],
  "y8-solubility": [
    ["What does soluble mean?", "Able to dissolve in a particular solvent.", "foundation", "explain"],
    ["What does insoluble mean?", "Unable to dissolve appreciably in a particular solvent.", "foundation", "explain"],
    ["What is an unsaturated solution?", "A solution that can still dissolve more solute at that temperature.", "core", "explain"],
    ["How can you tell that a solution may be saturated?", "Added solute remains undissolved even after mixing at the same temperature.", "core", "explain"],
    ["Is solubility a measure of how quickly a substance dissolves?", "No", "foundation", "short"],
    ["What is the difference between solubility and dissolving rate?", "Solubility is the maximum amount that can dissolve; rate is how quickly it dissolves.", "stretch", "explain"],
    ["Does crushing a solute usually change its final solubility?", "No", "core", "short"],
    ["Why does crushing a solid make it dissolve faster?", "It increases the surface area in contact with the solvent.", "core", "explain"],
    ["Does increasing surface area change the maximum amount that dissolves at a fixed temperature?", "No", "stretch", "short"],
    ["How does warming usually affect the rate at which a solid dissolves?", "It increases the rate.", "core", "short"],
    ["Why does warming often make a solid dissolve faster?", "Solvent particles move faster and collide with the solute more often and with more energy.", "stretch", "explain"],
    ["What should be kept constant when comparing the solubility of two substances?", "The type and amount of solvent and the temperature.", "stretch", "explain"],
    ["Why must temperature be stated with a solubility value?", "Solubility usually changes with temperature.", "core", "explain"],
    ["What does a point on a solubility curve show?", "The maximum mass of solute that dissolves in a stated amount of solvent at that temperature.", "stretch", "explain"],
    ["What does a line sloping upward on a solubility graph show?", "Solubility increases as temperature increases.", "core", "explain"],
    ["How can a saturated hot solution produce crystals?", "Cool it so the solubility decreases and excess solute crystallises.", "core", "explain"],
    ["Why do crystals form as a saturated solution cools?", "The cooler solvent can dissolve less solute.", "stretch", "explain"],
    ["What is crystallisation?", "The formation of solid crystals from a solution.", "foundation", "explain"],
    ["Why should a solution not always be heated to complete dryness when making crystals?", "Strong heating can spit the solution or decompose the solute.", "stretch", "explain"],
    ["What is the purpose of evaporating some solvent before cooling a crystal solution?", "To make the solution concentrated or saturated.", "core", "explain"],
    ["How can crystals be separated from the remaining solution?", "By filtration.", "foundation", "short"],
    ["How should wet crystals be dried safely?", "Blot them between filter papers or leave them to dry.", "core", "explain"],
    ["If all added solute dissolves, is the solution definitely saturated?", "No", "core", "short"],
    ["A solution contains undissolved solid. What should be done before deciding it is saturated?", "Stir it and allow enough time at a constant temperature.", "stretch", "explain"],
    ["Can a substance be soluble in one solvent but insoluble in another?", "Yes", "foundation", "short"],
    ["Why is water called a solvent in a sugar solution?", "It is the liquid that dissolves the sugar.", "foundation", "explain"],
    ["What happens to the concentration of a saturated solution if it is warmed and no more solute is added?", "It remains the same initially, but it can now dissolve more solute.", "stretch", "explain"],
    ["What could make a saturated solution unsaturated?", "Add more solvent or increase the temperature if solubility rises with temperature.", "core", "explain"],
    ["Why is the same volume of solvent needed in a fair solubility comparison?", "A larger volume could dissolve more solute.", "core", "explain"],
    ["State one factor that changes dissolving rate but not final solubility at a fixed temperature.", "Stirring or solute particle size.", "core", "short"],
    ["What happens to dissolved particles when crystals form?", "They leave the solution and arrange into a solid structure.", "stretch", "explain"],
    ["A hot saturated solution is cooled but no crystals form immediately. Give one possible reason.", "Crystallisation may need time or a seed crystal to begin.", "stretch", "explain"],
  ],
  "y8-reproduction": [
    ["Where are sperm cells produced?", "Testes", "foundation", "short"],
    ["Where are egg cells produced?", "Ovaries", "foundation", "short"],
    ["Which tube carries sperm away from the testes?", "Sperm duct", "core", "short"],
    ["Which tube carries an egg from an ovary toward the uterus?", "Oviduct or fallopian tube", "core", "short"],
    ["Where does fertilisation usually occur?", "In an oviduct or fallopian tube.", "core", "short"],
    ["What is the function of the uterus?", "It is where an embryo implants and a fetus develops.", "core", "explain"],
    ["What is the function of the penis in reproduction?", "It transfers semen containing sperm into the vagina.", "core", "explain"],
    ["What is the function of the vagina in reproduction?", "It receives sperm and forms the birth canal.", "core", "explain"],
    ["What is semen?", "A fluid containing sperm cells and substances that support them.", "core", "explain"],
    ["Why are testes held outside the main body cavity?", "Sperm production works best at a temperature slightly below body temperature.", "stretch", "explain"],
    ["What is ovulation?", "The release of a mature egg from an ovary.", "core", "explain"],
    ["What is menstruation?", "The shedding of the uterus lining when pregnancy has not occurred.", "core", "explain"],
    ["Why does the uterus lining thicken during the menstrual cycle?", "To prepare for the possible implantation and nourishment of an embryo.", "stretch", "explain"],
    ["What is implantation?", "The attachment of an early embryo to the uterus lining.", "core", "explain"],
    ["What happens to the zygote after fertilisation?", "It divides repeatedly to form an embryo.", "core", "explain"],
    ["What is an embryo?", "An early stage of development after the zygote begins dividing.", "foundation", "explain"],
    ["What is a fetus?", "A later stage of development in the uterus when body structures are recognisable.", "foundation", "explain"],
    ["What connects the fetus to the placenta?", "Umbilical cord", "foundation", "short"],
    ["Name one substance that passes from the mother to the fetus through the placenta.", "Oxygen or nutrients such as glucose", "foundation", "short"],
    ["Name one waste substance that passes from the fetus to the mother.", "Carbon dioxide or urea", "core", "short"],
    ["Do the mother's blood and the fetus's blood normally mix directly?", "No", "core", "short"],
    ["Why is the placenta an exchange surface?", "It allows substances to move between the mother's and fetus's blood supplies.", "stretch", "explain"],
    ["How is an egg cell adapted for early development?", "It is large and contains a nutrient-rich cytoplasm.", "stretch", "explain"],
    ["Why does a sperm cell have many mitochondria?", "To release energy for swimming.", "core", "explain"],
    ["Why does a sperm cell have an acrosome?", "It contains enzymes that help the sperm penetrate the egg.", "stretch", "explain"],
    ["How many sperm cells normally fertilise one egg cell?", "One", "foundation", "short"],
    ["Why does the egg membrane change after fertilisation?", "To prevent additional sperm entering.", "stretch", "explain"],
    ["What causes many changes during puberty?", "Hormones", "foundation", "short"],
    ["Name one change that commonly occurs in all people during puberty.", "For example: growth spurt, body hair, oilier skin or emotional changes.", "foundation", "short"],
    ["Why is puberty important for reproduction?", "The reproductive organs mature and begin producing gametes.", "core", "explain"],
    ["How does sexual reproduction create variation?", "Offspring receive a different combination of genetic information from two parents.", "stretch", "explain"],
    ["What is the difference between a gamete and a zygote?", "A gamete is a sex cell; a zygote is the cell formed when two gametes fuse.", "stretch", "explain"],
  ],
  "y8-chemical-changes": [
    ["What is a physical change?", "A change in state or form in which no new substance is made.", "foundation", "explain"],
    ["What is a chemical change?", "A change in which one or more new substances are formed.", "foundation", "explain"],
    ["Is dissolving usually a physical or chemical change?", "Physical change", "foundation", "short"],
    ["Is rusting a physical or chemical change?", "Chemical change", "foundation", "short"],
    ["Is boiling water a physical or chemical change?", "Physical change", "foundation", "short"],
    ["Is cooking an egg a physical or chemical change?", "Chemical change", "core", "short"],
    ["Why is freezing water a physical change?", "No new substance forms, and the water can be melted again.", "core", "explain"],
    ["Why is rusting iron a chemical change?", "A new substance, iron oxide, is formed.", "core", "explain"],
    ["Does every colour change prove that a chemical reaction occurred?", "No", "core", "short"],
    ["Why is one observation alone sometimes insufficient evidence of a reaction?", "Some physical changes can produce similar observations, so evidence must be interpreted.", "stretch", "explain"],
    ["What is a precipitate?", "An insoluble solid formed when two solutions react.", "core", "explain"],
    ["What observation suggests a gas is being produced?", "Bubbles or fizzing not caused by boiling.", "foundation", "short"],
    ["What can a temperature increase during a reaction show?", "The reaction transfers energy to the surroundings.", "core", "explain"],
    ["What can a temperature decrease during a reaction show?", "The reaction takes in energy from the surroundings.", "core", "explain"],
    ["In a word equation, where are reactants written?", "On the left of the arrow.", "foundation", "short"],
    ["In a word equation, where are products written?", "On the right of the arrow.", "foundation", "short"],
    ["What does the arrow in a word equation mean?", "Reacts to form or produces.", "core", "short"],
    ["Why are products different from reactants?", "Their atoms are joined and arranged differently, giving them different properties.", "stretch", "explain"],
    ["What happens to atoms during a chemical reaction?", "They are rearranged into new combinations.", "core", "explain"],
    ["Are atoms created during a chemical reaction?", "No", "foundation", "short"],
    ["Are atoms destroyed during a chemical reaction?", "No", "foundation", "short"],
    ["State the law of conservation of mass.", "Mass is not created or destroyed in a chemical reaction.", "core", "explain"],
    ["Why can measured mass decrease when a reaction occurs in an open container?", "A gaseous product may escape.", "stretch", "explain"],
    ["Why can measured mass increase when a substance burns in air?", "Atoms from oxygen in the air join the substance.", "stretch", "explain"],
    ["Why does a sealed container help demonstrate conservation of mass?", "No substances can enter or leave the system.", "core", "explain"],
    ["What is a closed system?", "A system in which matter cannot enter or leave.", "core", "explain"],
    ["What does reversible mean?", "Able to be changed back to the original substance or state.", "foundation", "explain"],
    ["Why are many chemical changes difficult to reverse?", "The original atoms have been rearranged into new substances.", "core", "explain"],
    ["Can a chemical reaction be reversible?", "Yes, some chemical reactions can proceed in both directions.", "stretch", "explain"],
    ["A solid forms when two clear solutions mix. What evidence of chemical change is this?", "Formation of a precipitate", "core", "short"],
    ["A reaction mixture becomes warm. What evidence of chemical change is this?", "A temperature change caused by energy transfer.", "core", "explain"],
    ["How could you test whether a change formed a new substance?", "Compare the properties of the material before and after the change.", "stretch", "explain"],
  ],
  "y9-elements-compounds": [
    ["What is an atom?", "The smallest particle of an element that retains that element's identity.", "foundation", "explain"],
    ["What is a molecule?", "Two or more atoms chemically bonded together.", "foundation", "explain"],
    ["Can a molecule contain atoms of only one element?", "Yes", "foundation", "short"],
    ["What is a compound?", "A substance made from atoms of two or more different elements chemically bonded in fixed proportions.", "core", "explain"],
    ["What is a mixture?", "Two or more substances together that are not chemically bonded.", "foundation", "explain"],
    ["Is every molecule a compound?", "No", "core", "short"],
    ["Is every compound made from more than one element?", "Yes", "foundation", "short"],
    ["Why is oxygen gas an element even though its particles are O2 molecules?", "Each molecule contains only oxygen atoms.", "core", "explain"],
    ["Why is carbon dioxide a compound?", "It contains carbon and oxygen atoms chemically bonded together.", "core", "explain"],
    ["Why is air a mixture rather than a compound?", "Its gases are not chemically bonded and their proportions can vary.", "core", "explain"],
    ["Can the parts of a mixture be present in any proportion?", "Yes", "foundation", "short"],
    ["Are elements in a compound present in a fixed ratio?", "Yes", "foundation", "short"],
    ["How can a mixture usually be separated?", "Using physical methods based on differences in properties.", "core", "explain"],
    ["Can a compound usually be separated by physical methods?", "No", "core", "short"],
    ["What does a chemical symbol represent?", "An element.", "foundation", "short"],
    ["Why do some chemical symbols have two letters?", "They distinguish elements whose names begin with the same letter; the second letter is lowercase.", "core", "explain"],
    ["How should the second letter of a two-letter element symbol be written?", "Lowercase", "foundation", "short"],
    ["What element is represented by H?", "Hydrogen", "foundation", "short"],
    ["What element is represented by O?", "Oxygen", "foundation", "short"],
    ["What element is represented by C?", "Carbon", "foundation", "short"],
    ["What does the formula H2O show?", "Each water molecule contains two hydrogen atoms and one oxygen atom.", "core", "explain"],
    ["How many total atoms are shown in one molecule of H2O?", "Three", "foundation", "short"],
    ["How many carbon atoms are shown in one molecule of CO2?", "One", "foundation", "short"],
    ["How many atoms are shown in one molecule of O2?", "Two", "foundation", "short"],
    ["What does a small lower number in a chemical formula show?", "The number of atoms of the element immediately before it.", "core", "explain"],
    ["If no small number follows a symbol in a formula, how many atoms of that element are present?", "One", "foundation", "short"],
    ["What does diatomic mean?", "Existing as molecules made of two atoms.", "core", "explain"],
    ["Give one example of a diatomic element.", "For example: hydrogen, nitrogen, oxygen, fluorine, chlorine, bromine or iodine.", "core", "short"],
    ["A particle diagram shows identical single atoms. What type of substance is present?", "An element", "core", "short"],
    ["A particle diagram shows identical groups containing two different atom types bonded together. What is present?", "A pure compound", "core", "short"],
    ["A particle diagram shows two different particle types together. What is present?", "A mixture", "core", "short"],
    ["What stays the same about atoms when they form a compound?", "Their element identities; the atoms are rearranged and bonded in a new combination.", "stretch", "explain"],
  ],
  "y9-periodic-table": [
    ["What is the periodic table?", "An arrangement of the chemical elements in order of atomic number.", "foundation", "explain"],
    ["How are elements ordered across the modern periodic table?", "By increasing atomic number.", "core", "short"],
    ["Where are non-metals mainly found on the periodic table?", "On the right-hand side.", "foundation", "short"],
    ["What does an element's period number tell you?", "The number of occupied electron shells.", "core", "explain"],
    ["What do elements in the same group share?", "Similar chemical properties and the same number of outer-shell electrons for the main groups.", "core", "explain"],
    ["What is found at the centre of an atom?", "The nucleus", "foundation", "short"],
    ["Which two particles are found in the nucleus?", "Protons and neutrons", "foundation", "short"],
    ["Which subatomic particle moves around the nucleus in shells?", "Electron", "foundation", "short"],
    ["What electrical charge does a proton have?", "Positive", "foundation", "short"],
    ["What electrical charge does an electron have?", "Negative", "foundation", "short"],
    ["What electrical charge does a neutron have?", "No charge or neutral", "foundation", "short"],
    ["Why is an atom electrically neutral?", "It has equal numbers of protons and electrons.", "core", "explain"],
    ["What is the relative mass of a proton?", "1", "core", "short"],
    ["What is the relative mass of a neutron?", "1", "core", "short"],
    ["What is the relative mass of an electron compared with a proton?", "Very small, approximately 1/1836.", "stretch", "short"],
    ["Which group contains the alkali metals?", "Group 1", "foundation", "short"],
    ["State one typical property of Group 1 metals.", "They are soft, low-density and reactive metals.", "core", "short"],
    ["How many outer-shell electrons do Group 1 atoms have?", "One", "core", "short"],
    ["Why do Group 1 elements react in similar ways?", "They all have one outer-shell electron.", "stretch", "explain"],
    ["Which group contains the halogens?", "Group 17", "foundation", "short"],
    ["How many outer-shell electrons do Group 17 atoms have?", "Seven", "core", "short"],
    ["How does halogen reactivity change down Group 17?", "It decreases.", "core", "short"],
    ["Why do halogens react in similar ways?", "They all have seven outer-shell electrons and tend to gain one electron.", "stretch", "explain"],
    ["Why are noble gases very unreactive?", "They have full outer electron shells.", "core", "explain"],
    ["How many outer-shell electrons do most Group 18 atoms have?", "Eight", "core", "short"],
    ["Why does helium have a full outer shell with only two electrons?", "Its first electron shell can hold a maximum of two electrons.", "stretch", "explain"],
    ["State one typical property of metals.", "For example: good conductor, malleable, shiny or high melting point.", "foundation", "short"],
    ["State one typical property of non-metals.", "For example: poor conductor, brittle when solid or dull.", "foundation", "short"],
    ["Why can an element's position help predict its properties?", "Elements in the same group have similar electron arrangements and chemical behaviour.", "stretch", "explain"],
    ["An atom has atomic number 8. How many protons does it have?", "Eight", "foundation", "short"],
    ["A neutral atom has 12 protons. How many electrons does it have?", "Twelve", "core", "short"],
    ["What changes by one as you move from one element to the next across a period?", "The atomic number or number of protons.", "core", "short"],
  ],
  "y9-traits": [
    ["What is a characteristic?", "A feature of an organism.", "foundation", "explain"],
    ["What is a trait?", "A particular form of a characteristic shown by an organism.", "foundation", "explain"],
    ["What is a chromosome?", "A long, coiled DNA molecule carrying many genes.", "core", "explain"],
    ["What is an allele?", "An alternative version of a gene.", "core", "explain"],
    ["How many alleles for a gene does an offspring usually inherit?", "Two, one from each parent.", "core", "short"],
    ["What is a genotype?", "The combination of alleles an organism has for a gene.", "core", "explain"],
    ["What is a phenotype?", "The observable characteristic produced by the genotype and environment.", "core", "explain"],
    ["What is a dominant allele?", "An allele expressed in the phenotype when one or two copies are present.", "core", "explain"],
    ["What is a recessive allele?", "An allele expressed in the phenotype only when two copies are present.", "core", "explain"],
    ["How is a dominant allele usually represented?", "With a capital letter.", "foundation", "short"],
    ["How is a recessive allele usually represented?", "With the corresponding lowercase letter.", "foundation", "short"],
    ["What does homozygous mean?", "Having two identical alleles for a gene.", "core", "explain"],
    ["What does heterozygous mean?", "Having two different alleles for a gene.", "core", "explain"],
    ["Can a person with a dominant phenotype carry a recessive allele?", "Yes", "core", "short"],
    ["Can a recessive phenotype appear when a dominant allele is present?", "No, in a simple dominant-recessive model.", "core", "short"],
    ["What is inherited variation?", "Differences caused by genetic information passed from parents.", "core", "explain"],
    ["What is environmental variation?", "Differences caused by conditions or experiences in the environment.", "core", "explain"],
    ["Give one example of an inherited characteristic.", "For example: natural eye colour, blood group or biological sex.", "foundation", "short"],
    ["Give one characteristic influenced by both genes and environment.", "For example: height, body mass or skin colour.", "core", "short"],
    ["Why are siblings genetically different from one another?", "They inherit different combinations of alleles from their parents.", "core", "explain"],
    ["Are identical twins always identical in every characteristic?", "No; environmental differences can affect their phenotypes.", "stretch", "explain"],
    ["What does a Punnett square predict?", "Possible allele combinations and their probabilities in offspring.", "core", "explain"],
    ["Does a Punnett square predict exactly which traits each child will have?", "No; it shows probabilities, not certain outcomes.", "stretch", "explain"],
    ["If B is dominant, what phenotype will genotype Bb show?", "The dominant phenotype", "core", "short"],
    ["If b is recessive, which genotype shows the recessive phenotype?", "bb", "core", "short"],
    ["What gametes can a parent with genotype Bb produce for this gene?", "B or b", "stretch", "short"],
    ["Why does each gamete carry only one allele for a particular gene?", "Gametes contain one chromosome from each pair.", "stretch", "explain"],
    ["Where is DNA located in most animal and plant cells?", "In chromosomes in the nucleus.", "foundation", "short"],
    ["What is the relationship between DNA, genes and chromosomes?", "Genes are sections of DNA, and DNA is packaged into chromosomes.", "stretch", "explain"],
    ["Why can two organisms have the same genotype but slightly different phenotypes?", "Their environments may influence how the characteristic develops.", "stretch", "explain"],
    ["Is a suntan inherited or environmental variation?", "Environmental variation", "foundation", "short"],
    ["Is blood group mainly inherited or environmental?", "Inherited", "foundation", "short"],
  ],
  "y9-reactions": [
    ["What is a reactant?", "A starting substance in a chemical reaction.", "foundation", "explain"],
    ["What is a product?", "A new substance formed in a chemical reaction.", "foundation", "explain"],
    ["What does a word equation show?", "The names of reactants and products in a chemical reaction.", "foundation", "explain"],
    ["Complete the general form: reactants ___ products.", "→", "foundation", "short"],
    ["What happens to atoms during a chemical reaction?", "They are rearranged into new substances.", "core", "explain"],
    ["Why is mass conserved in a chemical reaction?", "The same atoms are present before and after the reaction.", "core", "explain"],
    ["Why can mass appear to decrease in an open reaction vessel?", "A gas product may escape into the surroundings.", "stretch", "explain"],
    ["What is reaction rate?", "How quickly reactants are used up or products are formed.", "core", "explain"],
    ["Name one way to measure the rate of a gas-producing reaction.", "Measure gas volume or mass loss over time.", "core", "short"],
    ["What happens to reaction rate when reactants are used up?", "It usually decreases.", "core", "short"],
    ["Why does reaction rate often decrease during a reaction?", "Reactant particles become less concentrated, so successful collisions occur less often.", "stretch", "explain"],
    ["What is collision theory?", "Reactions occur when particles collide with sufficient energy and suitable orientation.", "stretch", "explain"],
    ["Are all particle collisions successful?", "No", "foundation", "short"],
    ["What is activation energy?", "The minimum energy particles need for a successful collision.", "core", "explain"],
    ["Why does increasing concentration increase reaction rate?", "More particles in the same volume cause more frequent collisions.", "core", "explain"],
    ["Why does increasing gas pressure increase reaction rate?", "Gas particles are closer together and collide more frequently.", "stretch", "explain"],
    ["Why does increasing temperature increase collision frequency?", "Particles move faster.", "core", "explain"],
    ["Why does increasing temperature increase the fraction of successful collisions?", "More particles have energy equal to or greater than the activation energy.", "stretch", "explain"],
    ["How does decreasing particle size affect reaction rate?", "It increases the rate by increasing surface area.", "core", "explain"],
    ["Why does only the exposed surface of a solid react?", "Reactant particles must collide with particles at the solid's surface.", "stretch", "explain"],
    ["What is a catalyst?", "A substance that increases reaction rate without being used up overall.", "core", "explain"],
    ["How does a catalyst increase reaction rate?", "It provides an alternative reaction pathway with lower activation energy.", "stretch", "explain"],
    ["Does a catalyst increase the amount of product made from fixed amounts of reactants?", "No; it changes how quickly the product forms.", "stretch", "explain"],
    ["What usually happens to the surroundings in an exothermic reaction?", "Their temperature increases.", "core", "short"],
    ["What usually happens to the surroundings in an endothermic reaction?", "Their temperature decreases.", "core", "short"],
    ["Is combustion usually exothermic or endothermic?", "Exothermic", "foundation", "short"],
    ["Is thermal decomposition usually exothermic or endothermic?", "Endothermic", "core", "short"],
    ["Where does transferred energy go in an exothermic reaction?", "From the reacting chemicals to the surroundings.", "core", "explain"],
    ["Where does transferred energy come from in an endothermic reaction?", "From the surroundings into the reacting chemicals.", "core", "explain"],
    ["A reaction mixture becomes colder. What type of energy change is suggested?", "Endothermic", "foundation", "short"],
    ["A reaction finishes sooner after warming. What happened to its rate?", "The reaction rate increased.", "foundation", "short"],
    ["Why should only one factor be changed in a reaction-rate investigation?", "So any change in rate can be attributed to that factor.", "core", "explain"],
  ],
  "y9-acids-bases": [
    ["What is an acid?", "A substance that produces hydrogen ions in water.", "core", "explain"],
    ["What is a base?", "A substance that reacts with and neutralises an acid.", "core", "explain"],
    ["What pH values show that a solution is alkaline?", "Above 7", "foundation", "short"],
    ["What does the pH scale measure?", "How acidic or alkaline a solution is.", "foundation", "explain"],
    ["Which ions make an aqueous solution acidic?", "Hydrogen ions, H+", "core", "short"],
    ["Which ions are associated with alkaline solutions?", "Hydroxide ions, OH-", "core", "short"],
    ["What colour is universal indicator at neutral pH?", "Green", "foundation", "short"],
    ["What colour is universal indicator in a strongly alkaline solution?", "Purple", "foundation", "short"],
    ["What colours can universal indicator show in a weakly acidic solution?", "Yellow or orange", "core", "short"],
    ["Why is universal indicator more useful than litmus for estimating pH?", "It produces a range of colours corresponding to different pH values.", "core", "explain"],
    ["What colour does blue litmus turn in acid?", "Red", "foundation", "short"],
    ["What colour does red litmus turn in an alkali?", "Blue", "foundation", "short"],
    ["Does dilution change an acid into an alkali?", "No", "foundation", "short"],
    ["What happens to the pH of an alkali when water is added?", "It decreases toward 7.", "core", "explain"],
    ["How are acid strength and concentration different?", "Strength is the extent of ionisation; concentration is the amount of acid per volume.", "stretch", "explain"],
    ["Can a strong acid be dilute?", "Yes", "core", "short"],
    ["Can a weak acid be concentrated?", "Yes", "core", "short"],
    ["Name one common strong acid.", "Hydrochloric, nitric or sulfuric acid", "foundation", "short"],
    ["Name one common weak acid.", "Ethanoic, citric or carbonic acid", "foundation", "short"],
    ["Complete the general equation: acid + base → ___.", "Salt + water", "core", "short"],
    ["Complete the general equation: acid + metal → ___.", "Salt + hydrogen", "core", "short"],
    ["Complete the general equation: acid + metal carbonate → ___.", "Salt + water + carbon dioxide", "core", "short"],
    ["What gas is produced when many metals react with dilute acids?", "Hydrogen", "foundation", "short"],
    ["What gas is produced when an acid reacts with a carbonate?", "Carbon dioxide", "foundation", "short"],
    ["What is the test for hydrogen gas?", "A lit splint gives a squeaky pop.", "core", "explain"],
    ["What is the test for carbon dioxide gas?", "It turns limewater milky or cloudy.", "core", "explain"],
    ["Which part of an acid's name determines the salt formed?", "The acid's negative ion or acid type.", "stretch", "explain"],
    ["Which salts are formed from hydrochloric acid?", "Chlorides", "core", "short"],
    ["Which salts are formed from sulfuric acid?", "Sulfates", "core", "short"],
    ["Which salts are formed from nitric acid?", "Nitrates", "core", "short"],
    ["What happens to hydrogen ions during neutralisation?", "They react with hydroxide ions to form water.", "stretch", "explain"],
    ["Why should eye protection be worn when handling acids and alkalis?", "They can irritate or damage eyes, especially when concentrated.", "foundation", "explain"],
  ],
  "y9-forces": [
    ["What is a force?", "A push or a pull caused by an interaction.", "foundation", "explain"],
    ["What is the SI unit of force?", "Newton", "foundation", "short"],
    ["What instrument can be used to measure force?", "Newton meter or force meter", "foundation", "short"],
    ["Name one effect a force can have on an object.", "Change its speed, direction or shape.", "foundation", "short"],
    ["What is a contact force?", "A force that acts only when objects or materials are touching.", "core", "explain"],
    ["Give one example of a contact force.", "For example: friction, drag, tension, normal contact force or upthrust.", "foundation", "short"],
    ["What is a non-contact force?", "A force that acts without the objects touching.", "core", "explain"],
    ["Give one example of a non-contact force.", "Gravitational, magnetic or electrostatic force", "foundation", "short"],
    ["What is the resultant force?", "The single force with the same effect as all forces acting together.", "core", "explain"],
    ["How do you find the resultant of two forces acting in the same direction?", "Add their magnitudes.", "foundation", "explain"],
    ["How do you find the resultant of two opposite forces?", "Subtract the smaller force from the larger and use the larger force's direction.", "core", "explain"],
    ["What is the resultant force when forces are balanced?", "Zero newtons", "foundation", "short"],
    ["Can a moving object have balanced forces acting on it?", "Yes", "core", "short"],
    ["How does an object move if the resultant force is zero?", "It remains at rest or continues at constant velocity.", "core", "explain"],
    ["What happens to an object's motion when there is a non-zero resultant force?", "It accelerates in the direction of the resultant force.", "core", "explain"],
    ["What does acceleration mean?", "A change in velocity per unit time.", "core", "explain"],
    ["Write the equation linking force, mass and acceleration.", "Force = mass × acceleration", "core", "short"],
    ["What unit is used for mass in F = ma?", "Kilogram", "foundation", "short"],
    ["What unit is used for acceleration?", "Metres per second squared, m/s²", "core", "short"],
    ["For the same mass, what happens to acceleration when resultant force increases?", "Acceleration increases.", "core", "explain"],
    ["For the same resultant force, what happens to acceleration when mass increases?", "Acceleration decreases.", "core", "explain"],
    ["What is mass?", "The amount of matter in an object and a measure of its inertia.", "core", "explain"],
    ["What is weight?", "The gravitational force acting on an object.", "core", "explain"],
    ["Write the equation linking weight, mass and gravitational field strength.", "Weight = mass × gravitational field strength", "core", "short"],
    ["Which remains constant when travelling from Earth to the Moon: mass or weight?", "Mass", "foundation", "short"],
    ["Why is an object's weight smaller on the Moon?", "The Moon's gravitational field strength is smaller.", "core", "explain"],
    ["What is friction?", "A force that opposes relative motion between surfaces in contact.", "foundation", "explain"],
    ["Give one situation where friction is useful.", "For example: walking, braking, gripping or writing.", "foundation", "short"],
    ["Give one situation where friction is unwanted.", "For example: in moving machine parts where it causes heating and wear.", "foundation", "short"],
    ["What is drag?", "A resistive force acting on an object moving through a fluid.", "core", "explain"],
    ["How can streamlining reduce drag?", "It allows fluid to flow more smoothly around an object.", "core", "explain"],
    ["Why do forces in a free-body diagram need arrows?", "Arrow direction shows force direction and arrow length can represent magnitude.", "core", "explain"],
  ],
  "y9-pressure-fluids": [
    ["What is pressure?", "Force acting per unit area.", "foundation", "explain"],
    ["Write the symbol equation for pressure.", "p = F ÷ A", "core", "short"],
    ["What unit must force use when calculating pressure in pascals?", "Newtons", "foundation", "short"],
    ["What unit must area use when calculating pressure in pascals?", "Square metres, m²", "core", "short"],
    ["What does one pascal mean?", "One newton per square metre.", "core", "explain"],
    ["A 20 N force acts over 4 m². What pressure is produced?", "5 Pa", "core", "short"],
    ["A pressure of 10 Pa acts over 3 m². What force is produced?", "30 N", "core", "short"],
    ["How can pressure be reduced when the force stays the same?", "Increase the contact area.", "foundation", "short"],
    ["Why do snowshoes reduce pressure on snow?", "They spread weight over a larger area.", "core", "explain"],
    ["Why does a sharp knife cut more easily than a blunt one?", "The smaller contact area produces greater pressure for the same force.", "core", "explain"],
    ["Why do drawing pins have wide heads?", "The wide head reduces pressure on the finger.", "core", "explain"],
    ["Why do drawing pins have sharp points?", "The small point area creates high pressure on the surface.", "core", "explain"],
    ["Are liquids and gases both fluids?", "Yes", "foundation", "short"],
    ["Why are liquids and gases called fluids?", "Their particles can move past one another, so they can flow.", "core", "explain"],
    ["In which directions does pressure act in a fluid at rest?", "In all directions.", "core", "short"],
    ["Why does liquid pressure increase with depth?", "There is a taller column and greater weight of liquid above.", "core", "explain"],
    ["At the same depth in the same liquid, how do pressures compare?", "They are equal.", "core", "short"],
    ["How does a denser liquid affect pressure at the same depth?", "It produces greater pressure.", "stretch", "explain"],
    ["Why is the wall of a dam thicker near the bottom?", "Water pressure is greater at greater depth.", "core", "explain"],
    ["What causes atmospheric pressure?", "Air particles colliding with surfaces and the weight of air above.", "core", "explain"],
    ["What is approximate normal atmospheric pressure at sea level?", "About 100,000 Pa", "core", "short"],
    ["Why does atmospheric pressure decrease with altitude?", "There is less air above and the air is less dense.", "stretch", "explain"],
    ["Can upthrust act on an object in air?", "Yes", "foundation", "short"],
    ["What causes upthrust on a submerged object?", "Greater fluid pressure on the bottom than on the top produces a resultant upward force.", "stretch", "explain"],
    ["What happens if upthrust is greater than weight?", "The object accelerates upward.", "core", "short"],
    ["What happens if weight is greater than upthrust?", "The object accelerates downward.", "core", "short"],
    ["What happens when upthrust equals weight?", "There is no vertical acceleration; the object floats or remains at constant vertical velocity.", "core", "explain"],
    ["Does an object floating at rest have zero forces acting on it?", "No; its weight and upthrust are balanced.", "core", "explain"],
    ["Why does a floating object settle lower when extra mass is added?", "It must displace more fluid to produce a larger upthrust.", "stretch", "explain"],
    ["Why can a steel ship float even though steel is denser than water?", "Its hollow shape gives the whole ship a lower average density and lets it displace enough water.", "stretch", "explain"],
    ["What generally happens if an object's average density is greater than the fluid's density?", "It sinks, unless another force supports it.", "core", "explain"],
    ["What generally happens if an object's average density is lower than the fluid's density?", "It floats.", "foundation", "short"],
  ],
};

export const extraQuestions: Record<string, BankQuestion[]> = Object.fromEntries(
  Object.entries(rows).map(([topicId, topicRows]) => [
    topicId,
    topicRows.map(([q, a, difficulty, kind]) => ({ q, a, difficulty, kind })),
  ]),
);
