export type SeniorCourse =
  | "Biology"
  | "Chemistry"
  | "Physics"
  | "Agricultural & Horticultural Science";

type Difficulty = "foundation" | "core" | "stretch";
type QuestionKind = "short" | "explain";

export type SeniorQuestion = {
  q: string;
  a: string;
  difficulty: Difficulty;
  kind: QuestionKind;
};

export type SeniorTopic = {
  id: string;
  year: 12;
  name: string;
  course: SeniorCourse;
  standard: string;
  strand: "Biology" | "Chemistry" | "Physics" | "Agriculture";
  keywords: string[];
  questions: SeniorQuestion[];
  oneWordQuestions?: SeniorQuestion[];
};

type QuestionRow = readonly [string, string, Difficulty, QuestionKind];

function makeTopic(
  details: Omit<SeniorTopic, "year" | "questions" | "oneWordQuestions">,
  rows: QuestionRow[],
  oneWordRows: QuestionRow[] = [],
): SeniorTopic {
  return {
    ...details,
    year: 12,
    questions: rows.map(([q, a, difficulty, kind]) => ({ q, a, difficulty, kind })),
    ...(oneWordRows.length
      ? { oneWordQuestions: oneWordRows.map(([q, a, difficulty, kind]) => ({ q, a, difficulty, kind })) }
      : {}),
  };
}

export const seniorCourses: SeniorCourse[] = [
  "Biology",
  "Chemistry",
  "Physics",
  "Agricultural & Horticultural Science",
];

export const seniorTopics: SeniorTopic[] = [
  makeTopic(
    {
      id: "y12-bio-life-processes",
      name: "Life Processes at the Cellular Level",
      course: "Biology",
      standard: "AS 91156",
      strand: "Biology",
      keywords: [
        "photosynthesis", "respiration", "mitosis", "DNA replication", "enzyme", "active site",
        "diffusion", "osmosis", "active transport", "facilitated diffusion", "chloroplast", "mitochondrion",
        "ATP", "aerobic", "anaerobic", "cell cycle", "surface area", "concentration gradient",
        "light-dependent", "light-independent", "semi-conservative", "denaturation", "limiting factor", "organelle",
      ],
    },
    [
      ["What is diffusion?", "The net movement of particles from higher concentration to lower concentration down a concentration gradient.", "foundation", "explain"],
      ["What is osmosis?", "The net movement of water across a selectively permeable membrane from higher water potential to lower water potential.", "core", "explain"],
      ["What is active transport?", "The movement of substances across a membrane against a concentration gradient using energy from ATP and carrier proteins.", "core", "explain"],
      ["How does facilitated diffusion differ from active transport?", "Facilitated diffusion uses membrane proteins but moves down a concentration gradient without ATP; active transport moves against the gradient using ATP.", "stretch", "explain"],
      ["Why does a cell need a selectively permeable membrane?", "It controls which substances enter and leave, helping maintain suitable internal conditions.", "core", "explain"],
      ["How does a large surface-area-to-volume ratio help a cell?", "It provides more membrane area for exchange relative to the cell's needs, so materials move in and out more efficiently.", "core", "explain"],
      ["What happens to an animal cell placed in a strongly hypotonic solution?", "Water enters by osmosis, so the cell swells and may lyse.", "core", "explain"],
      ["Why does a plant cell become turgid rather than burst in a hypotonic solution?", "The rigid cell wall resists further expansion and pressure builds inside the cell.", "stretch", "explain"],
      ["What is an enzyme?", "A biological catalyst, usually a protein, that increases reaction rate without being used up.", "foundation", "explain"],
      ["What is the active site of an enzyme?", "The region with a specific shape where the substrate binds and the reaction is catalysed.", "foundation", "explain"],
      ["Why are enzymes described as specific?", "The active site has a shape and chemical properties complementary to particular substrate molecules.", "core", "explain"],
      ["How does increasing temperature initially affect enzyme activity?", "Particles gain kinetic energy, so successful enzyme-substrate collisions occur more frequently and the rate rises.", "core", "explain"],
      ["Why does enzyme activity fall above the optimum temperature?", "Bonds maintaining the enzyme's shape are disrupted, changing the active site so the substrate no longer binds effectively.", "stretch", "explain"],
      ["How can an extreme pH reduce enzyme activity?", "It changes charges and bonding within the enzyme, altering the active site's shape and possibly denaturing the enzyme.", "stretch", "explain"],
      ["What happens to reaction rate when substrate concentration rises but all active sites are already occupied?", "The rate levels off because enzyme concentration becomes the limiting factor.", "core", "explain"],
      ["State the overall word equation for photosynthesis.", "Carbon dioxide + water → glucose + oxygen, using light energy and chlorophyll.", "foundation", "short"],
      ["Where do the light-dependent processes of photosynthesis occur?", "On the thylakoid membranes inside chloroplasts.", "core", "short"],
      ["What happens to water during the light-dependent processes?", "It is split, releasing oxygen and providing hydrogen and electrons for later reactions.", "core", "explain"],
      ["What is the role of chlorophyll in photosynthesis?", "It absorbs light energy that drives the light-dependent reactions.", "foundation", "explain"],
      ["Where do the light-independent processes occur?", "In the stroma of the chloroplast.", "core", "short"],
      ["What is carbon dioxide used for in the light-independent processes?", "It is fixed and used with products from the light-dependent stage to build carbohydrate molecules.", "core", "explain"],
      ["Why can low light intensity limit photosynthesis?", "Less light energy is absorbed, so fewer light-dependent products are available to drive carbohydrate production.", "stretch", "explain"],
      ["Why can increasing carbon dioxide stop raising photosynthesis rate at high concentrations?", "Another factor, such as light intensity or temperature, becomes limiting.", "core", "explain"],
      ["State the overall word equation for aerobic respiration.", "Glucose + oxygen → carbon dioxide + water + a large yield of ATP.", "foundation", "short"],
      ["Where does aerobic respiration mainly occur in a eukaryotic cell?", "In the mitochondria, after an initial stage in the cytoplasm.", "core", "short"],
      ["What is the main useful product of cellular respiration?", "ATP, which transfers usable energy for cellular processes.", "foundation", "short"],
      ["Why does aerobic respiration release more usable energy than anaerobic respiration?", "Glucose is broken down more completely in the presence of oxygen, producing much more ATP.", "core", "explain"],
      ["What are the products of anaerobic respiration in animal muscle cells?", "Lactate and a small yield of ATP.", "foundation", "short"],
      ["What are the products of anaerobic respiration in yeast?", "Ethanol, carbon dioxide, and a small yield of ATP.", "foundation", "short"],
      ["Why can anaerobic respiration be useful during intense exercise?", "It supplies ATP rapidly when oxygen delivery cannot meet demand, although the ATP yield is low and lactate accumulates.", "stretch", "explain"],
      ["What is the purpose of DNA replication before mitosis?", "It produces two identical copies of each DNA molecule so each daughter cell can receive a complete genome.", "core", "explain"],
      ["What does semi-conservative DNA replication mean?", "Each new DNA molecule contains one original strand and one newly synthesised strand.", "core", "explain"],
      ["Why must the two DNA strands separate during replication?", "Each original strand acts as a template for complementary nucleotides.", "core", "explain"],
      ["How does complementary base pairing support accurate DNA replication?", "A pairs with T and C pairs with G, so the sequence of each template determines the new strand.", "stretch", "explain"],
      ["What is produced by mitosis?", "Two genetically identical daughter cells with the same chromosome number as the parent cell.", "foundation", "short"],
      ["Give one role of mitosis in a multicellular organism.", "Growth, tissue repair, cell replacement, or asexual reproduction.", "foundation", "short"],
      ["Why must chromosomes be separated accurately during mitosis?", "Each daughter cell needs one complete, identical set of genetic information.", "core", "explain"],
      ["Why do muscle cells contain many mitochondria?", "Contraction has a high ATP demand, so many mitochondria support a high rate of aerobic respiration.", "core", "explain"],
      ["Why do palisade cells contain many chloroplasts?", "Their main function is photosynthesis, so many chloroplasts maximise light absorption and carbohydrate production.", "core", "explain"],
      ["Compare how chloroplasts and mitochondria contribute to energy transformations in a plant cell.", "Chloroplasts convert light energy into chemical energy in carbohydrates; mitochondria transfer chemical energy from respiratory substrates into ATP.", "stretch", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-bio-genetic-variation",
      name: "Genetic Variation and Change",
      course: "Biology",
      standard: "AS 91157",
      strand: "Biology",
      keywords: [
        "gene pool", "allele frequency", "mutation", "meiosis", "segregation", "independent assortment",
        "crossing over", "gamete", "monohybrid", "dihybrid", "complete dominance", "co-dominance",
        "incomplete dominance", "multiple alleles", "lethal allele", "linked genes", "sex linkage", "recombination",
        "natural selection", "migration", "gene flow", "genetic drift", "founder effect", "bottleneck",
      ],
    },
    [
      ["What is a gene pool?", "All the alleles of all genes present in a population at a particular time.", "foundation", "explain"],
      ["What is allele frequency?", "The proportion of a particular allele among all copies of that gene in a population.", "foundation", "explain"],
      ["What is a mutation?", "A permanent change in the DNA base sequence that can create a new allele.", "foundation", "explain"],
      ["Why are mutations important for evolution?", "They introduce new alleles, providing the original source of heritable genetic variation on which selection can act.", "core", "explain"],
      ["How does a gametic mutation differ from a somatic mutation?", "A gametic mutation occurs in a cell that forms gametes and can be inherited; a somatic mutation occurs in body cells and is not normally passed to offspring.", "core", "explain"],
      ["What is segregation during meiosis?", "The separation of homologous chromosome pairs, and therefore allele pairs, into different gametes.", "core", "explain"],
      ["How does independent assortment create variation?", "Each homologous chromosome pair aligns independently, producing many possible combinations of maternal and paternal chromosomes in gametes.", "core", "explain"],
      ["What is crossing over?", "The exchange of corresponding DNA sections between non-sister chromatids of homologous chromosomes during meiosis.", "core", "explain"],
      ["How does crossing over increase genetic variation?", "It creates recombinant chromosomes with new combinations of alleles.", "core", "explain"],
      ["Why are gametes produced by one individual usually genetically different?", "Segregation, independent assortment, and crossing over produce different allele combinations in each gamete.", "stretch", "explain"],
      ["What does complete dominance mean?", "The heterozygote has the same phenotype as the homozygous dominant genotype.", "foundation", "explain"],
      ["What does incomplete dominance mean?", "The heterozygote has an intermediate phenotype between the two homozygous phenotypes.", "core", "explain"],
      ["What does co-dominance mean?", "Both alleles are fully and separately expressed in the heterozygous phenotype.", "core", "explain"],
      ["What are multiple alleles?", "More than two alternative alleles of one gene exist in the population, although each individual carries only two.", "core", "explain"],
      ["What is a lethal allele?", "An allele that causes death in a particular genotype, often altering expected offspring ratios.", "core", "explain"],
      ["In a complete-dominance cross Aa × Aa, what genotype ratio is expected?", "1 AA : 2 Aa : 1 aa.", "foundation", "short"],
      ["In a complete-dominance cross Aa × Aa, what phenotype ratio is expected?", "3 dominant phenotype : 1 recessive phenotype.", "foundation", "short"],
      ["In an incomplete-dominance cross of two heterozygotes, what phenotype ratio is expected?", "1 : 2 : 1 because each genotype has a distinguishable phenotype.", "core", "short"],
      ["What is a test cross used for?", "To infer the genotype of an individual with a dominant phenotype by crossing it with a homozygous recessive individual.", "core", "explain"],
      ["What does a dihybrid cross follow?", "The inheritance of alleles at two different gene loci.", "foundation", "explain"],
      ["For unlinked genes with complete dominance, what phenotype ratio is expected from AaBb × AaBb?", "9 : 3 : 3 : 1.", "core", "short"],
      ["What are linked genes?", "Genes located on the same chromosome, especially close together, that tend to be inherited together.", "core", "explain"],
      ["Why do linked genes not usually produce a 9:3:3:1 dihybrid ratio?", "Their alleles do not assort independently, so parental allele combinations occur more often than recombinant combinations.", "stretch", "explain"],
      ["How does distance between linked genes affect recombination frequency?", "Genes farther apart are more likely to have crossing over occur between them, so recombination frequency is higher.", "stretch", "explain"],
      ["What is sex linkage?", "Inheritance of a gene located on a sex chromosome, commonly the X chromosome.", "core", "explain"],
      ["Why are X-linked recessive conditions more common in XY individuals?", "They have only one X chromosome, so one recessive allele on it is expressed without a second allele masking it.", "stretch", "explain"],
      ["What is natural selection?", "Differential survival and reproduction caused by heritable variation, leading advantageous alleles to become more frequent over generations.", "foundation", "explain"],
      ["What is a selection pressure?", "An environmental factor that affects survival or reproductive success of different phenotypes.", "foundation", "explain"],
      ["How does natural selection change allele frequencies?", "Individuals with advantageous heritable phenotypes leave more offspring, so the associated alleles increase in the gene pool.", "core", "explain"],
      ["Why does natural selection act on phenotypes rather than directly on genotypes?", "The environment interacts with expressed characteristics, while the underlying alleles are inherited.", "stretch", "explain"],
      ["What is migration in population genetics?", "Movement of individuals and their alleles into or out of a population.", "foundation", "explain"],
      ["How can immigration change a gene pool?", "It can add alleles or increase the frequencies of alleles carried by immigrants.", "core", "explain"],
      ["What is genetic drift?", "Random change in allele frequencies, with the strongest effects in small populations.", "core", "explain"],
      ["Why is genetic drift stronger in small populations?", "Chance survival and reproduction of a few individuals represent a large proportion of the gene pool.", "stretch", "explain"],
      ["What is the founder effect?", "Genetic drift when a new population is established by a small, unrepresentative group from a larger population.", "core", "explain"],
      ["What is a population bottleneck?", "A sharp reduction in population size that leaves a chance sample of the original alleles.", "core", "explain"],
      ["How can a bottleneck reduce future adaptability?", "It can remove alleles and lower genetic diversity, leaving fewer variants available when conditions change.", "stretch", "explain"],
      ["Compare natural selection with genetic drift.", "Selection changes allele frequencies non-randomly through fitness differences; drift changes them randomly, especially in small populations.", "stretch", "explain"],
      ["Why can migration oppose local natural selection?", "Gene flow can repeatedly introduce alleles that are less advantageous in the local environment.", "stretch", "explain"],
      ["Explain how mutation and natural selection work together in evolutionary change.", "Mutation creates new alleles randomly; selection then changes their frequencies according to their effects on survival and reproduction in that environment.", "stretch", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-bio-gene-expression",
      name: "Gene Expression",
      course: "Biology",
      standard: "AS 91159",
      strand: "Biology",
      keywords: [
        "DNA", "RNA", "nucleotide", "deoxyribose", "ribose", "phosphate", "base pairing", "template strand",
        "coding strand", "triplet", "codon", "anticodon", "degenerate code", "transcription", "translation",
        "mRNA", "tRNA", "ribosome", "amino acid", "polypeptide", "protein", "enzyme", "metabolic pathway",
        "mutation", "mutagen", "phenotype", "environment", "gene expression",
      ],
    },
    [
      ["What three components make up a nucleotide?", "A phosphate group, a pentose sugar, and a nitrogenous base.", "foundation", "short"],
      ["Which sugar is present in DNA?", "Deoxyribose.", "foundation", "short"],
      ["Which sugar is present in RNA?", "Ribose.", "foundation", "short"],
      ["State the complementary base pairs in DNA.", "Adenine pairs with thymine, and cytosine pairs with guanine.", "foundation", "short"],
      ["Which base in RNA replaces thymine?", "Uracil.", "foundation", "short"],
      ["What forms the backbone of a DNA strand?", "Alternating deoxyribose sugars and phosphate groups.", "core", "short"],
      ["Why are the two DNA strands described as complementary?", "The base sequence of one strand determines the other through A-T and C-G pairing.", "core", "explain"],
      ["What is the template strand of a gene?", "The DNA strand read during transcription to produce a complementary mRNA molecule.", "core", "explain"],
      ["How does the mRNA sequence compare with the DNA coding strand?", "It has the same base sequence except uracil replaces thymine.", "core", "explain"],
      ["What is a DNA triplet?", "A sequence of three DNA bases that corresponds to an mRNA codon.", "foundation", "explain"],
      ["What is a codon?", "A sequence of three bases on mRNA that specifies an amino acid or a start or stop signal.", "foundation", "explain"],
      ["What is an anticodon?", "A three-base sequence on tRNA complementary to an mRNA codon.", "foundation", "explain"],
      ["Explain what is meant by saying that the genetic code is degenerate.", "More than one codon can code for the same amino acid.", "core", "explain"],
      ["How can degeneracy reduce the effect of a substitution mutation?", "A changed codon may still specify the same amino acid, producing a silent mutation.", "stretch", "explain"],
      ["What is transcription?", "The production of a complementary mRNA copy of a gene from a DNA template.", "foundation", "explain"],
      ["Where does transcription occur in a eukaryotic cell?", "In the nucleus.", "foundation", "short"],
      ["Why is mRNA needed between DNA and a ribosome?", "DNA remains protected in the nucleus, while mRNA can carry a copy of the code to a ribosome in the cytoplasm.", "core", "explain"],
      ["What is translation?", "The process at a ribosome in which the mRNA codon sequence is used to assemble a polypeptide.", "foundation", "explain"],
      ["What is the role of tRNA in translation?", "Each tRNA carries a specific amino acid and pairs its anticodon with a complementary mRNA codon.", "core", "explain"],
      ["What is the role of a ribosome in translation?", "It holds mRNA and tRNAs in position and joins amino acids into a polypeptide.", "core", "explain"],
      ["How does a gene's base sequence determine a protein's primary structure?", "The base sequence determines the order of mRNA codons, which determines the amino acid sequence.", "core", "explain"],
      ["Why can changing an amino acid alter protein function?", "It may change bonding and folding, altering the protein's three-dimensional shape and active or binding sites.", "stretch", "explain"],
      ["What does the one gene-one polypeptide idea state?", "The base sequence of one gene determines the amino acid sequence of one polypeptide.", "core", "explain"],
      ["Give one structural role of proteins in living things.", "For example: collagen provides tensile strength, or keratin forms protective structures.", "foundation", "short"],
      ["Give one catalytic role of proteins in living things.", "Enzymes catalyse specific biochemical reactions.", "foundation", "short"],
      ["What is a metabolic pathway?", "A linked series of enzyme-catalysed reactions in which the product of one step becomes the substrate for the next.", "core", "explain"],
      ["How can one faulty gene block a metabolic pathway?", "The gene may produce a non-functional enzyme, so its substrate is not converted and later products are reduced or absent.", "stretch", "explain"],
      ["How can a blocked metabolic pathway change phenotype?", "An intermediate may accumulate or a final product may be missing, changing an observable characteristic.", "stretch", "explain"],
      ["What is a gene mutation?", "A change in the DNA base sequence of a gene.", "foundation", "explain"],
      ["What is a substitution mutation?", "One DNA base is replaced by another.", "foundation", "explain"],
      ["What is a silent mutation?", "A base change that does not alter the amino acid sequence because of code degeneracy.", "core", "explain"],
      ["What is a missense mutation?", "A base change that creates a codon for a different amino acid.", "core", "explain"],
      ["What is a nonsense mutation?", "A base change that creates a stop codon, producing a shortened polypeptide.", "core", "explain"],
      ["Why can an insertion or deletion cause a frameshift?", "It changes how bases are grouped into codons from the mutation onward, often altering many amino acids.", "stretch", "explain"],
      ["What is a mutagen?", "An environmental agent that increases the rate of DNA mutation.", "foundation", "explain"],
      ["Give one example of a mutagen.", "For example: ultraviolet radiation, ionising radiation, or a mutagenic chemical.", "foundation", "short"],
      ["How can the environment alter phenotype without changing genotype?", "Environmental conditions can change gene activity, enzyme action, or resource availability, altering the expressed characteristic.", "core", "explain"],
      ["Why can genetically identical organisms have different phenotypes?", "They may experience different environments that affect gene expression and metabolic pathways.", "core", "explain"],
      ["Explain the relationship DNA → mRNA → polypeptide → phenotype.", "A gene is transcribed into mRNA and translated into a polypeptide; the protein's structural or catalytic function contributes to phenotype.", "stretch", "explain"],
      ["Explain how a mutation can change phenotype through an enzyme-controlled pathway.", "The mutation can alter an enzyme's amino acid sequence and shape, changing pathway activity and therefore the amount or presence of a product that contributes to phenotype.", "stretch", "explain"],
    ],
  ),

  // Level 2 Chemistry banks audited against the NZQA Version 2 standards,
  // the 2026 assessment specification, and the 2024–2025 papers and schedules.
  makeTopic(
    {
      id: "y12-chem-bonding-energy",
      name: "Bonding, Structure, Properties and Energy Changes",
      course: "Chemistry",
      standard: "AS 91164",
      strand: "Chemistry",
      keywords: [
        "ionic", "covalent", "metallic", "Lewis structure", "electron pair", "molecular shape", "polarity",
        "intermolecular force", "lattice", "covalent network", "malleability", "ductility", "conductivity",
        "solubility", "enthalpy", "exothermic", "endothermic", "bond enthalpy", "stoichiometry", "mole",
        "melting point", "boiling point", "delocalised electron", "electronegativity", "energy profile",
      ],
    },
    [
      ["What is an ionic bond?", "The electrostatic attraction between oppositely charged ions.", "foundation", "explain"],
      ["What is a covalent bond?", "The electrostatic attraction between a shared pair of electrons and the nuclei of the bonded atoms.", "foundation", "explain"],
      ["What is metallic bonding?", "The electrostatic attraction between positive metal ions and delocalised electrons in a lattice.", "foundation", "explain"],
      ["Name the particles and attractions in an ionic solid.", "Positive and negative ions held in a three-dimensional lattice by strong ionic attractions.", "core", "short"],
      ["Name the particles and attractions in a molecular solid.", "Molecules held together by intermolecular attractions.", "core", "short"],
      ["Describe the structure of a covalent network solid.", "Atoms joined by strong covalent bonds in a continuous network.", "core", "explain"],
      ["Why do ionic solids usually have high melting points?", "Strong electrostatic attractions act throughout the ionic lattice and require a large energy input to overcome.", "core", "explain"],
      ["Why do molecular substances usually have low melting and boiling points?", "Only the intermolecular attractions between molecules are overcome, and these attractions are relatively weak.", "core", "explain"],
      ["Why do covalent network solids usually have high melting points?", "Many strong covalent bonds must be overcome, which requires a large amount of energy.", "core", "explain"],
      ["Why does solid sodium chloride not conduct electricity?", "Its ions are fixed in the lattice and cannot move to carry charge.", "core", "explain"],
      ["Why does molten sodium chloride conduct electricity?", "The ions are free to move through the liquid and carry charge.", "core", "explain"],
      ["Why is melting an endothermic change?", "Energy is absorbed to overcome attractions between particles so they can move past one another.", "core", "explain"],
      ["Why are metals malleable and ductile?", "Layers of metal ions can slide while attraction to delocalised electrons continues to hold the structure together.", "core", "explain"],
      ["Why do metals conduct electricity?", "Their delocalised electrons are free to move and carry charge through the structure.", "core", "explain"],
      ["Why can graphite conduct electricity?", "Each carbon contributes a delocalised electron that can move along the layers.", "stretch", "explain"],
      ["Why is diamond very hard?", "Each carbon is covalently bonded in a rigid three-dimensional network with no easy planes of weakness.", "core", "explain"],
      ["What information does a Lewis structure show?", "Valence electrons arranged as bonding pairs and non-bonding pairs around atoms.", "foundation", "explain"],
      ["Why do electron regions spread out around a central atom?", "They repel one another and arrange themselves as far apart as possible.", "core", "explain"],
      ["State the shape and bond angle for two electron regions around a central atom.", "Linear, 180°.", "foundation", "short"],
      ["State the arrangement and bond angle for three electron regions around a central atom.", "Trigonal planar, 120°.", "foundation", "short"],
      ["State the arrangement and bond angle for four electron regions around a central atom.", "Tetrahedral, 109.5°.", "foundation", "short"],
      ["Explain why water has a bent molecular shape.", "Oxygen has four electron regions, but two are lone pairs, so only the two bonded regions determine the bent shape.", "core", "explain"],
      ["What is electronegativity?", "The ability of an atom in a covalent bond to attract the shared electrons.", "foundation", "explain"],
      ["What makes a covalent bond polar?", "The bonded atoms have different electronegativities, so the bonding electrons are shared unequally.", "foundation", "explain"],
      ["How are molecular shape and bond dipoles used to decide whether a molecule is polar?", "Check whether the bond dipoles cancel. If they do not cancel, the molecule is polar.", "core", "explain"],
      ["Why is carbon dioxide non-polar overall?", "Its two polar C=O bonds are equal and opposite in a linear molecule, so their dipoles cancel.", "core", "explain"],
      ["Why is water polar?", "Its O-H bonds are polar and its bent shape means the bond dipoles do not cancel.", "core", "explain"],
      ["State the usual solubility rule for polar and non-polar substances.", "Polar solutes tend to dissolve in polar solvents, while non-polar solutes tend to dissolve in non-polar solvents.", "foundation", "short"],
      ["Explain why sodium chloride dissolves in water.", "The attractions between water molecules and the ions are strong enough to overcome attractions in the ionic lattice and between water molecules.", "stretch", "explain"],
      ["What does exothermic mean?", "The system releases energy to the surroundings, so ΔH is negative.", "foundation", "explain"],
      ["What does endothermic mean?", "The system absorbs energy from the surroundings, so ΔH is positive.", "foundation", "explain"],
      ["In an exothermic energy profile, how do product and reactant enthalpies compare?", "Products have lower enthalpy than reactants.", "core", "short"],
      ["In an endothermic energy profile, how do product and reactant enthalpies compare?", "Products have higher enthalpy than reactants.", "core", "short"],
      ["Why is bond breaking endothermic?", "Energy must be supplied to overcome the attraction holding bonded atoms together.", "core", "explain"],
      ["Why is bond making exothermic?", "Energy is released when atoms form a more stable bonded arrangement.", "core", "explain"],
      ["State the equation used to calculate ΔrH from bond enthalpies.", "ΔrH = Σ(bond enthalpies of bonds broken) − Σ(bond enthalpies of bonds formed).", "core", "short"],
      ["Bonds broken require 500 kJ mol⁻¹ and bonds formed release 650 kJ mol⁻¹. Calculate ΔrH.", "ΔrH = 500 − 650 = −150 kJ mol⁻¹.", "core", "short"],
      ["A reaction has ΔrH = +45 kJ mol⁻¹. Calculate the energy change for 0.50 mol.", "+22.5 kJ, so energy is absorbed.", "core", "short"],
      ["A reaction releases 120 kJ when 2.0 mol reacts. Calculate ΔrH per mole.", "ΔrH = −120 ÷ 2.0 = −60 kJ mol⁻¹.", "core", "short"],
      ["Why is condensation an exothermic change?", "Energy is released as attractions form between particles when a gas becomes a liquid.", "core", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-chem-organic",
      name: "Properties of Selected Organic Compounds",
      course: "Chemistry",
      standard: "AS 91165",
      strand: "Chemistry",
      keywords: [
        "alkane", "alkene", "alkyne", "haloalkane", "amine", "alcohol", "carboxylic acid", "functional group",
        "constitutional isomer", "geometric isomer", "primary alcohol", "secondary alcohol", "tertiary alcohol",
        "primary haloalkane", "secondary haloalkane", "tertiary haloalkane",
        "addition reaction", "substitution reaction", "oxidation reaction", "elimination reaction", "polymerisation", "major product", "solubility",
        "boiling point", "structural formula", "IUPAC", "reagent", "conditions", "observation",
      ],
    },
    [
      ["How can you identify an alkane from its carbon-carbon bonds?", "It contains only carbon-carbon single bonds.", "foundation", "short"],
      ["What functional group identifies an alkene?", "A carbon-carbon double bond, C=C.", "foundation", "short"],
      ["What functional group identifies an alkyne?", "A carbon-carbon triple bond, C≡C.", "foundation", "short"],
      ["What functional group identifies an alcohol?", "A hydroxyl group, -OH, bonded to carbon.", "foundation", "short"],
      ["What functional group identifies a carboxylic acid?", "A carboxyl group, -COOH.", "foundation", "short"],
      ["What functional group identifies a primary amine?", "An amino group, -NH₂, bonded to a carbon chain.", "foundation", "short"],
      ["Give the IUPAC name for CH₃CH₂CH₂Cl.", "1-chloropropane, which is a haloalkane.", "foundation", "short"],
      ["What are constitutional isomers?", "Compounds with the same molecular formula but different connections between atoms.", "core", "explain"],
      ["State the two structural requirements for geometric isomerism.", "There must be a C=C bond, and each carbon in the double bond must have two different groups attached.", "core", "short"],
      ["Describe how cis and trans isomers are different.", "In a cis isomer, matching groups are on the same side of C=C; in a trans isomer, they are on opposite sides.", "foundation", "explain"],
      ["How do you classify an alcohol as primary, secondary or tertiary?", "Count how many carbon atoms are bonded to the carbon carrying the -OH group: one, two or three.", "core", "explain"],
      ["How do you classify a haloalkane as primary, secondary or tertiary?", "Count how many carbon atoms are bonded to the carbon carrying the halogen: one, two or three.", "core", "explain"],
      ["State the usual boiling-point trend as a carbon chain becomes longer.", "Boiling point increases.", "foundation", "short"],
      ["State the usual water-solubility trend as the carbon chain in an alcohol becomes longer.", "Water solubility decreases.", "foundation", "short"],
      ["Describe what happens in an addition reaction of an alkene.", "The C=C double bond opens and atoms are added to the two carbon atoms.", "foundation", "explain"],
      ["Name the product when ethene reacts with H₂ using a platinum catalyst.", "Ethane.", "foundation", "short"],
      ["State the colour change when an alkene reacts with bromine water without UV light.", "Orange-brown bromine water becomes colourless.", "foundation", "short"],
      ["Name the product type when an alkene reacts with H₂O/H⁺.", "An alcohol.", "foundation", "short"],
      ["How do you identify the major product when HX adds to an asymmetric alkene?", "Hydrogen adds to the double-bond carbon that already has more hydrogen atoms.", "stretch", "explain"],
      ["Describe what happens during addition polymerisation.", "Many alkene molecules open their C=C bonds and join to form a long-chain polymer.", "core", "explain"],
      ["How does the bonding in an alkene monomer change when it forms an addition polymer?", "The C=C double bond becomes C-C single bonds that link the repeating units.", "core", "explain"],
      ["State the reaction type and condition when an alkane reacts with a halogen.", "Substitution using UV light; one hydrogen atom is replaced by a halogen atom.", "core", "short"],
      ["Name the organic product when an alcohol reacts with a hydrogen halide.", "A haloalkane.", "foundation", "short"],
      ["Name three reagents that can convert an alcohol into a chloroalkane.", "PCl₃, PCl₅ or SOCl₂.", "core", "short"],
      ["Name the organic product when a haloalkane reacts with aqueous KOH and heat.", "An alcohol, formed by substitution.", "foundation", "short"],
      ["Name the organic product when a haloalkane reacts with excess alcoholic ammonia and heat.", "A primary amine, formed by substitution.", "foundation", "short"],
      ["State the reagents and product for the oxidation of a primary alcohol.", "Heat with acidified MnO₄⁻ or Cr₂O₇²⁻ to form a carboxylic acid.", "core", "short"],
      ["State the colour change when acidified dichromate oxidises a primary alcohol.", "Orange to green.", "foundation", "short"],
      ["State the colour change when acidified permanganate oxidises a primary alcohol.", "Purple to colourless.", "foundation", "short"],
      ["What product forms when MnO₄⁻ oxidises an alkene?", "A diol, with an -OH group added to each carbon from the C=C bond.", "core", "explain"],
      ["State the reagent and conditions used to eliminate water from an alcohol.", "Concentrated H₂SO₄ and heat.", "core", "short"],
      ["Name the organic product when water is eliminated from an alcohol.", "An alkene.", "foundation", "short"],
      ["State the reagent and conditions used to eliminate a hydrogen halide from a haloalkane.", "Alcoholic KOH and heat.", "core", "short"],
      ["Explain why an asymmetric elimination reaction can form two different alkenes.", "A hydrogen can be removed from either adjacent carbon, placing the C=C bond in different positions.", "stretch", "explain"],
      ["How do you identify the major product in an elimination reaction?", "The major alkene forms by removing hydrogen from the adjacent carbon with fewer hydrogen atoms.", "stretch", "explain"],
      ["How does a carboxylic acid act in an acid-base reaction?", "It donates a proton and forms a carboxylate ion or salt.", "core", "explain"],
      ["State the observation when a carboxylic acid reacts with a carbonate.", "Fizzing occurs because carbon dioxide gas is produced.", "foundation", "short"],
      ["How does a primary amine act in an acid-base reaction?", "It accepts a proton and forms an alkylammonium ion or salt.", "core", "explain"],
      ["State the litmus-paper results for a carboxylic acid and a primary amine.", "A carboxylic acid turns blue litmus red; a primary amine turns red litmus blue.", "foundation", "short"],
      ["How can bromine water distinguish an alkene from an alkane without UV light?", "The alkene rapidly decolourises bromine water; the alkane shows no rapid colour change.", "core", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-chem-reactivity",
      name: "Chemical Reactivity",
      course: "Chemistry",
      standard: "AS 91166",
      strand: "Chemistry",
      keywords: [
        "reaction rate", "collision theory", "activation energy", "concentration", "temperature", "surface area",
        "catalyst", "equilibrium", "dynamic", "Le Chatelier", "pressure", "equilibrium constant", "Kc",
        "homogeneous", "acid", "base", "proton transfer", "strong", "weak", "dissociation", "conductivity",
        "pH", "Kw", "hydronium", "hydroxide", "conjugate acid-base pair",
      ],
    },
    [
      ["What is reaction rate?", "The change in amount or concentration of a reactant or product per unit time.", "foundation", "explain"],
      ["State the two conditions needed for a successful collision.", "Particles must collide with enough energy to overcome the activation energy and with a suitable orientation.", "core", "short"],
      ["What is activation energy?", "The minimum collision energy required for a reaction to occur.", "foundation", "explain"],
      ["Why does increasing concentration usually increase reaction rate?", "More reactant particles occupy the same volume, so collision frequency and the number of successful collisions per second increase.", "core", "explain"],
      ["Why does increasing surface area of a solid increase reaction rate?", "More reactant particles are exposed for collisions, increasing successful collisions per second.", "core", "explain"],
      ["Explain how increasing temperature changes the collision frequency.", "Particles move faster, so they collide more often each second.", "core", "explain"],
      ["Explain how increasing temperature changes the number of successful collisions.", "A larger proportion of particles have enough energy to overcome the activation energy.", "core", "explain"],
      ["How does a catalyst increase reaction rate?", "It provides an alternative pathway with lower activation energy and is not used up overall.", "core", "explain"],
      ["What is dynamic equilibrium?", "In a closed system, forward and reverse reactions continue at equal rates, so macroscopic concentrations remain constant.", "core", "explain"],
      ["Why is a closed system needed for dynamic equilibrium?", "Reactants and products cannot enter or leave, so both reactions can continue and concentrations can become constant.", "core", "explain"],
      ["At equilibrium, how do the forward and reverse reaction rates compare?", "They are equal.", "foundation", "short"],
      ["At equilibrium, how do reactant and product concentrations change with time?", "They remain constant but are not necessarily equal.", "foundation", "explain"],
      ["Predict what happens when more reactant is added to an equilibrium mixture.", "The equilibrium shifts in the direction that uses up some of the added reactant.", "core", "explain"],
      ["Predict what happens when a product is removed from an equilibrium mixture.", "The equilibrium shifts toward the products to replace some of the removed substance.", "core", "explain"],
      ["Predict the effect of increasing pressure when the product side has fewer moles of gas.", "The equilibrium shifts toward the products, the side with fewer moles of gas.", "core", "explain"],
      ["State when a pressure change has no effect on a gaseous equilibrium.", "When both sides have the same total number of moles of gas.", "core", "short"],
      ["Predict the effect of increasing temperature on an exothermic forward reaction.", "The equilibrium shifts in the endothermic reverse direction, so more reactants form.", "core", "explain"],
      ["Predict the effect of increasing temperature on an endothermic forward reaction.", "The equilibrium shifts in the endothermic forward direction, so more products form.", "core", "explain"],
      ["Which change can alter the value of Kc for a reaction?", "A change in temperature.", "foundation", "short"],
      ["Explain the effect of a catalyst on equilibrium position and Kc.", "It changes neither. It speeds up both reactions, so equilibrium is reached sooner.", "core", "explain"],
      ["Explain what very large and very small Kc values indicate.", "A very large Kc means products are favoured; a very small Kc means reactants are favoured.", "foundation", "explain"],
      ["Write the Kc expression for A(aq) + B(aq) ⇌ 2C(aq).", "Kc = [C]² ÷ ([A][B]).", "core", "short"],
      ["For A(aq) ⇌ 2B(aq), [A] = 0.50 mol L⁻¹ and [B] = 0.20 mol L⁻¹. Calculate Kc.", "Kc = [B]²/[A] = 0.20²/0.50 = 0.080.", "core", "short"],
      ["What is a Brønsted-Lowry acid?", "A proton donor.", "foundation", "short"],
      ["What is a Brønsted-Lowry base?", "A proton acceptor.", "foundation", "short"],
      ["Explain why magnesium reacts faster with a strong acid than with a weak acid of the same concentration.", "The strong acid has more H₃O⁺ ions, so successful collisions with magnesium occur more often.", "stretch", "explain"],
      ["How does a strong acid behave in water?", "It reacts essentially completely with water to form hydronium ions and its conjugate base.", "core", "explain"],
      ["How does a weak acid behave in water?", "It only partially reacts, establishing an equilibrium containing acid molecules and ions.", "core", "explain"],
      ["How does a strong base behave in water?", "It completely dissociates or reacts to produce hydroxide ions.", "core", "explain"],
      ["How does a weak base behave in water?", "It only partially reacts with water, so relatively few hydroxide ions are produced.", "core", "explain"],
      ["Explain why equal-concentration strong and weak acids have different pH values.", "The strong acid produces more H₃O⁺ ions, so it has a lower pH.", "core", "explain"],
      ["Explain why a strong acid conducts better than an equal-concentration weak acid.", "The strong acid forms more mobile ions in solution, so it carries more electric current.", "core", "explain"],
      ["State the equation that links pH and hydronium-ion concentration.", "pH = −log₁₀[H₃O⁺].", "foundation", "short"],
      ["Calculate the pH of 1.0 × 10⁻³ mol L⁻¹ HCl.", "pH = 3.00.", "core", "short"],
      ["Calculate [H₃O⁺] for a solution with pH 2.00.", "[H₃O⁺] = 10⁻²·⁰⁰ = 1.0 × 10⁻² mol L⁻¹.", "core", "short"],
      ["State the Kw expression and its value at 25 °C.", "Kw = [H₃O⁺][OH⁻] = 1.0 × 10⁻¹⁴.", "core", "short"],
      ["Calculate [OH⁻] when [H₃O⁺] = 1.0 × 10⁻⁵ mol L⁻¹ at 25 °C.", "[OH⁻] = Kw/[H₃O⁺] = 1.0 × 10⁻⁹ mol L⁻¹.", "core", "short"],
      ["Calculate the pH of 1.0 × 10⁻² mol L⁻¹ NaOH at 25 °C.", "[OH⁻] = 1.0 × 10⁻², so [H₃O⁺] = 1.0 × 10⁻¹² mol L⁻¹ and pH = 12.0.", "stretch", "short"],
      ["Write the equation for HCl reacting with water.", "HCl + H₂O → Cl⁻ + H₃O⁺.", "core", "short"],
      ["Write the equation for ethanoate ions acting as a base in water.", "CH₃COO⁻ + H₂O ⇌ CH₃COOH + OH⁻.", "stretch", "short"],
    ],
  ),

  makeTopic(
    {
      id: "y12-physics-mechanics",
      name: "Mechanics",
      course: "Physics",
      standard: "AS 91171",
      strand: "Physics",
      keywords: [
        "displacement", "velocity", "acceleration", "projectile motion", "free fall", "circular motion", "resultant force",
        "vector component", "force equilibrium", "torque", "centripetal force", "spring", "Hooke's law", "momentum",
        "impulse", "conservation law", "work", "power", "kinetic energy", "gravitational potential energy", "elastic potential energy",
        "vector quantity", "force", "energy",
      ],
    },
    [
      ["What is displacement?", "The straight-line change in position from start to finish, including direction.", "foundation", "explain"],
      ["What is velocity?", "The rate of change of displacement, including direction.", "foundation", "explain"],
      ["What is acceleration?", "The rate of change of velocity.", "foundation", "explain"],
      ["A car changes velocity from 4.0 m s⁻¹ to 16 m s⁻¹ in 3.0 s. Calculate its acceleration.", "a = Δv/Δt = 12/3.0 = 4.0 m s⁻².", "core", "short"],
      ["Write the constant-acceleration equation linking final velocity, initial velocity, acceleration, and time.", "v_f = v_i + at.", "foundation", "short"],
      ["An object starts from rest and accelerates at 2.0 m s⁻² for 5.0 s. Calculate its displacement.", "d = v_i t + ½at² = 0 + 0.5 × 2.0 × 25 = 25 m.", "core", "short"],
      ["What acceleration is used for free fall near Earth's surface in NCEA Level 2 Physics?", "9.8 m s⁻² downward.", "foundation", "short"],
      ["Why is horizontal velocity constant in ideal projectile motion?", "Air resistance is neglected, so no resultant horizontal force acts.", "core", "explain"],
      ["Why does the vertical velocity of a projectile change?", "Gravity provides a constant downward acceleration.", "core", "explain"],
      ["At the highest point of projectile motion, what are the vertical velocity and acceleration?", "Vertical velocity is zero momentarily; acceleration remains 9.8 m s⁻² downward.", "core", "short"],
      ["What is centripetal acceleration?", "Acceleration directed toward the centre of a circular path, changing the direction of velocity.", "core", "explain"],
      ["Write the equation for centripetal acceleration.", "a_c = v²/r.", "foundation", "short"],
      ["A 2.0 kg object moves at 6.0 m s⁻¹ in a circle of radius 3.0 m. Calculate centripetal force.", "F_c = mv²/r = 2.0 × 36/3.0 = 24 N toward the centre.", "core", "short"],
      ["Why is centripetal force not an extra type of force?", "It is the name for the resultant inward force supplied by real forces such as tension, friction, gravity, or normal force.", "stretch", "explain"],
      ["What does resolving a force mean?", "Splitting a force vector into perpendicular components with the same combined effect.", "foundation", "explain"],
      ["A 10 N force acts at 30° above horizontal. Calculate its horizontal component.", "F_x = 10 cos 30° = 8.66 N.", "core", "short"],
      ["What condition is required for translational equilibrium?", "The vector sum of all forces is zero.", "foundation", "short"],
      ["What condition is required for rotational equilibrium?", "The sum of clockwise torques equals the sum of anticlockwise torques about any point.", "core", "explain"],
      ["Define torque and write its equation for a force acting perpendicular to the lever arm.", "The turning effect of a force: τ = Fd, where d is the perpendicular distance from the pivot to the force's line of action.", "foundation", "explain"],
      ["A 15 N force acts perpendicularly 0.40 m from a pivot. Calculate the torque.", "τ = Fd = 15 × 0.40 = 6.0 N m.", "core", "short"],
      ["Why does pushing farther from a door hinge produce a larger turning effect?", "The perpendicular distance from the pivot is larger, so τ = Fd is larger for the same force.", "core", "explain"],
      ["Write Newton's second-law relationship.", "F_net = ma.", "foundation", "short"],
      ["A 1200 kg car has a resultant force of 3600 N forward. Calculate its acceleration.", "a = F/m = 3600/1200 = 3.0 m s⁻² forward.", "core", "short"],
      ["What does Hooke's law state for a spring?", "Within its proportional limit, extension is proportional to applied force: F = kx in magnitude.", "core", "explain"],
      ["A spring with k = 200 N m⁻¹ extends 0.050 m. Calculate the spring force magnitude.", "F = kx = 200 × 0.050 = 10 N.", "core", "short"],
      ["Write the equation for elastic potential energy in a spring.", "E_p = ½kx².", "foundation", "short"],
      ["Calculate the elastic energy stored when k = 100 N m⁻¹ and x = 0.20 m.", "E_p = 0.5 × 100 × 0.20² = 2.0 J.", "core", "short"],
      ["Define momentum and write its equation.", "A vector quantity equal to mass times velocity: p = mv.", "foundation", "explain"],
      ["Calculate the momentum of a 0.50 kg ball moving east at 8.0 m s⁻¹.", "p = mv = 0.50 × 8.0 = 4.0 kg m s⁻¹ east.", "core", "short"],
      ["Define impulse and write two equivalent relationships for it.", "Change in momentum; for a constant force, impulse = FΔt.", "foundation", "explain"],
      ["How does an airbag reduce the average force on a passenger?", "It increases the stopping time for the same change in momentum, so F = Δp/Δt is smaller.", "core", "explain"],
      ["State the principle of conservation of momentum.", "Total momentum of an isolated system remains constant.", "foundation", "explain"],
      ["A 2.0 kg trolley at 3.0 m s⁻¹ sticks to a stationary 1.0 kg trolley. Calculate their shared velocity.", "v = total momentum/total mass = 6.0/3.0 = 2.0 m s⁻¹ in the original direction.", "stretch", "short"],
      ["Define work done and write its equation for a constant force parallel to the displacement.", "Energy transferred by the force: W = Fd.", "foundation", "explain"],
      ["A 50 N force moves an object 4.0 m in its direction. Calculate the work done.", "W = Fd = 50 × 4.0 = 200 J.", "core", "short"],
      ["Define power and write its equation in terms of work done and time.", "The rate of energy transfer or work done: P = W/Δt.", "foundation", "explain"],
      ["A machine transfers 1200 J in 6.0 s. Calculate its power.", "P = 1200/6.0 = 200 W.", "core", "short"],
      ["Write the equation for kinetic energy.", "E_k = ½mv².", "foundation", "short"],
      ["Write the equation for change in gravitational potential energy near Earth's surface.", "ΔE_p = mgΔh.", "foundation", "short"],
      ["Explain why doubling speed quadruples kinetic energy.", "Kinetic energy depends on v², so (2v)² = 4v² while mass is unchanged.", "stretch", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-physics-electricity",
      name: "Electricity and Electromagnetism",
      course: "Physics",
      standard: "AS 91173",
      strand: "Physics",
      keywords: [
        "electric field", "field strength", "charge", "force", "potential energy", "uniform field", "voltage",
        "current", "resistance", "series", "parallel", "power", "electrical energy", "magnetic field", "conductor",
        "motor effect", "charged particle", "induced voltage", "generator", "right-hand rule", "electron", "conventional current",
        "potential difference", "electromagnetism",
      ],
    },
    [
      ["Define electric field strength and write its equation.", "Force per unit positive charge at a point: E = F/q.", "foundation", "explain"],
      ["What is the direction of an electric field?", "The direction of the force on a positive test charge.", "foundation", "explain"],
      ["How are electric field lines directed between parallel plates?", "Straight and parallel from the positive plate to the negative plate.", "foundation", "short"],
      ["Write the relationship for electric field strength between uniform parallel plates.", "E = V/d.", "foundation", "short"],
      ["A potential difference of 600 V is across plates 0.020 m apart. Calculate field strength.", "E = V/d = 600/0.020 = 3.0 × 10⁴ V m⁻¹.", "core", "short"],
      ["Write the equation for force on a charge in an electric field.", "F = Eq.", "foundation", "short"],
      ["A charge of +2.0 × 10⁻⁶ C is in a 5.0 × 10³ N C⁻¹ field. Calculate the force.", "F = Eq = 1.0 × 10⁻² N in the field direction.", "core", "short"],
      ["How does the force direction on a negative charge compare with the electric field direction?", "It is opposite to the electric field direction.", "core", "explain"],
      ["What energy change occurs when a positive charge moves in the direction of an electric field?", "Its electric potential energy decreases as the field does work on it.", "core", "explain"],
      ["Write the equation for electric potential energy change across uniform plates.", "ΔE_p = Eqd, with sign determined by displacement and charge direction.", "core", "short"],
      ["Define electric current and write its equation in terms of charge and time.", "The rate of flow of charge: I = q/Δt.", "foundation", "explain"],
      ["A current of 0.40 A flows for 30 s. Calculate the charge transferred.", "q = IΔt = 0.40 × 30 = 12 C.", "core", "short"],
      ["What is potential difference?", "Energy transferred per unit charge between two points.", "foundation", "explain"],
      ["Write Ohm's law for a resistor.", "V = IR.", "foundation", "short"],
      ["A 12 V supply drives 3.0 A through a resistor. Calculate resistance.", "R = V/I = 12/3.0 = 4.0 Ω.", "core", "short"],
      ["How does current behave at a junction in a parallel circuit?", "Total current entering the junction equals total current leaving; branch currents add to the supply current.", "core", "explain"],
      ["How does voltage compare across branches connected in parallel?", "Each branch has the same potential difference.", "foundation", "short"],
      ["Write the total-resistance equation for resistors in series.", "R_T = R₁ + R₂ + ... .", "foundation", "short"],
      ["Write the total-resistance relationship for resistors in parallel.", "1/R_T = 1/R₁ + 1/R₂ + ... .", "core", "short"],
      ["Calculate the total resistance of 6.0 Ω and 3.0 Ω connected in parallel.", "1/R_T = 1/6.0 + 1/3.0 = 1/2.0, so R_T = 2.0 Ω.", "core", "short"],
      ["Why is total resistance lower when another resistor is added in parallel?", "The added branch provides another path for charge, increasing total current for the same supply voltage.", "core", "explain"],
      ["A source has a resistor in series with a parallel network. Why does changing one branch affect the voltage across the network?", "Changing branch resistance changes total circuit current, which changes the voltage drop across the series resistor and therefore the voltage left for the parallel network.", "stretch", "explain"],
      ["Write the equation for electrical power.", "P = IV.", "foundation", "short"],
      ["A device uses 2.0 A at 230 V. Calculate its power.", "P = IV = 2.0 × 230 = 460 W.", "core", "short"],
      ["Write the equation linking electrical energy, voltage, charge, and time.", "ΔE = Vq = VIΔt.", "core", "short"],
      ["A 60 W lamp operates for 120 s. Calculate the energy transferred.", "E = PΔt = 60 × 120 = 7200 J.", "core", "short"],
      ["What is the motor effect?", "A current-carrying conductor in a magnetic field experiences a force.", "foundation", "explain"],
      ["Write the equation for force on a perpendicular current-carrying conductor.", "F = BIL.", "foundation", "short"],
      ["A 0.20 m wire carries 4.0 A perpendicular to a 0.50 T field. Calculate the force.", "F = BIL = 0.50 × 4.0 × 0.20 = 0.40 N.", "core", "short"],
      ["How can the force direction on a current-carrying wire be found?", "Use the appropriate hand rule with magnetic field direction and conventional current direction.", "core", "explain"],
      ["What happens to magnetic force if a wire is parallel to the field?", "The force is zero because there is no perpendicular component of motion or current.", "core", "explain"],
      ["Write the equation for magnetic force on a charged particle moving perpendicular to a field.", "F = Bqv.", "foundation", "short"],
      ["Why does a magnetic field change the direction but not the speed of a charged particle?", "The magnetic force is perpendicular to velocity, so it changes direction without doing work on the particle.", "stretch", "explain"],
      ["How does a negative particle curve compared with a positive particle entering the same magnetic field?", "It curves in the opposite direction because its magnetic force direction is reversed.", "core", "explain"],
      ["What is electromagnetic induction?", "The production of a potential difference when a conductor cuts magnetic field lines.", "foundation", "explain"],
      ["Write the equation for voltage induced across a straight conductor moving perpendicularly through a uniform field.", "V = BvL.", "foundation", "short"],
      ["A 0.30 m conductor moves at 5.0 m s⁻¹ through a 0.40 T field. Calculate induced voltage.", "V = BvL = 0.40 × 5.0 × 0.30 = 0.60 V.", "core", "short"],
      ["Name three ways to increase induced voltage in a straight moving conductor.", "Increase magnetic field strength, conductor speed, or the length cutting the field.", "core", "short"],
      ["Why must a conductor cut across magnetic field lines to generate voltage?", "Only the velocity component perpendicular to the field separates charges along the conductor.", "stretch", "explain"],
      ["Compare electric and magnetic forces on a stationary charged particle.", "An electric field can exert F = Eq on a stationary charge; a magnetic field exerts no force until the charge moves through it.", "stretch", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-physics-waves",
      name: "Waves",
      course: "Physics",
      standard: "AS 91170",
      strand: "Physics",
      keywords: [
        "amplitude", "wavelength", "frequency", "period", "wave speed", "reflection", "refraction", "diffraction",
        "superposition", "interference", "phase", "path difference", "mechanical wave", "electromagnetic wave",
        "curved mirror", "lens", "focal length", "magnification", "refractive index", "Snell's law", "critical angle",
        "total internal reflection", "real image", "virtual image",
      ],
    },
    [
      ["What is wavelength?", "The shortest distance between points in the same phase on consecutive cycles of a wave.", "foundation", "explain"],
      ["What is frequency?", "The number of complete wave cycles passing a point per second, measured in hertz.", "foundation", "explain"],
      ["Define wave period and write its relationship with frequency.", "The time taken for one complete cycle: T = 1/f.", "foundation", "explain"],
      ["Write the wave-speed relationship.", "v = fλ.", "foundation", "short"],
      ["A wave has frequency 25 Hz and wavelength 0.80 m. Calculate its speed.", "v = fλ = 25 × 0.80 = 20 m s⁻¹.", "core", "short"],
      ["How does an electromagnetic wave differ from a mechanical wave?", "An electromagnetic wave can travel through a vacuum; a mechanical wave requires a material medium.", "core", "explain"],
      ["What happens to frequency when a wave crosses into a new medium?", "Frequency remains constant because it is set by the source.", "foundation", "short"],
      ["What usually changes when a wave enters a new medium?", "Wave speed and wavelength can change, while frequency stays constant.", "foundation", "short"],
      ["State the law of reflection.", "Angle of incidence equals angle of reflection, measured from the normal.", "foundation", "short"],
      ["What causes refraction at a boundary?", "A change in wave speed causes the wavefront to change direction unless it enters along the normal.", "core", "explain"],
      ["When does a ray bend toward the normal?", "When it enters a medium in which its speed is lower and refractive index is higher.", "core", "short"],
      ["Write Snell's law.", "n₁ sin θ₁ = n₂ sin θ₂.", "foundation", "short"],
      ["Light travels from air into glass with n = 1.50 at 30°. Calculate the refracted angle.", "sin θ₂ = sin 30°/1.50 = 0.333, so θ₂ ≈ 19.5°.", "core", "short"],
      ["Write the relationship between refractive index and wave speed for two media.", "n₁/n₂ = v₂/v₁, or v₁/v₂ = n₂/n₁.", "core", "short"],
      ["What is the critical angle?", "The incident angle in the higher-index medium that produces a refracted ray at 90° to the normal.", "core", "explain"],
      ["State the two conditions for total internal reflection.", "The wave travels from higher to lower refractive index, and incidence angle is greater than the critical angle.", "core", "short"],
      ["Why does an optical fibre guide light around bends?", "Light repeatedly undergoes total internal reflection at the core-cladding boundary.", "core", "explain"],
      ["What does a converging lens do to parallel rays?", "It refracts them toward a principal focus.", "foundation", "short"],
      ["What image is formed by a converging lens when the object is beyond twice the focal length?", "A real, inverted, diminished image between f and 2f on the other side.", "core", "explain"],
      ["What image is formed when an object is inside the focal length of a converging lens?", "A virtual, upright, magnified image on the same side as the object.", "core", "explain"],
      ["Write the thin-lens or curved-mirror equation.", "1/f = 1/d_o + 1/d_i.", "foundation", "short"],
      ["A converging lens has f = 0.20 m and d_o = 0.60 m. Calculate d_i.", "1/d_i = 1/0.20 − 1/0.60 = 3.33, so d_i = 0.30 m.", "core", "short"],
      ["Write one equation for linear magnification.", "m = h_i/h_o = d_i/d_o, with sign conventions where required.", "foundation", "short"],
      ["What image is formed by a concave mirror when an object is beyond the focal point?", "A real, inverted image; its size depends on object distance.", "core", "explain"],
      ["What image does a convex mirror always form?", "A virtual, upright, diminished image behind the mirror.", "foundation", "short"],
      ["What is superposition?", "When waves overlap, the resultant displacement is the vector sum of their individual displacements.", "foundation", "explain"],
      ["What happens when two equal upward pulses completely overlap?", "They interfere constructively to produce a pulse with twice the amplitude at that instant.", "foundation", "explain"],
      ["What happens when equal and opposite pulses completely overlap?", "They interfere destructively to give zero resultant displacement at that instant, then continue through each other.", "core", "explain"],
      ["What is constructive interference from two coherent sources?", "Waves arrive in phase, so their displacements reinforce and amplitude is larger.", "core", "explain"],
      ["What path difference produces constructive interference for in-phase sources?", "A whole-number multiple of wavelength: nλ.", "core", "short"],
      ["What path difference produces destructive interference for in-phase sources?", "An odd half-wavelength: (n + ½)λ.", "core", "short"],
      ["What phase difference corresponds to half a wavelength?", "180° or π radians.", "foundation", "short"],
      ["Why are stable two-source interference patterns produced by coherent sources?", "They maintain the same frequency and a constant phase relationship.", "core", "explain"],
      ["What is diffraction?", "The spreading of a wave as it passes through a gap or around an obstacle.", "foundation", "explain"],
      ["When is diffraction through a slit most noticeable?", "When the slit width is similar to or smaller than the wavelength.", "core", "short"],
      ["How does increasing wavelength affect diffraction through the same slit?", "The wave spreads more because the wavelength is larger relative to the slit width.", "core", "explain"],
      ["How does a reflected pulse change at a fixed end?", "It is inverted, producing a 180° phase change.", "core", "explain"],
      ["How does a reflected pulse change at a free end?", "It is not inverted, so there is no 180° phase change.", "core", "explain"],
      ["Compare wave refraction with ray refraction.", "Both result from a speed change at a boundary; wavefront spacing changes and the ray, perpendicular to the wavefronts, changes direction.", "stretch", "explain"],
      ["Explain why frequency stays constant but wavelength decreases when light slows in glass.", "The source fixes frequency and wave crests must remain continuous at the boundary; since v = fλ, a lower speed at unchanged frequency requires a shorter wavelength.", "stretch", "explain"],
    ],
  ),

  makeTopic(
    {
      id: "y12-aghort-livestock-growth",
      name: "NZ Livestock Growth and Development",
      course: "Agricultural & Horticultural Science",
      standard: "AS 91294",
      strand: "Agriculture",
      keywords: [
        "growth", "development", "livestock", "management practice", "genetics", "breeding", "nutrition", "pasture",
        "weaning", "stocking rate", "animal health", "parasite", "vaccination", "shelter", "temperature", "stress",
        "live weight", "condition score", "growth rate", "maturity", "carcass", "fibre", "milk", "quantity",
        "quality", "timing", "economics", "New Zealand production",
      ],
    },
    [
      ["What is livestock growth?", "An increase in measurable size or mass, such as live weight, muscle, bone, or fibre.", "foundation", "explain"],
      ["What is livestock development?", "Progressive changes in body form and function as an animal matures, including changes in tissues, organs, and reproductive status.", "foundation", "explain"],
      ["How does growth differ from development?", "Growth is a quantitative increase in size or mass; development is a qualitative change toward maturity and function.", "core", "explain"],
      ["What is a management practice in commercial livestock production?", "A deliberate action taken to influence growth, development, product quantity or quality, timing, or production economics.", "foundation", "explain"],
      ["Name four production outcomes management practices can influence.", "Quantity, quality, timing, and economics of production.", "foundation", "short"],
      ["Why is live-weight monitoring useful?", "It shows growth rate and progress toward target weights, allowing feeding or health management to be adjusted early.", "core", "explain"],
      ["What does body-condition scoring estimate?", "The animal's energy reserves, mainly fat cover, using a standard visual and handling scale.", "foundation", "explain"],
      ["How can selecting high-growth genetics affect production?", "Offspring may reach target weight sooner or produce more saleable product, improving timing and potential income.", "core", "explain"],
      ["Why must genetic selection consider more than maximum growth rate?", "Traits can be genetically linked or involve trade-offs with health, fertility, product quality, feed needs, and suitability for the farm environment.", "stretch", "explain"],
      ["How can crossbreeding influence livestock performance?", "It can combine useful parental traits and produce hybrid vigour in growth, survival, fertility, or health.", "core", "explain"],
      ["Why is matching breed to the New Zealand production environment important?", "Animals suited to local climate, terrain, pasture, and disease pressures are more likely to grow efficiently and remain healthy.", "core", "explain"],
      ["How does adequate energy intake support growth?", "Energy fuels maintenance and activity first; energy above maintenance can be used to build tissue and product.", "core", "explain"],
      ["Why is protein important for growing livestock?", "It supplies amino acids needed to build muscle, organs, enzymes, and other body proteins.", "foundation", "explain"],
      ["How can a mineral deficiency reduce growth or development?", "A required physiological process may be limited, reducing bone growth, metabolism, immunity, or reproductive development.", "core", "explain"],
      ["Why is clean water essential for livestock growth?", "Water supports digestion, transport, temperature regulation, metabolism, and feed intake; restricted water reduces performance.", "core", "explain"],
      ["How can high-quality pasture increase growth rate?", "It provides more digestible energy and protein, increasing nutrient intake available for tissue and product formation.", "core", "explain"],
      ["Why can very mature pasture reduce animal growth?", "It usually contains more fibre and less digestible energy and protein, so intake and nutrient supply may fall.", "core", "explain"],
      ["How can rotational grazing improve livestock growth?", "It offers stock fresh pasture at a suitable stage and gives grazed areas time to recover, supporting feed quality and supply.", "core", "explain"],
      ["How can an excessive stocking rate reduce individual animal growth?", "Competition lowers feed intake per animal and can increase stress, parasite challenge, and pasture damage.", "core", "explain"],
      ["Why might supplementary feed be used during a pasture shortage?", "It fills an energy or protein deficit, helping maintain growth rate and target production timing.", "foundation", "explain"],
      ["How can the timing of weaning influence young-stock growth?", "Weaning too early can reduce nutrient intake and cause stress; well-timed weaning allows transition to sufficient solid feed while supporting continued growth.", "core", "explain"],
      ["Why is gradual dietary change safer than a sudden change?", "It allows rumen microbes or the digestive system to adapt, reducing digestive upset and lost growth.", "core", "explain"],
      ["How can internal parasites reduce livestock growth?", "They take nutrients or damage tissues, reducing digestion, feed efficiency, health, and weight gain.", "core", "explain"],
      ["How can strategic parasite control improve production economics?", "Effective treatment protects growth and product output, but timing and product choice must justify cost and slow resistance development.", "stretch", "explain"],
      ["How can vaccination support growth and development?", "It reduces the risk or severity of disease, so less energy is diverted to illness and fewer animals lose growth or die.", "core", "explain"],
      ["Why can routine health checks improve production timing?", "Early detection and treatment reduce the length of illness and help animals stay on track to reach target weight or maturity.", "core", "explain"],
      ["How can lameness reduce growth?", "Pain reduces grazing and movement, lowering feed intake and diverting energy from production to recovery.", "core", "explain"],
      ["How does cold stress affect young livestock?", "More energy is used to maintain body temperature, leaving less energy for growth and increasing feed requirements.", "core", "explain"],
      ["How can shelter improve survival and growth in exposed New Zealand conditions?", "It reduces wind chill and heat loss, lowering maintenance energy needs and stress, especially in newborn animals.", "core", "explain"],
      ["How can heat stress reduce production?", "Animals reduce feed intake and spend energy cooling themselves, so growth, milk production, or fertility can decline.", "core", "explain"],
      ["Why does low-stress handling support growth?", "It reduces injury and stress responses that suppress feeding, immunity, and efficient energy use.", "foundation", "explain"],
      ["How can separating livestock into management groups improve growth?", "Feed and care can be targeted by age, size, sex, pregnancy status, or condition, reducing competition and meeting different needs.", "core", "explain"],
      ["How can castration influence growth and product quality?", "It alters hormone-driven development and behaviour, which can change growth pattern, fat deposition, meat quality, handling, and market timing.", "stretch", "explain"],
      ["Why might male and female livestock require different management?", "Sex hormones and mature size affect growth rate, tissue deposition, behaviour, and reproductive development.", "core", "explain"],
      ["How can pregnancy and lactation alter a female's feed requirements?", "Nutrients are needed for fetal growth or milk production as well as maintenance, so requirements rise and body reserves may be used if intake is inadequate.", "core", "explain"],
      ["Why is colostrum management critical for newborn mammals?", "Early colostrum supplies antibodies and concentrated nutrients, improving immunity, survival, and the foundation for later growth.", "core", "explain"],
      ["How can reaching a target live weight earlier improve farm economics?", "Animals may be sold sooner, use less feed and labour, free pasture for other stock, and meet higher-value market windows.", "stretch", "explain"],
      ["Why can the fastest growth strategy fail to maximise profit?", "Extra feed, housing, labour, or health costs may exceed the value of additional or earlier product, and quality may not match market requirements.", "stretch", "explain"],
      ["Compare the effects of nutrition and disease control on growth.", "Nutrition supplies materials and energy for growth; disease control prevents nutrients and energy being diverted from growth and reduces tissue damage or lost intake.", "stretch", "explain"],
      ["Explain how monitoring, feeding, and health management can work together to meet a market target.", "Monitoring identifies animals below target; feed quality or allocation can then be adjusted and health causes treated, improving growth rate, product quality, timing, and economic return.", "stretch", "explain"],
    ],
    [
      ["What term means an increase in an animal's measurable size or mass?", "Growth", "foundation", "short"],
      ["What term describes changes in body form and function as an animal matures?", "Development", "foundation", "short"],
      ["What scoring method estimates an animal's fat reserves?", "Body-condition scoring", "foundation", "short"],
      ["What is the antibody-rich first milk produced after birth called?", "Colostrum", "foundation", "short"],
      ["What practice protects livestock by stimulating immunity before disease exposure?", "Vaccination", "foundation", "short"],
      ["What is extra feed supplied when pasture does not meet animal needs called?", "Supplementary feed", "foundation", "short"],
      ["What is the separation of young livestock from their mother's milk called?", "Weaning", "foundation", "short"],
      ["What term means the number of animals grazing a given area?", "Stocking rate", "foundation", "short"],
      ["What grazing system moves stock between paddocks and allows pasture recovery?", "Rotational grazing", "foundation", "short"],
      ["What type of parasite lives inside an animal's body?", "Internal parasite", "foundation", "short"],
      ["Which nutrient supplies amino acids for muscle and tissue growth?", "Protein", "foundation", "short"],
      ["What measurement is commonly used to track progress towards target sale weights?", "Live weight", "foundation", "short"],

      ["What term describes improved offspring performance produced by crossbreeding?", "Hybrid vigour", "core", "short"],
      ["What production outcome refers to how much saleable product is produced?", "Quantity", "core", "short"],
      ["What production outcome refers to the characteristics or grade of the product?", "Quality", "core", "short"],
      ["What production outcome refers to reaching a target at the required date?", "Timing", "core", "short"],
      ["What farm measure compares financial return with production costs?", "Profit", "core", "short"],
      ["What term describes feed energy used simply to keep an animal alive?", "Maintenance energy", "core", "short"],
      ["What pasture characteristic usually rises as pasture becomes older and less digestible?", "Fibre", "core", "short"],
      ["What usually decreases when excessive stocking creates strong competition for pasture?", "Feed intake", "core", "short"],
      ["What environmental protection reduces wind chill for exposed young stock?", "Shelter", "core", "short"],
      ["What behaviour commonly decreases first when livestock experience heat stress?", "Feed intake", "core", "short"],
      ["What practice sorts animals so feeding and care can match their needs?", "Management grouping", "core", "short"],
      ["What term describes how efficiently feed is converted into live-weight gain?", "Feed efficiency", "core", "short"],
      ["What term means the increase in live weight per unit of time?", "Growth rate", "core", "short"],
      ["What name is given to the dressed body of an animal after slaughter?", "Carcass", "core", "short"],
      ["What saleable fibre is produced by sheep?", "Wool", "core", "short"],
      ["What type of medicine is used to control internal parasites?", "Anthelmintic", "core", "short"],

      ["What term describes a compromise in which improving one trait can worsen another?", "Trade-off", "stretch", "short"],
      ["What can develop when the same parasite treatment is overused repeatedly?", "Drench resistance", "stretch", "short"],
      ["What male-management practice changes hormone-driven growth and behaviour?", "Castration", "stretch", "short"],
      ["What term describes the genetically influenced age or stage at which an animal becomes fully developed?", "Maturity", "stretch", "short"],
      ["What body response diverts nutrients and energy away from growth during illness?", "Immune response", "stretch", "short"],
      ["What energy requirement increases when livestock experience cold stress?", "Maintenance requirement", "stretch", "short"],
      ["What reproductive state sharply increases a female's nutrient needs before birth?", "Pregnancy", "stretch", "short"],
      ["What production stage sharply increases a female's nutrient needs after birth?", "Lactation", "stretch", "short"],
      ["What process uses repeated measurements to identify animals falling behind target growth?", "Monitoring", "stretch", "short"],
      ["What term describes choosing breeding animals for desired inherited traits?", "Selective breeding", "stretch", "short"],
      ["What market feature may reward animals that reach target weight at a particular time?", "Price premium", "stretch", "short"],
      ["What term describes how well a breed matches local climate, terrain and feed conditions?", "Breed suitability", "stretch", "short"],
    ],
  ),
];

for (const topic of seniorTopics) {
  if (topic.questions.length !== 40) {
    throw new Error(`${topic.id} must contain exactly 40 questions; found ${topic.questions.length}.`);
  }

  const uniqueQuestions = new Set(topic.questions.map((question) => question.q.trim().toLowerCase()));
  if (uniqueQuestions.size !== topic.questions.length) {
    throw new Error(`${topic.id} contains duplicate question wording.`);
  }

  if (topic.oneWordQuestions) {
    for (const difficulty of ["foundation", "core", "stretch"] as const) {
      const questionsAtLevel = topic.oneWordQuestions.filter((question) => question.difficulty === difficulty);
      const minimum = difficulty === "core" ? 16 : 12;
      if (questionsAtLevel.length < minimum) {
        throw new Error(`${topic.id} must contain at least ${minimum} ${difficulty} one-word questions.`);
      }
    }

    if (topic.oneWordQuestions.some((question) => question.kind !== "short")) {
      throw new Error(`${topic.id} one-word bank contains a non-short question.`);
    }

    const uniqueOneWordQuestions = new Set(topic.oneWordQuestions.map((question) => question.q.trim().toLowerCase()));
    if (uniqueOneWordQuestions.size !== topic.oneWordQuestions.length) {
      throw new Error(`${topic.id} contains duplicate one-word question wording.`);
    }
  }
}
