import type { SeniorCourse, SeniorQuestion } from "./year12-question-bank";

type Difficulty = SeniorQuestion["difficulty"];
type QuestionKind = SeniorQuestion["kind"];

export type Year13Topic = {
  id: string;
  year: 13;
  name: string;
  course: SeniorCourse;
  standard: string;
  strand: "Biology" | "Chemistry" | "Physics" | "Agriculture";
  keywords: string[];
  questions: SeniorQuestion[];
  oneWordQuestions: SeniorQuestion[];
};

type QuestionRow = readonly [string, string, Difficulty, QuestionKind];
type OneWordRow = readonly [string, string, Difficulty];

function makeTopic(
  details: Omit<Year13Topic, "year" | "questions" | "oneWordQuestions">,
  rows: QuestionRow[],
  oneWordRows: OneWordRow[],
): Year13Topic {
  return {
    ...details,
    year: 13,
    questions: rows.map(([q, a, difficulty, kind]) => ({ q, a, difficulty, kind })),
    oneWordQuestions: oneWordRows.map(([q, a, difficulty]) => ({ q, a, difficulty, kind: "short" })),
  };
}

export const year13Topics: Year13Topic[] = [
  makeTopic(
    {
      id: "y13-bio-responses",
      name: "Plant and Animal Responses",
      course: "Biology",
      standard: "AS 91603",
      strand: "Biology",
      keywords: [
        "tropism", "nastic response", "taxis", "kinesis", "homing", "migration", "circadian rhythm",
        "circannual rhythm", "lunar rhythm", "tidal rhythm", "zeitgeber", "entrainment", "free-running period",
        "actogram", "photoperiodism", "phytochrome", "auxin", "abscisic acid", "competition", "mutualism",
        "predation", "parasitism", "territoriality", "hierarchy", "courtship", "cooperative breeding",
        "altruism", "kin selection", "agonistic behaviour", "selective advantage", "ecological niche",
      ],
    },
    [
      // Foundation (12)
      ["What is a tropism?", "A directional growth response by a plant toward or away from an external stimulus.", "foundation", "explain"],
      ["What is a nastic response?", "A plant movement whose direction is independent of the direction of the stimulus.", "foundation", "explain"],
      ["What is a taxis?", "A directional movement of an organism toward or away from a stimulus.", "foundation", "explain"],
      ["What is a kinesis?", "A non-directional change in an animal's movement rate or turning rate in response to stimulus intensity.", "foundation", "explain"],
      ["What is a circadian rhythm?", "An endogenous biological rhythm with a period of about 24 hours.", "foundation", "explain"],
      ["What is a zeitgeber?", "An external environmental cue, such as light, that resets or synchronises a biological clock.", "foundation", "explain"],
      ["What is entrainment?", "The synchronising of an endogenous biological rhythm to an external environmental cycle.", "foundation", "explain"],
      ["What does an actogram display?", "An organism's activity pattern plotted over successive time periods or days.", "foundation", "explain"],
      ["What is photoperiodism?", "A biological response to the relative lengths of day and night.", "foundation", "explain"],
      ["What is mutualism?", "An interspecific relationship in which both species gain a benefit.", "foundation", "explain"],
      ["What is territoriality?", "The defence of an area against other members of the same species.", "foundation", "explain"],
      ["What is courtship behaviour?", "A sequence of signals or actions used to attract, recognise, and assess a potential mate.", "foundation", "explain"],
      // Core (16)
      ["How does auxin cause a shoot to bend toward light?", "Auxin accumulates on the shaded side and promotes greater cell elongation there, so the shoot curves toward the light.", "core", "explain"],
      ["How does positive gravitropism benefit a plant root?", "It directs root growth downward into soil, improving anchorage and access to water and mineral ions.", "core", "explain"],
      ["How can a nastic response protect a plant?", "Rapid, non-directional leaf closure can reduce herbivory, water loss, or physical damage.", "core", "explain"],
      ["How does kinesis help a woodlouse remain in a humid habitat?", "It moves faster or turns less in dry conditions and slows or turns more in humid conditions, increasing time spent where water loss is lower.", "core", "explain"],
      ["Why is migration described as an orientation response?", "Animals use environmental cues to move directionally between habitats that support feeding, breeding, or survival.", "core", "explain"],
      ["How does homing differ from migration?", "Homing is a return to a particular site, whereas migration is regular movement between regions, often seasonally.", "core", "explain"],
      ["What is a free-running period?", "The natural period of an endogenous rhythm measured without external timing cues.", "core", "explain"],
      ["How can an actogram show that a rhythm is endogenous?", "In constant conditions, activity continues with a regular free-running period rather than disappearing.", "core", "explain"],
      ["How does phytochrome help a plant detect photoperiod?", "Its interconvertible forms provide information about light and darkness duration, influencing flowering and other responses.", "core", "explain"],
      ["How can abscisic acid help a plant during water stress?", "It promotes stomatal closure, reducing transpiration and conserving water.", "core", "explain"],
      ["How does competition affect an organism's ecological niche?", "Limited resources restrict where and how it can survive and reproduce, potentially narrowing its realised niche.", "core", "explain"],
      ["How does predation provide a selective advantage to a predator?", "Successful hunting increases food intake, survival, and the energy available for reproduction.", "core", "explain"],
      ["How can hierarchical behaviour reduce the costs of conflict?", "Established ranks settle access to resources with fewer repeated fights, reducing injury and energy use.", "core", "explain"],
      ["Why can cooperative breeding increase inclusive fitness?", "Helpers improve survival of related young that share some of their alleles.", "core", "explain"],
      ["What is kin selection?", "Selection favouring behaviour that helps relatives reproduce because relatives share alleles with the helper.", "core", "explain"],
      ["How can agonistic behaviour avoid serious injury?", "Threats, displays, submission, and ritualised contests can resolve conflict before costly physical fighting occurs.", "core", "explain"],
      // Stretch (12)
      ["Compare taxis and kinesis as ways of reaching favourable conditions.", "Taxis directly orients movement toward or away from a stimulus; kinesis changes movement pattern non-directionally so the organism accumulates in favourable conditions.", "stretch", "explain"],
      ["Explain why both an internal clock and a zeitgeber are useful.", "The clock anticipates regular change, while the zeitgeber resets it so activity remains aligned with local environmental time.", "stretch", "explain"],
      ["Explain why a nocturnal animal may begin activity before darkness.", "An entrained endogenous clock allows anticipation, so preparation and movement can start before the external light cue changes.", "stretch", "explain"],
      ["How could an actogram reveal entrainment after a shifted light-dark cycle?", "The activity onset would gradually or rapidly shift until it keeps a stable relationship with the new light-dark cycle.", "stretch", "explain"],
      ["Explain how photoperiodism can coordinate reproduction with seasonal conditions.", "Day length provides a reliable seasonal cue, so reproductive development occurs before conditions best support offspring survival.", "stretch", "explain"],
      ["Why can a tropism increase a plant's fitness even though growth is slow?", "Permanent directional growth positions organs where resource capture is improved, increasing survival and reproductive output over time.", "stretch", "explain"],
      ["Compare mutualism and parasitism in terms of fitness effects.", "In mutualism both partners gain fitness benefits; in parasitism the parasite benefits while the host's survival or reproduction is reduced.", "stretch", "explain"],
      ["Explain how territoriality can have both benefits and costs.", "Exclusive resources can improve survival and breeding success, but defence uses time and energy and risks injury; it is favoured when benefits exceed costs.", "stretch", "explain"],
      ["Why can altruistic behaviour evolve without benefiting the actor directly?", "If recipients are close relatives, the behaviour can increase transmission of shared alleles through inclusive fitness.", "stretch", "explain"],
      ["Explain how courtship contributes to reproductive isolation.", "Species-specific signals promote mating with appropriate partners, reducing unsuccessful interspecific mating and gene flow.", "stretch", "explain"],
      ["Analyse how a response must be linked to ecological niche for an Excellence-level explanation.", "The mechanism, environmental cue, resulting behaviour or growth, and effect on survival or reproduction must be connected in the organism's particular resource and habitat context.", "stretch", "explain"],
      ["Why might the same response be advantageous in one environment but costly in another?", "Its fitness effect depends on local resources, predators, competitors, climate, and timing, so the benefits and costs change with ecological context.", "stretch", "explain"],
    ],
    [
      ["What directional plant growth response occurs toward or away from a stimulus?", "Tropism", "foundation"],
      ["What non-directional plant movement does not depend on stimulus direction?", "Nastic response", "foundation"],
      ["What directional animal movement occurs toward or away from a stimulus?", "Taxis", "foundation"],
      ["What response changes movement rate or turning without a set direction?", "Kinesis", "foundation"],
      ["What roughly 24-hour biological rhythm is controlled internally?", "Circadian rhythm", "foundation"],
      ["What external cue resets a biological clock?", "Zeitgeber", "foundation"],
      ["What process synchronises a rhythm to an environmental cycle?", "Entrainment", "foundation"],
      ["What graph displays activity over successive days?", "Actogram", "foundation"],
      ["What response depends on relative day and night length?", "Photoperiodism", "foundation"],
      ["What plant pigment system detects red and far-red light?", "Phytochrome", "foundation"],
      ["What plant hormone promotes shoot cell elongation?", "Auxin", "foundation"],
      ["What plant hormone promotes stomatal closure during water stress?", "Abscisic acid", "foundation"],
      ["What is the natural rhythm period without timing cues called?", "Free-running period", "core"],
      ["What annual biological rhythm follows the seasons?", "Circannual rhythm", "core"],
      ["What rhythm is timed to phases of the Moon?", "Lunar rhythm", "core"],
      ["What rhythm follows the rise and fall of tides?", "Tidal rhythm", "core"],
      ["What return movement brings an animal back to a specific site?", "Homing", "core"],
      ["What regular long-distance movement occurs between habitats?", "Migration", "core"],
      ["What relationship benefits both interacting species?", "Mutualism", "core"],
      ["What relationship benefits one organism while harming its host?", "Parasitism", "core"],
      ["What interaction occurs when organisms seek the same limited resource?", "Competition", "core"],
      ["What behaviour involves defending an area from conspecifics?", "Territoriality", "core"],
      ["What stable ranking system regulates access to resources?", "Hierarchy", "core"],
      ["What mating behaviour attracts and assesses partners?", "Courtship", "core"],
      ["What behaviour includes threats, submission, and fighting?", "Agonistic behaviour", "core"],
      ["What shared care system uses helpers to raise young?", "Cooperative breeding", "core"],
      ["What behaviour benefits another individual at a cost to the actor?", "Altruism", "core"],
      ["What selection favours help directed toward genetic relatives?", "Kin selection", "core"],
      ["What term means the role and resource use of an organism in its environment?", "Ecological niche", "stretch"],
      ["What fitness benefit makes a response more likely to be retained?", "Selective advantage", "stretch"],
      ["What term includes an individual's own reproduction plus effects on relatives' reproduction?", "Inclusive fitness", "stretch"],
      ["What plant response directs a shoot toward light?", "Positive phototropism", "stretch"],
      ["What root response directs growth with gravity?", "Positive gravitropism", "stretch"],
      ["What process is reduced when abscisic acid closes stomata?", "Transpiration", "stretch"],
      ["What niche describes the full conditions a species could occupy without competitors?", "Fundamental niche", "stretch"],
      ["What niche describes where a species actually lives with biotic interactions?", "Realised niche", "stretch"],
      ["What cue commonly entrains circadian rhythms in animals?", "Light", "stretch"],
      ["What fitness component increases when courtship leads to successful mating?", "Reproductive success", "stretch"],
      ["What term describes interactions between different species?", "Interspecific", "stretch"],
      ["What term describes interactions within one species?", "Intraspecific", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-bio-human-evolution",
      name: "Human Evolution",
      course: "Biology",
      standard: "AS 91606",
      strand: "Biology",
      keywords: [
        "hominin", "hominid", "bipedalism", "foramen magnum", "valgus angle", "pelvis", "spine", "foot arch",
        "opposable thumb", "precision grip", "prognathism", "endocranial capacity", "dentition", "cultural evolution",
        "Oldowan", "Acheulean", "Mousterian", "Paleolithic", "Neolithic", "fire", "language", "art",
        "hunter-gatherer", "domestication", "dispersal", "mitochondrial DNA", "nuclear DNA", "relative dating",
        "absolute dating", "selection pressure", "scientific evidence",
      ],
    },
    [
      // Foundation (12)
      ["What is a hominin?", "A living or fossil species belonging to the human lineage after divergence from the lineage leading to chimpanzees and bonobos.", "foundation", "explain"],
      ["How does a hominin differ from a hominid?", "Hominins are members of the human lineage, while hominids include humans and all great apes.", "foundation", "explain"],
      ["What is bipedalism?", "Habitual locomotion using two hind limbs in an upright posture.", "foundation", "explain"],
      ["What skull feature shows that the head balanced over an upright spine?", "A foramen magnum positioned more centrally underneath the skull.", "foundation", "short"],
      ["What is prognathism?", "Forward projection of the jaws and face beyond the upper part of the skull.", "foundation", "explain"],
      ["What is endocranial capacity?", "The volume inside the cranium, used as an estimate of brain size.", "foundation", "explain"],
      ["What is a precision grip?", "Holding and manipulating an object accurately between the thumb and fingertips.", "foundation", "explain"],
      ["What is cultural evolution?", "Change in learned behaviours, technologies, and social practices transmitted between individuals and generations.", "foundation", "explain"],
      ["What are Oldowan tools?", "Early simple stone flakes and cores made by striking stones together.", "foundation", "explain"],
      ["What are Acheulean tools?", "More symmetrical, deliberately shaped bifacial tools such as hand axes.", "foundation", "explain"],
      ["What does hominin dispersal mean?", "Movement and establishment of hominin populations across new geographic regions.", "foundation", "explain"],
      ["Name two types of genetic evidence used to study human evolution.", "Mitochondrial DNA and nuclear DNA.", "foundation", "short"],
      // Core (16)
      ["How does a short, broad pelvis support bipedalism?", "It supports abdominal organs and positions the gluteal muscles to stabilise the pelvis during single-leg support.", "core", "explain"],
      ["How does a valgus angle improve bipedal walking?", "It angles the femur inward so the knees and feet lie beneath the body's centre of mass, improving balance and efficiency.", "core", "explain"],
      ["How does an S-shaped spine assist upright posture?", "Its curves position the torso over the pelvis and absorb shocks during walking.", "core", "explain"],
      ["Why are a non-opposable big toe and foot arches advantageous for bipedalism?", "The aligned toe supports push-off, while arches absorb impact, store elastic energy, and stiffen the foot as a lever.", "core", "explain"],
      ["Why are relatively long legs advantageous for habitual bipedalism?", "They increase stride length and make long-distance walking and running more energy-efficient.", "core", "explain"],
      ["What general skull trend occurred during hominin evolution?", "Average endocranial capacity increased while prognathism, tooth size, and heavy jaw features generally decreased.", "core", "explain"],
      ["How can reduced canine size relate to social change?", "Smaller canines may indicate reduced use of canine display or combat and changes in diet or social behaviour.", "core", "explain"],
      ["How did increasing manipulative ability affect tool use?", "A refined precision grip allowed smaller, more controlled movements and more complex tool manufacture.", "core", "explain"],
      ["How did controlled fire provide a selective advantage?", "It supplied warmth, protection, light, and cooked food, increasing energy availability and enabling occupation of colder environments.", "core", "explain"],
      ["How did Mousterian tools differ from many earlier tools?", "They were commonly made from prepared cores to produce planned flakes suited to specialised tasks.", "core", "explain"],
      ["How could language accelerate cultural evolution?", "Detailed information, plans, and techniques could be shared accurately and accumulated across generations.", "core", "explain"],
      ["How did domestication change human subsistence?", "People increasingly managed plants and animals, supporting food surpluses, permanent settlements, and population growth.", "core", "explain"],
      ["What is the difference between relative and absolute dating?", "Relative dating places evidence in sequence; absolute dating estimates a numerical age.", "core", "explain"],
      ["Why is mitochondrial DNA useful for tracing maternal ancestry?", "It is inherited mainly from the mother and changes through mutations that can be compared among lineages.", "core", "explain"],
      ["Why can nuclear DNA provide a broader ancestry picture than mitochondrial DNA?", "It is inherited from both parents and contains recombined evidence from many ancestral lineages.", "core", "explain"],
      ["Why must claims about human evolution be based on multiple lines of evidence?", "Fossils, tools, dating, and DNA each have limitations; agreement among independent evidence produces stronger interpretations.", "core", "explain"],
      // Stretch (12)
      ["Explain how environmental change could select for efficient bipedalism.", "More open or patchy habitats would favour individuals able to travel efficiently between resources, carry food, and scan surroundings, increasing survival and reproduction.", "stretch", "explain"],
      ["Why is human evolution described as branching rather than a straight ladder?", "Multiple hominin species coexisted, diverged, and sometimes exchanged genes, so evolution involved a branching phylogeny rather than one linear sequence.", "stretch", "explain"],
      ["Explain why a larger brain alone does not prove greater behavioural complexity.", "Behaviour also depends on brain organisation, development, social learning, dexterity, communication, and culture; brain size must be interpreted with other evidence.", "stretch", "explain"],
      ["Link changes in teeth and jaw size to cultural evolution.", "Food processing, tools, and cooking reduced the need for large chewing muscles and teeth, altering selection pressures on the face and jaws.", "stretch", "explain"],
      ["How could bipedalism and manual dexterity reinforce one another?", "Upright walking freed the hands for carrying and tool use; selection for effective manipulation then favoured improved grip and control.", "stretch", "explain"],
      ["Explain how gene-culture coevolution can occur.", "A cultural practice changes the environment and selection pressures, so alleles that improve success under that practice become more frequent.", "stretch", "explain"],
      ["How can climate change drive hominin dispersal?", "Changing rainfall, temperature, and habitats alter food and water distribution, opening or closing migration routes and creating pressure to move.", "stretch", "explain"],
      ["Why can DNA evidence revise a fossil-based dispersal model?", "Genetic relationships and divergence estimates can reveal ancestry, interbreeding, or migration not apparent from incomplete or morphologically ambiguous fossils.", "stretch", "explain"],
      ["Explain how Neolithic food production changed selection pressures.", "Dense settlements, altered diets, close contact with animals, and new disease exposure favoured different immune, digestive, and metabolic traits.", "stretch", "explain"],
      ["Evaluate why named hominin species should be used cautiously.", "Species boundaries and fossil assignments can change with new evidence, so claims must match current evidence and the features of the named species.", "stretch", "explain"],
      ["Explain how archaeological evidence can indicate abstract thought.", "Symbolic art, ornaments, ritual burials, and planned objects imply representation, shared meaning, and communication beyond immediate practical use.", "stretch", "explain"],
      ["What makes a comprehensive explanation of a human evolutionary trend?", "It links evidence, anatomical or cultural change, environmental selection pressure, and consequences for survival or reproduction while recognising uncertainty.", "stretch", "explain"],
    ],
    [
      ["What term describes members of the human lineage after divergence from chimpanzees?", "Hominin", "foundation"],
      ["What group includes humans and all great apes?", "Hominids", "foundation"],
      ["What locomotion uses two legs habitually?", "Bipedalism", "foundation"],
      ["What opening in the skull transmits the spinal cord?", "Foramen magnum", "foundation"],
      ["What term describes forward projection of the jaws?", "Prognathism", "foundation"],
      ["What measurement estimates brain volume from the skull?", "Endocranial capacity", "foundation"],
      ["What inward angle of the femur positions the knees beneath the body?", "Valgus angle", "foundation"],
      ["What grip holds an object between thumb and fingertips?", "Precision grip", "foundation"],
      ["What simple early stone-tool industry used flakes and cores?", "Oldowan", "foundation"],
      ["What tool industry is associated with symmetrical hand axes?", "Acheulean", "foundation"],
      ["What prepared-core tool industry is often associated with Neanderthals?", "Mousterian", "foundation"],
      ["What movement of populations into new regions is studied in human evolution?", "Dispersal", "foundation"],
      ["What DNA type traces mainly maternal ancestry?", "Mitochondrial DNA", "core"],
      ["What DNA type combines ancestry from both parents?", "Nuclear DNA", "core"],
      ["What dating method places finds in an older-to-younger sequence?", "Relative dating", "core"],
      ["What dating method estimates a numerical age?", "Absolute dating", "core"],
      ["What spine shape positions the torso above the pelvis?", "S-shaped spine", "core"],
      ["What foot structures absorb impact and store elastic energy?", "Foot arches", "core"],
      ["What aligned toe acts as a lever during push-off?", "Non-opposable big toe", "core"],
      ["What learned change in technology and behaviour accumulates across generations?", "Cultural evolution", "core"],
      ["What controlled energy source supported warmth, cooking, and protection?", "Fire", "core"],
      ["What communication system allows detailed knowledge to accumulate?", "Language", "core"],
      ["What lifestyle obtains food from wild plants and animals?", "Hunter-gathering", "core"],
      ["What process brought plants and animals under human management?", "Domestication", "core"],
      ["What period is associated with farming and permanent settlements?", "Neolithic", "core"],
      ["What evidence type includes fossils and skeletal remains?", "Anatomical evidence", "core"],
      ["What evidence type includes stone, bone, and wooden tools?", "Archaeological evidence", "core"],
      ["What environmental factor changes survival and reproduction among phenotypes?", "Selection pressure", "core"],
      ["What term describes the branching evolutionary relationships among groups?", "Phylogeny", "stretch"],
      ["What concept links cultural practices with changes in allele frequency?", "Gene-culture coevolution", "stretch"],
      ["What body region became shorter and broader in habitual bipeds?", "Pelvis", "stretch"],
      ["What muscles stabilise the pelvis during one-legged support?", "Gluteal muscles", "stretch"],
      ["What facial trend generally accompanied reduced jaw projection?", "Reduced prognathism", "stretch"],
      ["What tooth type generally became smaller in later hominins?", "Canines", "stretch"],
      ["What process produces estimates from isotope decay?", "Radiometric dating", "stretch"],
      ["What evidence can reveal interbreeding between hominin populations?", "Genetic evidence", "stretch"],
      ["What term describes symbolic communication through images or objects?", "Art", "stretch"],
      ["What innovation increased digestibility and energy gained from food?", "Cooking", "stretch"],
      ["What settlement type became common with food production?", "Permanent settlement", "stretch"],
      ["What scientific process tests evolutionary interpretations against new evidence?", "Peer review", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-chem-thermochemical-particles",
      name: "Thermochemical Principles, Particles and Substances",
      course: "Chemistry",
      standard: "AS 91390",
      strand: "Chemistry",
      keywords: [
        "electron configuration", "orbital", "sublevel", "ionisation energy", "electronegativity", "atomic radius",
        "ionic radius", "Lewis structure", "VSEPR", "molecular shape", "polarity", "temporary dipole",
        "permanent dipole", "hydrogen bonding", "enthalpy", "entropy", "spontaneity", "specific heat capacity",
        "Hess's law", "formation enthalpy", "combustion enthalpy", "fusion", "vaporisation", "sublimation",
      ],
    },
    [
      // Foundation (12)
      ["What does an electron configuration show?", "The arrangement of an atom's or ion's electrons among shells, sublevels, and orbitals.", "foundation", "explain"],
      ["How many electrons can one orbital hold?", "Two electrons with opposite spins.", "foundation", "short"],
      ["How many electrons can fill an s, p, and d sublevel?", "An s sublevel holds 2, a p sublevel 6, and a d sublevel 10 electrons.", "foundation", "short"],
      ["What is first ionisation energy?", "The energy required to remove one electron from each atom in one mole of gaseous atoms.", "foundation", "explain"],
      ["What is electronegativity?", "The ability of an atom in a covalent bond to attract the bonding electrons.", "foundation", "explain"],
      ["What causes temporary dipole attractions?", "Momentary uneven electron distribution creates an instantaneous dipole that induces dipoles in nearby particles.", "foundation", "explain"],
      ["When do permanent dipole attractions occur?", "Between polar molecules whose permanent partial charges attract.", "foundation", "explain"],
      ["What atoms must hydrogen be bonded to for hydrogen bonding in this course?", "Nitrogen, oxygen, or fluorine.", "foundation", "short"],
      ["What is enthalpy change?", "The heat energy transferred by a process at constant pressure.", "foundation", "explain"],
      ["What is entropy?", "A measure of the dispersal of energy and matter, often described as the number of possible particle arrangements.", "foundation", "explain"],
      ["What sign does ΔH have for an exothermic reaction?", "Negative, because heat is released by the system.", "foundation", "short"],
      ["What is standard enthalpy of formation?", "The enthalpy change when one mole of a compound forms from its elements in their standard states.", "foundation", "explain"],
      // Core (16)
      ["Write the electron configuration of a calcium atom.", "1s² 2s² 2p⁶ 3s² 3p⁶ 4s².", "core", "short"],
      ["Why are 4s electrons removed before 3d electrons when a transition-metal ion forms?", "Once the 3d sublevel is occupied, the 4s electrons are higher in energy and are removed first.", "core", "explain"],
      ["Why does atomic radius generally decrease across a period?", "Nuclear charge increases while added electrons enter the same main shell, so stronger attraction pulls the electron cloud closer.", "core", "explain"],
      ["Why does first ionisation energy generally decrease down a group?", "The outer electron is farther from the nucleus and more shielded, so nuclear attraction is weaker.", "core", "explain"],
      ["Why is a cation smaller than its neutral atom?", "Electron loss reduces repulsion and may remove an outer shell, while the same nuclear charge attracts fewer electrons.", "core", "explain"],
      ["Why is an anion larger than its neutral atom?", "Added electrons increase electron-electron repulsion while nuclear charge is unchanged, expanding the electron cloud.", "core", "explain"],
      ["How does VSEPR theory predict molecular shape?", "Electron regions around a central atom repel and arrange as far apart as possible; lone pairs repel more strongly than bonding pairs.", "core", "explain"],
      ["What shape results from five bonding regions and no lone pairs?", "Trigonal bipyramidal, with 90° and 120° bond angles.", "core", "short"],
      ["What shape results from six bonding regions and no lone pairs?", "Octahedral, with 90° bond angles.", "core", "short"],
      ["Why can a molecule with polar bonds be non-polar overall?", "A symmetrical arrangement can make the bond dipoles cancel to give no net molecular dipole.", "core", "explain"],
      ["Why does water have a higher boiling point than hydrogen sulfide?", "Water forms stronger hydrogen bonds, so more energy is required to separate its molecules.", "core", "explain"],
      ["Why does increasing molar mass often raise the boiling point of non-polar molecules?", "Larger, more polarisable electron clouds produce stronger temporary dipole attractions.", "core", "explain"],
      ["How do enthalpy and entropy changes influence spontaneity?", "A reaction is favoured by a negative enthalpy change and a positive entropy change; when they oppose, temperature affects which factor dominates.", "core", "explain"],
      ["Write the calorimetry relationship used in this standard.", "q = mcΔT.", "core", "short"],
      ["What does Hess's law state?", "The total enthalpy change depends only on initial and final states, not on the pathway taken.", "core", "explain"],
      ["Write the equation used to calculate reaction enthalpy from formation enthalpies.", "ΔrH° = ΣΔfH°(products) − ΣΔfH°(reactants), including stoichiometric coefficients.", "core", "short"],
      // Stretch (12)
      ["Explain the first-ionisation-energy difference between magnesium and aluminium.", "Aluminium's removed electron is in the higher-energy, more shielded 3p sublevel, whereas magnesium loses a 3s electron, so aluminium's value is lower.", "stretch", "explain"],
      ["Compare the radii of Na⁺ and F⁻, which are isoelectronic.", "Na⁺ is smaller because its 11 protons attract the same 10 electrons more strongly than the 9 protons in F⁻.", "stretch", "explain"],
      ["Explain why SF₄ is polar.", "Five electron regions give a trigonal-bipyramidal arrangement; one is a lone pair, producing a seesaw shape whose S–F bond dipoles do not cancel.", "stretch", "explain"],
      ["Explain why graphite conducts electricity but diamond does not.", "Graphite has one delocalised electron per carbon mobile within layers; all four valence electrons in diamond are localised in covalent bonds.", "stretch", "explain"],
      ["Link bonding, entropy, and solubility when an ionic solid dissolves.", "Dissolving is favoured when ion-water attractions and increased dispersal of ions compensate for energy needed to separate lattice ions and water molecules.", "stretch", "explain"],
      ["A 100.0 g solution warms by 6.5°C. Calculate heat absorbed using c = 4.18 J g⁻¹ °C⁻¹.", "q = 100.0 × 4.18 × 6.5 = 2.72 × 10³ J, or 2.72 kJ.", "stretch", "short"],
      ["A reaction releases 2.72 kJ when 0.0500 mol reacts. Calculate ΔrH.", "ΔrH = −2.72/0.0500 = −54.4 kJ mol⁻¹.", "stretch", "short"],
      ["Why must the heat gained by solution have the opposite sign to the reaction enthalpy?", "Energy is conserved: heat released by the reaction is absorbed by the surroundings, and vice versa.", "stretch", "explain"],
      ["How does reversing and multiplying a thermochemical equation affect ΔH?", "Reversing changes the sign of ΔH; multiplying all coefficients multiplies ΔH by the same factor.", "stretch", "explain"],
      ["Why is vaporisation endothermic and associated with increased entropy?", "Energy is absorbed to overcome attractions, and gas particles have many more accessible positions and energy arrangements than liquid particles.", "stretch", "explain"],
      ["Predict spontaneity when ΔH is positive and ΔS is negative.", "The process is non-spontaneous at all temperatures because both energy and entropy changes oppose it.", "stretch", "explain"],
      ["Explain why a process with positive ΔH and positive ΔS may become spontaneous at high temperature.", "At higher temperature the favourable entropy contribution becomes more important and can outweigh the unfavourable enthalpy change.", "stretch", "explain"],
    ],
    [
      ["What sublevel holds a maximum of two electrons?", "s sublevel", "foundation"],
      ["What sublevel holds a maximum of six electrons?", "p sublevel", "foundation"],
      ["What sublevel holds a maximum of ten electrons?", "d sublevel", "foundation"],
      ["What region can hold two electrons with opposite spin?", "Orbital", "foundation"],
      ["What property measures attraction for bonding electrons?", "Electronegativity", "foundation"],
      ["What energy removes an electron from a gaseous atom?", "Ionisation energy", "foundation"],
      ["What attraction arises from momentary electron movement?", "Temporary dipole attraction", "foundation"],
      ["What attraction acts between polar molecules?", "Permanent dipole attraction", "foundation"],
      ["What strong intermolecular attraction involves H bonded to N, O, or F?", "Hydrogen bonding", "foundation"],
      ["What symbol represents enthalpy change?", "ΔH", "foundation"],
      ["What measure describes energy and matter dispersal?", "Entropy", "foundation"],
      ["What law makes enthalpy change independent of pathway?", "Hess's law", "foundation"],
      ["What notation is used for the standard enthalpy of formation?", "ΔfH°", "core"],
      ["What notation is used for the standard enthalpy of combustion?", "ΔcH°", "core"],
      ["What notation is used for the standard enthalpy of reaction?", "ΔrH°", "core"],
      ["What notation is used for enthalpy of fusion?", "ΔfusH°", "core"],
      ["What notation is used for enthalpy of vaporisation?", "ΔvapH°", "core"],
      ["What notation is used for enthalpy of sublimation?", "ΔsubH°", "core"],
      ["What equation links heat, mass, heat capacity, and temperature change?", "q = mcΔT", "core"],
      ["What theory predicts shape from electron-region repulsion?", "VSEPR theory", "core"],
      ["What five-region shape has no lone pairs?", "Trigonal bipyramidal", "core"],
      ["What six-region shape has no lone pairs?", "Octahedral", "core"],
      ["What term describes equal-electron species?", "Isoelectronic", "core"],
      ["What generally increases down a group: atomic radius or ionisation energy?", "Atomic radius", "core"],
      ["What generally increases across a period: electronegativity or atomic radius?", "Electronegativity", "core"],
      ["What particle is smaller than its parent atom after electron loss?", "Cation", "core"],
      ["What particle is larger than its parent atom after electron gain?", "Anion", "core"],
      ["What type of molecule has a net dipole?", "Polar molecule", "core"],
      ["What factor reflects ease of distorting an electron cloud?", "Polarisability", "stretch"],
      ["What standard-state enthalpy forms one mole of compound from its elements?", "Formation enthalpy", "stretch"],
      ["What process changes a solid directly to a gas?", "Sublimation", "stretch"],
      ["What process changes a liquid to a gas?", "Vaporisation", "stretch"],
      ["What process changes a solid to a liquid?", "Fusion", "stretch"],
      ["What sign of ΔH favours spontaneity?", "Negative", "stretch"],
      ["What sign of ΔS favours spontaneity?", "Positive", "stretch"],
      ["What force holds positive metal ions to delocalised electrons?", "Metallic bonding", "stretch"],
      ["What structure gives graphite mobile electrons within layers?", "Delocalised system", "stretch"],
      ["What quantity must be conserved across a calorimetry energy transfer?", "Energy", "stretch"],
      ["What shell electrons are removed first from transition-metal atoms?", "4s electrons", "stretch"],
      ["What charge effect pulls electrons closer across a period?", "Increasing nuclear charge", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-chem-organic",
      name: "Properties of Organic Compounds",
      course: "Chemistry",
      standard: "AS 91391",
      strand: "Chemistry",
      keywords: [
        "aldehyde", "ketone", "ester", "triglyceride", "acyl chloride", "amide", "amine", "stereoisomer",
        "enantiomer", "chiral carbon", "plane-polarised light", "nucleophilic substitution", "esterification",
        "condensation", "hydrolysis", "oxidation", "reduction", "Tollens reagent", "Benedict reagent",
        "polyester", "polyamide", "peptide bond", "elimination", "addition", "solubility", "boiling point",
      ],
    },
    [
      // Foundation (12)
      ["What functional group identifies an aldehyde?", "A terminal carbonyl group written as -CHO.", "foundation", "short"],
      ["What functional group identifies a ketone?", "A carbonyl group, C=O, bonded to two carbon groups.", "foundation", "short"],
      ["What functional group identifies an ester?", "The -COO- linkage between two carbon groups.", "foundation", "short"],
      ["What functional group identifies an amide?", "A carbonyl carbon bonded to nitrogen, such as -CONH₂.", "foundation", "short"],
      ["What is an acyl chloride?", "A compound containing the -COCl functional group.", "foundation", "explain"],
      ["What is a stereoisomer?", "A compound with the same atom connectivity as another but a different three-dimensional arrangement.", "foundation", "explain"],
      ["What is a chiral carbon?", "A tetrahedral carbon atom bonded to four different groups.", "foundation", "explain"],
      ["What are enantiomers?", "Non-superimposable mirror-image stereoisomers.", "foundation", "explain"],
      ["What reagent reduces aldehydes and ketones?", "Sodium borohydride, NaBH₄.", "foundation", "short"],
      ["What product forms when a carboxylic acid reacts with an alcohol under acid catalysis?", "An ester and water.", "foundation", "short"],
      ["What linkage joins amino acids in a protein?", "An amide or peptide bond.", "foundation", "short"],
      ["What type of reaction forms a polymer while releasing a small molecule?", "Condensation polymerisation.", "foundation", "short"],
      // Core (16)
      ["How does Tollens' reagent distinguish an aldehyde from a ketone?", "An aldehyde is oxidised and produces a silver mirror; a ketone gives no reaction under these conditions.", "core", "explain"],
      ["What observation occurs when an aldehyde reacts with Benedict's or Fehling's reagent?", "The blue solution forms a brick-red or orange copper(I) oxide precipitate on warming.", "core", "short"],
      ["What products form when a primary alcohol is oxidised in controlled and then stronger conditions?", "It first forms an aldehyde and can be further oxidised to a carboxylic acid.", "core", "explain"],
      ["What product forms when a secondary alcohol is oxidised?", "A ketone.", "core", "short"],
      ["Why does a tertiary alcohol resist oxidation under normal test conditions?", "Its carbon bearing -OH has no hydrogen that can be removed without breaking a carbon-carbon bond.", "core", "explain"],
      ["State the products formed when NaBH₄ reacts with an aldehyde and with a ketone.", "An aldehyde is reduced to a primary alcohol; a ketone is reduced to a secondary alcohol.", "core", "explain"],
      ["How does SOCl₂ react with an alcohol?", "It substitutes chlorine for the hydroxyl group, forming a haloalkane and gaseous SO₂ and HCl.", "core", "explain"],
      ["How does an acyl chloride react with water?", "It hydrolyses rapidly to a carboxylic acid and HCl.", "core", "explain"],
      ["How does an acyl chloride react with a primary amine?", "Nucleophilic substitution forms a substituted amide and an amine salt or HCl-derived product.", "core", "explain"],
      ["How is an ester hydrolysed in acidic conditions?", "Reversible hydrolysis with water forms a carboxylic acid and an alcohol.", "core", "explain"],
      ["How is ester hydrolysis different in basic conditions?", "Hydroxide produces an alcohol and a carboxylate salt, making the reaction effectively irreversible.", "core", "explain"],
      ["How does a triglyceride form?", "Glycerol forms three ester bonds with three fatty acids in condensation reactions, releasing three water molecules.", "core", "explain"],
      ["State the monomer features needed to make a polyester.", "Monomers need two reactive groups overall, typically a diol and a dicarboxylic acid or acyl chloride.", "core", "explain"],
      ["State the monomer features needed to make a polyamide.", "Monomers need two reactive groups overall, typically a diamine and a dicarboxylic acid or acyl chloride.", "core", "explain"],
      ["Why do carboxylic acids generally boil at higher temperatures than similar-sized aldehydes?", "Carboxylic acids form strong hydrogen-bonded pairs, while aldehydes mainly have permanent and temporary dipole attractions.", "core", "explain"],
      ["How does increasing hydrocarbon-chain length affect water solubility?", "Solubility generally decreases because the non-polar region becomes larger relative to polar functional groups.", "core", "explain"],
      // Stretch (12)
      ["Explain why enantiomers rotate plane-polarised light in opposite directions.", "Their mirror-image three-dimensional arrangements interact differently with plane-polarised light, producing equal and opposite rotations.", "stretch", "explain"],
      ["Why does a racemic mixture show no net optical rotation?", "It contains equal amounts of two enantiomers whose opposite rotations cancel.", "stretch", "explain"],
      ["Design a two-test sequence to distinguish an alkene, aldehyde, and ketone.", "Use bromine solution to identify the alkene by decolourisation, then Tollens', Fehling's, or Benedict's reagent to identify the aldehyde; the remaining carbonyl is the ketone.", "stretch", "explain"],
      ["Explain why acyl chlorides are more reactive than carboxylic acids in substitution reactions.", "The carbonyl carbon is strongly electron-poor and chloride is a good leaving group, so nucleophilic substitution occurs readily.", "stretch", "explain"],
      ["Compare acid and base hydrolysis of an amide.", "Acid hydrolysis forms a carboxylic acid and an ammonium species; base hydrolysis forms a carboxylate salt and ammonia or an amine.", "stretch", "explain"],
      ["Why can an asymmetric elimination produce major and minor alkene products?", "Hydrogen can be removed from different adjacent carbons; the more substituted alkene is usually favoured as the more stable product.", "stretch", "explain"],
      ["Explain why a polyamide can have a high melting point.", "Many amide groups form hydrogen bonds between chains, so substantial energy is needed to separate the chains.", "stretch", "explain"],
      ["Link protein primary structure to condensation polymerisation.", "Amino acids join in a specific sequence by peptide bonds, with water released for each bond; the sequence is the protein's primary structure.", "stretch", "explain"],
      ["Explain why trans fats can pack more closely than cis fats.", "Trans double bonds leave chains more linear, allowing stronger intermolecular contact and often a higher melting point than kinked cis chains.", "stretch", "explain"],
      ["How can reaction observations identify an unknown containing two functional groups?", "A combination of positive and negative tests must be linked to each group's reactivity, while accounting for one group altering the conditions or products of another.", "stretch", "explain"],
      ["Explain how structure links to both boiling point and solubility for an amide.", "The polar amide group forms hydrogen bonds, raising boiling point and promoting water solubility; a longer non-polar carbon chain reduces the solubility effect.", "stretch", "explain"],
      ["Why must an organic reaction scheme conserve every carbon atom?", "Atoms are rearranged rather than created or destroyed, so the carbon skeleton and any carbon-containing reagent products must be tracked through each step.", "stretch", "explain"],
    ],
    [
      ["What terminal carbonyl functional group is written -CHO?", "Aldehyde", "foundation"],
      ["What internal carbonyl functional group is bonded to two carbons?", "Ketone", "foundation"],
      ["What functional group contains -COO- between carbon groups?", "Ester", "foundation"],
      ["What functional group contains -COCl?", "Acyl chloride", "foundation"],
      ["What functional group contains a carbonyl bonded to nitrogen?", "Amide", "foundation"],
      ["What lipid contains glycerol joined to three fatty acids?", "Triglyceride", "foundation"],
      ["What carbon is bonded to four different groups?", "Chiral carbon", "foundation"],
      ["What mirror-image stereoisomers cannot be superimposed?", "Enantiomers", "foundation"],
      ["What reagent reduces aldehydes and ketones?", "NaBH₄", "foundation"],
      ["What reagent can produce a silver mirror with an aldehyde?", "Tollens' reagent", "foundation"],
      ["What linkage joins amino acids?", "Peptide bond", "foundation"],
      ["What polymer forms from amino acids?", "Protein", "foundation"],
      ["What product forms when a primary alcohol is mildly oxidised?", "Aldehyde", "core"],
      ["What product forms when a secondary alcohol is oxidised?", "Ketone", "core"],
      ["What product forms when an aldehyde is reduced?", "Primary alcohol", "core"],
      ["What product forms when a ketone is reduced?", "Secondary alcohol", "core"],
      ["What gaseous reagent converts an alcohol to a haloalkane while releasing SO₂ and HCl?", "Thionyl chloride", "core"],
      ["What reaction joins a carboxylic acid and alcohol?", "Esterification", "core"],
      ["What reaction splits a compound using water?", "Hydrolysis", "core"],
      ["What reaction joins monomers and releases a small molecule?", "Condensation", "core"],
      ["What polymer linkage is -COO-?", "Ester linkage", "core"],
      ["What polymer linkage is -CONH-?", "Amide linkage", "core"],
      ["What reagent oxidises an aldehyde to form a red copper(I) oxide precipitate?", "Benedict's reagent", "core"],
      ["What type of isomer has different atom connectivity?", "Constitutional isomer", "core"],
      ["What type of isomer has the same connectivity but different 3D arrangement?", "Stereoisomer", "core"],
      ["What mixture contains equal amounts of two enantiomers?", "Racemic mixture", "core"],
      ["What light is rotated by a chiral substance?", "Plane-polarised light", "core"],
      ["What base condition favours haloalkane elimination?", "Alcoholic KOH", "core"],
      ["What reaction of an acyl chloride with an amine forms an amide?", "Nucleophilic substitution", "stretch"],
      ["What ion forms when an amide is hydrolysed in base?", "Carboxylate ion", "stretch"],
      ["What acid-catalysed reaction reverses esterification?", "Acid hydrolysis", "stretch"],
      ["What irreversible ester-cleavage reaction produces a carboxylate salt?", "Base hydrolysis", "stretch"],
      ["What test reagent also contains copper(II) ions and identifies aldehydes?", "Fehling's reagent", "stretch"],
      ["What reagent oxidises primary alcohols from orange to green?", "Acidified dichromate", "stretch"],
      ["What reagent oxidises suitable compounds while losing its purple colour?", "Acidified permanganate", "stretch"],
      ["What polymer forms from diols and dicarboxylic acids?", "Polyester", "stretch"],
      ["What polymer forms from diamines and dicarboxylic acids?", "Polyamide", "stretch"],
      ["What do we call the arrangement with groups on opposite sides of C=C?", "Trans", "stretch"],
      ["What do we call the arrangement with groups on the same side of C=C?", "Cis", "stretch"],
      ["What product is favoured in many asymmetric eliminations?", "More substituted alkene", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-chem-aqueous-equilibrium",
      name: "Equilibrium Principles in Aqueous Systems",
      course: "Chemistry",
      standard: "AS 91392",
      strand: "Chemistry",
      keywords: [
        "Brønsted-Lowry acid", "conjugate pair", "Ka", "pKa", "Kw", "strong acid", "weak acid", "buffer",
        "common ion", "titration curve", "equivalence point", "indicator", "solubility product", "Ks",
        "precipitation", "sparingly soluble", "complex ion", "conductivity", "hydronium", "hydroxide",
      ],
    },
    [
      // Foundation (12)
      ["What is a Brønsted-Lowry acid?", "A proton donor.", "foundation", "short"],
      ["What is a Brønsted-Lowry base?", "A proton acceptor.", "foundation", "short"],
      ["What is a conjugate acid-base pair?", "Two species that differ by one proton.", "foundation", "explain"],
      ["What is the difference between a strong and weak acid?", "A strong acid reacts essentially completely with water; a weak acid establishes an equilibrium and reacts only partially.", "foundation", "explain"],
      ["What does a larger Ka indicate?", "A stronger acid and a greater extent of proton donation in water.", "foundation", "explain"],
      ["How are pKa and acid strength related?", "A lower pKa corresponds to a stronger acid.", "foundation", "explain"],
      ["Write the relationship between pH and hydronium concentration.", "pH = −log[H₃O⁺].", "foundation", "short"],
      ["What is a buffer?", "A solution containing a weak acid-base conjugate pair that resists pH change when small amounts of acid or base are added.", "foundation", "explain"],
      ["What is the equivalence point of a titration?", "The point where reactants have been mixed in their stoichiometric mole ratio.", "foundation", "explain"],
      ["What is a sparingly soluble ionic solid?", "An ionic solid that dissolves only to a small extent and establishes a dissolution equilibrium.", "foundation", "explain"],
      ["What does Ks describe?", "The equilibrium constant for dissolution of a sparingly soluble ionic solid.", "foundation", "explain"],
      ["What is a precipitate?", "An insoluble or sparingly soluble solid formed from ions in solution.", "foundation", "explain"],
      // Core (16)
      ["Write the acid-ionisation expression for HA in water.", "Ka = [H₃O⁺][A⁻]/[HA].", "core", "short"],
      ["Write the relationship linking Ka, Kb, and Kw, then rearrange it for Kb.", "KaKb = Kw, so Kb = Kw/Ka.", "core", "short"],
      ["Calculate [H₃O⁺] in a solution with pH 3.40.", "[H₃O⁺] = 10⁻³·⁴⁰ = 3.98 × 10⁻⁴ mol L⁻¹.", "core", "short"],
      ["Why can two acid solutions with the same concentration have different pH values?", "Different acid strengths produce different extents of reaction with water and therefore different hydronium concentrations.", "core", "explain"],
      ["Why can a weak acid solution still conduct electricity?", "Partial ionisation produces mobile ions, although fewer than in an equally concentrated strong acid.", "core", "explain"],
      ["How does adding a common conjugate base affect a weak acid equilibrium?", "It shifts the equilibrium toward the weak acid, reducing ionisation and hydronium concentration.", "core", "explain"],
      ["How does an HA/A⁻ buffer remove added H₃O⁺?", "A⁻ accepts the added proton to form HA, so most added hydronium is consumed.", "core", "explain"],
      ["How does an HA/A⁻ buffer remove added OH⁻?", "HA donates a proton to OH⁻, forming water and A⁻.", "core", "explain"],
      ["At what condition does pH equal pKa in a weak-acid buffer?", "When [HA] equals [A⁻], such as at half-equivalence in a weak-acid/strong-base titration.", "core", "explain"],
      ["Why is the equivalence point above pH 7 for a weak-acid/strong-base titration?", "The conjugate base present at equivalence reacts with water to form OH⁻.", "core", "explain"],
      ["How should an indicator be selected for a titration?", "Its transition range must lie within the steep pH change near the equivalence point.", "core", "explain"],
      ["Write the Ks expression for AB(s) ⇌ A⁺ + B⁻.", "Ks = [A⁺][B⁻].", "core", "short"],
      ["Write the Ks expression for A₂B(s) ⇌ 2A⁺ + B²⁻.", "Ks = [A⁺]²[B²⁻].", "core", "short"],
      ["How does a common ion affect the solubility of a sparingly soluble salt?", "It shifts dissolution equilibrium toward the solid, decreasing molar solubility.", "core", "explain"],
      ["When is precipitation predicted using an ion product?", "When the ion product exceeds Ks.", "core", "short"],
      ["How can complex-ion formation increase solubility?", "It removes a free dissolved ion, shifting the dissolution equilibrium toward more dissolved salt.", "core", "explain"],
      // Stretch (12)
      ["Estimate the pH of 0.100 mol L⁻¹ CH₃COOH when Ka = 1.8 × 10⁻⁵.", "[H₃O⁺] ≈ √(KaC) = √(1.8 × 10⁻⁶) = 1.34 × 10⁻³ mol L⁻¹, so pH ≈ 2.87.", "stretch", "short"],
      ["Explain why the approximation [HA]eq ≈ [HA]initial is often valid for a weak acid.", "Only a small fraction ionises, so the decrease in weak-acid concentration is negligible relative to its initial concentration.", "stretch", "explain"],
      ["Compare pH and conductivity of equal-concentration strong and weak acids.", "The strong acid has greater ion concentration, so it has lower pH and higher conductivity than the weak acid.", "stretch", "explain"],
      ["Explain why dilution raises the percentage ionisation of a weak acid but lowers [H₃O⁺].", "Equilibrium shifts toward more ions after dilution, increasing the fraction ionised, but all species are diluted so the absolute hydronium concentration falls.", "stretch", "explain"],
      ["Why does a buffer have its greatest capacity near pH = pKa?", "Comparable amounts of weak acid and conjugate base are available to consume added base and acid.", "stretch", "explain"],
      ["Explain the main regions of a weak-acid/strong-base titration curve.", "It begins acidic, passes through a buffer region and half-equivalence, rises steeply near equivalence above pH 7, then is controlled by excess strong base.", "stretch", "explain"],
      ["A salt AB has Ks = 4.0 × 10⁻¹⁰. Calculate its molar solubility in pure water.", "For AB, Ks = s², so s = √(4.0 × 10⁻¹⁰) = 2.0 × 10⁻⁵ mol L⁻¹.", "stretch", "short"],
      ["A salt A₂B has molar solubility s. Express Ks in terms of s.", "[A⁺] = 2s and [B²⁻] = s, so Ks = (2s)²(s) = 4s³.", "stretch", "short"],
      ["How can added acid increase the solubility of a salt containing a basic anion?", "The acid consumes the anion, lowering its free concentration and shifting dissolution toward more ions.", "stretch", "explain"],
      ["Explain why adding NH₃ can first precipitate and then redissolve some metal hydroxides.", "NH₃ can produce OH⁻ and precipitate the hydroxide; in excess it may form a stable soluble complex that lowers free metal-ion concentration and dissolves the solid.", "stretch", "explain"],
      ["Why must equilibrium concentrations rather than initial concentrations be used in Ka and Ks expressions?", "Equilibrium constants relate species concentrations after forward and reverse processes have reached equilibrium.", "stretch", "explain"],
      ["Link pH, equilibrium, and indicator colour in a titration.", "Titration changes the dominant acid-base species and hydronium concentration; an indicator equilibrium shifts over its transition range, changing the observed colour near equivalence.", "stretch", "explain"],
    ],
    [
      ["What species donates a proton?", "Acid", "foundation"],
      ["What species accepts a proton?", "Base", "foundation"],
      ["What pair differs by one proton?", "Conjugate pair", "foundation"],
      ["What constant measures weak-acid ionisation?", "Ka", "foundation"],
      ["What logarithmic quantity is −logKa?", "pKa", "foundation"],
      ["What ion determines acidity in water?", "Hydronium ion", "foundation"],
      ["What ion determines alkalinity in water?", "Hydroxide ion", "foundation"],
      ["What solution resists small pH changes?", "Buffer", "foundation"],
      ["What point has stoichiometrically equivalent acid and base amounts?", "Equivalence point", "foundation"],
      ["What coloured weak acid-base pair signals a pH range?", "Indicator", "foundation"],
      ["What solid forms when ion concentrations exceed solubility limits?", "Precipitate", "foundation"],
      ["What constant describes a sparingly soluble salt equilibrium?", "Ks", "foundation"],
      ["What relationship links water's ion concentrations at 25°C?", "Kw", "core"],
      ["What effect reduces weak-acid ionisation when its salt is added?", "Common-ion effect", "core"],
      ["What titration region contains appreciable weak acid and conjugate base?", "Buffer region", "core"],
      ["What titration point has equal weak acid and conjugate base concentrations?", "Half-equivalence point", "core"],
      ["What quantity measures a solution's ability to carry current?", "Conductivity", "core"],
      ["What acid type ionises essentially completely?", "Strong acid", "core"],
      ["What acid type establishes a partial-ionisation equilibrium?", "Weak acid", "core"],
      ["What base type reacts essentially completely with water or dissociates fully?", "Strong base", "core"],
      ["What base type reacts only partially with water?", "Weak base", "core"],
      ["What expression predicts precipitation by comparison with Ks?", "Ion product", "core"],
      ["What term means moles of solute dissolved per litre at saturation?", "Molar solubility", "core"],
      ["What ion already present suppresses salt dissolution?", "Common ion", "core"],
      ["What charged coordination species can increase metal-salt solubility?", "Complex ion", "core"],
      ["What ligand forms complexes with several transition-metal ions?", "Ammonia", "core"],
      ["What curve plots pH against titrant volume?", "Titration curve", "core"],
      ["What pH range should overlap a titration's steep region?", "Indicator range", "core"],
      ["What approximation treats equilibrium weak-acid concentration as its initial value?", "Small-change approximation", "stretch"],
      ["What salt formula gives Ks = s² in pure water?", "AB", "stretch"],
      ["What salt formula gives Ks = 4s³ in pure water?", "A₂B", "stretch"],
      ["What happens when ion product is less than Ks?", "No precipitation", "stretch"],
      ["What happens when ion product equals Ks?", "Saturation", "stretch"],
      ["What happens when ion product exceeds Ks?", "Precipitation", "stretch"],
      ["What acid-base system is excluded from Level 3 titration curves?", "Weak acid–weak base", "stretch"],
      ["What acid is the conjugate acid of NH₃?", "NH₄⁺", "stretch"],
      ["What base is the conjugate base of CH₃COOH?", "CH₃COO⁻", "stretch"],
      ["What equation converts pH to hydronium concentration?", "[H₃O⁺] = 10⁻pH", "stretch"],
      ["What reaction can remove a basic anion and increase salt solubility?", "Protonation", "stretch"],
      ["What process removes free metal ions by binding ligands?", "Complex formation", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-physics-mechanics",
      name: "Mechanical Systems",
      course: "Physics",
      standard: "AS 91524",
      strand: "Physics",
      keywords: [
        "centre of mass", "momentum", "impulse", "two dimensions", "circular motion", "centripetal acceleration",
        "gravitation", "satellite", "angular displacement", "angular velocity", "angular acceleration", "torque",
        "rotational inertia", "angular momentum", "rotational kinetic energy", "simple harmonic motion",
        "angular frequency", "phasor", "damping", "driving", "resonance", "energy conservation",
      ],
    },
    [
      // Foundation (12)
      ["What is the centre of mass of a system?", "The point at which the system's mass can be treated as concentrated when analysing translational motion.", "foundation", "explain"],
      ["Why is momentum a vector?", "It has both magnitude and direction because p = mv and velocity is a vector.", "foundation", "explain"],
      ["Define impulse and write two equivalent relationships for it.", "The change in momentum produced by a net force acting over a time interval: J = FΔt = Δp.", "foundation", "explain"],
      ["What is angular displacement?", "The angle through which an object rotates, measured in radians.", "foundation", "explain"],
      ["Define angular velocity and write its equation.", "The rate of change of angular displacement: ω = Δθ/Δt.", "foundation", "explain"],
      ["Define angular acceleration and write its equation.", "The rate of change of angular velocity: α = Δω/Δt.", "foundation", "explain"],
      ["Define torque and write its equation using perpendicular distance from the axis.", "The turning effect of a force about an axis: τ = Fr⊥.", "foundation", "explain"],
      ["What is rotational inertia?", "A measure of an object's resistance to angular acceleration, determined by its mass distribution about the axis.", "foundation", "explain"],
      ["For a rigid body, define angular momentum and state when it is conserved.", "The rotational quantity L = Iω for a rigid body, conserved when external torque is zero.", "foundation", "explain"],
      ["What condition defines simple harmonic motion?", "Acceleration is proportional to displacement from equilibrium and directed toward equilibrium: a = −ω²y.", "foundation", "explain"],
      ["Write the equation linking angular frequency and frequency.", "ω = 2πf.", "foundation", "short"],
      ["What is resonance?", "A large-amplitude response when a periodic driving frequency is at or near a system's natural frequency.", "foundation", "explain"],
      // Core (16)
      ["Write the equation for the centre-of-mass position along one dimension.", "xcm = Σmixi/Σmi.", "core", "short"],
      ["How is momentum conserved in a two-dimensional collision?", "The vector sum of momentum is conserved independently in the x and y directions when external impulse is negligible.", "core", "explain"],
      ["Why does increasing collision time reduce average impact force for the same momentum change?", "Faverage = Δp/Δt, so a longer stopping time gives a smaller average force.", "core", "explain"],
      ["What provides centripetal force?", "The inward resultant of real forces such as tension, gravity, friction, or normal force; it is not an extra force.", "core", "explain"],
      ["Write the relationships for circular acceleration and force.", "ac = v²/r = rω² and Fc = mv²/r = mrω².", "core", "short"],
      ["Write Newton's law of universal gravitation.", "F = GMm/r².", "core", "short"],
      ["Why does an orbiting satellite continually fall without hitting Earth?", "Gravity accelerates it inward while its tangential velocity carries it around Earth's curved surface.", "core", "explain"],
      ["Write the equation linking linear speed and angular speed.", "v = rω.", "core", "short"],
      ["Write the equation linking tangential acceleration and angular acceleration.", "at = rα.", "core", "short"],
      ["Write one constant-angular-acceleration equation.", "For example, ωf = ωi + αt.", "core", "short"],
      ["Write the equation linking net torque, rotational inertia, and angular acceleration.", "τnet = Iα.", "core", "short"],
      ["Write the rotational kinetic-energy relationship.", "EK(rot) = ½Iω².", "core", "short"],
      ["Why does pulling mass toward the rotation axis increase angular speed?", "With negligible external torque, angular momentum Iω is conserved; reducing I requires ω to increase.", "core", "explain"],
      ["In SHM, state where speed is greatest, where acceleration magnitude is greatest, and the direction of acceleration.", "Velocity is greatest at equilibrium; acceleration magnitude is greatest at the extremes and always points toward equilibrium.", "core", "explain"],
      ["Write the period equations for a simple pendulum and mass-spring system.", "Pendulum: T = 2π√(l/g). Spring: T = 2π√(m/k).", "core", "short"],
      ["What does damping do to an oscillator?", "It removes mechanical energy, causing amplitude to decrease with time.", "core", "explain"],
      // Stretch (12)
      ["Two masses, 2.0 kg at x = 0 and 3.0 kg at x = 4.0 m, form a system. Calculate the centre-of-mass position, xcm.", "xcm = (2.0×0 + 3.0×4.0)/(5.0) = 2.4 m.", "stretch", "short"],
      ["A 0.20 kg ball moving east at 8.0 m s⁻¹ rebounds west at 6.0 m s⁻¹. Calculate the magnitude and direction of its impulse.", "Taking east positive, Δp = 0.20(−6.0 − 8.0) = −2.8 N s, or 2.8 N s west.", "stretch", "short"],
      ["Explain how to solve a two-dimensional momentum problem.", "Choose perpendicular axes, resolve every momentum vector into components, apply conservation separately on each axis, then recombine components for unknown magnitude and direction.", "stretch", "explain"],
      ["Derive the orbital-speed relationship for a circular satellite orbit.", "Set gravity equal to centripetal force: GMm/r² = mv²/r, giving v = √(GM/r).", "stretch", "explain"],
      ["Why does a higher circular orbit have a lower orbital speed and longer period?", "Weaker gravity at larger r requires lower v, while the satellite also travels a larger circumference, so its period increases.", "stretch", "explain"],
      ["A wheel starts from rest with α = 3.0 rad s⁻² for 4.0 s. Calculate its final angular velocity and angular displacement.", "ω = αt = 12 rad s⁻¹; θ = ½αt² = 24 rad.", "stretch", "short"],
      ["A 6.0 N tangential force acts 0.25 m from an axis on a wheel with I = 0.50 kg m². Calculate the angular acceleration.", "τ = Fr = 1.50 N m, so α = τ/I = 3.0 rad s⁻².", "stretch", "short"],
      ["Explain why redistributing mass outward increases rotational kinetic energy at fixed angular speed.", "Moving mass outward increases I, so EK(rot) = ½Iω² increases if ω is maintained by an external energy supply.", "stretch", "explain"],
      ["How does a phasor diagram represent SHM?", "Uniform circular motion of a reference vector is projected onto an axis; the projection gives displacement, with phase locating the oscillator in its cycle.", "stretch", "explain"],
      ["An SHM oscillator has amplitude 0.080 m and ω = 5.0 rad s⁻¹. Calculate its maximum speed and maximum acceleration.", "vmax = Aω = 0.40 m s⁻¹; amax = Aω² = 2.0 m s⁻².", "stretch", "short"],
      ["Explain the energy changes during one SHM cycle.", "Energy alternates between kinetic energy, greatest at equilibrium, and potential energy, greatest at the extremes; total energy is constant if undamped.", "stretch", "explain"],
      ["Why can resonance be dangerous in a weakly damped structure?", "Driving adds energy in phase each cycle, so amplitude can grow until stresses exceed structural limits.", "stretch", "explain"],
    ],
    [
      ["What point represents the average position of a system's mass?", "Centre of mass", "foundation"],
      ["What vector quantity equals mass times velocity?", "Momentum", "foundation"],
      ["What quantity equals force multiplied by time?", "Impulse", "foundation"],
      ["What angular unit is used in rotational equations?", "Radian", "foundation"],
      ["What symbol represents angular displacement?", "θ", "foundation"],
      ["What symbol represents angular velocity?", "ω", "foundation"],
      ["What symbol represents angular acceleration?", "α", "foundation"],
      ["What turning effect is measured in newton metres?", "Torque", "foundation"],
      ["What rotational property is symbolised by I?", "Rotational inertia", "foundation"],
      ["What rotational quantity is L = Iω?", "Angular momentum", "foundation"],
      ["What motion has a = −ω²y?", "Simple harmonic motion", "foundation"],
      ["What large response occurs at the natural frequency?", "Resonance", "foundation"],
      ["What force direction is required for uniform circular motion?", "Inward", "core"],
      ["What acceleration points toward the centre of a circle?", "Centripetal acceleration", "core"],
      ["What force governs satellite orbit around Earth?", "Gravity", "core"],
      ["What constant appears in F = GMm/r²?", "Gravitational constant", "core"],
      ["What equation links tangential and angular speed?", "v = rω", "core"],
      ["What equation links tangential and angular acceleration?", "at = rα", "core"],
      ["What equation links net torque and angular acceleration?", "τ = Iα", "core"],
      ["What energy equals ½Iω²?", "Rotational kinetic energy", "core"],
      ["What quantity is conserved when external torque is zero?", "Angular momentum", "core"],
      ["What SHM quantity is greatest at equilibrium?", "Speed", "core"],
      ["What SHM quantity is greatest at maximum displacement?", "Acceleration", "core"],
      ["What process removes energy and reduces oscillation amplitude?", "Damping", "core"],
      ["What periodic input supplies energy to an oscillator?", "Driving force", "core"],
      ["What diagram uses circular projection to model SHM?", "Phasor diagram", "core"],
      ["What pendulum property sets its period for small angles?", "Length", "core"],
      ["What spring property is symbolised by k?", "Spring constant", "core"],
      ["What equation gives circular acceleration from speed?", "ac = v²/r", "stretch"],
      ["What equation gives circular acceleration from angular speed?", "ac = rω²", "stretch"],
      ["What theorem conserves vector momentum in isolated collisions?", "Conservation of momentum", "stretch"],
      ["What two component directions are normally used in 2D momentum?", "x and y", "stretch"],
      ["What quantity is the area under a force-time graph?", "Impulse", "stretch"],
      ["What quantity is the gradient of an angular-velocity-time graph?", "Angular acceleration", "stretch"],
      ["What quantity is the area under an angular-velocity-time graph?", "Angular displacement", "stretch"],
      ["What speed is Aω in SHM?", "Maximum speed", "stretch"],
      ["What acceleration is Aω² in SHM?", "Maximum acceleration", "stretch"],
      ["What frequency unit means cycles per second?", "Hertz", "stretch"],
      ["What orbit remains above the same point on Earth's equator?", "Geostationary orbit", "stretch"],
      ["What condition keeps total SHM mechanical energy constant?", "No damping", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-physics-electricity",
      name: "Electrical Systems",
      course: "Physics",
      standard: "AS 91526",
      strand: "Physics",
      keywords: [
        "internal resistance", "emf", "terminal voltage", "Kirchhoff's laws", "capacitor", "capacitance",
        "dielectric", "time constant", "electric energy", "magnetic flux", "Faraday's law", "Lenz's law",
        "inductor", "self-inductance", "transformer", "alternating current", "rms", "peak voltage",
        "reactance", "impedance", "phasor", "resonance", "LR circuit", "CR circuit", "LCR circuit",
      ],
    },
    [
      // Foundation (12)
      ["What is the emf of a source?", "The energy supplied by the source per unit charge.", "foundation", "explain"],
      ["What is internal resistance?", "Resistance inside a cell or source that causes energy loss and a drop in terminal voltage when current flows.", "foundation", "explain"],
      ["State Kirchhoff's junction law.", "The total current entering a junction equals the total current leaving it.", "foundation", "short"],
      ["State Kirchhoff's loop law.", "The algebraic sum of potential changes around any closed loop is zero.", "foundation", "short"],
      ["Define capacitance and write its equation.", "Charge stored per unit potential difference: C = Q/V.", "foundation", "explain"],
      ["What is a dielectric?", "An insulating material placed between capacitor plates that polarises and increases capacitance.", "foundation", "explain"],
      ["For an RC circuit, define the time constant and write its equation.", "τ = RC, the time for charging or discharging to complete about 63% of the total change.", "foundation", "explain"],
      ["Define magnetic flux and write its equation for a uniform field perpendicular to an area.", "A measure of magnetic field passing through an area: Φ = BA for a perpendicular uniform field.", "foundation", "explain"],
      ["State Faraday's law.", "Induced emf equals the negative rate of change of magnetic flux linkage.", "foundation", "explain"],
      ["State Lenz's law.", "The induced current acts in a direction that opposes the change in magnetic flux that produced it.", "foundation", "explain"],
      ["What is self-inductance?", "The property by which a changing current in a circuit induces an emf in that same circuit.", "foundation", "explain"],
      ["Define rms voltage.", "The DC voltage that would produce the same average power in a resistor as the alternating voltage.", "foundation", "explain"],
      // Core (16)
      ["Write the equation linking emf, terminal voltage, current, and internal resistance for a discharging cell.", "Vterminal = ε − Ir.", "core", "short"],
      ["Why does a cell's terminal voltage fall as current increases?", "The internal voltage drop Ir increases, leaving less of the emf across the external circuit.", "core", "explain"],
      ["How can Kirchhoff's laws solve a multi-loop circuit?", "Assign current directions, apply junction conservation, write signed voltage sums for independent loops, and solve the simultaneous equations.", "core", "explain"],
      ["Write the capacitance of a parallel-plate capacitor.", "C = εrε₀A/d.", "core", "short"],
      ["How does inserting a dielectric increase capacitance?", "Polarisation reduces the effective electric field and potential difference for a given charge, so C = Q/V increases.", "core", "explain"],
      ["Write the total-capacitance equation for capacitors in parallel and explain why it applies.", "Capacitances add: Ctotal = C1 + C2 + … because each has the same voltage and stored charges add.", "core", "explain"],
      ["Write the total-capacitance equation for capacitors in series and explain why it applies.", "1/Ctotal = 1/C1 + 1/C2 + … because each stores the same charge and voltages add.", "core", "explain"],
      ["Write two expressions for energy stored in a capacitor.", "E = ½QV = ½CV², with Q²/(2C) also equivalent.", "core", "short"],
      ["How do capacitor charge and current change during charging?", "Charge and voltage rise exponentially toward maximum, while current falls exponentially toward zero.", "core", "explain"],
      ["Use Lenz's law to state how the direction of an induced current is determined.", "It creates a magnetic effect opposing the change in flux, as required by Lenz's law.", "core", "explain"],
      ["Write the induced-emf relationships for a coil and an inductor.", "ε = −NΔΦ/Δt and εL = −LΔI/Δt.", "core", "short"],
      ["Write the equation for the energy stored in an inductor.", "E = ½LI².", "core", "short"],
      ["How does current change after a DC supply is connected to an LR circuit?", "It rises exponentially toward a steady value with time constant τ = L/R.", "core", "explain"],
      ["Write the equation linking the primary and secondary voltages and turns of an ideal transformer.", "Vs/Vp = Ns/Np.", "core", "short"],
      ["Write the equations linking peak and rms voltage and current for a sinusoidal supply.", "Vrms = Vmax/√2 and Irms = Imax/√2.", "core", "short"],
      ["Write the expressions for capacitive and inductive reactance, then state how each changes as frequency increases.", "XC = 1/(ωC) decreases with frequency; XL = ωL increases with frequency.", "core", "explain"],
      // Stretch (12)
      ["A 12.0 V cell with r = 0.50 Ω supplies 4.0 A. Calculate its terminal voltage.", "V = ε − Ir = 12.0 − 4.0×0.50 = 10.0 V.", "stretch", "short"],
      ["Explain how a potential-divider model differs from a loaded source with internal resistance.", "Both divide voltage through series resistance, but internal resistance is part of the source and its voltage drop changes with load current.", "stretch", "explain"],
      ["A 220 μF capacitor charges through 10 kΩ. Calculate the circuit's time constant.", "τ = RC = 10,000 × 220×10⁻⁶ = 2.2 s.", "stretch", "short"],
      ["State the charging and discharging fractions after one time constant.", "Charging reaches about 63% of its final change; discharging falls to about 37% of its initial value.", "stretch", "short"],
      ["Explain how changing plate separation affects an isolated charged capacitor.", "Increasing d reduces C; with Q fixed, V = Q/C and stored energy Q²/(2C) increase because work is done separating attracting plates.", "stretch", "explain"],
      ["Why does an inductor oppose a rapid current change?", "A rapid change creates a large self-induced emf whose direction opposes the change, according to Faraday's and Lenz's laws.", "stretch", "explain"],
      ["Explain why a transformer requires changing magnetic flux.", "A changing primary current creates changing core flux, which induces emf in the secondary; steady DC produces no continuous induced emf.", "stretch", "explain"],
      ["In a series LR AC circuit, state whether current leads or lags the supply voltage and explain why.", "Current lags the supply voltage because the inductor's voltage leads current by 90°.", "stretch", "explain"],
      ["In a series CR AC circuit, state whether current leads or lags the supply voltage and explain why.", "Current leads the supply voltage because capacitor voltage lags current by 90°.", "stretch", "explain"],
      ["Write the equations for impedance and current in a series LCR circuit.", "Z = √(R² + (XL − XC)²), and I = V/Z.", "stretch", "short"],
      ["At resonance in a series LCR circuit, state what happens to reactance, impedance, current, and the phase difference.", "XL = XC, reactances cancel, impedance is minimum at R, current is maximum, and supply voltage is in phase with current.", "stretch", "explain"],
      ["Write the resonance-frequency equation for a series LCR circuit and explain why it depends on both L and C.", "Energy alternates between the inductor's magnetic field and capacitor's electric field at f₀ = 1/(2π√LC).", "stretch", "explain"],
    ],
    [
      ["What energy per charge is supplied by a source?", "EMF", "foundation"],
      ["What source property causes a voltage drop when current flows?", "Internal resistance", "foundation"],
      ["What law conserves current at a junction?", "Kirchhoff's junction law", "foundation"],
      ["What law makes voltage changes sum to zero around a loop?", "Kirchhoff's loop law", "foundation"],
      ["What device stores separated electric charge?", "Capacitor", "foundation"],
      ["What quantity equals charge divided by voltage?", "Capacitance", "foundation"],
      ["What insulator increases a capacitor's capacitance?", "Dielectric", "foundation"],
      ["What RC quantity is represented by τ?", "Time constant", "foundation"],
      ["What magnetic quantity equals BA for perpendicular field and area?", "Magnetic flux", "foundation"],
      ["What law links induced emf to flux-change rate?", "Faraday's law", "foundation"],
      ["What law gives the opposing direction of induced current?", "Lenz's law", "foundation"],
      ["What device stores energy in a magnetic field?", "Inductor", "foundation"],
      ["What property of a coil is symbolised by L?", "Self-inductance", "core"],
      ["What LR quantity equals L/R?", "Time constant", "core"],
      ["What capacitor energy expression contains CV²?", "½CV²", "core"],
      ["What inductor energy expression contains LI²?", "½LI²", "core"],
      ["What device changes AC voltage using two coils?", "Transformer", "core"],
      ["What current alternates direction periodically?", "Alternating current", "core"],
      ["What AC value gives equivalent DC heating?", "RMS value", "core"],
      ["What maximum sinusoidal value is √2 times its rms value?", "Peak value", "core"],
      ["What opposition does a capacitor provide to AC?", "Capacitive reactance", "core"],
      ["What opposition does an inductor provide to AC?", "Inductive reactance", "core"],
      ["What total AC opposition includes resistance and reactance?", "Impedance", "core"],
      ["What diagram represents AC voltages as rotating vectors?", "Phasor diagram", "core"],
      ["What circuit contains resistance and inductance in series?", "LR circuit", "core"],
      ["What circuit contains capacitance and resistance in series?", "CR circuit", "core"],
      ["What circuit contains inductance, capacitance, and resistance?", "LCR circuit", "core"],
      ["What condition occurs when XL equals XC?", "Resonance", "core"],
      ["What frequency gives maximum current in a series LCR circuit?", "Resonant frequency", "stretch"],
      ["Which type of capacitor connection has the same voltage across each capacitor?", "Parallel", "stretch"],
      ["Which type of capacitor connection gives each capacitor the same charge?", "Series", "stretch"],
      ["What graph area represents charge transferred?", "Current-time area", "stretch"],
      ["What sign in Faraday's law represents opposition to flux change?", "Negative sign", "stretch"],
      ["What core property improves magnetic flux linkage in a transformer?", "High permeability", "stretch"],
      ["What current behaviour does an inductor resist?", "Change in current", "stretch"],
      ["What voltage behaviour does a capacitor resist?", "Change in voltage", "stretch"],
      ["What happens to XC as frequency rises?", "Decreases", "stretch"],
      ["What happens to XL as frequency rises?", "Increases", "stretch"],
      ["What phase relationship occurs at LCR resonance?", "In phase", "stretch"],
      ["What quantity is minimum at series resonance?", "Impedance", "stretch"],
    ],
  ),

  makeTopic(
    {
      id: "y13-aghort-meat-market",
      name: "Meat Production Processes and Market Requirements",
      course: "Agricultural & Horticultural Science",
      standard: "AS 91531",
      strand: "Agriculture",
      keywords: [
        "production process", "market requirement", "meat", "carcass", "yield", "carcass weight", "fat depth",
        "marbling", "tenderness", "meat colour", "pH", "food safety", "residue", "traceability", "animal welfare",
        "genetics", "mating", "lambing", "calving", "nutrition", "pasture", "weaning", "growth rate", "finishing",
        "transport", "slaughter", "quality", "quantity", "timing", "price", "consistency", "quantitative data",
      ],
    },
    [
      // Foundation (12)
      ["What is a production process in AS 91531?", "The sequence of manipulated management practices from establishment of the animal enterprise or crop until harvest.", "foundation", "explain"],
      ["What four broad market requirements can producers need to meet?", "Quality, quantity, timing, and price.", "foundation", "short"],
      ["What is a product attribute?", "A measurable characteristic that affects a primary product's marketability.", "foundation", "explain"],
      ["What is carcass weight?", "The mass of the dressed animal after slaughter and removal of specified non-carcass parts.", "foundation", "explain"],
      ["What is carcass yield?", "The proportion or amount of saleable meat obtained from an animal or carcass.", "foundation", "explain"],
      ["Why is fat depth measured?", "It helps assess carcass composition and whether the animal meets a market's lean-to-fat specification.", "foundation", "explain"],
      ["What is marbling?", "Intramuscular fat distributed within muscle tissue.", "foundation", "explain"],
      ["Why is meat tenderness a market requirement?", "Consumers and buyers value an easy-to-chew eating experience and consistent product quality.", "foundation", "explain"],
      ["What is traceability?", "The ability to track an animal and its product through the production and supply chain.", "foundation", "explain"],
      ["Why are withholding periods important?", "They allow veterinary medicines to fall below permitted residue limits before slaughter.", "foundation", "explain"],
      ["What does finishing livestock mean?", "Managing feed, health, and growth so animals reach target carcass specifications before slaughter.", "foundation", "explain"],
      ["Why does slaughter timing matter?", "Animals must reach market specifications within supply windows when processors and customers require the product.", "foundation", "explain"],
      // Core (16)
      ["How can sire selection influence meat-market outcomes?", "Genetics can affect growth rate, mature size, muscling, fat deposition, meat quality, health, and the time needed to reach target specifications.", "core", "explain"],
      ["Why must mating date be planned backward from a market window?", "Mating controls birth date, which affects age, seasonal feed availability, growth period, and likely slaughter date.", "core", "explain"],
      ["How can good maternal nutrition before birth affect meat production?", "It supports fetal growth, birth weight, survival, colostrum production, and later growth potential.", "core", "explain"],
      ["Why is colostrum management important in a meat-production process?", "Adequate early colostrum improves immunity and survival, protecting the number of animals available for sale.", "core", "explain"],
      ["How can weaning date influence carcass timing?", "Well-timed weaning supports continued growth on suitable feed; early or poorly managed weaning can cause a growth check and delay finishing.", "core", "explain"],
      ["How does pasture quality affect growth rate?", "High digestibility and suitable energy and protein increase nutrient intake and live-weight gain.", "core", "explain"],
      ["Why might supplementary feed be economically justified?", "It can close a feed deficit so stock meet a higher-value weight or timing specification, provided the added return exceeds feed and labour costs.", "core", "explain"],
      ["How can parasite control affect carcass quality and quantity?", "It protects feed intake and nutrient use, improving growth, carcass weight, muscling, and the number of stock reaching specification.", "core", "explain"],
      ["Why is live-weight monitoring not enough on its own?", "Animals of the same live weight can differ in fatness, gut fill, frame size, and muscling, so condition and carcass predictors are also needed.", "core", "explain"],
      ["How does body-condition scoring support reproductive and meat targets?", "It guides feeding so breeding animals conceive, carry young, and lactate effectively without excessive feed cost or poor offspring growth.", "core", "explain"],
      ["How can stress before slaughter reduce meat quality?", "Prolonged stress depletes muscle glycogen, which can keep ultimate pH high and produce dark, firm, dry meat; acute stress can also damage carcasses.", "core", "explain"],
      ["Why is low-stress transport part of meeting market requirements?", "It reduces injury, bruising, mortality, weight loss, welfare breaches, and pH-related quality defects.", "core", "explain"],
      ["How can hygiene practices affect market access?", "They reduce contamination and food-safety risk, helping product meet processor, regulatory, and importing-market requirements.", "core", "explain"],
      ["Why is consistency valuable to a meat buyer?", "Uniform carcass weight, fatness, size, and eating quality allow predictable processing, portioning, branding, and customer experience.", "core", "explain"],
      ["How can processor schedules influence farm decisions?", "Price grids and specification premiums or penalties guide breed choice, feeding, drafting, and sale timing.", "core", "explain"],
      ["Why is quantitative data required for an in-depth AS 91531 response?", "Numbers such as target weights, growth rates, dates, fat depths, yields, prices, or survival rates show precisely how a practice meets a requirement.", "core", "explain"],
      // Stretch (12)
      ["Link genetics, nutrition, and slaughter timing for a defined meat market.", "Genetics set growth and carcass potential; nutrition determines how much of that potential is realised; monitoring and drafting then place animals at target weight and fatness within the required market window.", "stretch", "explain"],
      ["Explain why maximising live-weight gain may not maximise profit.", "Extra feed and labour may cost more than the value gained, and overly heavy or fat carcasses may receive schedule penalties.", "stretch", "explain"],
      ["How can a drought disrupt the production process and market supply?", "Lower pasture growth reduces intake and weight gain, delays finishing, increases feed costs, and may force early sale of lighter stock outside preferred specifications.", "stretch", "explain"],
      ["Justify using rotational grazing to meet a carcass-weight target.", "It maintains pasture at a digestible stage and controls allocation, supporting predictable intake and growth; monitoring data can show whether target gains justify fencing and labour costs.", "stretch", "explain"],
      ["How could a producer use carcass feedback to improve the next production cycle?", "Compare weights, grades, fat depths, yields, and defects with targets, then adjust genetics, feeding, health, drafting, or timing where shortfalls occurred.", "stretch", "explain"],
      ["Why can animal-welfare practices also improve financial performance?", "Good handling, shelter, health care, and transport reduce deaths, bruising, disease, poor growth, rejected carcasses, and loss of market trust.", "stretch", "explain"],
      ["Explain the trade-off between lean yield and eating quality.", "Very low fat can improve saleable lean yield but may reduce juiciness and flavour; the best target depends on the chosen market specification and price signals.", "stretch", "explain"],
      ["How can traceability protect a premium brand?", "Verified origin and treatment records support claims, enable rapid recall, demonstrate compliance, and give buyers confidence in consistency and safety.", "stretch", "explain"],
      ["Why should evidence for a 2026 Ag/Hort response be recent?", "Markets, prices, production technologies, regulations, and consumer expectations change, so data from the past five years better supports current decisions.", "stretch", "explain"],
      ["How can changing a production practice affect quality, quantity, timing, and price together?", "For example, improved feeding may increase growth and carcass weight, bring slaughter forward, alter fatness, and gain a premium, but it also raises costs and may overshoot specifications.", "stretch", "explain"],
      ["What makes an Excellence-level justification in AS 91531?", "It uses detailed causal links and quantitative evidence to explain why a sequence of practices is appropriate for specific market requirements, while weighing consequences and alternatives.", "stretch", "explain"],
      ["Why must an answer focus on one product for one market?", "The relevant specifications, production sequence, evidence, and trade-offs depend on the chosen product and buyer, so a defined context enables justified links.", "stretch", "explain"],
    ],
    [
      ["What sequence runs from establishment to harvest?", "Production process", "foundation"],
      ["What measurable feature affects product marketability?", "Product attribute", "foundation"],
      ["What requirement describes how good the product is?", "Quality", "foundation"],
      ["What requirement describes how much product is supplied?", "Quantity", "foundation"],
      ["What requirement describes when product is supplied?", "Timing", "foundation"],
      ["What requirement describes the amount paid or received?", "Price", "foundation"],
      ["What mass is measured after an animal is dressed?", "Carcass weight", "foundation"],
      ["What proportion describes saleable product from a carcass?", "Yield", "foundation"],
      ["What intramuscular fat contributes to flavour and juiciness?", "Marbling", "foundation"],
      ["What eating-quality attribute describes ease of chewing?", "Tenderness", "foundation"],
      ["What system tracks animals and products through the supply chain?", "Traceability", "foundation"],
      ["What final growth phase prepares livestock for slaughter?", "Finishing", "foundation"],
      ["What genetic decision chooses parents for desired carcass traits?", "Sire selection", "core"],
      ["What farm event determines the later birth period?", "Mating", "core"],
      ["What first milk supplies antibodies to newborn livestock?", "Colostrum", "core"],
      ["What process separates young stock from milk?", "Weaning", "core"],
      ["What feed source dominates many New Zealand red-meat systems?", "Pasture", "core"],
      ["What extra feed fills a pasture deficit?", "Supplementary feed", "core"],
      ["What monitoring measure tracks animal mass over time?", "Live weight", "core"],
      ["What score estimates animal fat reserves?", "Body-condition score", "core"],
      ["What treatment controls internal worms?", "Anthelmintic", "core"],
      ["What period must pass after medicine before slaughter?", "Withholding period", "core"],
      ["What condition results from depleted glycogen and high ultimate meat pH?", "Dark, firm, dry meat", "core"],
      ["What handling approach reduces stress and bruising?", "Low-stress handling", "core"],
      ["What market feature means uniform product between consignments?", "Consistency", "core"],
      ["What processor pricing table rewards and penalises carcass specifications?", "Schedule", "core"],
      ["What numerical measure describes weight gained per day?", "Growth rate", "core"],
      ["What evidence type uses measured numbers?", "Quantitative data", "core"],
      ["What quality defect can rough transport cause?", "Bruising", "stretch"],
      ["What energy store is depleted by prolonged pre-slaughter stress?", "Muscle glycogen", "stretch"],
      ["What meat measurement falls normally after slaughter as lactic acid forms?", "pH", "stretch"],
      ["What safety problem is prevented by clean processing?", "Contamination", "stretch"],
      ["What chemical concern is controlled by withholding periods?", "Residues", "stretch"],
      ["What market reward is paid for meeting a preferred specification?", "Premium", "stretch"],
      ["What market reduction is applied for missing a specification?", "Penalty", "stretch"],
      ["What decision separates finished animals from those needing more growth?", "Drafting", "stretch"],
      ["What processor information reports carcass outcomes to farmers?", "Carcass feedback", "stretch"],
      ["What requirement protects animals from avoidable suffering?", "Animal welfare", "stretch"],
      ["What factor can delay finishing by reducing pasture growth?", "Drought", "stretch"],
      ["What financial result remains after costs are subtracted from revenue?", "Profit", "stretch"],
    ],
  ),
];

for (const topic of year13Topics) {
  if (topic.questions.length !== 40) {
    throw new Error(`${topic.id} must contain exactly 40 questions; found ${topic.questions.length}.`);
  }

  if (topic.oneWordQuestions.length !== 40) {
    throw new Error(`${topic.id} must contain exactly 40 one-word questions; found ${topic.oneWordQuestions.length}.`);
  }

  for (const bank of [topic.questions, topic.oneWordQuestions]) {
    const unique = new Set(bank.map((question) => question.q.trim().toLowerCase()));
    if (unique.size !== bank.length) {
      throw new Error(`${topic.id} contains duplicate question wording.`);
    }
  }

  for (const difficulty of ["foundation", "core", "stretch"] as const) {
    const expected = difficulty === "core" ? 16 : 12;
    const count = topic.oneWordQuestions.filter((question) => question.difficulty === difficulty).length;
    if (count !== expected) {
      throw new Error(`${topic.id} must contain ${expected} ${difficulty} one-word questions; found ${count}.`);
    }
  }
}
