export type ExpansionQuestion = {
  q: string;
  a: string;
  difficulty: "foundation" | "core" | "stretch";
  kind: "short" | "explain";
};

type ConceptRow = readonly [
  answer: string,
  clue: string,
  alternateClue: string,
  explanationQuestion: string,
  explanationAnswer: string,
  difficulty: ExpansionQuestion["difficulty"],
];

// Six deliberately new concepts per topic. Each row supplies a concise-recall
// prompt, an alternate One Worders prompt and a deeper explanation prompt.
const concepts: Record<string, ConceptRow[]> = {
  "y7-material-properties": [
    ["Tensile strength", "Which property is tested by pulling a material until it stretches or breaks?", "What term means resistance to being pulled apart?", "Why is high tensile strength useful in a suspension-bridge cable?", "The cable must withstand a large pulling force without stretching excessively or breaking.", "foundation"],
    ["Compressive strength", "Which property describes resistance to being squashed?", "What strength is important for a load-bearing concrete column?", "Why is compressive strength important for building foundations?", "Foundations must support large downward forces without crushing or changing shape.", "foundation"],
    ["Ductility", "What property allows a material to be drawn into a wire?", "Which property makes copper suitable for forming long thin wires?", "How is ductility different from malleability?", "Ductility is the ability to be drawn into wires, whereas malleability is the ability to be hammered or rolled into sheets.", "core"],
    ["Corrosion resistance", "Which property helps a material avoid chemical damage from air or water?", "What property is valuable for a metal used outdoors in wet weather?", "Why is corrosion resistance important when choosing a material for a boat fitting?", "It reduces chemical deterioration in water, so the fitting remains strong and lasts longer.", "core"],
    ["Composite", "What is a material made by combining two or more materials to gain useful properties?", "Which term describes fibreglass or reinforced concrete?", "Why can a composite perform better than either of its component materials alone?", "The components contribute different useful properties, such as strength, low mass or resistance to cracking.", "stretch"],
    ["Fair test", "What type of investigation changes one variable while controlling the others?", "Which investigation design allows material properties to be compared reliably?", "How would you make a fair test of the absorbency of different fabrics?", "Use equal-sized samples, add the same volume of water under the same conditions and measure the amount absorbed in the same way.", "stretch"],
  ],
  "y7-particle-model": [
    ["Random motion", "What term describes the unpredictable movement of particles in a liquid or gas?", "How do gas particles move between collisions?", "How does random particle motion help explain diffusion?", "Particles move in many directions, so their overall spread is from regions of high concentration to regions of low concentration.", "foundation"],
    ["Kinetic energy", "What form of energy do moving particles possess?", "Which particle energy increases when temperature rises?", "Why do gas particles collide with container walls more often when heated?", "Their average kinetic energy increases, so they move faster and reach the walls more frequently.", "foundation"],
    ["Surface", "At which part of a liquid does evaporation occur?", "Where must a liquid particle be to escape during evaporation?", "Why can evaporation occur below a liquid's boiling point?", "Some surface particles already have enough kinetic energy to overcome attractions and escape into the gas state.", "core"],
    ["Thermal expansion", "What is the increase in size of a substance when it is heated called?", "Which effect occurs because heated particles become farther apart on average?", "Use the particle model to explain thermal expansion in a solid.", "The particles vibrate with greater amplitude, increasing their average separation even though the particles themselves do not grow.", "core"],
    ["Closed system", "What type of container prevents matter entering or leaving?", "Which system should keep the same total number of particles during a change of state?", "Why does the mass stay constant when ice melts in a closed container?", "No particles enter or leave; the same water particles remain while only their arrangement and movement change.", "stretch"],
    ["Pressure difference", "What difference causes gas to move from one region to another?", "Which difference makes air escape from an opened inflated balloon?", "Why does air rush out when an inflated balloon is released?", "Pressure is greater inside the balloon, so particle collisions produce a net movement of air toward the lower-pressure surroundings.", "stretch"],
  ],
  "y7-cells": [
    ["Unicellular", "What word describes an organism made from one cell?", "Which term applies to bacteria and many protists?", "How can a unicellular organism carry out all life processes?", "Its single cell contains structures that perform every process needed for survival and reproduction.", "foundation"],
    ["Specimen", "What is the object or sample viewed through a microscope called?", "Which word describes the material placed on a microscope slide?", "Why must a microscope specimen usually be thin?", "A thin specimen allows light to pass through and reduces overlapping layers, making cell structures easier to see.", "foundation"],
    ["Stain", "What substance is added to make transparent cell structures easier to see?", "Which treatment increases contrast in a microscope specimen?", "Why can staining improve a microscope image?", "It colours particular structures and increases contrast, so boundaries and internal features are easier to distinguish.", "core"],
    ["Magnification", "What quantity tells how many times larger an image is than the object?", "Which microscope value is found by multiplying eyepiece and objective values?", "How do you calculate total microscope magnification?", "Multiply the eyepiece magnification by the objective-lens magnification.", "core"],
    ["Surface-area-to-volume ratio", "Which ratio compares a cell's outer membrane area with its internal volume?", "What ratio is usually larger in a small cell than in a large cell?", "Why does a high surface-area-to-volume ratio help a cell?", "It provides more membrane area per unit volume for rapid exchange of substances with the surroundings.", "stretch"],
    ["Differentiation", "What process produces specialised cells with different structures and functions?", "Which process turns unspecialised cells into cell types such as muscle or nerve cells?", "Why is differentiation necessary in a multicellular organism?", "Different tissues and organs need cells adapted for different roles, so one unspecialised cell type could not perform every function efficiently.", "stretch"],
  ],
  "y7-thermal-energy": [
    ["Temperature difference", "What difference drives net thermal energy transfer between objects?", "Which difference becomes zero at thermal equilibrium?", "Why does a larger temperature difference usually make cooling faster?", "A larger difference produces a greater rate of net energy transfer from the hotter object to the cooler surroundings.", "foundation"],
    ["Trapped air", "What inside wool or foam makes these materials good thermal insulators?", "Which poor conductor is held in small pockets by many insulating materials?", "Why must the air pockets in insulation be small?", "Small pockets limit bulk movement of air, so they reduce convection as well as conduction.", "foundation"],
    ["Thermal conductor", "What type of material transfers thermal energy quickly by conduction?", "Which term describes metals used in saucepan bases?", "Why does a metal saucepan base heat food efficiently?", "Its mobile electrons and closely packed particles transfer thermal energy through the metal rapidly.", "core"],
    ["Emitter", "What is a surface that gives out infrared radiation called?", "Which role does a hot matt-black surface perform well?", "Why is a matt-black surface usually a better infrared emitter than a shiny surface?", "It absorbs and emits a larger fraction of infrared radiation, while a shiny surface reflects more.", "core"],
    ["Convection loop", "What circulation forms when warm fluid rises and cool fluid sinks?", "Which repeating movement transfers energy through a heated fluid?", "Explain how a convection loop forms in water heated from below.", "Water near the heater expands and becomes less dense, so it rises; cooler denser water sinks to replace it and the cycle continues.", "stretch"],
    ["Rate of transfer", "What describes how quickly thermal energy moves from one place to another?", "Which quantity insulation is designed to reduce?", "How do a lid and an insulating sleeve reduce the rate at which a hot drink cools?", "The lid limits convection and evaporation at the surface, while the sleeve reduces conduction through the sides.", "stretch"],
  ],
  "y8-mixtures": [
    ["Decanting", "What separation method carefully pours a liquid away from a settled solid?", "Which method could remove clear water from sand after the sand settles?", "When is decanting less effective than filtration?", "Small suspended particles may pour out with the liquid, whereas filter paper can trap them.", "foundation"],
    ["Immiscible", "What word describes two liquids that do not mix to form one layer?", "Which term applies to oil and water?", "How could two immiscible liquids be separated?", "Allow them to form layers, then use a separating funnel or carefully remove one layer.", "foundation"],
    ["Distillate", "What is the condensed liquid collected during distillation called?", "Which product forms after solvent vapour cools in a condenser?", "Why is the distillate from salt water mainly water?", "Water evaporates and condenses, while the non-volatile dissolved salt remains in the flask.", "core"],
    ["Solvent front", "What is the furthest point reached by the solvent on chromatography paper called?", "Which line must be marked promptly after a chromatogram is removed?", "Why should the solvent front be marked immediately?", "The solvent evaporates quickly, so its final position would otherwise be lost.", "core"],
    ["Centrifugation", "What separation method spins a mixture so denser particles move outward or settle?", "Which method is used to separate blood components by rapid spinning?", "Why can centrifugation separate very small suspended particles?", "Rapid spinning produces different movement according to density, allowing particles that settle too slowly under gravity to separate.", "stretch"],
    ["Proportional concentration", "What relationship exists between solute amount and concentration when volume stays fixed?", "How does concentration change if solute amount doubles at constant volume?", "A solution contains twice as much solute in the same volume. Compare its concentration with the original.", "Its concentration is twice as great because concentration is proportional to solute amount when volume is unchanged.", "stretch"],
  ],
  "y8-solubility": [
    ["Solubility curve", "What graph shows how the solubility of a substance changes with temperature?", "Which graph can predict whether crystals form during cooling?", "How can a solubility curve be used to estimate the mass of crystals formed on cooling?", "Find the decrease in solubility between the two temperatures for the stated amount of solvent; that decrease is the mass able to crystallise.", "foundation"],
    ["Unsaturated", "What word describes a solution that can still dissolve more solute at that temperature?", "Which solution contains less than the maximum dissolved amount?", "What happens when more solute is added to an unsaturated solution?", "The added solute dissolves until the solution becomes saturated or all the solute has dissolved.", "foundation"],
    ["Nucleation", "What is the first formation of tiny crystal sites called?", "Which process begins crystal growth from a cooling saturated solution?", "Why can a seed crystal encourage crystallisation?", "It provides an ordered surface on which dissolved particles can arrange and join the growing crystal lattice.", "core"],
    ["Particle size", "Which factor increases dissolving rate when a solid is crushed?", "What is reduced when a large crystal is ground into powder?", "Why does powder dissolve faster than an equal mass of large crystals?", "Powder has a larger total surface area in contact with the solvent, so collisions occur at more sites.", "core"],
    ["Gas solubility", "What usually decreases when the temperature of a fizzy drink rises?", "Which property helps cold water hold more dissolved oxygen than warm water?", "Why does a warm fizzy drink lose carbon dioxide more readily?", "Gas solubility decreases as temperature rises, so more carbon dioxide escapes from the liquid.", "stretch"],
    ["Supersaturated", "What word describes an unstable solution containing more dissolved solute than its normal solubility?", "Which solution can crystallise rapidly when disturbed or seeded?", "How can a supersaturated solution be prepared?", "Dissolve extra solute at a high temperature, then cool the solution carefully without allowing crystals to form.", "stretch"],
  ],
  "y8-reproduction": [
    ["Ovulation", "What is the release of an egg cell from an ovary called?", "Which event normally occurs once during a menstrual cycle?", "Why must ovulation occur before fertilisation can happen naturally?", "An egg must be released into the oviduct so it can meet a sperm cell.", "foundation"],
    ["Implantation", "What is the attachment of an early embryo to the uterus lining called?", "Which event establishes an embryo in the endometrium?", "Why is the uterus lining important during implantation?", "It is thick and well supplied with blood vessels, providing support and nutrients to the early embryo.", "foundation"],
    ["Amniotic fluid", "What liquid surrounds and cushions a developing fetus?", "Which fluid helps protect a fetus from physical shocks?", "How does amniotic fluid protect a developing fetus?", "It cushions impacts, allows movement and helps maintain a stable surrounding environment.", "core"],
    ["Umbilical cord", "What structure connects a fetus to the placenta?", "Which cord contains blood vessels carrying substances to and from a fetus?", "Why do maternal and fetal blood not need to mix directly?", "Substances diffuse across the placental exchange surface between nearby separate blood supplies.", "core"],
    ["FSH", "Which hormone stimulates an egg follicle to mature in an ovary?", "Which pituitary hormone promotes follicle development?", "How does FSH contribute to the menstrual cycle?", "It stimulates follicle maturation and promotes oestrogen production by the ovary.", "stretch"],
    ["LH", "Which hormone surge triggers ovulation?", "Which pituitary hormone causes release of a mature egg?", "How does the interaction of oestrogen and LH help time ovulation?", "High oestrogen causes an LH surge, which triggers release of the mature egg at the appropriate stage of the cycle.", "stretch"],
  ],
  "y8-chemical-changes": [
    ["Precipitate", "What insoluble solid forms when some solutions react?", "Which observation is evidence that a new insoluble substance has formed?", "Why does formation of a precipitate indicate a chemical change?", "Dissolved reactant particles rearrange to form a new insoluble product with different properties.", "foundation"],
    ["Combustion", "What type of reaction occurs when a substance burns in oxygen?", "Which reaction releases energy and often forms oxides?", "Why does a fuel lose mass in an open combustion experiment?", "Some gaseous products escape into the surroundings, so the measured system no longer includes all products.", "foundation"],
    ["Corrosion", "What gradual chemical reaction damages a metal through contact with its environment?", "Which process includes rusting of iron?", "Why are both oxygen and water needed for iron to rust?", "They participate in the reactions that convert iron into hydrated iron oxide.", "core"],
    ["Decomposition", "What reaction type breaks one compound into simpler substances?", "Which reaction has one reactant and two or more products?", "How can heating cause a decomposition reaction?", "Transferred energy breaks bonds in the compound so its atoms rearrange into simpler products.", "core"],
    ["Activation energy", "What minimum collision energy is needed for a chemical reaction?", "Which energy barrier must reacting particles overcome?", "Why do not all particle collisions lead to a reaction?", "Many collisions have insufficient energy or an unsuitable orientation, so bonds do not rearrange.", "stretch"],
    ["Open system", "What type of system allows matter to enter or leave?", "Which system can show an apparent mass change when a gas escapes?", "How can an open system make conservation of mass appear to fail?", "A gas reactant or product can cross the system boundary, so the balance does not measure all matter involved.", "stretch"],
  ],
  "y9-elements-compounds": [
    ["Diatomic molecule", "What molecule contains two atoms and may consist of one element?", "Which term describes O2, N2 and H2 particles?", "Why is oxygen gas an element even though each particle contains two atoms?", "Both atoms are oxygen, so the substance contains only one type of atom.", "foundation"],
    ["Subscript", "What small number in a chemical formula shows how many atoms of an element are present?", "Which number in H2O applies only to hydrogen?", "Why must a subscript not be changed when balancing an equation?", "Changing a subscript changes the identity and composition of the substance rather than only its amount.", "foundation"],
    ["Coefficient", "What number placed before a formula shows the number of particles or formula units?", "Which number can be changed to balance a chemical equation?", "How does a coefficient of 3 affect the formula 3CO2?", "It represents three carbon dioxide particles, containing three carbon atoms and six oxygen atoms altogether.", "core"],
    ["Fixed ratio", "What composition rule applies to the elements in a compound?", "Which term explains why water always contains hydrogen and oxygen in the same atom ratio?", "Why can a compound not have any proportion of its component elements?", "Its atoms are chemically bonded in a particular whole-number ratio determined by the compound's structure.", "core"],
    ["Particle diagram", "What model uses circles or symbols to show atoms, molecules and mixtures?", "Which representation can distinguish an element from a compound at particle level?", "How would a particle diagram of a mixture differ from one of a pure compound?", "A mixture shows more than one type of unbonded particle, while a pure compound shows identical particles with atoms bonded in the same ratio.", "stretch"],
    ["Formula unit", "What term describes the simplest whole-number ratio of ions in an ionic compound?", "Which particle description is used for sodium chloride instead of a molecule?", "Why is sodium chloride described using formula units rather than separate molecules?", "It forms a giant repeating ionic lattice, so NaCl represents the simplest ion ratio rather than an individual molecule.", "stretch"],
  ],
  "y9-periodic-table": [
    ["Metalloid", "What type of element has properties between those of metals and non-metals?", "Which classification includes silicon?", "Why are metalloids useful in electronic devices?", "Their electrical conductivity can be controlled, so they can act as semiconductors.", "foundation"],
    ["Transition metal", "What type of metal occupies the central block of the periodic table?", "Which family includes iron, copper and nickel?", "State two properties commonly shown by transition metals.", "They commonly conduct well and are strong, dense metals; many also form coloured compounds or act as catalysts.", "foundation"],
    ["Electron arrangement", "What notation such as 2,8,1 shows electrons distributed among shells?", "Which pattern links an element's period and group to its electrons?", "How does electron arrangement explain sodium's position in the periodic table?", "Sodium has three occupied shells, placing it in Period 3, and one outer electron, placing it in Group 1.", "core"],
    ["Ion charge", "What value results from the difference between proton and electron numbers?", "Which quantity becomes +1 when an atom loses one electron?", "Why do Group 1 elements usually form +1 ions?", "They lose their single outer electron, leaving one more proton than electron and a full outer shell beneath.", "core"],
    ["Nuclear charge", "What positive charge increases as proton number rises across a period?", "Which attraction pulls electrons toward an atom's nucleus?", "How does increasing nuclear charge affect electrons added across a period?", "The stronger attraction generally pulls electrons closer while they are added to the same main shell.", "stretch"],
    ["Shielding", "What effect reduces the attraction between the nucleus and outer electrons?", "Which effect increases when extra inner electron shells are present?", "Why does increased shielding help explain greater Group 1 reactivity down the group?", "Inner electrons shield the outer electron from nuclear attraction, so it is lost more easily during reaction.", "stretch"],
  ],
  "y9-traits": [
    ["Continuous variation", "What variation shows a full range of values between two extremes?", "Which type of variation includes human height?", "Why is continuous variation often influenced by both genes and environment?", "Many genes contribute small effects, while factors such as nutrition and conditions also alter the final value.", "foundation"],
    ["Discontinuous variation", "What variation has distinct categories with no intermediate values?", "Which type of variation includes ABO blood group?", "How is discontinuous variation usually displayed in a graph?", "Separate categories are shown with a bar chart because values do not form a continuous numerical range.", "foundation"],
    ["Mutation", "What random change in genetic material can create a new allele?", "Which process is the original source of new inherited variation?", "How can a mutation affect a characteristic?", "It may alter a gene's instructions and therefore the structure or amount of a protein involved in the characteristic.", "core"],
    ["Chromosome pair", "What matching pair contains one chromosome inherited from each parent?", "Which pair carries corresponding genes at the same loci?", "Why can siblings inherit different allele combinations from the same parents?", "Different chromosomes and alleles are placed into gametes, and fertilisation combines gametes randomly.", "core"],
    ["Gene-environment interaction", "What term describes genes and surroundings working together to influence a phenotype?", "Which interaction explains why identical genotypes can develop differently under different conditions?", "Use plant height to explain a gene-environment interaction.", "Genes influence growth potential, but light, water and mineral supply affect how fully that potential is reached.", "stretch"],
    ["Random fertilisation", "What process combines one sperm and one egg by chance?", "Which event creates many possible allele combinations in offspring?", "Why does random fertilisation increase variation among offspring?", "Any genetically different sperm may combine with any genetically different egg, producing many possible allele combinations.", "stretch"],
  ],
  "y9-reactions": [
    ["Catalyst", "What substance increases reaction rate without being used up overall?", "Which substance provides an alternative pathway with lower activation energy?", "Why can a catalyst be reused after a reaction?", "It participates in intermediate steps but is regenerated, so it is not consumed overall.", "foundation"],
    ["Collision frequency", "What number increases when reacting particles meet more often each second?", "Which collision factor rises when concentration increases?", "Why does increasing concentration usually increase reaction rate?", "More particles occupy the same volume, so successful collisions occur more frequently.", "foundation"],
    ["Surface area", "What property increases when a solid reactant is crushed into powder?", "Which factor exposes more particles for collisions?", "Why does a powder react faster than equal-mass lumps?", "Its larger total surface area exposes more particles, increasing collision frequency at the solid surface.", "core"],
    ["Conservation of atoms", "What principle means each type of atom has the same total before and after a reaction?", "Which rule is shown by a balanced chemical equation?", "How does a balanced equation show conservation of atoms?", "Its coefficients give equal numbers of every element's atoms on the reactant and product sides.", "core"],
    ["Energy profile", "What graph shows energy changes from reactants to products during a reaction?", "Which diagram displays activation energy and overall energy change?", "How does an exothermic energy profile differ from an endothermic one?", "Exothermic products lie below reactants in energy, while endothermic products lie above them.", "stretch"],
    ["Successful collision", "What collision has enough energy and suitable orientation to form products?", "Which collision overcomes activation energy and rearranges bonds?", "Why does a higher temperature increase the fraction of successful collisions?", "The particle energy distribution shifts upward, so a greater proportion of collisions meet or exceed activation energy.", "stretch"],
  ],
  "y9-acids-bases": [
    ["Hydrogen ion", "Which positive ion is produced by acids in water?", "Which ion becomes less concentrated when an acid is diluted?", "Why does an acid's pH rise when water is added?", "Dilution lowers the concentration of hydrogen ions, moving the pH toward 7.", "foundation"],
    ["Hydroxide ion", "Which negative ion is produced by alkalis in water?", "Which ion reacts with hydrogen ions during neutralisation?", "What happens to hydrogen and hydroxide ions during neutralisation?", "They combine in a one-to-one ratio to form water molecules.", "foundation"],
    ["Metal oxide", "What type of basic compound reacts with an acid to form salt and water?", "Which metal compound can neutralise an acid without producing carbon dioxide?", "Why is copper oxide added until some remains when preparing copper sulfate?", "Excess solid ensures all acid is neutralised and can then be removed by filtration.", "core"],
    ["Limewater", "What solution turns milky in the presence of carbon dioxide?", "Which reagent tests the gas from an acid-carbonate reaction?", "Why does limewater turn cloudy when carbon dioxide is bubbled through it?", "Carbon dioxide reacts to form insoluble calcium carbonate particles.", "core"],
    ["Ionic equation", "What equation shows only the particles that change during a reaction?", "Which equation for neutralisation is H+ + OH− → H2O?", "Why are spectator ions omitted from an ionic equation?", "They remain unchanged on both sides and do not take part in the chemical change.", "stretch"],
    ["Serial dilution", "What method repeatedly dilutes a solution by the same factor?", "Which process can prepare a sequence of progressively lower concentrations?", "Why must equal measured volumes be used carefully in a serial dilution?", "Accurate repeated ratios are needed because any early error is carried into every later dilution.", "stretch"],
  ],
  "y9-forces": [
    ["Inertia", "What property makes an object resist a change in its motion?", "Which property increases with mass?", "Why is a larger force needed to give a more massive object the same acceleration?", "Greater mass means greater inertia, so a larger resultant force is required for the same rate of velocity change.", "foundation"],
    ["Normal contact force", "What support force acts perpendicular to a surface?", "Which upward force can a table exert on a book?", "Why does a stationary book on a table not accelerate downward?", "The upward normal contact force balances the book's downward weight.", "foundation"],
    ["Tension", "What pulling force is transmitted through a taut string or rope?", "Which force acts along a cable supporting a load?", "How does tension act on an object attached to a rope?", "The taut rope pulls the object along the rope and away from the object.", "core"],
    ["Elastic force", "What restoring force is produced when a spring is stretched or compressed?", "Which force acts to return a deformed elastic object to its original shape?", "Why does a stretched elastic band accelerate inward when released?", "Its elastic restoring force creates a resultant force toward its original length.", "core"],
    ["Terminal velocity", "What constant speed is reached when drag balances weight?", "Which motion occurs after a falling object's resultant force becomes zero?", "Explain how a falling object reaches terminal velocity.", "As speed rises, drag increases until it equals weight; the resultant becomes zero, so acceleration stops and speed stays constant.", "stretch"],
    ["Vector", "What quantity has both magnitude and direction?", "Which quantity type includes force, velocity and acceleration?", "Why must force direction be included when finding a resultant?", "Forces in opposite directions partly cancel, while forces in the same direction add, so magnitude alone is insufficient.", "stretch"],
  ],
  "y9-pressure-fluids": [
    ["Density", "What quantity is mass divided by volume?", "Which property helps predict whether an object floats in a fluid?", "How does average density help explain whether an object floats?", "An object floats when it can displace enough fluid for upthrust to balance weight; this is generally possible when its average density is no greater than the fluid's.", "foundation"],
    ["Displacement", "What is the pushing aside of fluid by an immersed object called?", "Which process determines the volume of fluid moved by a submerged object?", "Why does a floating object displace more water when extra mass is added?", "It must create a larger upthrust to balance the increased weight, so it sinks farther and displaces more water.", "foundation"],
    ["Barometer", "What instrument measures atmospheric pressure?", "Which instrument may contain mercury or a sealed sensor to measure air pressure?", "Why can barometer readings help forecast weather changes?", "Moving air masses have different pressures, so changing atmospheric pressure can indicate approaching weather systems.", "core"],
    ["Hydraulic system", "What system transfers pressure through a confined liquid?", "Which system allows a small input force to produce a larger output force using different piston areas?", "How can a hydraulic lift multiply force?", "The same pressure acts throughout the liquid, so a larger output-piston area produces a larger output force.", "core"],
    ["Archimedes' principle", "What principle states that upthrust equals the weight of displaced fluid?", "Which principle links buoyant force to displaced fluid?", "Use Archimedes' principle to explain why a larger submerged volume gives greater upthrust.", "A larger submerged volume displaces more fluid, whose greater weight equals a greater upthrust.", "stretch"],
    ["Pressure gradient", "What term describes pressure changing with position or depth?", "Which gradient exists from high pressure at the bottom of a liquid to lower pressure above?", "Why does a pressure gradient produce upthrust on a submerged object?", "Pressure on the lower surface is greater than on the upper surface, producing a resultant upward force.", "stretch"],
  ],
  "y10-atoms-ions-periodic": [
    ["Relative charge", "What property has values +1 for a proton, 0 for a neutron and −1 for an electron?", "Which subatomic comparison determines whether an atom or ion is electrically charged?", "How do relative charges show that a neutral atom has equal proton and electron numbers?", "Each proton contributes +1 and each electron −1, so equal numbers give a total charge of zero.", "foundation"],
    ["Nucleon number", "What alternative name is used for mass number?", "Which number gives the total protons and neutrons in a nucleus?", "How can neutron number be calculated from nucleon number?", "Subtract atomic number, which is the proton number, from nucleon number.", "foundation"],
    ["Electrostatic attraction", "What force holds negative electrons near a positive nucleus?", "Which attraction holds oppositely charged ions together?", "Why does an electron remain associated with an atom instead of moving away freely?", "Electrostatic attraction between the negative electron and positive nucleus binds it to the atom.", "core"],
    ["Isoelectronic", "What term describes particles with the same electron arrangement?", "Which word links Ne, Na+ and Mg2+ because each has ten electrons?", "Why can different elements form isoelectronic ions?", "They gain or lose different numbers of electrons to reach the same stable outer-shell arrangement.", "core"],
    ["Periodic trend", "What is a repeating pattern in properties across the periodic table called?", "Which term describes systematic change in atomic or chemical properties across periods or groups?", "How does the periodic table help predict an unfamiliar element's behaviour?", "Position reveals repeating electron arrangements, so nearby group members are likely to show related properties and ion charges.", "stretch"],
    ["Charge balance", "What condition requires total positive and negative charge in an ionic formula to equal zero?", "Which rule explains the formula MgCl2 rather than MgCl?", "How is the formula of magnesium chloride obtained from ion charges?", "One Mg2+ ion needs two Cl− ions so the total charge is zero, giving MgCl2.", "stretch"],
  ],
  "y10-forces-motion": [
    ["Reaction time", "What interval passes between noticing a hazard and beginning to brake?", "Which human factor contributes to thinking distance?", "How can tiredness affect a vehicle's stopping distance?", "Tiredness can lengthen reaction time, so the vehicle travels farther before braking begins.", "foundation"],
    ["Braking distance", "What distance does a vehicle travel after the brakes are applied?", "Which part of stopping distance depends strongly on speed, road grip and brake condition?", "Why does braking distance increase greatly as speed rises?", "The vehicle has more kinetic energy to remove, so the brakes need more distance to transfer that energy.", "foundation"],
    ["Distance-time gradient", "What feature of a distance-time graph represents speed?", "Which graph quantity is calculated as change in distance divided by change in time?", "What does a steeper line on a distance-time graph show?", "Distance is changing more each second, so the object is moving faster.", "core"],
    ["Velocity-time area", "What feature under a velocity-time graph gives displacement?", "Which graph calculation combines velocity and time to find change in position?", "Why does the area under a velocity-time graph represent displacement?", "Each small area is velocity multiplied by a time interval, which equals displacement; adding the areas gives total displacement.", "core"],
    ["Momentum", "What quantity is mass multiplied by velocity?", "Which vector quantity is measured in kg m/s?", "Why is a fast heavy object difficult to stop?", "It has large momentum, so a large impulse is required to reduce its velocity to zero.", "stretch"],
    ["Impulse", "What quantity equals force multiplied by the time for which it acts?", "Which quantity is equal to change in momentum?", "How does an airbag reduce the force on a passenger?", "It increases the time over which momentum falls to zero, so the same impulse is produced by a smaller average force.", "stretch"],
  ],
  "y10-genetics": [
    ["Gamete", "What reproductive cell carries one allele for each gene?", "Which cell type includes sperm and egg cells?", "Why does a gamete contain only one allele from each gene pair?", "Allele pairs separate during gamete formation, halving the chromosome number before fertilisation.", "foundation"],
    ["Monohybrid cross", "What genetic cross follows the inheritance of one gene?", "Which cross is commonly represented by a two-by-two Punnett square?", "What can a monohybrid cross predict?", "It predicts possible offspring genotypes and their probabilities for one gene, not the exact outcome of a small family.", "foundation"],
    ["Carrier", "What is a heterozygous person with a recessive allele but no recessive phenotype called?", "Which individual can pass on a recessive condition without showing it?", "Why can two unaffected carriers have an affected child?", "Each can pass on the recessive allele, and a child receiving both recessive alleles expresses the condition.", "core"],
    ["Pedigree", "What diagram traces a characteristic through several generations of a family?", "Which chart uses circles, squares and connecting lines to show inheritance?", "How can a pedigree suggest that an allele is recessive?", "Two unaffected parents producing an affected child suggests both parents carry a recessive allele.", "core"],
    ["Codominance", "What inheritance pattern expresses both alleles fully in a heterozygote?", "Which pattern explains the AB blood-group phenotype?", "How is codominance different from simple dominance?", "In codominance both allele effects are visible in the heterozygote; in simple dominance one masks the other.", "stretch"],
    ["Test cross", "What cross with a homozygous recessive organism can reveal an unknown genotype?", "Which breeding cross distinguishes a dominant homozygote from a heterozygote?", "How does offspring from a test cross reveal a heterozygous parent?", "Any recessive offspring must have received a recessive allele from the unknown parent, showing it is heterozygous.", "stretch"],
  ],
  "y10-acids-bases": [
    ["Metal carbonate", "What compound type reacts with acid to form salt, water and carbon dioxide?", "Which substance type fizzes when added to dilute acid?", "Why does an acid-carbonate reaction stop fizzing when the acid is used up?", "No hydrogen ions remain to react with carbonate ions and produce carbon dioxide.", "foundation"],
    ["Squeaky pop", "What result identifies hydrogen in a gas test with a lit splint?", "Which sound confirms the gas from many acid-metal reactions?", "Why should only a small sample of hydrogen be tested?", "Hydrogen burns rapidly with oxygen, so a small sample limits the energy released and keeps the test safe.", "foundation"],
    ["Salt naming", "What rule uses the metal or ammonium first and an acid-derived ending second?", "Which process names sodium chloride from sodium and hydrochloric acid?", "How does the acid determine the ending of a salt's name?", "Hydrochloric acid forms chlorides, sulfuric acid forms sulfates and nitric acid forms nitrates.", "core"],
    ["Excess solid", "What describes adding more insoluble base than the acid can react with?", "Which technique ensures all acid is neutralised before filtration?", "Why is excess copper oxide removed before crystallising copper sulfate?", "Unreacted copper oxide is insoluble and would contaminate the crystals if it were not filtered out.", "core"],
    ["Titration", "What method uses measured volumes to find the point of exact neutralisation?", "Which technique adds one solution from a burette to another until an indicator changes?", "Why is titration more precise than simply mixing approximate volumes?", "It measures the volume required to reach the endpoint accurately, allowing exact reacting proportions to be determined.", "stretch"],
    ["Endpoint", "What observed indicator change marks completion of a titration?", "Which point is used as an estimate of equivalence during titration?", "Why should solution be added dropwise near a titration endpoint?", "A tiny extra volume can overshoot the colour change, so dropwise addition improves volume precision.", "stretch"],
  ],
  "y10-electricity": [
    ["Electrical power", "What quantity is energy transferred per second by a device?", "Which quantity is calculated using P = IV?", "Why does a high-power appliance transfer more energy in the same time?", "Power is the rate of energy transfer, so a larger power means more joules are transferred each second.", "foundation"],
    ["Electrical energy", "What quantity is calculated by multiplying power by time?", "Which quantity measured in joules or kilowatt-hours is supplied to an appliance?", "How does leaving an appliance on longer affect the energy it uses?", "At constant power, energy is proportional to time, so doubling time doubles the energy transferred.", "foundation"],
    ["Fuse", "What safety device melts and breaks a circuit when current becomes too large?", "Which thin wire protects a circuit from excessive current?", "How does a fuse reduce the risk of an electrical fire?", "Excess current heats and melts the fuse wire, opening the circuit before other wiring overheats.", "core"],
    ["Short circuit", "What low-resistance connection allows an abnormally large current to bypass a component?", "Which fault can cause wires to overheat rapidly?", "Why does a short circuit produce a large current?", "The supply potential difference acts across a very low resistance, so current becomes large according to I = V/R.", "core"],
    ["Circuit breaker", "What resettable safety device opens a circuit when current exceeds a limit?", "Which protective switch can be used again after a fault is cleared?", "How is a circuit breaker different from a fuse?", "Both interrupt excessive current, but a breaker trips mechanically or electronically and can be reset, whereas a fuse wire must be replaced.", "stretch"],
    ["Earth wire", "What safety conductor connects a metal appliance case to ground?", "Which wire provides a low-resistance path for fault current?", "How does an earth wire protect a user if a live wire touches a metal case?", "A large fault current flows to ground, causing the fuse or breaker to disconnect the supply while keeping the case near ground potential.", "stretch"],
  ],
  "y10-human-body": [
    ["Plasma", "What liquid part of blood transports dissolved substances and blood cells?", "Which blood component carries nutrients, hormones, carbon dioxide and urea?", "How does plasma link different organ systems?", "It transports substances between exchange surfaces, cells and excretory organs throughout the circulatory system.", "foundation"],
    ["Capillary", "What tiny blood vessel has a wall one cell thick?", "Which vessel forms networks close to body cells?", "Why are capillary walls thin?", "A one-cell-thick wall creates a short diffusion distance for rapid exchange of substances.", "foundation"],
    ["Alveolus", "What microscopic air sac is the site of gas exchange in the lungs?", "Which lung structure has a large surface area and rich capillary supply?", "How is an alveolus adapted for rapid gas exchange?", "It has a thin moist wall, a large total surface area, ventilation and a rich blood supply that maintain steep concentration gradients.", "core"],
    ["Villus", "What finger-like projection increases absorption surface area in the small intestine?", "Which structure contains capillaries and a lacteal for nutrient absorption?", "Why do villi contain many capillaries?", "Blood flow carries absorbed nutrients away, maintaining concentration gradients and distributing nutrients to cells.", "core"],
    ["Nephron", "What microscopic functional unit filters blood and forms urine in a kidney?", "Which kidney structure includes a glomerulus and tubule?", "How does selective reabsorption in a nephron prevent useful substances being lost?", "Needed glucose, ions and most water move from filtrate back into the blood while urea and excess substances remain for excretion.", "stretch"],
    ["Homeostasis", "What is the maintenance of a stable internal environment called?", "Which process regulates variables such as temperature, glucose and water balance?", "Why is homeostasis essential for enzyme-controlled reactions?", "It keeps internal conditions near the optimum range so enzymes and cells function reliably despite external change.", "stretch"],
  ],
  "y10-earth-science": [
    ["Tectonic plate", "What rigid section of lithosphere moves slowly over the mantle?", "Which large slab carries continental or oceanic crust?", "Why do many earthquakes occur near tectonic plate boundaries?", "Relative plate movement builds stress in rocks until sudden slipping releases stored elastic energy.", "foundation"],
    ["Mantle convection", "What slow circulation transfers thermal energy inside Earth and helps drive plates?", "Which movement involves hot mantle material rising and cooler material sinking?", "How can mantle convection contribute to plate movement?", "Density differences create slow mantle flow that exerts forces on the overlying lithospheric plates.", "foundation"],
    ["Subduction", "What process forces one tectonic plate beneath another?", "Which process occurs when denser oceanic lithosphere sinks at a convergent boundary?", "Why can subduction zones produce explosive volcanoes?", "Water and other volatiles from the descending plate promote melting; gas-rich viscous magma can trap pressure and erupt explosively.", "core"],
    ["Epicentre", "What point on Earth's surface lies directly above an earthquake focus?", "Which mapped location is vertically above where rupture begins?", "How is an earthquake epicentre located using seismic stations?", "Distances inferred from P–S arrival-time differences are triangulated from at least three stations.", "core"],
    ["P wave", "What fastest seismic wave can travel through solids and liquids?", "Which compressional earthquake wave arrives first?", "Why do P waves pass through Earth's liquid outer core?", "They transfer energy by compression and expansion, which can occur in both solids and fluids.", "stretch"],
    ["S wave", "What transverse seismic wave travels only through solids?", "Which earthquake wave does not pass through the liquid outer core?", "How does the S-wave shadow zone provide evidence for a liquid outer core?", "S waves are not transmitted through liquid, so their absence beyond certain angles indicates a liquid layer inside Earth.", "stretch"],
  ],
  "y12-bio-life-processes": [
    ["Light-dependent reactions", "Which stage of photosynthesis uses light to produce ATP and reduced carriers?", "Which chloroplast reactions split water and release oxygen?", "How do the light-dependent reactions support carbon fixation?", "They supply ATP and reducing power used to convert carbon dioxide into carbohydrate.", "foundation"],
    ["Calvin cycle", "Which photosynthetic cycle fixes carbon dioxide into organic molecules?", "Which light-independent pathway occurs in the chloroplast stroma?", "Why does the Calvin cycle depend indirectly on light?", "It uses ATP and reduced carriers made by the light-dependent reactions, so it cannot continue for long without them.", "foundation"],
    ["Cofactor", "What non-protein helper may be required for an enzyme to function?", "Which helper can be a mineral ion or an organic coenzyme?", "How can absence of a required cofactor limit a metabolic pathway?", "The enzyme's active form cannot catalyse its step efficiently, reducing the rate of that step and downstream product formation.", "core"],
    ["Competitive inhibitor", "What inhibitor competes with substrate for an enzyme's active site?", "Which inhibitor's effect can be reduced by increasing substrate concentration?", "Why can more substrate reduce competitive inhibition?", "More substrate molecules compete successfully for active sites, so a greater proportion of enzyme-substrate collisions lead to reaction.", "core"],
    ["Checkpoint", "What control stage prevents a cell progressing through the cell cycle when conditions are unsuitable?", "Which cell-cycle control can halt division after DNA damage?", "Why are cell-cycle checkpoints important in multicellular organisms?", "They reduce transmission of damaged DNA and uncontrolled division, protecting tissue function.", "stretch"],
    ["Chemiosmosis", "What process uses a proton gradient to drive ATP synthesis?", "Which mechanism links electron transport with ATP synthase?", "How does a proton gradient lead to ATP production?", "Protons flow down their electrochemical gradient through ATP synthase, providing energy to join ADP and phosphate.", "stretch"],
  ],
  "y12-bio-genetic-variation": [
    ["Segregation", "What separation of allele pairs occurs during gamete formation?", "Which Mendelian principle gives each gamete one allele for a gene?", "How does segregation contribute to genetic variation?", "Homologous chromosomes and their alleles separate into different gametes, producing gametes with different allele combinations.", "foundation"],
    ["Independent assortment", "What random orientation of homologous pairs produces different chromosome combinations in gametes?", "Which meiotic process mixes maternal and paternal chromosomes independently?", "Why does independent assortment create many possible gamete types?", "Each homologous pair can orient in two ways independently, so the number of combinations increases rapidly with chromosome number.", "foundation"],
    ["Chiasma", "What visible point shows where homologous chromosomes exchange DNA?", "At which connection does crossing over occur between non-sister chromatids?", "How does crossing over at chiasmata increase variation?", "It produces recombinant chromatids containing new combinations of alleles from homologous chromosomes.", "core"],
    ["Gene linkage", "What describes genes located on the same chromosome that tend to be inherited together?", "Which relationship can make observed offspring ratios differ from independent assortment?", "Why does crossing over weaken gene linkage?", "Crossing over can separate linked alleles and place them into new combinations on recombinant chromatids.", "core"],
    ["Lethal allele", "What allele combination causes death and can alter expected offspring ratios?", "Which genetic factor may produce a two-to-one ratio among surviving offspring?", "Why can a recessive lethal allele remain in a population?", "It can be hidden in unaffected heterozygous carriers and passed to offspring without being selected against in those carriers.", "stretch"],
    ["Polygenic inheritance", "What inheritance pattern involves many genes contributing to one phenotype?", "Which pattern often produces continuous variation?", "Why does polygenic inheritance generate a broad range of phenotypes?", "Many loci contribute additive or interacting effects, producing numerous genotype combinations and phenotype values.", "stretch"],
  ],
  "y12-bio-gene-expression": [
    ["Promoter", "What DNA region is the binding site that begins transcription?", "Which gene-control sequence recruits RNA polymerase?", "How can a promoter mutation affect gene expression?", "It may change RNA-polymerase binding and therefore alter how often the gene is transcribed.", "foundation"],
    ["Anticodon", "What three-base sequence on tRNA pairs with an mRNA codon?", "Which triplet ensures the correct amino acid is delivered during translation?", "How does anticodon-codon pairing maintain protein sequence accuracy?", "Complementary pairing positions the tRNA carrying the specified amino acid at the correct mRNA codon.", "foundation"],
    ["Degenerate code", "What property means more than one codon can specify the same amino acid?", "Which feature of the genetic code can make some substitutions silent?", "Why can a base substitution fail to change a protein?", "The altered codon may still specify the same amino acid because the genetic code is degenerate.", "core"],
    ["Reading frame", "What grouping of mRNA bases into consecutive codons determines translation?", "Which sequence organisation is shifted by a one-base insertion?", "Why can a frameshift mutation have a large effect on a protein?", "It changes every downstream codon and may create an early stop, greatly altering the amino-acid sequence.", "core"],
    ["Regulatory gene", "What gene produces a product that controls expression of another gene?", "Which gene can encode a repressor protein?", "How can a regulatory gene coordinate a metabolic response?", "Its product switches pathway genes on or off together in response to cellular conditions.", "stretch"],
    ["Epigenetic modification", "What heritable change in gene activity occurs without changing DNA base sequence?", "Which control includes DNA methylation or histone modification?", "How can DNA methylation reduce gene expression?", "It can make DNA less accessible to transcription machinery or block binding at regulatory regions.", "stretch"],
  ],
  "y12-chem-bonding-energy": [
    ["Electron-domain geometry", "What arrangement minimises repulsion between regions of electron density around a central atom?", "Which VSEPR idea counts bonding and lone-pair regions?", "Why can molecular shape differ from electron-domain geometry?", "Electron-domain geometry includes lone pairs, whereas molecular shape describes only atom positions; lone pairs also repel more strongly.", "foundation"],
    ["Electronegativity", "What ability of an atom attracts bonding electrons toward itself?", "Which property difference determines bond polarity?", "How does electronegativity difference create a polar covalent bond?", "The more electronegative atom attracts the shared electrons more strongly, producing partial charges.", "foundation"],
    ["Instantaneous dipole", "What temporary uneven electron distribution forms in any atom or molecule?", "Which momentary dipole initiates London dispersion attractions?", "Why do dispersion forces become stronger in larger electron clouds?", "Larger clouds are more polarizable, so they form larger temporary dipoles that induce stronger attractions.", "core"],
    ["Molecular polarity", "What overall charge separation results from both polar bonds and an asymmetric shape?", "Which property is cancelled when equal bond dipoles point symmetrically?", "Why is carbon dioxide non-polar even though each C=O bond is polar?", "Its linear symmetric shape makes the two equal bond dipoles point in opposite directions and cancel.", "core"],
    ["Lattice", "What repeating three-dimensional arrangement forms in ionic or metallic solids?", "Which giant structure has no separate molecules?", "Why does an ionic lattice have a high melting point?", "Strong electrostatic attractions act in all directions between many oppositely charged ions and require substantial energy to overcome.", "stretch"],
    ["Solvation", "What process surrounds and stabilises solute particles with solvent particles?", "Which interaction is called hydration when the solvent is water?", "Why can a polar solvent dissolve many ionic substances?", "Its partial charges attract and surround separated ions strongly enough to compete with attractions in the ionic lattice.", "stretch"],
  ],
  "y12-chem-organic": [
    ["Primary alcohol", "What alcohol has its hydroxyl-bearing carbon bonded to one other carbon?", "Which alcohol type can oxidise first to an aldehyde?", "How does oxidation of a primary alcohol differ from oxidation of a secondary alcohol?", "A primary alcohol forms an aldehyde and then a carboxylic acid, while a secondary alcohol forms a ketone.", "foundation"],
    ["Bromine test", "What test uses decolourisation of bromine solution to identify a carbon-carbon double bond?", "Which reagent changes from orange or brown to colourless with an alkene?", "Why does bromine solution lose colour when added to an alkene?", "Bromine adds across the carbon-carbon double bond to form a colourless dibromo product.", "foundation"],
    ["Substitution", "What reaction replaces one atom or group in an organic molecule with another?", "Which reaction converts a haloalkane to an alcohol using aqueous hydroxide?", "How is substitution different from addition?", "Substitution replaces a group while retaining saturation; addition joins groups across a multiple bond to form one more saturated product.", "core"],
    ["Esterification", "What reaction between an alcohol and a carboxylic acid forms an ester and water?", "Which condensation reaction produces many fruity-smelling compounds?", "Why is concentrated sulfuric acid often used in esterification?", "It catalyses the reaction and can help remove water, increasing the rate and favouring ester formation.", "core"],
    ["Major product", "What product forms in the greatest amount when more than one structural product is possible?", "Which product is favoured by the orientation of an addition or elimination reaction?", "How can structural evidence be used to identify a major organic product?", "Apply the relevant reaction rule and compare possible intermediate stability or hydrogen availability at neighbouring carbons.", "stretch"],
    ["Addition polymer", "What long-chain molecule forms when alkene monomers join without losing a small molecule?", "Which polymer type retains the monomer atoms while opening C=C bonds?", "How is the repeating unit of an addition polymer obtained from an alkene?", "Open the carbon-carbon double bond to single bonds and show the connected carbon skeleton inside brackets with continuation bonds.", "stretch"],
  ],
  "y12-chem-reactivity": [
    ["Spectator ion", "What ion remains unchanged during an ionic reaction?", "Which ion appears on both sides of a full ionic equation and is cancelled?", "Why are spectator ions removed from a net ionic equation?", "They do not undergo chemical change, so removing them highlights only the reacting species.", "foundation"],
    ["Oxidation number", "What bookkeeping value tracks electron transfer in redox reactions?", "Which value increases when a species is oxidised?", "How can oxidation numbers identify oxidation and reduction?", "An increase shows oxidation and a decrease shows reduction, revealing the direction of electron transfer.", "foundation"],
    ["Conjugate pair", "What acid-base pair differs by one proton?", "Which pair is formed when an acid donates H+?", "How are a Brønsted acid and its conjugate base related?", "The acid loses one proton to form its conjugate base, so the pair differs by H+.", "core"],
    ["Equilibrium shift", "What response restores equilibrium after concentration or temperature changes?", "Which change in forward and reverse rates produces a new equilibrium composition?", "Why does removing a product usually favour the forward reaction?", "The forward rate temporarily exceeds the reverse rate, replacing some removed product until the rates become equal again.", "core"],
    ["Redox couple", "What paired oxidised and reduced forms are written together in an electrochemical context?", "Which pair can accept or donate electrons reversibly?", "How does relative oxidising strength predict a spontaneous redox reaction?", "A stronger oxidant accepts electrons from the reduced form of a weaker oxidant, producing the favoured redox couples.", "stretch"],
    ["Dynamic equilibrium", "What state has equal forward and reverse rates in a closed system?", "Which equilibrium continues reacting microscopically while concentrations remain constant?", "Why are equilibrium concentrations constant but not necessarily equal?", "Equal reaction rates produce and consume each species at the same rate; the actual concentrations depend on the equilibrium position.", "stretch"],
  ],
  "y12-physics-mechanics": [
    ["Displacement", "What vector change in position includes direction?", "Which motion quantity can be zero after returning to the starting point?", "How can distance be non-zero while displacement is zero?", "A moving object can travel along a path and return to its start, giving path length but no net position change.", "foundation"],
    ["Free-body diagram", "What diagram shows all external forces acting on one object?", "Which diagram uses labelled force arrows from a chosen body?", "Why should internal forces not appear on a free-body diagram of one object?", "The diagram includes only forces exerted on the chosen object by external agents; internal interactions lie within the defined system.", "foundation"],
    ["Conservation of momentum", "What principle keeps total momentum constant in an isolated system?", "Which rule links total momentum before and after a collision?", "Why can individual momenta change while total momentum is conserved?", "Objects exert equal and opposite interaction forces, transferring momentum between them without changing the system total.", "core"],
    ["Work-energy theorem", "What principle states that net work equals change in kinetic energy?", "Which relationship links resultant force over distance to speed change?", "How can braking distance be explained using the work-energy theorem?", "Braking forces must do work equal to the vehicle's initial kinetic energy; more kinetic energy requires more force-distance work.", "core"],
    ["Projectile", "What object moves under gravity after launch when air resistance is neglected?", "Which motion combines constant horizontal velocity with vertical acceleration?", "Why can horizontal and vertical projectile motion be analysed separately?", "Gravity acts vertically only, so it changes vertical velocity while horizontal velocity remains constant when drag is neglected.", "stretch"],
    ["Energy dissipation", "What process transfers mechanical energy into less useful thermal or sound energy?", "Which effect occurs when friction reduces a system's mechanical energy?", "Why is mechanical energy not conserved in a collision with deformation?", "Some kinetic energy is transferred into internal energy, sound and permanent deformation, although total energy remains conserved.", "stretch"],
  ],
  "y12-physics-electricity": [
    ["Potential divider", "What series arrangement provides an output voltage that is a fraction of the supply?", "Which circuit uses resistor ratios to share potential difference?", "How does increasing one resistor in a potential divider affect the voltage across it?", "It receives a larger fraction of the fixed supply voltage because voltage division follows resistance ratio.", "foundation"],
    ["Kirchhoff's current law", "What rule states that total current entering a junction equals total current leaving?", "Which circuit law follows conservation of charge at a node?", "Why must currents at a junction balance?", "Charge cannot accumulate indefinitely at the junction, so the rate of charge flow in equals the rate out.", "foundation"],
    ["Internal resistance", "What resistance inside a source causes terminal voltage to fall when current flows?", "Which source property produces lost volts?", "Why does a battery's terminal voltage decrease under a larger load current?", "The voltage lost inside the battery equals Ir, so a larger current leaves less of the emf across the external circuit.", "core"],
    ["Resistivity", "What material property links resistance to length and cross-sectional area?", "Which quantity appears in R = ρL/A?", "Why does a long thin wire have greater resistance than a short thick wire of the same material?", "Greater length gives more scattering along the path, while smaller area provides fewer parallel paths for charge flow.", "core"],
    ["Charge carrier", "What mobile particle transports electric charge through a material?", "Which carrier in a metal is a delocalised electron?", "Why can current flow in a metal when a potential difference is applied?", "The electric field causes mobile electrons to gain a small net drift through the lattice.", "stretch"],
    ["Efficiency", "What ratio compares useful electrical output energy with total input energy?", "Which percentage reveals how much input avoids waste?", "Why is an electrical device never more than 100 percent efficient?", "It cannot provide more energy than it receives, and real devices transfer some input energy to unwanted thermal or sound stores.", "stretch"],
  ],
  "y12-physics-waves": [
    ["Phase difference", "What angular measure compares positions within two wave cycles?", "Which quantity is 180 degrees for antiphase waves?", "How is phase difference related to path difference?", "One wavelength corresponds to 360 degrees, so phase difference equals 360 degrees multiplied by path difference divided by wavelength.", "foundation"],
    ["Coherence", "What property requires waves to maintain a constant phase relationship and frequency?", "Which condition is needed for a stable interference pattern?", "Why do independent ordinary light sources not usually form stable fringes?", "Their relative phase changes rapidly and unpredictably, so constructive and destructive regions do not stay fixed.", "foundation"],
    ["Standing wave", "What stationary pattern forms when equal waves travel in opposite directions?", "Which pattern contains fixed nodes and antinodes?", "How does a standing wave transfer energy differently from a travelling wave?", "There is no net energy transfer along an ideal standing wave because the opposing travelling waves carry equal energy in opposite directions.", "core"],
    ["Fundamental frequency", "What lowest natural frequency forms the simplest standing-wave pattern?", "Which resonance is also called the first harmonic?", "How is string length related to fundamental frequency when wave speed is fixed?", "The fundamental wavelength is twice the string length, so increasing length lowers frequency according to f = v/λ.", "core"],
    ["Rayleigh criterion", "What idea links resolvability to diffraction and aperture size?", "Which criterion explains why a wider aperture improves angular resolution?", "Why does increasing aperture improve resolution?", "A larger aperture produces a narrower diffraction pattern, allowing two close sources to be distinguished.", "stretch"],
    ["Beat frequency", "What frequency equals the absolute difference between two nearby frequencies?", "Which pulsing rate is heard when similar tones interfere?", "How are beats produced?", "The relative phase of the two waves changes, causing alternating constructive and destructive interference at the difference frequency.", "stretch"],
  ],
  "y12-aghort-livestock-growth": [
    ["Flushing", "What pre-mating practice raises feed intake to improve ovulation and conception?", "Which short-term feeding strategy can increase reproductive performance in breeding females?", "How can flushing influence later livestock growth outcomes?", "Improved conception and multiple births can increase offspring numbers, but feed and management must then support the greater lactation demand and young-stock growth.", "foundation"],
    ["Creep feeding", "What practice gives young stock access to supplementary feed while excluding adults?", "Which feeding system supports pre-weaning growth directly?", "Why might creep feeding help meet an early market target?", "It increases nutrient intake before weaning, raising growth rate and helping young animals reach target live weight sooner.", "foundation"],
    ["Parasite burden", "What describes the number and impact of internal or external parasites on an animal?", "Which health factor competes for nutrients and damages tissues?", "How does a high parasite burden reduce growth?", "Parasites consume nutrients, damage the gut or tissues and stimulate an immune response, leaving less energy and protein for growth.", "core"],
    ["Compensatory growth", "What rapid growth can occur after a period of restricted nutrition?", "Which response may follow improved feeding after a feed shortage?", "Why should farmers not assume compensatory growth will fully repair earlier restriction?", "Its extent depends on age, severity and duration of restriction and later feed quality; permanent developmental losses may remain.", "core"],
    ["Feed conversion efficiency", "What ratio compares feed intake with live-weight gain?", "Which measure improves when animals gain more mass from the same feed?", "How can disease lower feed conversion efficiency?", "Nutrients and energy are diverted to immune responses and tissue repair instead of productive growth.", "stretch"],
    ["Growth curve", "What graph shows body mass or size changing with age?", "Which curve can reveal rapid juvenile growth and later maturity?", "How can a growth curve guide drafting and feeding decisions?", "Comparing actual weights with target trajectories identifies animals needing extra feed, health checks or different sale timing.", "stretch"],
  ],
  "y13-bio-responses": [
    ["Circatidal rhythm", "What endogenous rhythm has a period close to the tidal cycle?", "Which rhythm repeats about every 12.4 hours?", "Why is a circatidal rhythm advantageous to a shore organism?", "It anticipates immersion and exposure, coordinating feeding, sheltering or movement with predictable tidal conditions.", "foundation"],
    ["Critical night length", "What uninterrupted dark period determines flowering in many photoperiodic plants?", "Which threshold can be interrupted by a night-break flash?", "Why can a brief red-light exposure during darkness alter flowering?", "It changes phytochrome state and makes the plant perceive a shorter night, affecting the flowering signal.", "foundation"],
    ["Apical dominance", "What suppression of lateral buds is caused by the shoot tip?", "Which growth pattern is reduced when the apical bud is removed?", "How does auxin contribute to apical dominance?", "Auxin from the shoot apex indirectly inhibits lateral-bud growth, directing resources toward upward extension.", "core"],
    ["Habituation", "What learned reduction in response occurs after repeated harmless stimulation?", "Which learning lets an animal ignore an irrelevant repeated cue?", "How can habituation increase fitness?", "It prevents wasteful responses to harmless stimuli, conserving time and energy for feeding, defence and reproduction.", "core"],
    ["Imprinting", "What rapid learning during a sensitive period forms a lasting attachment or recognition?", "Which behaviour can cause young birds to follow the first suitable moving object?", "Why can imprinting improve survival?", "Rapid parent recognition promotes following, feeding and protection during a vulnerable early-life period.", "stretch"],
    ["Reciprocal altruism", "What cooperation provides a cost now in expectation of a later returned benefit?", "Which behaviour is most stable when individuals recognise and meet repeatedly?", "Under what conditions can reciprocal altruism be selected?", "Repeated interactions, recognition and punishment of cheaters make future returned benefits likely to exceed the initial cost.", "stretch"],
  ],
  "y13-bio-human-evolution": [
    ["Sagittal crest", "What ridge on top of a skull provides attachment for large chewing muscles?", "Which feature is prominent in robust australopithecines?", "What can a large sagittal crest suggest about diet?", "It indicates powerful chewing muscles, consistent with processing tough or hard foods.", "foundation"],
    ["Diastema", "What gap in a tooth row accommodates a large projecting canine?", "Which dental feature is reduced in later hominins?", "How does reduced diastema relate to hominin dentition change?", "It accompanies smaller canines and a less projecting jaw, reflecting changes in diet and social signalling.", "foundation"],
    ["Encephalisation", "What evolutionary increase in brain size relative to body size is called?", "Which trend is measured more meaningfully than cranial capacity alone?", "Why is relative brain size useful when comparing hominins?", "It accounts for body-size differences and better indicates investment in neural processing than absolute volume alone.", "core"],
    ["Mitochondrial DNA", "What maternally inherited DNA is commonly used to trace female ancestry?", "Which genome is abundant in cells and useful in ancient remains?", "Why is mitochondrial DNA useful for reconstructing dispersal?", "Its maternal inheritance and accumulating mutations allow lineages to be compared and branching patterns estimated.", "core"],
    ["Radiocarbon dating", "What absolute dating method measures decay of carbon-14 in once-living material?", "Which method is suitable for relatively recent organic remains?", "Why cannot radiocarbon dating directly date very old stone tools?", "Stone was never alive and contains no original biological carbon; associated organic material must be dated instead.", "stretch"],
    ["Cultural selection pressure", "What human-made environmental factor can alter biological selection?", "Which pressure may arise from diet, settlement or disease exposure created by culture?", "How can cultural and biological evolution interact?", "A cultural change alters the environment and selection pressures, favouring biological variants that then influence later cultural possibilities.", "stretch"],
  ],
  "y13-chem-thermochemical-particles": [
    ["Standard enthalpy change", "What enthalpy change is measured under specified standard conditions?", "Which ΔH value assumes substances in their standard states?", "Why must states be included in a thermochemical equation?", "Changing state changes particle interactions and enthalpy, so the numerical ΔH depends on the physical states specified.", "foundation"],
    ["Hess's law", "What law states that total enthalpy change is independent of reaction pathway?", "Which principle allows reaction equations and ΔH values to be added?", "Why does Hess's law work?", "Enthalpy is a state function, so change depends only on initial and final states, not the steps taken.", "foundation"],
    ["Entropy", "What thermodynamic quantity describes energy dispersal and the number of possible particle arrangements?", "Which quantity generally increases when a solid becomes a gas?", "Why does gas formation usually increase entropy?", "Gas particles have far more possible positions and energy arrangements than particles constrained in a solid or liquid.", "core"],
    ["Lattice enthalpy", "What enthalpy change is associated with forming or separating an ionic lattice?", "Which value reflects electrostatic attraction between gaseous ions in a crystal?", "Why is lattice attraction stronger for smaller, more highly charged ions?", "Higher charges increase electrostatic force and smaller separation strengthens it according to Coulombic attraction.", "core"],
    ["Hydration enthalpy", "What enthalpy change occurs when gaseous ions become surrounded by water molecules?", "Which exothermic process stabilises dissolved ions?", "How do lattice and hydration enthalpies affect ionic solubility?", "Dissolution is more energetically favourable when hydration releases enough energy to compensate for separating the lattice, alongside entropy effects.", "stretch"],
    ["Spontaneity", "What describes a process that is thermodynamically feasible under stated conditions?", "Which property depends on both enthalpy and entropy contributions?", "Why can an endothermic reaction be spontaneous at high temperature?", "A sufficiently favourable entropy increase multiplied by temperature can outweigh the positive enthalpy change in Gibbs energy.", "stretch"],
  ],
  "y13-chem-organic": [
    ["Chiral centre", "What tetrahedral carbon is bonded to four different groups?", "Which carbon feature can produce non-superimposable mirror images?", "Why does one chiral centre usually create two enantiomers?", "The four different groups can occupy two mirror-image arrangements that cannot be superimposed by rotation.", "foundation"],
    ["Enantiomer", "What stereoisomer is a non-superimposable mirror image of another molecule?", "Which pair has identical connectivity but opposite three-dimensional handedness?", "Why can enantiomers behave differently in biological systems?", "Chiral receptors and enzymes may bind one three-dimensional arrangement more strongly than the other.", "foundation"],
    ["Acyl chloride", "What reactive carboxylic-acid derivative contains the −COCl group?", "Which compound reacts readily with water, alcohols and amines?", "Why are acyl chlorides more reactive than carboxylic acids?", "The carbonyl carbon is strongly electron-poor and chloride is a good leaving group, making substitution easier.", "core"],
    ["Condensation polymer", "What polymer forms when bifunctional monomers join and eliminate small molecules?", "Which polymer type includes polyesters and polyamides?", "How does condensation polymerisation differ from addition polymerisation?", "Condensation uses two functional groups and releases a small molecule, whereas addition opens C=C bonds without eliminating a molecule.", "core"],
    ["Optical activity", "What property rotates plane-polarised light?", "Which measurable effect is caused by a non-racemic chiral sample?", "Why is a racemic mixture optically inactive?", "Equal amounts of enantiomers rotate light by equal magnitudes in opposite directions, so their effects cancel.", "stretch"],
    ["Reaction scheme", "What linked sequence shows reagents and conditions for converting one organic compound into others?", "Which representation tests connections across multiple functional groups?", "How should evidence be used to distinguish possible products in a reaction scheme?", "Combine reagents, conditions, observed tests and structural constraints so every conversion and product is chemically consistent.", "stretch"],
  ],
  "y13-chem-aqueous-equilibrium": [
    ["Ionic product of water", "What equilibrium constant is written Kw = [H3O+][OH−]?", "Which constant equals 1.0 × 10−14 at 25 °C?", "How does Kw relate hydronium and hydroxide concentrations?", "Their concentration product is fixed at a stated temperature, so increasing one requires the other to decrease.", "foundation"],
    ["Acid dissociation constant", "What equilibrium constant measures the extent of weak-acid ionisation?", "Which Ka value is larger for a stronger weak acid?", "Why does a larger Ka indicate a stronger acid?", "The equilibrium lies further toward hydronium and conjugate base, showing a greater tendency to donate protons.", "foundation"],
    ["Buffer", "What solution resists pH change when small amounts of acid or base are added?", "Which mixture commonly contains a weak acid and its conjugate base?", "How does an acid buffer respond to added hydroxide ions?", "The weak acid donates protons to neutralise OH−, producing water and more conjugate base, so pH changes only slightly.", "core"],
    ["Solubility product", "What equilibrium constant multiplies ion concentrations for a sparingly soluble salt?", "Which Ksp value is used to assess precipitation?", "How can Ksp predict whether a precipitate forms?", "Calculate the ion product; precipitation is favoured when it exceeds Ksp until concentrations fall back to equilibrium.", "core"],
    ["Common-ion effect", "What reduction in ionisation or solubility occurs when an ion already present is added?", "Which effect can make a sparingly soluble salt less soluble?", "Why does adding a common ion reduce solubility?", "The increased product-ion concentration shifts the dissolution equilibrium toward the undissolved solid.", "stretch"],
    ["Equivalence point", "What titration point has stoichiometrically equivalent reactant amounts?", "Which point is determined by mole ratio rather than indicator colour?", "Why is the equivalence-point pH not always 7?", "The salt produced may hydrolyse to form hydronium or hydroxide ions, depending on the strengths of the acid and base.", "stretch"],
  ],
  "y13-physics-mechanics": [
    ["Torque", "What turning effect equals force multiplied by perpendicular distance from a pivot?", "Which rotational quantity is measured in N m?", "Why does applying a force farther from a pivot increase angular acceleration?", "The larger perpendicular lever arm produces greater torque, giving a greater angular acceleration for the same rotational inertia.", "foundation"],
    ["Centripetal acceleration", "What inward acceleration keeps an object moving in a circle?", "Which acceleration has magnitude v²/r?", "Why can an object accelerate at constant speed in circular motion?", "Its velocity direction changes continuously, so it has inward acceleration even though velocity magnitude is constant.", "foundation"],
    ["Angular momentum", "What rotational quantity is conserved when external torque is zero?", "Which quantity can be written L = Iω for a rigid body?", "Why does a spinning person rotate faster when pulling their arms inward?", "Rotational inertia decreases, so angular speed increases to conserve angular momentum.", "core"],
    ["Gravitational potential", "What potential energy per unit mass is defined relative to infinity?", "Which scalar field quantity is negative around an isolated mass?", "Why is gravitational potential negative near a planet?", "Work must be supplied to move a unit mass from that position to infinity, where potential is defined as zero.", "core"],
    ["SHM phase", "What quantity identifies a point within an oscillation cycle?", "Which relationship distinguishes displacement, velocity and acceleration timing?", "How are velocity and displacement phased in simple harmonic motion?", "Velocity is a quarter-cycle out of phase with displacement and is greatest at equilibrium when displacement is zero.", "stretch"],
    ["Damping", "What process removes energy and reduces oscillation amplitude?", "Which effect can be light, critical or heavy?", "Why is critical damping useful in a measuring instrument?", "It returns the system to equilibrium as quickly as possible without repeated oscillation.", "stretch"],
  ],
  "y13-physics-electricity": [
    ["Electric flux", "What measure describes electric field passing through a surface?", "Which quantity depends on field strength, area and orientation?", "How does rotating a flat surface affect electric flux in a uniform field?", "Flux is greatest when the field is perpendicular to the surface and falls with the cosine of the angle to the surface normal.", "foundation"],
    ["Capacitance", "What ratio of stored charge to potential difference defines a capacitor?", "Which quantity is measured in farads?", "How does increasing plate area affect a parallel-plate capacitor?", "A larger area allows more separated charge at the same voltage, so capacitance increases.", "foundation"],
    ["Time constant", "What quantity RC sets the charging or discharging timescale of a capacitor?", "Which interval leaves about 37 percent of an initial capacitor charge during discharge?", "How does increasing resistance affect capacitor discharge?", "It increases the time constant, reducing current and making charge and voltage fall more slowly.", "core"],
    ["Magnetic flux", "What product BA cos θ measures magnetic field through a loop?", "Which quantity must change to induce an emf?", "Why does moving a magnet faster through a coil induce a larger emf?", "Flux linkage changes more rapidly, so Faraday's law gives a larger induced emf.", "core"],
    ["Lenz's law", "What law states that induced current opposes the change that produces it?", "Which rule determines induced-current direction from energy conservation?", "How does Lenz's law explain magnetic braking?", "Induced currents create magnetic fields opposing the relative motion, transferring kinetic energy into thermal energy.", "stretch"],
    ["RMS voltage", "What AC voltage produces the same average heating effect as an equivalent DC voltage?", "Which effective sinusoidal voltage equals peak voltage divided by √2?", "Why are household AC voltages normally quoted as RMS values?", "RMS directly compares power and heating effects with DC, making appliance ratings meaningful.", "stretch"],
  ],
  "y13-aghort-meat-market": [
    ["Value chain", "What linked sequence adds value from farm inputs through processing and sale?", "Which chain connects producer decisions with final consumers?", "How can coordination across the value chain improve market returns?", "Sharing specifications and feedback aligns production, processing and timing, reducing waste and increasing the proportion meeting premium requirements.", "foundation"],
    ["Cold chain", "What temperature-controlled system protects meat from processing to purchase?", "Which chain limits microbial growth and quality loss during transport and storage?", "Why is an unbroken cold chain essential for chilled meat exports?", "Stable low temperature protects food safety and shelf life during the long supply period required by distant markets.", "foundation"],
    ["Quality assurance", "What verified system shows production follows specified standards and records?", "Which programme can support welfare, safety or sustainability claims?", "How can quality assurance earn market access or premiums?", "Independent verification reduces buyer risk and provides evidence that product claims and required practices are consistently met.", "core"],
    ["Biosecurity", "What practices prevent harmful pests and diseases entering or spreading?", "Which protection reduces production loss and market restrictions from animal disease?", "How can a biosecurity failure affect both quantity and price?", "Disease can lower growth and supply while movement controls or lost market access reduce sale options and returns.", "core"],
    ["Carcass classification", "What system groups carcasses using traits such as weight, fatness and muscling?", "Which classification determines schedule premiums and penalties?", "How can carcass classification feedback change farm management?", "It identifies recurring specification failures, guiding changes to genetics, feeding, drafting and slaughter timing.", "stretch"],
    ["Market segmentation", "What process divides buyers into groups with different product requirements?", "Which strategy distinguishes premium chilled, commodity frozen or specialist markets?", "Why should production practices be matched to a defined market segment?", "Each segment rewards different quality, timing, traceability and price features, so the most profitable practice sequence depends on the target buyer.", "stretch"],
  ],
};

export const expandedQuestions: Record<string, ExpansionQuestion[]> = Object.fromEntries(
  Object.entries(concepts).map(([topicId, topicConcepts]) => [
    topicId,
    topicConcepts.flatMap(([answer, clue, alternateClue, explanationQuestion, explanationAnswer, difficulty]) => [
      { q: clue, a: answer, difficulty, kind: "short" as const },
      { q: alternateClue, a: answer, difficulty, kind: "short" as const },
      { q: explanationQuestion, a: explanationAnswer, difficulty, kind: "explain" as const },
    ]),
  ]),
);

export const expandedOneWordQuestions: Record<string, ExpansionQuestion[]> = Object.fromEntries(
  Object.entries(concepts).map(([topicId, topicConcepts]) => [
    topicId,
    topicConcepts.flatMap(([answer, clue, alternateClue, , , difficulty]) => [
      { q: clue, a: answer, difficulty, kind: "short" as const },
      { q: alternateClue, a: answer, difficulty, kind: "short" as const },
    ]),
  ]),
);

for (const [topicId, topicConcepts] of Object.entries(concepts)) {
  if (topicConcepts.length !== 6) {
    throw new Error(`${topicId} must contain exactly 6 expansion concepts; found ${topicConcepts.length}.`);
  }

  for (const bank of [expandedQuestions[topicId], expandedOneWordQuestions[topicId]]) {
    const uniqueQuestions = new Set(bank.map((question) => question.q.trim().toLowerCase()));
    if (uniqueQuestions.size !== bank.length) {
      throw new Error(`${topicId} contains duplicate expansion question wording.`);
    }
  }

  if (expandedOneWordQuestions[topicId].some((question) => /^(?:is|are|can|could|do|does|did|will|would|should|has|have|had)\b/i.test(question.q))) {
    throw new Error(`${topicId} contains a Yes/No One Worders prompt.`);
  }
}
