export const acidsBasesConcepts = [
  ["acid", "What type of substance releases H⁺ ions when it reacts with water?", "What type of substance has a pH below 7 in water?", "foundation"],
  ["hydrogen ion", "Which ion is written H⁺ and is released by acids in water?", "Which ion is present in greater relative amounts in acidic solutions?", "core"],
  ["pH", "What scale is used to show how acidic, neutral or alkaline a solution is?", "What scale runs from 0 to 14 with 7 as neutral?", "foundation"],
  ["indicator", "What do we call a substance that changes colour depending on pH?", "What type of substance can show whether a solution is acidic or alkaline by changing colour?", "foundation"],
  ["universal indicator", "Which indicator shows a range of colours across the pH scale?", "Which indicator can be compared with a colour chart to estimate pH?", "core"],
  ["hydrochloric acid", "What is the name of the acid with formula HCl?", "Which common laboratory acid has the formula HCl?", "core"],
  ["sulfuric acid", "What is the name of the acid with formula H₂SO₄?", "Which common laboratory acid has the formula H₂SO₄?", "core"],
  ["nitric acid", "What is the name of the acid with formula HNO₃?", "Which common laboratory acid has the formula HNO₃?", "core"],
  ["base", "What type of substance reacts with an acid to neutralise it?", "What class of substances includes metal hydroxides and metal carbonates?", "foundation"],
  ["alkali", "What do we call a base that dissolves in water?", "Which type of base forms hydroxide ions in water?", "foundation"],
  ["hydroxide ion", "Which ion is written OH⁻ and is released by bases in water?", "Which ion combines with H⁺ during neutralisation to form water?", "core"],
  ["sodium hydroxide", "What is the name of the base with formula NaOH?", "Which common alkali has the formula NaOH?", "core"],
  ["potassium hydroxide", "What is the name of the base with formula KOH?", "Which common alkali has the formula KOH?", "core"],
  ["calcium carbonate", "What is the name of the base with formula CaCO₃?", "Which metal carbonate has the formula CaCO₃?", "core"],
  ["neutralisation", "What do we call the reaction between an acid and a base?", "What reaction occurs when H⁺ and OH⁻ ions combine to form water?", "core"],
  ["sodium chloride", "What salt is formed when sodium reacts with hydrochloric acid?", "What salt is formed in the reaction sodium + hydrochloric acid → salt + hydrogen?", "core"],
  ["magnesium chloride", "What salt is formed when magnesium reacts with hydrochloric acid?", "What salt is made in the reaction between magnesium and hydrochloric acid?", "core"],
  ["acid + metal → salt + hydrogen", "What is the general word equation for the reaction between an acid and a metal?", "Complete the general equation: acid + metal → ?", "core"],
  ["acid + base → salt + water", "What is the general word equation for the reaction between an acid and a base?", "Complete the general equation: acid + base → ?", "core"],
  ["acid + metal carbonate → salt + water + carbon dioxide", "What is the general word equation for the reaction between an acid and a metal carbonate?", "Complete the general equation: acid + metal carbonate → ?", "core"],
  ["pop test", "What gas test gives a squeaky pop with a lit splint?", "Which test is used to identify hydrogen gas?", "core"],
  ["limewater test", "What gas test turns clear limewater milky?", "Which test is used to identify carbon dioxide gas?", "core"],
  ["concentrated", "What term describes a solution with a relatively large amount of solute in a given volume?", "Which word describes an acid solution containing more acid particles in the same volume?", "core"],
  ["dilute", "What term describes a solution with a relatively small amount of solute in a given volume?", "Which word describes a solution after more solvent has been added to reduce its concentration?", "core"],
  ["collision theory", "What theory explains why increasing acid concentration can increase reaction rate?", "Which theory explains reaction rate by considering how often reacting particles collide successfully?", "stretch"],
  ["word equation", "What type of equation uses chemical names to show the reactants and products?", "What do we call an equation such as hydrochloric acid + magnesium → magnesium chloride + hydrogen?", "core"],
  ["balanced chemical equation", "What do we call a symbol equation with the same number of each type of atom on both sides?", "What type of equation uses coefficients so atoms are conserved?", "stretch"],
  ["neutral", "What term describes a solution with pH 7?", "What word describes a solution with neither an acidic nor alkaline overall pH?", "foundation"],
] as const;
