export const atomsIonsPeriodicConcepts = [
  ["atom", "What is the smallest particle of an element that can exist?", "What do we call a particle with a nucleus and electrons around it?", "foundation"],
  ["molecule", "What do we call two or more atoms chemically bonded together?", "Which term describes bonded atoms such as O₂ or H₂O?", "foundation"],
  ["element", "What do we call a substance made from only one type of atom?", "Which type of substance is represented by a chemical symbol such as Na or O?", "foundation"],
  ["compound", "What do we call a substance made when atoms or ions of different elements are chemically combined?", "Which term describes substances such as NaCl or H₂O?", "foundation"],
  ["proton", "Which subatomic particle has a positive charge?", "Which particle in the nucleus determines the atomic number?", "foundation"],
  ["neutron", "Which subatomic particle has no electrical charge?", "Which neutral particle is found in the nucleus?", "foundation"],
  ["electron", "Which subatomic particle has a negative charge?", "Which particle is gained or lost when an atom forms an ion?", "foundation"],
  ["nucleus", "Which part of an atom contains protons and neutrons?", "Where are the protons and neutrons found in an atom?", "foundation"],
  ["atomic number", "Which number on the periodic table tells you the number of protons in an atom?", "Which number identifies the element?", "core"],
  ["mass number", "Which number is the total number of protons and neutrons in the nucleus?", "Which number can you use with atomic number to calculate the number of neutrons?", "core"],
  ["electron configuration", "What do we call an electron arrangement written as numbers such as 2,8,8,2?", "Which representation shows how electrons are arranged in energy levels?", "core"],
  ["energy level", "What do we call the areas around the nucleus where electrons are found?", "In an electron configuration such as 2,8,1, what does each number show the electrons in?", "core"],
  ["valence electron", "What do we call an electron in the outermost occupied energy level?", "Which electrons help determine how reactive an atom is?", "core"],
  ["group", "What is a vertical column in the periodic table called?", "What part of the periodic table contains elements with the same number of valence electrons?", "core"],
  ["period", "What is a horizontal row in the periodic table called?", "What part of the periodic table tells you the number of occupied energy levels?", "core"],
  ["ion", "What charged particle forms when an atom gains or loses electrons?", "What do we call an atom that no longer has equal numbers of protons and electrons?", "core"],
  ["cation", "What do we call a positively charged ion?", "What type of ion forms when an atom loses electrons?", "core"],
  ["anion", "What do we call a negatively charged ion?", "What type of ion forms when an atom gains electrons?", "core"],
  ["electrically neutral", "What do we call an atom with equal numbers of protons and electrons?", "What term means the positive and negative charges cancel so there is no overall charge?", "core"],
  ["NaCl", "What formula is formed when Na⁺ and Cl⁻ ions combine in the correct ratio?", "What is the formula of sodium chloride?", "core"],
  ["MgCl₂", "What formula is formed when Mg²⁺ and Cl⁻ ions combine so the charges cancel?", "What is the formula of magnesium chloride?", "stretch"],
  ["sodium chloride", "What is the name of the ionic compound NaCl?", "What ionic compound is formed from sodium ions and chloride ions?", "core"],
  ["magnesium chloride", "What is the name of the ionic compound MgCl₂?", "Which ionic compound contains Mg²⁺ ions and Cl⁻ ions in a 1:2 ratio?", "stretch"],
  ["chemical word equation", "What type of equation shows reactants and products using their chemical names?", "What do we call an equation such as magnesium + oxygen → magnesium oxide?", "core"],
  ["balanced chemical equation", "What do we call a chemical equation with the same number of each type of atom on both sides?", "What type of equation uses coefficients so the number of each atom is conserved?", "stretch"],
  ["reactivity", "What term describes how readily an element takes part in a chemical reaction?", "Which property can be linked to how easily an atom gains or loses electrons to reach a full outer energy level?", "core"],
  ["oxygen", "Which gas relights a glowing splint?", "A glowing splint relights in a gas. Which gas is present?", "core"],
  ["Rutherford model", "Which model of the atom has a small central nucleus with electrons around it?", "Which atomic model was supported by Rutherford's gold-foil experiment?", "stretch"],
  ["atomic model", "What do we call a scientific representation of the structure of an atom?", "What type of scientific representation changes when new evidence about atomic structure is discovered?", "stretch"],
] as const;
