export const earthScienceConcepts = [
  ["Earth's surface", "What part of Earth is described as being made of water, air, rocks and soil?", "What do we call the part of Earth made up of water, air, rocks and soil?", "foundation"],
  ["crust", "What is Earth's thin outer solid layer called?", "Which layer forms the outside of Earth?", "foundation"],
  ["mantle", "Which thick layer lies below the crust?", "Which Earth layer contains slowly moving material involved in convection?", "foundation"],
  ["outer core", "Which liquid layer lies between the mantle and inner core?", "Which Earth layer does not allow S-waves to travel through it?", "core"],
  ["inner core", "What is the solid layer at the centre of Earth called?", "Which Earth layer lies inside the outer core?", "core"],
  ["convection", "What process involves warmer mantle material rising and cooler material sinking?", "Which process in the mantle contributes to tectonic plate movement?", "core"],
  ["tectonic plate", "What do we call a large section of Earth's outer surface that moves slowly?", "Which moving part of Earth's surface interacts with other plates at boundaries?", "core"],
  ["collision", "What happens when two tectonic plates move toward each other and push together?", "Which plate movement can lead to mountain building?", "core"],
  ["subduction", "What process occurs when one tectonic plate is forced beneath another?", "What do we call the sinking of one plate beneath another at a plate boundary?", "core"],
  ["sea-floor spreading", "What process creates new ocean floor where plates move apart?", "What process occurs as new crust forms and the sea floor moves away on either side?", "core"],
  ["strike-slip", "What type of plate movement occurs when two plates slide sideways past each other?", "Which plate movement can produce earthquakes as plates move past each other?", "core"],
  ["mountain building", "What surface change can happen when tectonic plates collide and push crust upward?", "What process forms large mountain ranges when crust is compressed?", "core"],
  ["earthquake", "What event happens when built-up stress is released and rocks move suddenly?", "Which geological event sends seismic waves through Earth?", "core"],
  ["focus", "What is the underground point where an earthquake begins?", "Where inside Earth do the seismic waves from an earthquake start?", "core"],
  ["epicentre", "What point on Earth's surface is directly above the focus of an earthquake?", "What do we call the surface location directly above where an earthquake starts?", "core"],
  ["P-wave", "Which seismic wave arrives first?", "Which earthquake wave can travel through both solids and liquids?", "core"],
  ["S-wave", "Which seismic wave cannot travel through liquids?", "Which earthquake wave arrives after the P-wave?", "core"],
  ["seismograph", "What instrument records seismic waves from earthquakes?", "Which instrument is used to record ground movement during an earthquake?", "core"],
  ["Richter scale", "Which scale is used to describe earthquake magnitude?", "What named scale gives a number for the size of an earthquake?", "core"],
  ["tsunami", "What series of large ocean waves can be caused by sudden movement of the sea floor?", "Which hazard can be triggered by an undersea earthquake?", "core"],
  ["volcano", "What geological feature can erupt lava, ash and gases?", "What feature forms when magma reaches Earth's surface through an opening?", "core"],
  ["magma reservoir", "What underground store of magma can feed a volcano?", "Where can magma collect below a volcano before an eruption?", "core"],
  ["vent", "What opening allows magma, ash and gases to reach the surface?", "Which part of a volcano is the opening through which material erupts?", "core"],
  ["crater", "What bowl-shaped depression can form around a volcanic vent?", "What feature is found around the opening at the top of many volcanoes?", "core"],
  ["cone", "What sloping volcanic landform builds up around a vent from erupted material?", "What volcano shape can form as erupted material builds up around the vent?", "core"],
  ["hot spot", "What do we call a volcanic area that can form away from a plate boundary above rising hot material?", "Which feature can produce volcanoes as a plate moves over a persistent hot region below?", "stretch"],
  ["lava", "What is molten rock called once it reaches Earth's surface?", "What do we call magma after it erupts onto the surface?", "foundation"],
  ["caldera", "What large volcanic depression can form after a major eruption and collapse?", "Which volcanic depression is much larger than a typical crater?", "stretch"],
  ["P-waves and S-waves", "What evidence can scientists use to infer the internal structure of Earth?", "Which two types of seismic waves provide evidence about Earth's layers?", "stretch"],
  ["follow evacuation and Civil Defence advice", "What should you do if authorities tell you to evacuate because of an earthquake, volcano or tsunami risk?", "What type of official advice should you follow during a major geological emergency?", "core"],
] as const;

