export const electricityConcepts = [
  ["static electricity", "What is a build-up of electric charge in one place called?", "What type of electricity stays in one place until it discharges?", "foundation"],
  ["electron transfer", "What happens to electrons when static electricity is produced by friction?", "What process moves electrons from one material to another when objects are rubbed?", "core"],
  ["repel", "What do like electric charges do to each other?", "What happens when two positive charges or two negative charges are brought close together?", "foundation"],
  ["attract", "What do opposite electric charges do to each other?", "What happens when a positive charge and a negative charge are brought close together?", "foundation"],
  ["electrical discharge", "What do we call the sudden movement of built-up charge that can produce a spark or shock?", "What process occurs in lightning when built-up charge moves suddenly?", "core"],
  ["insulator", "What do we call a material that does not allow electrons to flow through it easily?", "Which type of material is used around electrical wires to stop charge flowing where it should not?", "foundation"],
  ["conductor", "What do we call a material that allows electrons to flow through it?", "Which type of material is used for metal connecting wires?", "foundation"],
  ["direct current", "What type of current moves in one direction?", "What does DC stand for?", "core"],
  ["circuit diagram", "What drawing uses standard symbols to show how components are connected?", "What do we call a simplified drawing of an electrical circuit using circuit symbols?", "foundation"],
  ["cell", "What component is shown by one long line and one short line in a circuit diagram?", "What single electrical source can provide energy to a simple circuit?", "core"],
  ["battery", "What do we call two or more cells connected together?", "Which source is shown by repeated long-short line pairs in a circuit diagram?", "core"],
  ["power supply", "Which laboratory component provides electrical energy to a circuit and can be used instead of cells?", "Which circuit source can provide a chosen voltage in a school practical?", "core"],
  ["lamp", "Which circuit component produces light when current flows through it?", "Which component is also called a bulb in a simple circuit?", "foundation"],
  ["switch", "Which component opens or closes a circuit?", "Which component stops current when it is open?", "foundation"],
  ["resistor", "Which component provides resistance in a circuit?", "Which fixed component can reduce the current in a circuit?", "core"],
  ["variable resistor", "Which component allows the resistance to be changed?", "Which component can be adjusted to change the current in a circuit?", "core"],
  ["ammeter", "Which instrument measures current?", "Which meter must be connected in series?", "core"],
  ["voltmeter", "Which instrument measures voltage?", "Which meter must be connected in parallel across a component?", "core"],
  ["series circuit", "What type of circuit has only one path for current?", "In which circuit is the current the same through every component?", "core"],
  ["parallel circuit", "What type of circuit has two or more branches?", "In which circuit can one branch keep working if another branch is broken?", "core"],
  ["current", "What quantity measures the flow of charge and is measured in amperes?", "What quantity is measured by an ammeter?", "foundation"],
  ["voltage", "What quantity measures the energy transferred by each charge as it moves through a component?", "What quantity is measured in volts by a voltmeter?", "foundation"],
  ["resistance", "What quantity describes how much a component opposes current?", "In V = IR, what does R represent?", "foundation"],
  ["V = IR", "Which equation links voltage, current and resistance?", "Which equation would you rearrange to calculate current from voltage and resistance?", "core"],
  ["current in series", "What happens to current at different points in a series circuit?", "In a series circuit, is the current the same or different through each component?", "core"],
  ["current in parallel", "What happens to current when it reaches a junction in a parallel circuit?", "In a parallel circuit, what happens to the total current when it divides between branches?", "core"],
  ["voltage in series", "What happens to the supply voltage across components in a series circuit?", "In a series circuit, is the supply voltage shared between the components or the same across each one?", "core"],
  ["voltage in parallel", "What happens to voltage across branches in a parallel circuit?", "In a parallel circuit, how does the voltage across each branch compare with the supply voltage?", "core"],
  ["P = IV", "Which equation links electrical power, current and voltage?", "Which equation would you use to calculate power from current and voltage?", "core"],
  ["power", "What quantity describes how quickly electrical energy is transferred and is measured in watts?", "In P = IV, what does P represent?", "core"],
  ["kilowatt-hour", "What unit do power companies use when charging for electrical energy?", "What electrical energy unit has the symbol kWh?", "stretch"],
  ["voltage-current graph", "What graph do you plot when investigating how current changes with voltage?", "Which graph uses voltage and current data from a circuit investigation?", "stretch"],
  ["brighter", "If identical bulbs are connected so each gets the full supply voltage in parallel, how will they compare with the same bulbs in series?", "For identical bulbs and the same supply, which word describes bulbs in parallel compared with bulbs in series?", "stretch"],
  ["short circuit", "What fault creates an unintended low-resistance path so a very large current can flow?", "What do we call a circuit fault where current bypasses the intended component?", "stretch"],
] as const;
