export const forcesMotionConcepts = [
  ["force", "What is a push, pull or twist that can change an object's shape or motion?", "What quantity is measured in newtons and can change an object's speed, direction or shape?", "foundation"],
  ["newton", "What is the unit of force?", "What unit has the symbol N?", "foundation"],
  ["mass", "What quantity measures the amount of matter in an object and is measured in kilograms?", "Which quantity stays the same if an object is moved to a planet with different gravity?", "foundation"],
  ["weight", "What force acts on an object because of gravity?", "In W = mg, what does W represent?", "foundation"],
  ["gravitational field strength", "In W = mg, what does g represent?", "Which quantity changes from planet to planet and changes an object's weight?", "core"],
  ["W = mg", "Which equation links weight, mass and gravitational field strength?", "Which equation would you use to calculate the weight of an object when its mass and g are known?", "core"],
  ["thrust", "Which force pushes a powered vehicle forwards?", "Which force can be produced by an engine or propeller to move a vehicle?", "core"],
  ["drag", "Which force opposes motion through air or water?", "Which resistive force acts opposite the movement of an object through a fluid?", "core"],
  ["support force", "Which force from a surface pushes up on an object resting on it?", "What is the upward force from a surface that supports an object?", "core"],
  ["lift", "Which upward force can act on an aircraft moving through air?", "Which force can act upward on a wing and oppose weight?", "core"],
  ["buoyancy", "Which upward force is exerted by a fluid on an object?", "Which force helps an object float in water?", "core"],
  ["density", "What quantity is calculated as mass divided by volume?", "Which property can be used to predict whether an object will float or sink compared with water?", "core"],
  ["force diagram", "What diagram uses labelled arrows to show the forces acting on an object?", "Which diagram would you draw to show weight, support, thrust and drag on an object?", "core"],
  ["resultant force", "What do we call the overall force after the forces acting on an object are combined?", "What force do you get after adding forces in the same direction and subtracting forces in opposite directions?", "core"],
  ["balanced forces", "What do we call forces that give a resultant force of zero?", "What type of forces cause no change in an object's motion?", "core"],
  ["unbalanced forces", "What do we call forces that give a non-zero resultant force?", "What type of forces cause an object's motion to change?", "core"],
  ["terminal velocity", "What constant speed is reached when a falling object's drag equals its weight?", "What has a falling object reached when the forces are balanced and it stops accelerating?", "core"],
  ["friction", "Which force opposes movement between surfaces that are in contact?", "Which force can be reduced by lubrication?", "core"],
  ["F = ma", "Which equation links force, mass and acceleration?", "Which equation would you use to calculate acceleration when force and mass are known?", "core"],
  ["speed", "What quantity tells you how fast an object is moving?", "Which quantity is measured in metres per second and can be calculated from distance and time?", "foundation"],
  ["v = Δd/Δt", "Which equation calculates speed from change in distance and change in time?", "Which equation would you rearrange to calculate distance from speed and time?", "core"],
  ["distance-time graph", "Which graph shows how distance changes with time?", "On which graph does the gradient show speed?", "core"],
  ["acceleration", "What quantity describes how quickly an object's speed changes?", "Which quantity is measured in metres per second squared?", "core"],
  ["a = Δv/Δt", "Which equation calculates acceleration from change in speed and time?", "Which equation would you use when an object's speed changes over a measured time?", "core"],
  ["speed-time graph", "Which graph shows how speed changes with time?", "On which graph does the gradient show acceleration?", "core"],
  ["Newton's first law", "Which law says an object's motion stays the same unless an unbalanced force acts?", "Which law says an object stays at rest or keeps moving at constant speed in a straight line when the forces are balanced?", "core"],
  ["Newton's second law", "Which law links force, mass and acceleration?", "Which Newton law is represented by F = ma?", "core"],
] as const;
