export const geneticsConcepts = [
  ["variation", "What term describes differences between individuals of the same species?", "What biological term includes differences such as height or eye colour between individuals?", "foundation"],
  ["continuous variation", "What type of variation has a range of values with many possible values in between?", "What type of variation is shown by human height?", "core"],
  ["discontinuous variation", "What type of variation falls into separate categories?", "What type of variation is shown by blood group?", "core"],
  ["DNA", "What molecule carries genetic information?", "Which molecule is found in chromosomes and contains genetic instructions?", "foundation"],
  ["nucleotide", "What is one repeating building block of DNA called?", "Which DNA building block contains a sugar, phosphate and base?", "core"],
  ["base pairing", "What rule says A pairs with T and C pairs with G in DNA?", "What do we call the rule that determines which DNA bases pair together?", "core"],
  ["chromosome", "What structure in the nucleus is made of DNA and contains many genes?", "Where are many genes carried inside the nucleus?", "foundation"],
  ["gene", "What section of DNA contains information that can influence a characteristic?", "What unit of inheritance is a section of DNA?", "foundation"],
  ["allele", "What do we call an alternative version of a gene?", "What term describes different forms of the same gene, such as B and b?", "core"],
  ["dominant allele", "Which allele is expressed when it is present in a heterozygous genotype?", "Which allele is usually shown with a capital letter in a simple genetic cross?", "core"],
  ["recessive allele", "Which allele is expressed only when no dominant allele is present in a simple genetic cross?", "Which allele is usually shown with a lowercase letter?", "core"],
  ["genotype", "What term describes the pair of alleles an organism has for a gene?", "What term could be represented by BB, Bb or bb?", "core"],
  ["phenotype", "What term describes the characteristic an organism shows?", "What do we call the observable trait produced from a genotype?", "core"],
  ["homozygous dominant", "What do we call a genotype with two identical dominant alleles, such as BB?", "What genotype type is BB?", "core"],
  ["homozygous recessive", "What do we call a genotype with two identical recessive alleles, such as bb?", "What do we call the genotype bb?", "core"],
  ["heterozygous", "What do we call a genotype with two different alleles, such as Bb?", "What genotype type contains one dominant and one recessive allele?", "core"],
  ["Punnett square", "What grid is used to predict possible allele combinations in offspring?", "What model do we use to show the possible genotypes from a monohybrid cross?", "core"],
  ["25%", "In a Bb × Bb monohybrid cross, what is the probability that an offspring will show the recessive phenotype?", "If B is dominant and two Bb parents are crossed, what percentage of offspring are expected to show the recessive phenotype?", "core"],
  ["50%", "In a Bb × bb monohybrid cross, what is the probability that an offspring will show the dominant phenotype?", "If B is dominant and a Bb parent is crossed with a bb parent, what percentage of offspring are expected to show the dominant phenotype?", "core"],
  ["mutation", "What do we call a change in genetic information in DNA?", "What process can create a new genetic change that may affect an organism's phenotype?", "core"],
  ["mutagen", "What do we call something that can cause a mutation?", "What term is used for a factor such as certain radiation or chemicals that can cause mutations?", "core"],
  ["genetic diversity", "What term describes the variety of genetic differences within a species?", "What type of diversity can make a wild population more likely to contain individuals suited to environmental change?", "stretch"],
  ["adaptation", "What is a characteristic that helps an organism survive in its environment?", "What term describes a feature that gives an organism a survival advantage in a particular environment?", "core"],
  ["structural adaptation", "What type of adaptation is a physical feature of an organism's body?", "What type of adaptation would thick fur or a streamlined body be?", "core"],
  ["behavioural adaptation", "What type of adaptation is something an organism does that helps it survive?", "What type of adaptation would migration or nocturnal activity be?", "core"],
  ["physiological adaptation", "What type of adaptation is an internal body process that helps an organism survive?", "What type of adaptation would producing concentrated urine in a dry environment be?", "stretch"],
  ["natural selection", "What process makes helpful inherited traits more common in a population over generations?", "What process occurs when individuals with advantageous traits are more likely to survive and reproduce?", "stretch"],
  ["selection pressure", "What environmental factor affects which individuals are more likely to survive and reproduce?", "What term describes factors such as predators, disease or food availability that influence survival?", "stretch"],
  ["evolution", "What term describes changes in inherited characteristics of a population over many generations?", "What process can be driven by natural selection over time?", "stretch"],
  ["endemic", "What term describes a species that is naturally found only in one particular place?", "What word describes a species found naturally in New Zealand and nowhere else?", "stretch"],
] as const;
