export const humanBodyConcepts = [
  ["aerobic respiration", "What process uses glucose and oxygen to release energy in cells?", "Which process produces carbon dioxide and water while releasing energy from glucose?", "foundation"],
  ["glucose + oxygen → carbon dioxide + water + energy (ATP)", "What is the word equation for aerobic respiration?", "Complete the word equation: glucose + oxygen → ?", "core"],
  ["digestion", "What process breaks large food molecules into smaller parts?", "What process makes food molecules small enough to be absorbed?", "foundation"],
  ["mouth", "Which digestive organ takes in food and begins physical digestion by chewing?", "Where does food enter the digestive system?", "foundation"],
  ["oesophagus", "Which muscular tube carries food from the mouth to the stomach?", "Which part of the digestive system moves swallowed food to the stomach?", "core"],
  ["stomach", "Which muscular organ churns food and continues digestion?", "Which digestive organ receives food from the oesophagus?", "core"],
  ["small intestine", "Which organ is the main site of digestion, diffusion and absorption of digested nutrients?", "Which digestive organ contains villi?", "core"],
  ["pancreas", "Which organ releases digestive enzymes into the small intestine?", "Which digestive organ helps chemical digestion by supplying enzymes?", "core"],
  ["liver", "Which organ produces bile?", "Which large digestive organ makes bile to help with digestion?", "core"],
  ["large intestine", "Which organ absorbs water from material left after the small intestine?", "Which digestive organ receives the remaining material after the small intestine?", "core"],
  ["rectum", "Which part of the digestive system stores faeces before they leave the body?", "Which part comes just before the anus?", "core"],
  ["anus", "Which opening is at the end of the digestive system?", "Through which opening do faeces leave the body?", "core"],
  ["carbohydrates", "Which food-molecule group includes sugars and starches and can provide glucose?", "Which nutrient group is a major source of glucose for respiration?", "core"],
  ["lipids", "Which food-molecule group includes fats and oils?", "Which nutrient group provides a rich energy supply?", "core"],
  ["proteins", "Which food-molecule group is important for building and repairing body tissues?", "Which nutrient group is broken down into smaller molecules during digestion and is important for growth?", "core"],
  ["vitamins and minerals", "Which food-molecule group is needed in small amounts to support healthy body processes?", "Which nutrient group includes substances such as vitamins, iron and calcium?", "core"],
  ["fibre", "Which part of food helps material move through the digestive system?", "Which dietary component adds bulk and supports movement through the gut?", "core"],
  ["absorption", "What process moves digested molecules from the gut into the bloodstream?", "What process mainly occurs across the villi of the small intestine?", "core"],
  ["diffusion", "What process moves molecules from an area of high concentration to an area of low concentration?", "Which process helps molecules move across thin exchange surfaces down a concentration gradient?", "core"],
  ["villi", "What finger-like structures increase the surface area of the small intestine?", "Which structures in the small intestine help absorption happen efficiently?", "core"],
  ["type 2 diabetes", "Which condition can be linked to a long-term high-sugar diet?", "Which type of diabetes is discussed when considering the health effects of a high-sugar diet?", "core"],
  ["gas exchange", "What process moves oxygen into the blood and carbon dioxide out of the blood in the lungs?", "Which process occurs at the alveoli?", "foundation"],
  ["bronchi", "What are the two main airways that carry air into the lungs called?", "Which airways branch from the trachea and lead into the lungs?", "core"],
  ["bronchioles", "What are the smaller branching airways inside the lungs called?", "Which airways lead from the bronchi toward the alveoli?", "core"],
  ["alveoli", "What tiny air sacs are the main gas-exchange surfaces in the lungs?", "Which lung structures have thin walls and a large surface area for gas exchange?", "core"],
  ["breathing", "What process moves air into and out of the lungs?", "What process uses muscles including the diaphragm to draw air in and push air out?", "core"],
  ["less oxygen available for respiration", "How can smoking or vaping reduce the body's ability to carry out aerobic respiration?", "What is one effect of smoking or vaping on the oxygen available for respiration?", "core"],
  ["circulation", "What process moves blood around the body?", "Which process transports oxygen and glucose to cells and removes products such as carbon dioxide?", "foundation"],
  ["heart", "Which organ pumps blood around the body?", "What is the pump of the circulatory system?", "foundation"],
  ["artery", "Which blood vessel carries blood away from the heart?", "Which blood vessel carries blood at relatively high pressure away from the heart?", "core"],
  ["vein", "Which blood vessel carries blood toward the heart?", "Which blood vessel has valves to help prevent backflow?", "core"],
  ["capillary", "Which thin blood vessel is the main site of diffusion into and out of the blood?", "Which small blood vessel has a thin wall for exchange with tissues?", "core"],
  ["heart attack", "Which circulatory-system breakdown happens when blood supply to part of the heart muscle is blocked?", "Which condition is studied as a breakdown of the circulatory system affecting the heart?", "stretch"],
  ["frostbite", "Which condition can damage cells when body tissues become extremely cold and blood flow is reduced?", "Which condition caused by severe cold can damage body tissues and cells?", "stretch"],
] as const;
